### ISSUE TITLE
Can't download skript Placeholder

### ISSUE THREAD

**Issue by KimpiegamesYT1** [PlaceholderAPI/PlaceholderAPI#1001]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

Can't install skript placeholder

### Expected Behaviour

Install Skript Placeholder

### How to Reproduce

1. /papi ecloud download skript
2. Error, Failed to find an exansion named: Skript

### `/papi dump` Output

https://paste.helpch.at/ogazepixub

### Errors

 Failed to find an expansion named: skript

### Additional Info

Skript is shown in the placeholder list https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#skript

**Comment by Andre601** [comment]
Looks like the expansion isn't verified. PlaceholderAPI won't retrieve nor download expansions that aren't verified on the ecloud for safety reasons.

**Comment by Redben1000** [comment]
> 

but then why have it in placeholder list and i have seen pic of it in there before.
i am having the same problem i am just trying to add a skript var in my scoreboard can you please fix this

**Comment by Andre601** [comment]
> but then why have it in placeholder list and i have seen pic of it in there before.

We have a large text at the very top of the page that explains why:

> **Note**
> We only add and/or update placeholders on request.
> We aren't responsible, to keep the placeholders of your plugin(s) up to date.
> If anything about your expansion/plugin has changed, consider [making a Pull request](https://github.com/PlaceholderAPI/PlaceholderAPI/pulls) to commit the changes yourself.
> 
> You can find a comprehensive guide on how to do this on the [Wiki's README file](https://github.com/PlaceholderAPI/PlaceholderAPI/blob/wiki/README.md).

The wiki is updated on request, not automatically nor periodically.

> i am having the same problem i am just trying to add a skript var in my scoreboard can you please fix this

This is not a PlaceholderAPI issue.
We can't and won't provide support for every Placeholder expansion that exists here, as that would waste a lot of our time which some of us only have in limited numbers.

If you need help, contact the author of the expansion, or ask in the [helpchat discord](https://helpch.at/discord) for further help. But this issue tracker is reserved to issues actually related to PlaceholderAPI (Actual bugs that happen within the plugin and that aren't caused through an expansion).
