### ISSUE TITLE
Papi Reload not working

### ISSUE THREAD

**Issue by RuuDarling** [PlaceholderAPI/PlaceholderAPI#1002]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

API Bug

### What happens?

Hello,

This has been mentioned a couple of times before but I'm finding that none of them work for me and unsure how to proceed. When I go to download an expansion, it works and comes up with a successful message but when I reload it, it doesn't do anything, no message or anything. When I look into the console, it comes up with a bunch of messages that I'm unsure how to discern or read properly. I'm assuming there's something blocking the connection but I'm not sure where to start.

### Expected Behaviour

To be able to use /papi reload 

### How to Reproduce

/papi ecloud download LuckPerms

Successfully downloaded expansion LuckPerms [5.4-R2] to file: Expansion-luckperms.jar

/papi reload

Nothing happens

Console loads a bunch of messages when hitting /papi reload (link in console log/errors

### `/papi dump` Output

https://paste.helpch.at/xunifupeha

### Console Log

https://paste.helpch.at/olohevuraq.md

### Errors

https://paste.helpch.at/losisatati.rb

### Additional Info

At first, I was just wanted the expansion for Luckperms but it also looks like its doing it with other expansions as well so it's universal

**Comment by Andre601** [comment]
The logs (Especially the error) is hard to read. I assume you just copied straight from the console?

Maybe copy the latest.log instead?

**Comment by iGabyTM** [comment]
Remove the townychat expansion jar, the plugin is not installed from what I can see.
