### ISSUE TITLE
Ping placeholders fail on 1.20.2

### ISSUE THREAD

**Issue by Strahilchu** [PlaceholderAPI/PlaceholderAPI#1009]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

When parsing ping or using a ping placeholder in any other capacity it fails to work.

### Expected Behaviour

For ping to display via placeholder just how when executing /Ping

### How to Reproduce

/Papi parse Player %player_ping%

### `/papi dump` Output

https://paste.helpch.at/poxovebede

### Console Log

https://paste.helpch.at/utiwacutam.rb

**Comment by iGabyTM** [comment]
Update the player expansion
