### ISSUE TITLE
New plugin supporting PlaceholderAPI (Daily Rewards)

### ISSUE THREAD

**Issue by Halflove1** [PlaceholderAPI/PlaceholderAPI#101]
[Request change]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

### Notes
This template is for **requesting additions for the wiki** and not for reporting bugs or requesting changes for the wiki!  
If you want changes to be made to the wiki, use the [Request change] template.  
For bug reports, use the [Bug report] template.

Also make sure, that your requested placeholders/plugin isn't already added in the [wiki] or listed in the [issues] page.

### Type
> What kind of request is this? (Multiple selections possible)

- [x] New expansion providing placeholders.
- [x] New plugin providing placeholders.
- [x] New plugin supporting PlaceholderAPI.

### Plugin
> What is the name of the plugin/expansion?
> Provide also a link to it.

Daily Rewards
https://www.spigotmc.org/resources/daily-rewards.16708/

### Placeholders/others
> What are the new placeholders/Any additional info?

%dailyrewards_remaining_time% <-- Formatted cooldown remaining time
%dailyrewards_remaining_hours% <-- Cooldown hours left
%dailyrewards_remaining_minutes% <-- Cooldown minutes left
%dailyrewards_remaining_seconds% <-- Cooldown seconds left
%dailyrewards_player_reward_available% <-- Configurable reward available message
%dailyrewards_player_no_rewards% <-- Configurable no rewards availble message
%dailyrewards_player_test_qualification% <-- Configurable current reward availability status message

**Comment by Andre601** [comment]
Please fill out the template properly.
Especially the Type section since it's not clear what it is now. Is yours a plugin providing the placeholders, or is it a seperate expansion (jar file) that provides those?

**Comment by Halflove1** [comment]
My bad, I didn't understand what it was asking for fully, my plugin provides the placeholders within it, there isn't a separate jar just for providing placeholders.

**Comment by Andre601** [comment]
Added your plugin to the [List](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#daily-rewards)
Thanks for supporting PlaceholderAPI
