### ISSUE TITLE
warning in connection with fe economy 

### ISSUE THREAD

**Issue by seema84** [PlaceholderAPI/PlaceholderAPI#1024]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin/Server Incompatability

### What happens?

I get the warning when starting the server.

This error only occurs if the PlaceholderAPI plugin and the expansion essentials are used.
Version: PlaceholderAPI-2.11.5

https://github.com/EssentialsX/Essentials/issues/5583#event-11075935829

### How to Reproduce

A simple server (with Fe, Essentialsx and PlaceholderAPI  -> expansion essentials) start is enough to reproduce the error.

### `/papi dump` Output

PlaceholderAPI-2.11.5

### Errors

https://paste.gg/p/anonymous/ed7ecb13fac2439fa2acfdb88b3dea8a

### Additional Info

Vault: v1.7.3-b131
Fe: v0.9
Essentials: v2.21.0-dev+21-c68b277
Paper-196 (MC: 1.20.1)

**Comment by Andre601** [comment]
Nothing in the error points to this being an issue of PlaceholderAPI. It at most is caused by a separate plugin, which also has been pointed out in the issue you mentioned.

**Comment by seema84** [comment]
However, it only occurs when playerholderapi is used on the server.

**Comment by Andre601** [comment]
Still doesn't mean it's PAPI's fault here... At least from the error you provided.

If you want help, share the full log too. But so far nothing here points at PlaceholderAPI being at fault. At most could it be an expansion, which isn't our responsability here.

**Comment by seema84** [comment]
Then I'll try again here.
https://github.com/PlaceholderAPI/Essentials-Expansion
