### ISSUE TITLE
Failed to find an expantion named: world

### ISSUE THREAD

**Issue by TheFlameB** [PlaceholderAPI/PlaceholderAPI#1029]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

I needed to use the %world_player_<world>% placeholder but i didn´t worked because the plugin could not find the vanilla expantion "world" and i used the command that is given in https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#world.

### Expected Behaviour

It sould download the World expantion

### How to Reproduce

1. /papi ecloud download world

### `/papi dump` Output

https://paste.helpch.at/gurihirema.yaml

### Additional Info

So i test it in the Paper version 1.20.1 #196 and it didn´t worked but in a plugin version in the 1.19.2 it worked just fine.

**Comment by iGabyTM** [comment]
The expansion is not verified, you have to download it manually from here: https://api.extendedclip.com/expansions/world/
