### ISSUE TITLE
Custom placeholders and placeholder inside another

### ISSUE THREAD

**Issue by chelminski** [PlaceholderAPI/PlaceholderAPI#1033]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

New config option

### Description

Allow one placeholder to be used as an argument to another placeholder. 
For example, I would like to put one placeholder inside another

Placeholder 1: `%example_placeholder_<value>%`
Placeholder 2: `%second_placeholder%`

I would like to do this: %example_placeholder_%second_placeholder%%

So <vaule> would be the value returned by %second_placeholder%. Of course, this is currently not possible, because the plugin reads placeholder from `%` to `%`. So let's, for example, use a second placeholder in a different character. E.g. `%example_placeholder_{second_placeholder}%`

Maybe also add a new config file where you can create custom placeholders. In this configuration file, e.g. "custom.yml" there would be something like this:

```
list:
  - '%example_placeholder_{second_placeholder}%':'double_placeholder'
  - 'Hello, we have promo for rank':'rank_promo'
```

To use text, it would be enough to enter, for example:
```
%placeholderapi_custom_double_placeholder%
%placeholderapi_custom_rank_promo%
```

That is, according to the formula:
`'<text>:'<id>'`

Why? This will allow you to change the text globally in all places where a placeholder is used. This is useful, especially when you have special characters/strings such as custom emojis or you simply want to update information that appears in many places, e.g. quests, holograms, tabs, scoreboard, etc.

**Comment by Starmism** [comment]
A. This already exists in the form of Bracket Placeholders.
B. PAPI doesn't control how placeholders are directly parsed, expansions are in charge of parsing. Some do bracket placeholders, some don't.
