### ISSUE TITLE
PAPI incompatible with future versions of Paper

### ISSUE THREAD

**Issue by kennytv** [PlaceholderAPI/PlaceholderAPI#1034]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

PAPI tries to parse the relocated CraftBukkit package version, which is unsupported behavior. 

### Expected Behaviour

PAPI not explicitly parsing the relocation version in https://github.com/PlaceholderAPI/PlaceholderAPI/blob/master/src/main/java/me/clip/placeholderapi/PlaceholderAPIPlugin.java#L58

See https://forums.papermc.io/threads/paper-velocity-1-20-4.998/#post-2955

### How to Reproduce

Currently not possible, but this will be important in the future

### `/papi dump` Output

N/A

### Errors

https://paste.helpch.at/egoxexuhim.rb

**Comment by kennytv** [comment]
Nevermind the testing part, you can use https://github.com/PaperMC/testing/releases/tag/no-relocation

**Comment by mrfloris** [comment]
Yep, this is the exact same error I received. And in the list of plugins that I load most have the out of bound message and a reference to PAPI.

**Comment by Andre601** [comment]
I see a minor problem here...

PAPI stores the String in a Version class, which itself is used for the `VersionSpecific` interface to allow expansions to only work with specific versions.
While the change would be rather trivial (Just swap one method for the other recommended when obtaining version) is this a breaking change in the end, since the outputed string is afaik not the same?

And I'm sure that breaking changes are something to be avoided here right now...

I hope you get what I mean.

**Comment by kennytv** [comment]
Right, you can't really change this without breaking the passed version, at least starting with the version the change will be introduced. but at that point, those revision numbers just won't exist anymore in Paper (and even right now are entirely meaningless and arbitrary, I really wouldn't have API make use of them)

**Comment by Andre601** [comment]
Yeah. It's one of the various old parts of PAPI that are... questionable to exist in their current form...

If I could  chose, I would honestly just deprecate that Version thing altogether...
Plugins/Expansions usually have access to the Bukkit API anyways, so they could easily do the proper checks themself and don't need to rely on PAPI to do this for them.

**Comment by PiggyPiglet** [comment]
I'm gonna PR a little hacky fix and deprecate the VersionSpecific interface so we can remove this shit entirely one day. Tested this on 1.8 & the 1.20 jar kenny provided though with the gradient expansion and it works as expected.
