### ISSUE TITLE
can you support folia？

### ISSUE THREAD

**Issue by ddsb520** [PlaceholderAPI/PlaceholderAPI#1037]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

Minor Code improvement (Won't affect Servers), Major Code improvement (Will affect Servers)

### Description

Is hard to support folia? Why is it not supported in 2024?

**Comment by Funny-cube** [comment]
Hello, there's already a PR that supports it and we're currently in the testing phase. https://github.com/PlaceholderAPI/PlaceholderAPI/pull/980

**Comment by ddsb520** [comment]
Thank you very much，Successful to use
