### ISSUE TITLE
Relational placeholder expansion for nametags to show different text to different clients/users

### ISSUE THREAD

**Issue by TheJoshue** [PlaceholderAPI/PlaceholderAPI#1039]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

New API feature, New config option

### Description

in short terms, a relational placeholders which will show text depending on conditions met; i will go straight to example which will explain how this should work:

- Player `HelloThere_1` and `HelloThere_2` are looking at player `HelloThere_3`
- Player `HelloThere_1` sees nametag of them and the nametag goes `[Admin] HelloThere_3`
- Player `HelloThere_2` meets other condition and it shows for them `[Operator] HelloThere_3`

As you can see, `[Admin] ` and `[Operator] `, those are different prefixes for player `HelloThere_3`, because `HelloThere_1` and `HelloThere_2` has met different conditions

### Code Example

```java
I am not sure...
```

### Additional Information

This could be new relational expansion for nametags

**Comment by Andre601** [comment]
1. Your example has a typo, since you use `HelloThere_1` in all three points.
2. Relational placeholders do exist already, see [this section on the wiki](https://wiki.placeholderapi.com/developers/creating-a-placeholderexpansion/#making-a-relational-expansion).

**Comment by TheJoshue** [comment]
> 1. Your example has a typo, since you use `HelloThere_1` in all three points.

You are very right, sorry it was late, glad you got the point already!

> 2. Relational placeholders do exist already, see [this section on the wiki](https://wiki.placeholderapi.com/developers/creating-a-placeholderexpansion/#making-a-relational-expansion).

Ok so you say this would be possible to be made as an PAPI expansion? Exactly what i gave in example? Certain players X, Y seeing different nametag prefix (in the example above) of player Z?
If yes, i will either look it myself, i never made papi expansion, i only have integrated it into my plugins sometimes, and i this is not a regular papi expansion but relational which (i assume) makes it complex and harder to understand; but thank you so much for feedback, much appreciated!

**Comment by iGabyTM** [comment]
[Here](https://wiki.placeholderapi.com/developers/creating-a-placeholderexpansion/#making-a-relational-expansion) you can find more details about how to create a relational expansion. To support relational placeholders you have to use another papi method.. something like `PlaceholderAPI#setRelPlaceholders(Player p1, Player p2, String string)`

**Comment by TheJoshue** [comment]
> [Here](https://wiki.placeholderapi.com/developers/creating-a-placeholderexpansion/#making-a-relational-expansion) you can find more details about how to create a relational expansion. To support relational placeholders you have to use another papi method.. something like `PlaceholderAPI#setRelPlaceholders(Player p1, Player p2, String string)`

Thank you
Sorry, where i need to use that method? in my plugin? asking because i actually want to implement this placeholder to be used inside of TAB plugin

**Comment by Andre601** [comment]
> Thank you Sorry, where i need to use that method? in my plugin? asking because i actually want to implement this placeholder to be used inside of TAB plugin

TAB has to implement this themself in some way. The difficult part is to determine the players to use here and their respective outputs...

Honestly speaking, I don't even know if what you want here is technically achievable, as it would require PAPI to return multiple Strings, one for each player, which kind of goes against its current system of where you call a method with a String and player (or two with relational ones) and PAPI returns a String with placeholders parsed.

**Comment by NEZNAMY** [comment]
The following code will do exactly that
```
    public String onPlaceholderRequest(Player viewer, Player target, String identifier) {
        if (target.getName().equals("HelloThere_3")) {
            if (viewer.getName().equals("HelloThere_1")) {
                return "[Admin] ";
            }
            if (viewer.getName().equals("HelloThere_2")) {
                return "[Operator] ";
            }
        }
        return null;
    }
```

All you need to find out is the order of the two players passed by your display plugin.

**Comment by Andre601** [comment]
> The following code will do exactly that
> 
> ```
>     public String onPlaceholderRequest(Player viewer, Player target, String identifier) {
>         if (target.getName().equals("HelloThere_3")) {
>             if (viewer.getName().equals("HelloThere_1")) {
>                 return "[Admin] ";
>             }
>             if (viewer.getName().equals("HelloThere_2")) {
>                 return "[Operator] ";
>             }
>         }
>         return null;
>     }
> ```
> 
> All you need to find out is the order of the two players passed by your display plugin.
> 
> You are not requesting a new PlaceholderAPI feature, since this is already available. You just need someone to code that expansion for you, therefore, your statement `My Feature Request is for PlaceholderAPI and not any expansion or other plugin.` is false.

Well, it does require work on your end too, since they mention to use in TAB and TAB afaik does not use relational placeholders...

**Comment by TheJoshue** [comment]
> The following code will do exactly that
> 
> ```
>     public String onPlaceholderRequest(Player viewer, Player target, String identifier) {
>         if (target.getName().equals("HelloThere_3")) {
>             if (viewer.getName().equals("HelloThere_1")) {
>                 return "[Admin] ";
>             }
>             if (viewer.getName().equals("HelloThere_2")) {
>                 return "[Operator] ";
>             }
>         }
>         return null;
>     }
> ```
> 
> All you need to find out is the order of the two players passed by your display plugin.
> 
> You are not requesting a new PlaceholderAPI feature, since this is already available. You just need someone to code that expansion for you, therefore, your statement `My Feature Request is for PlaceholderAPI and not any expansion or other plugin.` is false.

Thanks for clarifications, i am really unsure what i should've requested as i don't know what should be where implemented and if it's already, i thought this could be used not only in TAB but in any other plugin that could modify nametags, but in my cas,e i use TAB, as i used it since v1



> > The following code will do exactly that
> > ```
> >     public String onPlaceholderRequest(Player viewer, Player target, String identifier) {
> >         if (target.getName().equals("HelloThere_3")) {
> >             if (viewer.getName().equals("HelloThere_1")) {
> >                 return "[Admin] ";
> >             }
> >             if (viewer.getName().equals("HelloThere_2")) {
> >                 return "[Operator] ";
> >             }
> >         }
> >         return null;
> >     }
> > ```
> >
> > All you need to find out is the order of the two players passed by your display plugin.
> > You are not requesting a new PlaceholderAPI feature, since this is already available. You just need someone to code that expansion for you, therefore, your statement `My Feature Request is for PlaceholderAPI and not any expansion or other plugin.` is false.
> 
> Well, it does require work on your end too, since they mention to use in TAB and TAB afaik does not use relational placeholders...

Relational placeholders for factions already work here, so i assume it has support for relational placeholders (?) because it is displayed to player depending on their faction relation (ally, neutral, enemy, truce...)
Although i am unsure about everything as i am really not a programmer, thanks for answers

**Comment by NEZNAMY** [comment]
> Well, it does require work on your end too, since they mention to use in TAB and TAB afaik does not use relational placeholders...
TAB supports PlaceholderAPI's relational placeholders for no less than 5 years and all details regarding relational placeholders are documented.

**Comment by Andre601** [comment]
Since there hasn't been any updates on this issue, and given that there seems to be a solution available will I close it.

Feel free to reply if there is still something you need help with in relation to this issue.
