### ISSUE TITLE
EssentialsX makes placeholderAPI non-functional

### ISSUE THREAD

**Issue by evan-ryr** [PlaceholderAPI/PlaceholderAPI#1049]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

When EssentialsX is not installed in the Plugins folder on the server, PlaceholderAPI will display placeholders and work normally. But when EssentialsX (stable version or build) is present in the plugins folder, PlaceholderAPI will not show any placeholder. I can install the expansions but when /papi reloads, 2 messages are displayed in the console (these are not errors: [PlaceholderAPI] Placeholder expansion registration initializing... and [PlaceholderAPI] Fetching available expansion information...) then no responses in the IG chat although the extensions are present in the expansions folder. The /papi dump doesn't work either.

### Expected Behaviour

PlaceholderAPI should fix the problem because it's rather annoying that 2 big plugins don't work together

### How to Reproduce

1. Install PlaceholderAPI on a blank server with a few plugins and launch the server
2. Install the extensions then do /papi reload
3. Stop the server
4. Add the EssentialsX plugin
5. Restart the server (/papi reload and dump not working)

### `/papi dump` Output

 No response in console or IG chat

### Console Log

https://paste.helpch.at/iluqaceyip.makefile

### Errors

No errors

### Additional Info

If the bug is not functional for you, I will leave you my discord to contact me for more information. I tried to contact EssentialsX support after seeing yours, they told me to go to you

Discord: nocti.s

(I am French, moreover I am writing to you with Google Translate)

**Comment by Andre601** [comment]
How exactly is this an issue with PlaceholderAPI?

The plugin does not manage or alter chat. It only parses placeholders that plugins give to it.

The fact that installing EssentialsX causes the chat to no longer use parsed placeholders could mean one of two things:

- The plugin managing the chat disables its chat function when it detects EssentialsX (Probs assuming EssentialsXChat is present too)
- EssentialsX overrides the Chat handling. This *usually* doesn't happen as EssentialsX normally gives other plugins priority, but you never know.

Whatever it may be, this is not a PlaceholderAPI bug.

**Comment by Andre601** [comment]
Looking at this again, I can see that I misread things and that it isn't about chat messages...

However, I still cannot see a reason that would put PlaceholderAPI at fault here. After all, why would installing a separate plugin cause it to not function? What would make that a fault of PlaceholderAPI and not EssentialsX?

My best guess for now is, that perhaps the connection to the ecloud is being blocked and that errors are being swallowed.

Unfortunately can I personally not give more help without extra info, so I would appreciate if you could do the following:

- Provide the complete output of `/pl`
- Test if PlaceholderAPI features (Downloading expansions, registering them, etc) works on a **fresh Server setup** with only it an EssentialsX present (No other plugins).

If it works fine with only EssentialsX present is one of the other plugins causing the issue here.

**Comment by evan-ryr** [comment]
Indeed, I'm not talking about chat messages which seems strange to me: your answer :)
Furthermore, I had already gone to EssentialsX support (as mentioned above) and they sent me directly to you without any solution...
I also saw an issue with approximately the same problem as me (https://github.com/PlaceholderAPI/PlaceholderAPI/issues/948) so I thought you were the problem too

After trying your solution, the problem is not with placeholderAPI, on a clean server with only PlaceHolderApi and EssentialsX, everything works correctly. I will take you further to find the plugin causing the problem.

I would like to apologize for having opened an issue which ultimately does not fall under the control of PlaceHolderAPI, I will try to find the plugin causing the problem in order to contact support directly from it.

**Comment by evan-ryr** [comment]
The plugin causing the problem is Skungee. I close the issue
