### ISSUE TITLE
1.20.5 paper is out!

### ISSUE THREAD

**Issue by F3F5** [PlaceholderAPI/PlaceholderAPI#1056]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

https://pastebin.com/PCJJm0a6 - 1.20.5 plugin error

### Expected Behaviour

no

### How to Reproduce

no

### `/papi dump` Output

how

### Console Log

https://pastebin.com/PCJJm0a6

### Errors

how

**Comment by Foxikle** [comment]
I'm going to add a new details:

I am facing the same issue using a Paper server on 1.20.5
It is due to the removal of the version package
```java
//before
org.bukkit.craftbukkit.VERSION.classname

// after
org.bukkit.craftbukkit.classname
```

**Comment by Foxikle** [comment]
After some peeking, #1035 fixes this :)

**Comment by darbyjack** [comment]
Should be fixed via https://github.com/PlaceholderAPI/PlaceholderAPI/commit/068b5a31b2240cc0cc786cce1fd4351695b72c85.

A dev build is available here: https://ci.extendedclip.com/job/PlaceholderAPI/
