### ISSUE TITLE
a problem with recursively calling placeholders

### ISSUE THREAD

**Issue by sniperdown** [PlaceholderAPI/PlaceholderAPI#1058]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

API Bug

### What happens?

I‘m want make a double nesting to locate where player at but seems papi can't deal with this kind of problem
Here's my code：
%changeoutput_equals_input:{player_world}_matcher:world_ifmatch:test1_else:{changeoutput_equals_input:{player_world}_matcher:world_nether_ifmatch:test2_else:test3}%

### Expected Behaviour

Nesting of code is supported

### How to Reproduce

Here's my code:
%changeoutput_equals_input:{player_world}_matcher:world_ifmatch:test1_else:{changeoutput_equals_input:{player_world}_matcher:world_nether_ifmatch:test2_else:test3}%
output when you get to nether:
{changeoutput_equals_input:{player_world}_matcher:world_nether_ifmatch:test2_else:test3}

### `/papi dump` Output

https://paste.helpch.at/inewobogax

**Comment by Andre601** [comment]
Nested placeholders are not something PlaceholderAPI supports by itself. It depends on the expansion you use. And even then can you only have 1 level of nesting, meaning something like `%example_{example2_{example3_a}}%` is **not** possible.

This is not a bug, but a normal behaviour of PlaceholderAPI and also not a PlaceholderAPI issue directly.
