### ISSUE TITLE
Update to 1.20.6 please!

### ISSUE THREAD

**Issue by EnvisagedMyron** [PlaceholderAPI/PlaceholderAPI#1059]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

Major Code improvement (Will affect Servers)

### Description

1.20.6 and 1.20.6 are out

**Comment by Andre601** [comment]
1.20.6 support is planned and there is no need to open an issue for this as it only wastes time.
