### ISSUE TITLE
Compatible spigot versions per expansion version

### ISSUE THREAD

**Issue by cj89898** [PlaceholderAPI/PlaceholderAPI#106]
On the ecloud, we should have it so each expansion version has a compatible versions variable along with it. Expansions like the Statistics expansion don't work on all versions. I believe 1.9.1 and 1.9.2 work on 1.13+ only, whereas you need 1.7.0 for 1.12 and below.

**Comment by Andre601** [comment]
So you mean like on the page where you submit the new expansion or the one where you update the version having a new text field or something to say what server versions are supported with this expansion (version)?
This would actually be an interesting idea and perhaps could be implemented in a future version of PlaceholderAPI to warn people about possible incompatibility if you download an expansion.
But this is something the maker of the ecloud @extendedclip and @Funny-cube have to decide and look into.

**Comment by extendedclip** [comment]
Nah we can add a “compatible versions” method in the expansion it’s self and then papi will not load the expansion and send a custom log message if it doesn’t load due to version incompatibility. Would be easy to implement.

**Comment by extendedclip** [comment]
Actually it’s already a thing... Check the interface “VersionSpecific” but we could modify it to support multiple versions rather than just one.

**Comment by Andre601** [comment]
Never heard, nor saw about this VersionSpecific interdace....
