### ISSUE TITLE
Error on Server Startup

### ISSUE THREAD

**Issue by KhrysAK47** [PlaceholderAPI/PlaceholderAPI#1064]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

Once a server is restarted, the following error is in the console, and none of the PlaceholderAPI placeholders work, unless we do /papi reload after the server restart, which fixes them.

https://pastebin.com/YzJaphDP

### Expected Behaviour

The error should not be present.

### How to Reproduce

Uncertain as it happens randomly.

### `/papi dump` Output

https://paste.helpch.at/uwixodufeg

### Errors

https://pastebin.com/YzJaphDP

**Comment by Andre601** [comment]
You're using an outdated version of PlaceholderAPI. Please check to have everything updated before reporting an issue as it may be fixed.
