### ISSUE TITLE
Upgrade NBTapi

### ISSUE THREAD

**Issue by 1470429149** [PlaceholderAPI/PlaceholderAPI#1065]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

[17:24:34 WARN]: [NBTAPI] [NBTAPI] This Server-Version(v1_20_R3) is not supported by this NBT-API Version(2.12.0) located in PlaceholderAPI. The NBT-API will try to work as good as it can! Some functions may not work!

### Expected Behaviour

null

### How to Reproduce

1. open server
2. [17:24:34 WARN]: [NBTAPI] [NBTAPI] This Server-Version(v1_20_R3) is not supported by this NBT-API Version(2.12.0) located in PlaceholderAPI. The NBT-API will try to work as good as it can! Some functions may not work!

### `/papi dump` Output

https://paste.helpch.at/emolazajor

**Comment by Andre601** [comment]
From what I can see is PlaceholderAPI not including NBTAPI here at all:
https://github.com/PlaceholderAPI/PlaceholderAPI/blob/master/build.gradle.kts#L26-L36

My best guess is, that an expansion includes it, and since it's loaded through PlaceholderAPI is it appearing as if PlaceholderAPI is at fault.

**Comment by Funny-cube** [comment]
This is most likely due to an expansion as we don't directly use the NBTAPI, try restarting without the CheckItem expansion to see if the error is still there.

**Comment by PiggyPiglet** [comment]
shush you two, checkitem uses it and yes it's outdated, fixing it now
