### ISSUE TITLE
MATH should add escape symbols

### ISSUE THREAD

**Issue by 1470429149** [PlaceholderAPI/PlaceholderAPI#1066]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

Minor Code improvement (Won't affect Servers)

### Description

Sorry, I can't find the MATH extended formula submission question window

Because some variables will contain {}
For example:
%objective_score_{apa}%
So use %math_{objective_score_{apa}}/100%
will return an error because MATH treats {apa} as a variable rather than a parameter in the variable.

**Comment by Andre601** [comment]
Also, `{}` inside bracket placeholders won't work either way, as it breaks placeholder parsing in general.
