### ISSUE TITLE
Update to 1.21 please!

### ISSUE THREAD

**Issue by MrSmi1ey** [PlaceholderAPI/PlaceholderAPI#1068]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

Major Code improvement (Will affect Servers)

### Description

Update to 1.21 please!

**Comment by Andre601** [comment]
See #1067
