### ISSUE TITLE
Plugin can’t be loaded on bungee

### ISSUE THREAD

**Issue by FewerElk** [PlaceholderAPI/PlaceholderAPI#1078]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin/Server Incompatability

### What happens?

Papi isn’t loaded on bungee cord with this error message : Java.lang.NoClassDefFoundError : org/bukkit/plugin/java/JavaPlugin
(Caused by class not found exception)
![IMG_6273](https://github.com/user-attachments/assets/40e80149-8c93-46a8-b9b3-d37e4c9a3b4e)
<img width="365" alt="image" src="https://github.com/user-attachments/assets/2ed4c751-bc84-4423-9248-9dab90e147b8">

### Expected Behaviour

Papi should start normally

### How to Reproduce

Install and setup a bungeecord server with papi
Get the bug

### `/papi dump` Output

N/A

### Console Log

No log files

### Additional Info

Server : bungee cord
Plugin version : downloaded today from spigot (lastest)

**Comment by Andre601** [comment]
Just for the sake of clarity:
PlaceholderAPI is a **Spigot Plugin**. It is build against, and designed for a Spigot (Or any fork of it) Server. You tried to run it on a BungeeCord Proxy, which is a completely different, unrelated API than Spigot and is therefore incompatible.
If you want to use PAPI Placeholders on your BungeeCord Proxy, check if the plugin(s) in question support [PAPIProxyBridge](https://modrinth.com/plugin/papiproxybridge) and in such a case use that plugin to create a bridge between the servers using PAPI and your Proxy.
