### ISSUE TITLE
The repository site is down

### ISSUE THREAD

**Issue by Psyrioty** [PlaceholderAPI/PlaceholderAPI#1085]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

I want to write my own plugin using PlaceholderAPI, but the repository site doesn't work. The error on the server side is 522

### Expected Behaviour

-

### How to Reproduce

-

### `/papi dump` Output

-

**Comment by Legoman99573** [comment]
Can confirm. I just use Maven Repository for now until the repo is back online.
https://mvnrepository.com/artifact/com.github.placeholderapi/placeholderapi

**Comment by ItsmeFawaz** [comment]
He means this one, It is still down.
https://repo.extendedclip.com/content/repositories/placeholderapi

**Comment by Olzie-12** [comment]
> He means this one, It is still down. https://repo.extendedclip.com/content/repositories/placeholderapi

Yep, so i suggest using Jitpack like @Legoman99573 suggwsted.

**Comment by BlitzOffline** [comment]
Hello. We are aware of the issue. We are waiting for the admins to wake up so they can take care of this.

**Comment by Funny-cube** [comment]
You can follow along with updates here https://status.helpch.at/ or in our Discord https://discord.gg/helpchat

**Comment by Psyrioty** [comment]
> Могу подтвердить. Я пока просто использую Maven Repository, пока репозиторий не будет снова доступен. https://mvnrepository.com/artifact/com.github.placeholderapi/placeholderapi

Thanks

**Comment by Black-Hole** [comment]
The Wiki at https://wiki.placeholderapi.com/developers/using-placeholderapi/ is still referring to the old URL.

**Comment by Andre601** [comment]
> The Wiki at https://wiki.placeholderapi.com/developers/using-placeholderapi/ is still referring to the old URL.

This should be addressed now. Sorry for the delay.
