### ISSUE TITLE
Placeholder %world_time_<world>%

### ISSUE THREAD

**Issue by Radmir52** [PlaceholderAPI/PlaceholderAPI#1087]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

Using Placeholder %world_time_<world>% for a world named %iarspawn% returns the world time, but for the world "world_new" and other worlds with %_% in their name it does not. Example: %world_time_world_new%

### Expected Behaviour

Placeholder %world_time_world_new% should return the time for the world "world_new"

### How to Reproduce

1. download the World extension
2. reload the plugin
3. Run the command /papi parse my %world_time_world_new%

### `/papi dump` Output

https://paste.helpch.at/xojuvipiru

**Comment by Andre601** [comment]
That's due to how PAPI finds placeholders.
When it found a second % after finding a _ without spaces before it, will it assume to have found a placeholder.

Nothing we really can change here.
At most can you go to the repository of the world expansion and suggest adding a workaround.
Or better: Don't use the percent symbol in world names.

Either way, this isn't a PAPI issue and works as intended.

**Comment by Radmir52** [comment]
> Это связано с тем, как PAPI находит заполнители. Когда он находит второй % после _ без пробелов перед ним, он предполагает, что нашёл заполнитель.
> 
> Мы действительно ничего не можем здесь изменить. Самое большее, что вы можете сделать, это зайти в репозиторий расширения world и предложить добавить обходной путь. Или лучше: не используйте символ процента в названиях стран мира.
> 
> В любом случае, это не проблема PAPI и работает так, как задумано.

Good morning! I just found an option that works - %world_time_{world_new}%.
Problem solved!
