### ISSUE TITLE
placeholderapi un-registers extension SimpleClans every reboot

### ISSUE THREAD

**Issue by FrozenBeard** [PlaceholderAPI/PlaceholderAPI#110]
Placeholder API: 292
Paper version git-Paper-1613 (MC: 1.12.2)
Extension: SimpleClans https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#simpleclans

I run `/papi ecloud download SimpleClans and it works` fine,  next reboot /papi list only shows 11 placeholder hooks, I have to /papi register Expansion-SimpleClans, then its back up fine  again, as the JAR is still in the expansions folder.

Next reboot, its no longer showing in /papi list, and I have to register it again!

**Comment by extendedclip** [comment]
Try this build and report back

http://ci.extendedclip.com/job/PlaceholderAPI/68/

**Comment by darbyjack** [comment]
Closing due to the fact that it looks like the problem has been solved.
