### ISSUE TITLE
New plugin placeholders for AsyncKeepAlive

### ISSUE THREAD

**Issue by ishland** [PlaceholderAPI/PlaceholderAPI#112]
[Request change]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

### Notes
This template is for **requesting additions for the wiki** and not for reporting bugs or requesting changes for the wiki!  
If you want changes to be made to the wiki, use the [Request change] template.  
For bug reports, use the [Bug report] template.

Also make sure, that your requested placeholders/plugin isn't already added in the [wiki] or listed in the [issues] page.

### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New expansion providing placeholders.
- [x] New plugin providing placeholders.
- [ ] New plugin supporting PlaceholderAPI.

### Plugin
> What is the name of the plugin/expansion?
> Provide also a link to it.

AsyncKeepAlive
https://www.spigotmc.org/resources/64676/

### Placeholders/others
> What are the new placeholders/Any additional info?

Get the player's ping
%asynckeepalive_ping%

**Comment by Mishyy** [comment]
According to the AsyncKeepAlive [source](https://github.com/ishlandbukkit/AsyncKeepAlive/blob/master/src/main/java/com/ishland/bukkit/AsyncKeepAlive/main/PlaceHolderMain.java), such a placeholder already exists.

**Comment by aBo0oDyy** [comment]
Thanks for supporting PlaceholderAPI.
The placeholder has been added to the wiki and you can find it [here](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#asynckeepalive) 😄
