### ISSUE TITLE
PlaceHolder color

### ISSUE THREAD

**Issue by Momonche** [PlaceholderAPI/PlaceholderAPI#113]
Hello, I have a problem with Color PlaceHolder
Like Bedwars team color and faction relation, color are not working

https://i.imgur.com/QpV86Nh.png

I use %bw1058_player_team%
And /papi parse <player> %bw1058_player_team%
And I have the same issue with %rel_factions_relation_color%
No color not appear and the place holder stay visible like this in the chat

PaperSpigot 1.13.2 git-Paper-624
PlaceHolderAPI 2.10.2
Bedwars1058 0.9.13beta (API 13)
Factions 3.1.5

**Comment by Andre601** [comment]
- Why is it `{TeamColor}`?
- What Chat plugin do you use?
- Does it actually support PlaceholderAPI?

**Comment by Momonche** [comment]
I think we see {TeamColor} because %bw1058_player_team% is {TeamColor}{TeamName} so just the TeamName work.
My chat Plugin is VentureChat but someone tell me /papi parse is not affected by the chat plugin
And BedWars 1058 support PlaceholderAPI
https://gitlab.com/andrei1058/BedWars1058/wikis/papi-hook
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#bedwars1058

**Comment by aBo0oDyy** [comment]
> /papi parse %bw1058_player_team%

this is the old parse command, use the new one `/papi parse <me/player> %placeholder%`, and if the placeholder returns a color code, add text after it to see if the placeholder is working or not, because it will display an empty line if you didn't add text.

for the relation placeholder, not all plugins support relation placeholders. you have to check if your chat plugin (or the plugin you're using it in) supports them. and you can try them using the relation parse command `/papi parserel <player one> <player two> %placeholder%`
and don't forget to download Factions expansion:
```
/papi ecloud download factions
/papi reload
```

**Comment by Momonche** [comment]
I just test what you say

/papi parse MOMO3915 %rel_factions_relation_color%
I have the same issue with the color

And /papi parserel MOMO3915 Ferocimo %rel_factions_relation_color%
An empty line appear in my chat

**Comment by aBo0oDyy** [comment]
> I just test what you say
> 
> /papi parse MOMO3915 %bw1058_player_team%
> I have the same issue with the color

if the placeholder is returning a wrong value, but its workin (not returning the placeholder itself) that means you have to contact the author of the plugin. We can't do anything about that.

> And /papi parserel MOMO3915 Ferocimo %rel_factions_relation_color%
> An empty line appear in my chat

i mentioned that you have to add text after placeholders that returns color codes to see if they're working, so try this `/papi parserel MOMO3915 Ferocimo %rel_factions_relation_color%This is a test`

**Comment by Momonche** [comment]
Ok, I will contact the author of BedWars1058

I just test the relation color and work with the papi command, sorry for that
But that doesn't work in the chat
https://i.imgur.com/wvwLFME.png
It's a problem with my chat plugin ?

**Comment by aBo0oDyy** [comment]
> But that doesn't work in the chat

as i mentioned, not all (chat) plugins support relation placeholders.
check if your chat plugin supports it.

**Comment by Momonche** [comment]
Ok, thanks for your help
I will ask them
