### ISSUE TITLE
SuperVanish placeholder change request

### ISSUE THREAD

**Issue by MyzelYam** [PlaceholderAPI/PlaceholderAPI#115]
[New placeholders/plugin]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=feature_request.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

### Notes
This template is for **requesting changes to the wiki** and not for reporting bugs or requesting additions for the wiki!  
If you want your placeholders added, use the [New placeholders/plugin] template.  
For bug reports, use the [Bug report] template.

Also make sure, that your requested change isn't already made in the [wiki] or listed in the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [x] Placeholder(s) changed.
- [ ] New placeholder(s).
- [ ] Plugin no longer supports PlaceholderAPI and/or was deleted.

### Plugin
> What is the name of the plugin?

SuperVanish

### What is the new value?
> **Placeholder(s) changed**: Type what the old and the new placeholder(s) is/are.  
> **New Placeholder(s)**: Type the new placeholder(s).  
> **Plugin no longer supports PlaceholderAPI**: Leave this blank.

Old:
%supervanish_isvanished%
%supervanish_vanishedplayers%
%supervanish_playercount%
%supervanish_bungeeplayercount%
New:
%supervanish_isvanished%
%supervanish_vanishedplayers%
%supervanish_playercount%

**Comment by aBo0oDyy** [comment]
Changed.

Thanks for supporting PlacrholderAPI :smile:
