### ISSUE TITLE
RandomColor

### ISSUE THREAD

**Issue by Andre601** [PlaceholderAPI/PlaceholderAPI#118]
[Request change]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

### Notes
This template is for **requesting additions for the wiki** and not for reporting bugs or requesting changes for the wiki!  
If you want changes to be made to the wiki, use the [Request change] template.  
For bug reports, use the [Bug report] template.

Also make sure, that your requested placeholders/plugin isn't already added in the [wiki] or listed in the [issues] page.

### Type
> What kind of request is this? (Multiple selections possible)

- [x] New expansion providing placeholders.
- [ ] New plugin providing placeholders.
- [ ] New plugin supporting PlaceholderAPI.

### Plugin
> What is the name of the plugin/expansion?
> Provide also a link to it.

**Name**: RandomColor
**Link**: https://github.com/Andre601/RandomColor
**Dependencies**: None

### Placeholders/others
> What are the new placeholders/Any additional info?

```
%randomcolor_all%
%randomcolor_color%
%randomcolor_format%
%randomcolor_selected_<option1,option2,option3,...>%
```

**Comment by aBo0oDyy** [comment]
[Added](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#randomcolor).

Thanks for creating a PlaceholderAPI expansions 😄
