### ISSUE TITLE
papi refresh command error

### ISSUE THREAD

**Issue by RussianRonin** [PlaceholderAPI/PlaceholderAPI#12]
Hello,

Whe I load the plugin up, it says there are 110 extensions available.

When I run papi refresh, an error is generated and then you can no longer list any extensions. You have to restart the server or reload all plugins to fix it.

![image](https://user-images.githubusercontent.com/21460243/38951939-efa36e8c-42fe-11e8-97eb-8de44524fb83.png)

Please let me know if you need any other info.

**Comment by extendedclip** [comment]
http://ci.extendedclip.com/view/Plugins/job/PlaceholderAPI/16/
