### ISSUE TITLE
BentoBox and addons

### ISSUE THREAD

**Issue by Poslovitch** [PlaceholderAPI/PlaceholderAPI#122]
### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New expansion providing placeholders.
- [x] New plugin providing placeholders.
- [x] New plugin supporting PlaceholderAPI.

### Plugin
> What is the name of the plugin/expansion?
> Provide also a link to it.

BentoBox and subsequent addons (each of them is likely to provide their own placeholders)
https://github.com/BentoBoxWorld/BentoBox

### Placeholders/others
> What are the new placeholders/Any additional info?

As each addon is likely to provide their own placeholders, we can't provide a detailed and comprehensive list of them. However, some of the pages on our wikis can give you a glimpse of them: https://github.com/BentoBoxWorld/BentoBox/wiki/Placeholders

**Comment by aBo0oDyy** [comment]
Added. You can find them [here](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#bentobox)
Also added it to `Plugins using PlaceholderAPI` [here](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#b)

added the placeholders that under `1.4.0`, the placeholders under `1.5.0 and above` doesn't have an identifier, and theres no placeholder that starts with argument, if those are BentoBox placeholders please update them in your wiki and let me know to add them.
I checked AcidIsland GameMode, BSkyBlock GameMode and CaveBlock GameMode all of them have placeholders, do you want me to add them to the wiki too, so like in BentoBox section,
AcidIsland GameMode
```
AcidIsland GameMode placeholders
....
```
same with the others

**Comment by Poslovitch** [comment]
> the placeholders under 1.5.0 and above doesn't have an identifier, and theres no placeholder that starts with argument, if those are BentoBox placeholders please update them in your wiki and let me know to add them.

Well, I had to come up with a way of making it easily understandable that `[gamemode]` must be replaced with the lowercased gamemode's name. E.g, %[gamemode]_island_name% would be %bskyblock_island_name% for BSkyBlock. Hope that it is clear enough.

Thanks for adding BentoBox to your Wiki anyways!

**Comment by aBo0oDyy** [comment]
> Well, I had to come up with a way of making it easily understandable that [gamemode] must be 
replaced with the lowercased gamemode's name. E.g, %[gamemode]_island_name% would be %bskyblock_island_name% for BSkyBlock. Hope that it is clear enough.

Well then thats not related to BentoBox, since its considered another plugin/expansion.
You're more than welcome, Thanks for supporting PlaceholderAPI 😄

**Comment by RobinDeBaets** [comment]
@aBo0oDyy would it be perhaps possible to put a name of possible `gamemode` values in the PlaceholderAPI wiki? A lot of people search for 'bskyblock' and they can't find it.

Also, the placeholders from the Level Add-on are not yet on the wiki: https://github.com/BentoBoxWorld/BSkyBlock/wiki/Placeholders

**Comment by aBo0oDyy** [comment]
[Updated](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#bentobox).
Let me know if there's anything wrong with it.

**Comment by RobinDeBaets** [comment]
Thanks a lot. Appreciated.

**Comment by Poslovitch** [comment]
Hi,

Wouldn't that be better if a link to our own Wiki page could be added? It seems it's going to be a real burden if you'd have to update everytime we either create an addon or add/rename/delete placeholders. Whereas our Wiki is kept up to date.
https://github.com/BentoBoxWorld/BentoBox/wiki/Placeholders

**Comment by aBo0oDyy** [comment]
Hello,

The aim of the wiki is to have all plugins placeholders in one place, and a lot of people are actually using it only.

> It seems it's going to be a real burden if you'd have to update everytime we either create an addon or add/rename/delete placeholders. 

No it won't at all, whenever you add/rename/delete/change a placeholder, feel free to open a new issue with the new modifications and we will be more than happy to update it in our wiki.

If you really think that having a link to your placeholders wiki will be useful to the users, i would add it.

**Comment by Poslovitch** [comment]
> If you really think that having a link to your placeholders wiki will be useful to the users, i would add it.

I definitely think so, and it would be really appreciated if you'd do that.

> The aim of the wiki is to have all plugins placeholders in one place, and a lot of people are actually using it only.

I understand. Yet, I don't think it's really appropriate to the very specific "way of working" of BentoBox and its addons. It can get really messy, real quick.

> No it won't at all, whenever you add/rename/delete/change a placeholder, feel free to open a new issue with the new modifications and we will be more than happy to update it in our wiki.

I'll do, once I get a clear view of all the placeholders we now have.

**Comment by aBo0oDyy** [comment]
Well then, sure, [Added](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#bentobox).

> I'll do, once I get a clear view of all the placeholders we now have.
Ok, thank you for your cooperation.
