### ISSUE TITLE
Update SimpleClans Expansion to 2.0.2

### ISSUE THREAD

**Issue by Peng1104** [PlaceholderAPI/PlaceholderAPI#123]
[New placeholders/plugin]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=feature_request.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki
### Type
> What kind of change is it?

- [x] Placeholder(s) changed.
- [x] New placeholder(s).
- [ ] Plugin no longer supports PlaceholderAPI and/or was deleted.

### Plugin
> What is the name of the plugin?

SimpleClans

### What is the new value?
> **Placeholder(s) changed**: Type what the old and the new placeholder(s) is/are.  
> **New Placeholder(s)**: Type the new placeholder(s).  
> **Plugin no longer supports PlaceholderAPI**: Leave this blank.

As I have remaked the SimpleClans Expension I have add a lot of new Placeholders... The list whit all of them is here:

%simpleclans_neutral_kills%
%simpleclans_rival_kills%
%simpleclans_civilian_kills%
%simpleclans_total_kills%
%simpleclans_weighted_kills%
%simpleclans_deaths%
%simpleclans_kdr%
%simpleclans_in_clan%
%simpleclans_is_leader%
%simpleclans_is_trusted%
%simpleclans_is_member%
%simpleclans_is_bb_enabled%
%simpleclans_is_usechatshortcut%
%simpleclans_is_allychat%
%simpleclans_is_clanchat%
%simpleclans_is_globalchat%
%simpleclans_is_cape_enabled%
%simpleclans_is_tag_enabled%
%simpleclans_is_friendlyfire_on%
%simpleclans_is_muted%
%simpleclans_is_mutedally%
%simpleclans_join_date%
%simpleclans_inactive_days%
%simpleclans_lastseen%
%simpleclans_lastseendays%
%simpleclans_tag%
%simpleclans_tag_label%
%simpleclans_rank%
%simpleclans_clan_total_neutral%
%simpleclans_clan_total_civilian%
%simpleclans_clan_total_rival%
%simpleclans_clan_total_kills%
%simpleclans_clan_total_deaths%
%simpleclans_clan_total_kdr%
%simpleclans_clan_average_wk%
%simpleclans_clan_leader_size%
%simpleclans_clan_balance%
%simpleclans_clan_allow_withdraw%
%simpleclans_clan_allow_deposit%
%simpleclans_clan_size%
%simpleclans_clan_name%
%simpleclans_clan_color_tag%
%simpleclans_clan_tag_label%
%simpleclans_clan_tag%
%simpleclans_clan_founded%
%simpleclans_clan_friendly_fire%
%simpleclans_clan_is_unrivable%
%simpleclans_clan_is_anyonline%
%simpleclans_clan_is_verified%
%simpleclans_clan_capeurl%
%simpleclans_clan_inactivedays%
%simpleclans_clan_onlinemembers_count%
%simpleclans_clan_allies_count%
%simpleclans_clan_rivals_count%

**Comment by aBo0oDyy** [comment]
Updated. You can find them [here](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#simpleclans)
Thanks for updating the expansion and adding new placeholders 😄
