### ISSUE TITLE
MOTD Pinger issue

### ISSUE THREAD

**Issue by XArcadeXx** [PlaceholderAPI/PlaceholderAPI#124]
### Issue
> What is the issue? Describe it like you would tell a friend.

Multiversion pinger issue, i using DeluxeMenus for Server Selector and i have some expressions for 1 minigame, that works on MOTD, when server have motd "Lobby" it shows item with "Waiting for players.." but when MOTD is "InGame" in server selector shows "In Game... you can'! join". And now to the issue, i have lobby server (Paper 1.12.2) and minigame (Paper 1.8.8) with different version but when i look at real motd of minigame server (http://prntscr.com/nvhzb0) it is what i need but when i parse that placeholder on lobby server (http://prntscr.com/nvhzr2) it shows something different

### Expected behaviour
> What should PlaceholderAPI do?

Shows correct MOTD

### Actual behaviour
> What does PlaceholderAPI actually do?

Showing incorrect data of MOTD

### How to reproduce
> What steps did you made, to get this bug?

1.  Changed server version of Minigame
2. Pinger started showing incorrect MOTD

**Comment by aBo0oDyy** [comment]
Are you sure you're pinging the correct server? Make sure that you set the server IP and Port correctly.
If so, check you pinger check interval in PlaceholderAPI config, its 30 seconds by default `check_interval: 30`, change it to 1 or anything you want and see if that works.

**Comment by XArcadeXx** [comment]
I ping correct IP and port, nothing after changed interval

**Comment by aBo0oDyy** [comment]
did you restart the server ? not so sure if that is needed but try restarting the server and see

**Comment by XArcadeXx** [comment]
http://prntscr.com/nvij7i
Yeah, i restarted

**Comment by extendedclip** [comment]
If a plugin changes the MOTD, the expansion will not get it.... The expansion gets the MOTD specified from the server, thats it.

**Comment by XArcadeXx** [comment]
But i using 1.12.2 minigame with same method and that works...

**Comment by XArcadeXx** [comment]
Same minigame, same settings but paper 1.12.2

**Comment by XArcadeXx** [comment]
http://prntscr.com/nviki5
