### ISSUE TITLE
Wiki: Update FAQ-question

### ISSUE THREAD

**Issue by Andre601** [PlaceholderAPI/PlaceholderAPI#127]
[New placeholders/plugin]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=feature_request.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki
[FAQ]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/FAQ
### Notes
This template is for **requesting changes to the wiki** and not for reporting bugs or requesting additions for the wiki!  
If you want your placeholders added, use the [New placeholders/plugin] template.  
For bug reports, use the [Bug report] template.

Also make sure, that your requested change isn't already made in the [wiki] or listed in the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [ ] Placeholder(s) changed.
- [ ] New placeholder(s).
- [ ] Plugin no longer supports PlaceholderAPI and/or was deleted.
- [x] Other: Changes to the wiki-page [FAQ]

### Change
The [first question in the FAQ](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/FAQ#it-only-shows-placeholder-and-not-the-variable) needs a small change.
Right now it mentions the following stuff.

![image](https://user-images.githubusercontent.com/11576465/58764312-eca5f100-8565-11e9-905a-1a1061712fb7.png)

You should add the following to the list:
* The plugin that should use the placeholder actually supports PlaceholderAPI.
For a list of plugins supporting PlaceholderAPI go [here](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI).

**Comment by aBo0oDyy** [comment]
Added.
Thank you 😄
