### ISSUE TITLE
Nicky placeholder doesn't include nickname prefix

### ISSUE THREAD

**Issue by BlackBeltPanda** [PlaceholderAPI/PlaceholderAPI#129]
[New placeholders/plugin]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=feature_request.md
[Request change]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request.md
[Spigot page]: https://www.spigotmc.org/resources/6245/
[Jenkins page]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issue]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

### Notes
This template is for **reporting a bug** and not for requesting changes to the wiki!  
If you want your placeholders added or updated, use the [New placeholders/plugin] or [Request change] template.

Also make sure, that you use the latest version of PlaceholderAPI from either the [Spigot page] or the [Jenkins page] and that your 
issue isn't already listed in the [issue] page.

### Issue
> What is the issue? Describe it like you would tell a friend.

The Nicky placeholder doesn't include the nickname prefix set in Nicky's config.

### Expected behaviour
> What should PlaceholderAPI do?

The placeholder should include the prefix.

### Actual behaviour
> What does PlaceholderAPI actually do?

The placeholder does not include the prefix.

### How to reproduce
> What steps did you made, to get this bug?

1. Set a nickname prefix in Nicky's config.
2. Set a nickname with Nicky.
3. Print the Nicky placeholder to chat and notice it does not include the prefix.

**Comment by aBo0oDyy** [comment]
What is the placeholder ? `%player_name%` ??
If so, use `%player_displayname%`.. or you can use another placeholder to display the prefix.
Check the placeholders list in the [wiki](https://helpch.at) for all placrholders

**Comment by BlackBeltPanda** [comment]
The placeholder is "%nicky_nickname%".

**Comment by aBo0oDyy** [comment]
From the placeholder name, it meant to return the nickname and not the nick name with the prefix.

> The placeholder is "%nicky_nickname%".
> 
> For the time being, I've worked around the issue with the javascript placeholder expansion using:
```
format_nick:
  expression: '"%nicky_nickname%" == "%player_displayname%"'
  type: boolean
  true_result: '%player_name%'
  false_result: ~{nicky_nickname}
```

this is the old way of making a JS placeholder, download the latest js expansion and check [JS expansion wiki](https://github.com/PlaceholderAPI/Javascript-Expansion/wiki) for more info about setting up a js placeholder.

**Comment by BlackBeltPanda** [comment]
Thanks, I'll look into the new JS placeholders.
As for the Nicky placeholder, if I didn't want the prefix, I'd set it blank in the Nicky config. I think it make sense to return the prefix as it's part of how Nicky's intended to display the nickname. Barring that, another placeholder to return the prefix would work. Something like "%nicky_prefix%", maybe.

**Comment by aBo0oDyy** [comment]
From what i understood, you want to return the prefix if theres no nickname and that can be done using JS placeholders.
If you don't have any other questions, please close the issue please.

If you need help with JS placeholder, open an issue in JS repository please.

**Comment by BlackBeltPanda** [comment]
Other way around, but yeah. I want it to prefix the nickname with the prefix set in Nicky's config. If there's no nickname, then it shouldn't display the prefix.

 It's definitely do-able with JS, so I'll close the issue, but following that logic there's a lot of existing placeholders than can be replaced with JS.
