### ISSUE TITLE
cant download minetopiasdb

### ISSUE THREAD

**Issue by TheCompieter** [PlaceholderAPI/PlaceholderAPI#130]
i can't download minetopiasdb placeholder for papi 
/papi ecloud download minetopiasdb
papi version is 2.10.2
server version 1.12.2

**Comment by aBo0oDyy** [comment]
This plugin doesn't have an expansion in [the cloud](https://api.extendedclip.com/home/).
It probably have a built-in expansion, so you don't have to download anything.
if the placeholders don't work, try restarting the server and then try them using PAPI parse command `/papi parse me/Player %placeholder%`

**Comment by TheCompieter** [comment]
srry it is a bug in the plugin itself i am now talking too the author itself
