### ISSUE TITLE
PAPI reload question

### ISSUE THREAD

**Issue by OnlyNoobDied** [PlaceholderAPI/PlaceholderAPI#135]
When reloading PAPI config settings using `/papi reload`, all the expansions being unregistered. After configuration reloaded, only the expansions that put inside PlaceHolderAPI expansions folder being register. If the plugin [`Using placeholders from PlaceholderAPI in your plugin`](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Hook-into-PlaceholderAPI#using-placeholders-from-placeholderapi-in-your-plugin) won't register automatically. 

Is there any ways to solve this problem? You might add a method that can detect papi is reloading so the plugin can register it manually.

**Comment by darbyjack** [comment]
There already is. Set the persist Boolean to true.
