### ISSUE TITLE
Multiple outdated/wrong informations

### ISSUE THREAD

**Issue by Andre601** [PlaceholderAPI/PlaceholderAPI#136]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

## Please read
This template is only for requesting new information to be added to the wiki or for updating of already existing information!  
Please use the [Request change (PlaceholderAPI)] template to ask for additions/changes to the plugin PlaceholderAPI.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already have the change and that there isn't a issue about this change on the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [ ] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [x] Other: Outdated (and no longer needed) information 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

The wiki of placeholderapi has some outdated information which should be removed or updated.

#### Navbar
- `EZPlaceholderhook (deprecated)` no longer links to any header in the [`Hook into PlaceholderAPI`](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Hook-into-PlaceholderAPI) page.

#### [Hook into PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Hook-into-PlaceholderAPI)
- The [Notes](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Hook-into-PlaceholderAPI#notes) mention the now removed EZPlaceholderHook, which should be removed

**Comment by aBo0oDyy** [comment]
Thank you for reporting that.
I've just updated them.
