### ISSUE TITLE
Missing API specification in plugin.yml for 1.14.

### ISSUE THREAD

**Issue by mibby** [PlaceholderAPI/PlaceholderAPI#137]
```
[13:22:52] [Server thread/WARN]: Plugin PlaceholderAPI v2.10.3-DEV-76 does not specify an api-version.
```

**Comment by darbyjack** [comment]
It's a warning, nothing to worry about.

**Comment by Andre601** [comment]
Should still have it tho.
Could be 1.12 iirc which would just let spigot 1.13+ know that it uses old apis...

Or just make it 1.13 since spigot 1.12 and older don't have this check anyway and PlaceholderAPI uses never libraries.
