### ISSUE TITLE
Placeholder Request for MSPT in Server 

### ISSUE THREAD

**Issue by CGDoctor8** [PlaceholderAPI/PlaceholderAPI#138]
**Type**
New placeholder

**For**
Default Category Server

MSPT (Milliseconds per tick) is a value that is commonly use for debugging lag in Spigot and Paper Spigot timing reports, as well as a default metric in the single player f3 menu(See Below). MSPT has the advantage of quantifying how much lag current addons/config settings add or remove then "It's at 20TPS! that means no lag!" and personally think it would be nice to have it accessible via Placeholder to use in plugin's like Animated Tab or DeluxeMenus for ease of access

![image](https://user-images.githubusercontent.com/39572468/60692886-49face00-9e95-11e9-8431-b829067be171.png)

Screen shot taken from carpet mod
![image](https://user-images.githubusercontent.com/39572468/60692900-54b56300-9e95-11e9-8c47-d1e46fdc190a.png)

**Comment by Andre601** [comment]
You should ask for this on the repository of the server-expansion ([link](https://GitHub.com/PlaceholderAPI/Server-Expansion))

Also should you use the templates next time. They were made for reasons.

**Comment by CGDoctor8** [comment]
Sorry for the messup i will move the issue over to the appropriate repository and use the desired template
