### ISSUE TITLE
[Placeholders request] ajParkour

### ISSUE THREAD

**Issue by ajgeiss0702** [PlaceholderAPI/PlaceholderAPI#139]
I have added placeholders for my plugin [ajParkour](https://www.spigotmc.org/resources/ajparkour-rewards-actionbar-1-7-10-1-14-2-specific-score-rewards.60909/).

- **%ajpk_stats_top_name_<number>%** - Returns the name of the person in top position number <number>.
- **%ajpk_stats_top_score_<number>%** - Returns the score of the person in top position number <number>.
- **%ajpk_stats_highscore%** - Returns the player's high score.

**Comment by darbyjack** [comment]
Added https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#ajparkour
