### ISSUE TITLE
uhh factionsuuid?

### ISSUE THREAD

**Issue by ItsAlpal** [PlaceholderAPI/PlaceholderAPI#14]
ive got factionsuuid, a papi-supported scoreboard plugin, and papi itself.
i have added placeholders to scoreboard but idk where on earth to get the expansion.
its not in /papi ecloud download.
its not in ur website
its not in /papi ecloud list
pls, @extendedclip need ur help

**Comment by DoNotSpamPls** [comment]
FactionsUUID has the placeholders built in to it, you don't need to download any extensions.
You can see the file [here](https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/util/ClipPlaceholderAPIManager.java)

**Comment by ItsAlpal** [comment]
yes but how come it didnt work when i did it?

**Comment by DoNotSpamPls** [comment]
Maybe you used the wrong identifier, it uses `factionsuuid`. 
Example: `%factionsuuid_player_name%`

**Comment by ItsAlpal** [comment]
nope i certainly used factionsuuid. even copy and paste straight from papi website. no luck

**Comment by DoNotSpamPls** [comment]
You may be able to get better help on [PAPI's Discord server](https://discord.gg/FtArYRQ), GitHub is more useful as a bug tracker.

**Comment by ItsAlpal** [comment]
ok thanks. im in australia. ill have 2 try tomorrow. i think about 8pm CST

**Comment by ItsAlpal** [comment]
having no luck on discord. sending a screenshot here so if anyone might be able to help it would be great (plugin: infoboard reborn):
in-game:
![capture](https://user-images.githubusercontent.com/27193116/39027148-2086a444-4483-11e8-9509-4d359261a540.PNG)
config file (board.yml):
`InfoBoard:
  '1':
    ShowTime: 20
    global:
      default:
        Title: '&4&lFactions'
        Rows:
        - '&b&l%player_name% &8>>'
        - '&7Rank &3> &f%vault_rank%'
        - '&7Balance &3> &f$%vault_eco_balance_formatted%'
        - '&8x=&7%player_x% &8y=&7%player_y% &8z=&7%player_z%'
        - '&7-=-'
        - '&b&l%factionsuuid_faction_name% &8>> &b&o$%factionsuuid_faction_bank_balance%'
        - '&7Power &3> &f%factionsuuid_player_power%&3/&f%factionsuuid_player_maxpower%'
        - '&7Online &3> &f%factionsuuid_faction_online%&3/&f%factionsuuid_faction_size%'
        - '&7-=-&l'
        - '&7%server_time_EE, dd MMM, YYYY%'
        - '&7%server_time_hh:mm a%  &7&oTZ: %server_time_zz%'
        - '&e<website>'
      Owner:
        Title: '&4&lFactions &3> &c&oStaff'
        Rows:
        - '&b&l%player_name% &8>>'
        - '&7Rank &3> &f%vault_rank%'
        - '&7Balance &3> &f$%vault_eco_balance_formatted%'
        - '&8x=&7%player_x% &8y=&7%player_y% &8z=&7%player_z%'
        - '&7-=-'
        - '&b&l%factionsuuid_faction_name% &8>> &b&o$%factionsuuid_faction_bank_balance%'
        - '&7Power &3> &f%factionsuuid_player_power%&3/&f%factionsuuid_player_maxpower%'
        - '&7Online &3> &f%factionsuuid_faction_online%&3/&f%factionsuuid_faction_size%'
        - '&7-=-&l'
        - '&b&lStaff &8>>'
        - '&7%server_ram_used%&8mb&3/&7%server_ram_max%&8mb'
        - '&7Vanished &3> &f%premiumvanish_isvanished%'
        - '&f&7-=-'
        - '&7%server_time_EE, dd MMM, YYYY%'
        - '&7%server_time_hh:mm a%  &7&oTZ: %server_time_zz%'`

**Comment by ItsNathanG** [comment]
Issue resolved on Discord.

For anyone looking for a solution: was fixed after @ItsAlpal updated to the latest version of PlaceholderAPI.
