### ISSUE TITLE
New minigame placeholders: RageMode

### ISSUE THREAD

**Issue by montlikadani** [PlaceholderAPI/PlaceholderAPI#143]
This plugin found on https://www.spigotmc.org/resources/69169/

I would like to add the registered placeholders for this plugin.
Here's a list of placeholders: https://github.com/montlikadani/RageMode/wiki/PlaceholderAPI-placeholders

**Comment by aBo0oDyy** [comment]
Added, Thanks for letting us know.
You can find them [here](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#ragemode).
