### ISSUE TITLE
Add Quests-Expansion to Wiki

### ISSUE THREAD

**Issue by PikaMug** [PlaceholderAPI/PlaceholderAPI#145]
### Type
> What kind of change is it? (Multiple selections possible)
- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

An expansion for Quests has been posted to the eCloud. This is in addition to its support for other placeholders per #79 

https://api.extendedclip.com/expansions/quests/

**Comment by aBo0oDyy** [comment]
[Added](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#quests).
Thanks for supporting PlaceholderAPI.
