### ISSUE TITLE
TABLIST %vault-rank% error

### ISSUE THREAD

**Issue by xOzzy7** [PlaceholderAPI/PlaceholderAPI#146]
This comes up in an error.txt folder on the TABlist plugin I use, Not sure what i'm doing wrong

found character '%' that cannot start any token. (Do not use % for indentation)
 in 'reader', line 126, column 13:
      _OTHER_: "%vault-prefix%"

The TABlist config.yml folder. 

# PLACEHOLDERS
# %online% = online count
# %maxplayers% = amount of slots on server
# %ping% = ping of player
# %nick% = nickname of player
# %ip% = IP of player
# %tps% = TPS of server
# %time% = for example 20:30:00
# %date% = current date, configurable below
# %rank% = permission group of player, output can be modified below
# %money% = money of player
# %deluxetag% = tag from plugin DeluxeTags
# %world% = name of world where player is
# %worldonline% = amount of players in the same world, might be useful with per-world-playerlist enabled
# %canseeonline% = similar to online, but doesn't count vanished players
# %staffonline% = amount of staff online, groups can be defined below
# %canseestaffonline% = combination of those 2 above
# %faction% = if a faction plugin is installed..
# %health% = health of player
# %memory-used% = used RAM memory of server
# %memory-max% = total RAM memory of server
# %memory-used-gb% = in GB
# %memory-max-gb% = in GB
# %vault-prefix% = chat prefix of player set in Vault
# %vault-suffix% = chat suffix of player set in Vault
# %xPos% = X position of player
# %yPos% = Y position of player
# %zPos% = Z position of player
# %afk% = if player is afk or not, MEASURED BY ESSENTIALS or AutoAfk
# %essentialsnick% = nickname of player set by essentials (if no nickname is set, uses player's name)
# %deaths% = deaths of a player
# plugin also supports PlaceholderAPI

change-nametag-prefix-suffix: true #Warning! Disabling will break sorting of players in tablist!
change-tablist-prefix-suffix: true
enable-header-footer: true

#20 ticks = 1 second (the popular "TPS" word)
#if you want to use animated prefix/suffix, you need to decrease this to 1 or 2 (depending on fastest animation) to make them work
nametag-refresh-interval-ticks: 20
tablist-refresh-interval-ticks: 20

#using very low interval to allow animations to work as expected
#if you aren't using any animations, increase this to save cpu
header-footer-refresh-interval-ticks: 1

#VERY EXPERIMENTAL !
#IF YOU EXPERIENCE ANY ISSUES CONTACT ME
unlimited-nametag-prefix-suffix-mode:
  enabled: false
  
  #modifying names of NPCs to avoid empty names on NPCs of online players
  #this blocks any other attemps to change the name visibility or anything, so you need to disable it if you are using some citizens addon that changes their name
  #needs a relog to see the change
  modify-npc-names: false

header:
  - "%animation:ServerName%"
  - "&6&lRank: %rank%"
  - "&7&l>> %animation:Welcome%&3 &l%nick%&7&l! &7&l<<"
  - "&7Online players: &f%online%"
  - "&6Online staff: &e%staffonline%"
  - "%animation:ping-tps%"
  - ""
  - "&7&l Used memory: %memory-used% MB / %memory-max% MB"
  - "%animation:MyAnimation1%"
# - "%animation:versions%" #requires ViaVersion or ProtocolSupport
footer:
  - "%animation:MyAnimation1%"
  - ""
  - "%animation:vote%"
  - ""
  - "%animation:time%"
  - ""
  - "&7Visit our webpage %animation:web%"
  
#SERVERS 1.9+
#this plugin overrides any other attemps to change collision rule, so it needs to be configured here
enable-collision: true

#PING - ping of players
#HEARTS - health of players
#DEATHS - total amount of deaths of players
#CUSTOM - custom configurable placeholder
#NONE - disabled
tablist-objective: PING

#if tablist-objective: CUSTOM
tablist-objective-custom-value: "%some_placeholderapi_placeholder%"

#preventing players in spectator gamemode from appearing at the bottom of tablist
#the spectator will still see himself incorrectly, but will look correctly to others
#disabled by default so you don't think it's obvious and every plugin has this
do-not-move-spectators: false

group-sorting-priority-list:
  - "Owner"
  - "Admin"
  - "Mod"
  - "Helper"
  - "Builder"
  - "Premium"
  - "Player"
  - "default"

#used for %staffonline% variable
staff-groups:
  - "Admin"
  - "Mod"
  - "Owner"
  - "Moderator"
  - "Helper"

#better showing of %rank% value
rank-aliases:
  Owner: "&8(&cOwner&8) "
  Admin: "&8(&cAdmin&8) "
  Mod: ""
  Premium: ""
  Ultra: ""
  Legend: ""
  Titan: ""
  Youtuber:""
  
  #default setting for other groups
  _OTHER_: "%vault-prefix%"

# - list of options
#tabprefix = prefix in tablist with no known limit of characters
#tagprefix = prefix above player's character (no limit if unlimited-nametag-prefix-suffix-mode is ENABLED)
#tabsuffix = suffix in tablist with no known limit of characters
#tagsuffix = suffix above player's character (no limit if unlimited-nametag-prefix-suffix-mode is ENABLED)
#header = per player or per group header
#footer = per player or per group footer
#belowname = a line under player's name (REQUIRES unlimited-nametag-prefix-suffix-mode ENABLED)
#abovename = a line above player's name (REQUIRES unlimited-nametag-prefix-suffix-mode ENABLED)
#customtabname = change a display name of player in tablist
#customtagname = change a display name of player in name tag (requires unlimited-nametag-prefix-suffix-mode enabled)

#you don't need to use all of these values, you can delete the empty values to not have this config full of "spam"
#if no personal (or per group) header/footer is set, the default one from above will be used

Groups:
  Owner:
    tabprefix: "&0&l[&a&lOwner&0&l] &a"
    tagprefix: "&2&lOwner &a"
    header:
      - "ur server man"
    footer:
      - "welcome"
      - ""
      - "THIS IS NOT A BUG"
      - "DO NOT REPORT THIS AS A BUG"
      - "This is per-group header/footer"
      - "applied to Owner group"
      - "You can modify this or delete in config in Groups section"
  Admin:
    tabprefix: "&0&l[&4&lAdmin&0&l] &1"
    tagprefix: "%animation:admin_prefix%"
  Player:
    tabprefix: "&0&l[&7&lPlayer&0&l] &3"
    tagprefix: "&2&lPlayer &3"
    
  #any other group not defined above
  _OTHER_:
    tabprefix: "%rank% "
    tagprefix: "%rank% "
    tabsuffix: "%afk%"
    tagsuffix: "%afk%"
    customtabname: "%essentialsnick%"
    customtagname: "%essentialsnick%"

#personal settings, override group settings
Users:
  md_5:
    tabprefix: "&6&lSpigot &a"
    tagprefix: "&6&lDev &a"
    tabsuffix: ""
    tagsuffix: ""
    abovename: "Hi"
    belowname: "There"
    customtabname: "MessageDigest5"
    customtagname: "MessageDigest5"
    
#list of worlds with different settings than default, other worlds will use settings from above
per-world-settings:
  world1:
    header:
      - "an example of world with custom"
    footer:
      - "header/footer and prefix/suffix"
    Groups:
      Owner:
        tabprefix: "&0&l[&a&lOwner&0&l] &a"
        tagprefix: "&2&lOwner &a"
        header:
          - "ur server man"
        footer:
          - "welcome"
      Admin:
        tabprefix: "&2&lAdmin &1&l"
        tagprefix: "&2&lAdmin &1&l"
      Player:
        tabprefix: "&5&lPlayer &3&l"
        tagprefix: "&5&lPlayer &3&l"
    Users:
      Player1:
        tabprefix: ""
        tagprefix: ""
        tabsuffix: ""
        tagsuffix: ""

#setting output of some placeholders        
placeholders:
  deluxetag-yes: "< %value% >"
  deluxetag-no: "&oNo Tag :("
  faction-yes: "< %value% >"
  faction-no: "&2Wilderness"
  afk-yes: " &4*&4&lAFK&4*&r"
  afk-no: ""
  # %date%
  date-format: "dd.MM.yyyy"
  # %time%, pick one of these formats
  time-format: "[HH:mm:ss / h:mm a]"
  
  #if time doesn't show correctly, you can change the time it shows
  #setting to -1 will make it show 1 hour less than it does currently, 1 makes it show one hour more than currently, 0 does nothing
  time-offset: 0
  
disable-features-in-worlds:
  header-footer:
    - disabledworld
  tablist-names:
    - disabledworld
  nametag:
    - disabledworld
  tablist-objective:
    - disabledworld
  bossbar:
    - disabledworld

**Comment by Funny-cube** [comment]
Please throw the error into a paste so we can see it

**Comment by xOzzy7** [comment]
Sorry i'm very new to this and the terms, how do i throw it into a paste?

**Comment by Funny-cube** [comment]
[](https://paste.helpch.at/)

**Comment by xOzzy7** [comment]
Cheers, do i just paste the URL after?

**Comment by xOzzy7** [comment]
https://paste.helpch.at/nohepafike.pl

**Comment by Funny-cube** [comment]
Seems it was just a simple syntax error,

Here's an updated config https://paste.helpch.at/ikadukuyup.makefile

**Comment by xOzzy7** [comment]
Thanks a tonne :D
