### ISSUE TITLE
WorldGuard Expansion not working with WorldGuard 7

### ISSUE THREAD

**Issue by AmazedMender16** [PlaceholderAPI/PlaceholderAPI#147]
### Issue
> What is the issue? Describe it like you would tell a friend.

The WorldGuard Expansion is not working with WorldGuard 7 

### Expected behaviour
> What should PlaceholderAPI do?

I would like it to work like with 1.12.2

### Actual behaviour
> What does PlaceholderAPI actually do?

Errors out when parsing the placeholder.
https://pastebin.com/qWCqLYtp

### How to reproduce
> What steps did you made, to get this bug?

Setup a server with the latest WorldGuard, WorldEdit, PlaceholderAPI, download the WorldGuard Expansion, reload Papi and parse on of the placeholders.

**Comment by Andre601** [comment]
Please report this to the right place, namely https://github.com/PlaceholderAPI/WorldGuard-Expansion.
