### ISSUE TITLE
PingTest supports PAPI now

### ISSUE THREAD

**Issue by lucamarcelpeters** [PlaceholderAPI/PlaceholderAPI#150]
Hey there. First of all, thank you for that great plugin! I created a simple plugin, to let players check their own and other players latency. For the messages I implemented your API as soft depending.

I don't add new placeholders, because in 'Player' is the ping already implemented. But server owners can use placeholders from other plugins/extensions.

https://www.spigotmc.org/resources/pingtest.69580/

**Comment by aBo0oDyy** [comment]
Thank you for supporting PlaceholderAPI plugin.
Your plugin has been added to the [Plugins using PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#p) page.
