### ISSUE TITLE
Playtime Download

### ISSUE THREAD

**Issue by killerbad21** [PlaceholderAPI/PlaceholderAPI#153]
### Issue
> What is the issue? Describe it like you would tell a friend.

eCloud for Playtime will download but will not hook on 1.14.3

### Expected behaviour
> What should PlaceholderAPI do?

Allow us to use 
%playtime_player%
%playtime_time%
%playtime_timesjoined%
%playtime_serveruptime%

### Actual behaviour
> What does PlaceholderAPI actually do?

will not hook so cant get 
%playtime_player%
%playtime_time%
%playtime_timesjoined%
%playtime_serveruptime%
to work

### How to reproduce
> What steps did you made, to get this bug?

1.

**Comment by aBo0oDyy** [comment]
Hey @killerbad21,

PlayTime expansion isn't handled by us, you'll have to contact its author `f64_rx` or open an issue in the [expansion's repository](https://github.com/Twi5TeD/Expansion-PlayTime/issues).

Good luck.
