### ISSUE TITLE
My New Plugin PAPI Support

### ISSUE THREAD

**Issue by Seth16225** [PlaceholderAPI/PlaceholderAPI#158]
Hello, I would like to add my plugin to the list of papi supported plugins.

https://www.spigotmc.org/resources/pvpstats-plugin.69984/

My placeholders:
%pvpstats_kills%
%pvpstats_deaths%
%pvpstats_killstreak%
%pvpstats_kdr%

hardcoded. no download required :)

**Comment by aBo0oDyy** [comment]
Added in [Placeholders page](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#pvpstats-plugin) and [Plugins using PlaceholderAPI page](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#p).

Thanks for supporting PlaceholderAPI plugin.
