### ISSUE TITLE
New plugin placeholders for spark

### ISSUE THREAD

**Issue by lucko** [PlaceholderAPI/PlaceholderAPI#163]
### Type
> What kind of change is it? (Multiple selections possible)

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

Placeholders for the [spark](https://github.com/lucko/spark) plugin.

```
%spark_tps%
%spark_tps_5s%
%spark_tps_10s%
%spark_tps_1m%
%spark_tps_5m%
%spark_tps_15m%
%spark_cpu_system%
%spark_cpu_system_10s%
%spark_cpu_system_1m%
%spark_cpu_system_15m%
%spark_cpu_process%
%spark_cpu_process_10s%
%spark_cpu_process_1m%
%spark_cpu_process_15m%
```

The placeholders are integrated directly into the plugin (not an expansion).

**Comment by darbyjack** [comment]
Added! https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders/4298966f05ce5386ce20392b4c3e3ac3b19a08a7

Thanks for using PlaceholderAPI!
