### ISSUE TITLE
PlaceholderExpansion example causing an IllegalAccessException

### ISSUE THREAD

**Issue by Leon167** [PlaceholderAPI/PlaceholderAPI#164]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

### Type
> What kind of change is it? (Multiple selections possible)

- [ ] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [x] Other: Small change to the PlaceholderExpansion wiki 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

The [PlaceholderExpansion](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/PlaceholderExpansion) example (seperate jar) is a class with a default constructor so it is package private. If someone is using this class, it won't be instantiated by PAPI because PAPI will throw an IllegalAccessException when trying to create an instance. Saw someone on the PAPI discord server using the default class (he couldnt get his expansion loaded). Would be nice if you can make the example class public.

**Comment by aBo0oDyy** [comment]
Thank you so much for letting us know, and we're sorry for this mistake.
I've just fixed them.
