### ISSUE TITLE
DeluxeCombat Placeholders

### ISSUE THREAD

**Issue by timderspieler** [PlaceholderAPI/PlaceholderAPI#165]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

## Please read
This template is only for requesting new information to be added to the wiki or for updating of already existing information!  
Please use the [Request change (PlaceholderAPI)] template to ask for additions/changes to the plugin PlaceholderAPI.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already have the change and that there isn't a issue about this change on the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [X] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

Placeholders for the DeluxeCombat plugin:
( https://www.spigotmc.org/resources/63970/ )

> %deluxecombat_ranking_points%
%deluxecombat_ranking_kills%
%deluxecombat_ranking_deaths%
%deluxecombat_ranking_combatlogs%
%deluxecombat_ranking_kd%
%deluxecombat_ranking_rank%
%deluxecombat_in_combat%

The placeholders are integrated into the plugin directly ( no expansion )

**Comment by aBo0oDyy** [comment]
Added in [Placeholders](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#deluxecombat) page and [Plugins using PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#d) page.

Thanks for supporting PlaceholderAPI.
