### ISSUE TITLE
Nukkit Support for PaPi

### ISSUE THREAD

**Issue by GamerDaniel3000** [PlaceholderAPI/PlaceholderAPI#166]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki
[Pull Requests]: https://github.com/PlaceholderAPI/PlaceholderAPI/pulls

## Please read
This template is only for requesting new functions to be added to PlaceholderAPI or for old one to be changed!  
Please use the [Request change (Wiki)] template to ask for additions/changes to the wiki.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already mention such a function/change and that there isn't a issue about this change on the [issues] page.

We recommend to [open a Pull Request][Pull Requests] for making changes to PlaceholderAPI's code.

### Type
> What kind of request is this? (Multiple selections possible)

- [x] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Info
> What is the change?  
> Please provide as much information (including links, images and code-snippeds) as possible.

Hey I really love this API very much but unfortunately I have a Nukkit server and had to realize that this plugin is only available for Bukkit and spigot ... Nukkit is the same as the Minecraft Bedrock version of Bukkit. Many of the plughins available for Bukkit and Spigot are also available for Nukkit such as PlotSquared, Economy, LuckPerms or MyMap. I would be pleased if at least the placeholder for PlotSquared would be available for Nukkit ... Thanks for the patience and have a nice day.
NukkitX Website: https://nukkitx.com
NukkitX GitHub Repository: https://github.com/NukkitX/Nukkit

**Comment by GMatrixGames** [comment]
I am currently working on a private version, that I can modify to be public.
I can update here when it happens.

**Comment by GamerDaniel3000** [comment]
Nice

**Comment by GMatrixGames** [comment]
@GamerDaniel3000 I have successfully done it, currently working on different expansions.

Can you send a list of expansions to port over first.

![image](https://user-images.githubusercontent.com/25112532/66441071-b4c72280-ea0b-11e9-9f10-bf0e30ab4f47.png)

**Comment by GMatrixGames** [comment]
Also, Sorry for the tag @extendedclip, but for this to work, it requires an update to the ecloud service, to allow for upload and download of expansions from it.

**Comment by GamerDaniel3000** [comment]
@GMatrixGames So a list of placeholders?

**Comment by GamerDaniel3000** [comment]
PlotSquared
Economy (If it has placeholder)
LuckPerms

For now.

**Comment by GMatrixGames** [comment]
@GamerDaniel3000 Can you let me know what Economy plugin you're using? Is it EconomyAPI?

**Comment by GamerDaniel3000** [comment]
Yeah

**Comment by GMatrixGames** [comment]
I will edit this message when I add the 2 others, but I've made the EconomyAPI one, if you can test to see if it works, that would be wonderful!


http://josephworks.ddns.net/papi-expansions/PAPI-Expansion-EconomyAPI.jar

**Comment by GamerDaniel3000** [comment]
@GMatrixGames 
It stays there at [PlaceholderAPI Nukkit] Placeholder extension registration initializing ...

**Comment by GMatrixGames** [comment]
It loads fine for me?
![image](https://user-images.githubusercontent.com/25112532/66702235-c0e90380-ecdb-11e9-9ab6-56baa8924af6.png)

**Comment by GamerDaniel3000** [comment]
Yeah for me too :D
Fixed

**Comment by GamerDaniel3000** [comment]
Can you import more expansions?

**Comment by GMatrixGames** [comment]
Yea

**Comment by GMatrixGames** [comment]
@GamerDaniel3000 Added PlotSquared

**Comment by extendedclip** [comment]
What y’all doing 😃

**Comment by GMatrixGames** [comment]
@extendedclip Currently, what this request issue has been turned into a place for people to get pre-release expansions for my PR for nukkit 😁

**Comment by extendedclip** [comment]
You have my support. Lately I have been busy with life so im glad to see you guys doing things like this. I can't say what 3.0 will hold as far as multi platform support but for now if your Nukkit version is working I salute you and port what you can! I will soon be dedicating time to focus on the team as well as the project and 3.0 will be here after that. I know @PiggyPiglet and @darbyjack have been doing a ton of work to prepare for it and it will be top notch compared to what it is now. Thank you for expanding the project and can't wait to see what the future holds with all of you contributing!!!!

Much love and keep at it!

-clip

**Comment by GMatrixGames** [comment]
Thanks for the support clip, it means a lot. Hope people can find this an actual useful port. If you want to see the code behind it, it's in PR #195
