### ISSUE TITLE
Add KitPvP placeholders to wiki

### ISSUE THREAD

**Issue by RobinDeBaets** [PlaceholderAPI/PlaceholderAPI#168]
### Type
- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
### Info

The plugin [KitPvP](https://www.spigotmc.org/resources/2-0-kitpvp-1-8-1-14-custom-kits-scoreboard-gui-levels-kill-streaks-abilities-more.27107/) has built-in PlaceholderAPI support and should be added to the wiki.
The placeholders can be found on their resource page.
Here's a copy:

```
%kitpvp_stats_kills% - The kills of a player
%kitpvp_stats_deaths% - The deaths of a player
%kitpvp_stats_kdr% - The kill : death ratio of a player
%kitpvp_stats_level% - The level of a player
%kitpvp_stats_experience% - The experience of a player
%kitpvp_player_killstreak% - The player's current kill streak
%kitpvp_player_kit% - The player's current kit
```

**Comment by aBo0oDyy** [comment]
Added to [Placeholders](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#kitpvp) and [Plugins using PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#k) pages.

Thanks for using PlaceholderAPI.
