### ISSUE TITLE
[Placeholder update] ajParkour

### ISSUE THREAD

**Issue by ajgeiss0702** [PlaceholderAPI/PlaceholderAPI#169]
I have added a new placeholder to my plugin ajParkour: **%ajpk_current%**

Also, my plugin supports other placeholders.

Thank you!

**Comment by aBo0oDyy** [comment]
Updated in [Placeholders](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#ajparkour) and Plugins using [PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#a) pages.

Thanks for supporting PlaceholderAPI
