### ISSUE TITLE
OtherPlayer ANY placeholder

### ISSUE THREAD

**Issue by ziemniok99** [PlaceholderAPI/PlaceholderAPI#173]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki
[Pull Requests]: https://github.com/PlaceholderAPI/PlaceholderAPI/pulls

## Please read
This template is only for requesting new functions to be added to PlaceholderAPI or for old one to be changed!  
Please use the [Request change (Wiki)] template to ask for additions/changes to the wiki.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already mention such a function/change and that there isn't a issue about this change on the [issues] page.

We recommend to [open a Pull Request][Pull Requests] for making changes to PlaceholderAPI's code.

### Type
> What kind of request is this? (Multiple selections possible)

- [x] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Info
> What is the change?  
> Please provide as much information (including links, images and code-snippeds) as possible.

Please replace all placeholders from OtherPlayer with just one %otherplayer_[player]_[placeholder]% It will return ANY placeholder using player specified. I think you are able to do that because u can use /papi parse for other player, if not It would be nice if u explain it why you can't do that. This would be very awesome feature for checking player. I think it could be useful for every user.
Thank you for creating an awesome plugin.

**Comment by aBo0oDyy** [comment]
Hey there,

Thanks for your suggestions, but there's another expansion does this. Its called [ParseOther](https://api.extendedclip.com/expansions/parseother/).
Please check it out and let me know if that's what you want or not.

**Comment by ziemniok99** [comment]
That is exacly what I needed. Thank you so much.

**Comment by ziemniok99** [comment]
Oh wait i tried using it but this happen: https://pastebin.com/zbtcePE4

**Comment by ziemniok99** [comment]
@aBo0oDyy

**Comment by aBo0oDyy** [comment]
Send the placeholder you tried please.

**Comment by ziemniok99** [comment]
%parseother_ziemniok9_player_ip%

**Comment by aBo0oDyy** [comment]
Its `%parseother_{ziemniok9}_{player_ip}%`.

**Comment by ziemniok99** [comment]
oh... I'll check :D

**Comment by ziemniok99** [comment]
Great it worked, but could you add placeholder when you use players UUID instead of player name?

**Comment by aBo0oDyy** [comment]
Contact the author of it, because I'm not the author and the expansion isn't open source (as far as I know).

**Comment by ziemniok99** [comment]
How Can I do that?

**Comment by aBo0oDyy** [comment]
He is in [HelpChat discord](https://helpch.at/discord), you can ask him there.
