### ISSUE TITLE
Please add GUIPlus

### ISSUE THREAD

**Issue by Leon338** [PlaceholderAPI/PlaceholderAPI#174]
- **[GUIPlus](https://www.spigotmc.org/resources/guiplus-simply-create-clickable-guis-supports-placeholderapi-1-7-1-14.38664/)**

- [x] Supports placeholders.
- [ ] Provides own placeholders. [Link]

**Comment by aBo0oDyy** [comment]
[Added](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#g).

Thanks for supporting PlaceholderAPI.
