### ISSUE TITLE
Add HPWizard placeholders on the PlaceholderAPI wiki

### ISSUE THREAD

**Issue by TheL0w3R** [PlaceholderAPI/PlaceholderAPI#175]
I've added PlaceholderAPI support on a recent version, I'd like to add it to the wiki!

Here's the plugin URL: https://www.spigotmc.org/resources/hpwizard.26821/

Here are the added placeholders:

- %hpw_house% -> The current wizard's house.
- %hpw_house_coloured% -> The current wizard's house with its color applied.
- %hpw_amount_of_spells% -> The amount of spells the wizard has.
- %hpw_housepoints% -> The points that the wizard's house has.
- %hpw_{house}_housepoints% -> The points that the specified house has.
- %hpw_hogwarts_last_winner% -> The last winner of the Hogwarts house cup.
- %hpw_hogwarts_last_winner_coloured% -> The last winner of the Hogwarts house cup with its color applied.
- %hpw_ministry_last_winner% -> The last winner of the Ministry house cup.
- %hpw_ministry_last_winner_coloured% -> The last winner of the Ministry house cup with its color applied.

**Comment by aBo0oDyy** [comment]
Added in [Placeholders](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#hpwizard) and [Plugins using PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#h) pages.

Thanks for supporting PlaceholderAPI.
