### ISSUE TITLE
Add BlockParty to placeholders wiki

### ISSUE THREAD

**Issue by RobinDeBaets** [PlaceholderAPI/PlaceholderAPI#177]
The [BlockParty expansion](https://api.extendedclip.com/expansions/blockparty/) for [BlockParty](https://www.spigotmc.org/resources/blockparty.7264/) is not listed on the Placeholder wiki. It should be added.

The following placeholders are available:
```
%blockparty_wins%
%blockparty_points%
%blockparty_gamesplayed%
```

Ecloud command: `/papi ecloud download BlockParty`

**Comment by Andre601** [comment]
You should use the right template next time...

**Comment by RobinDeBaets** [comment]
I'm sorry. For some reason it didn't give me the options to select a template. I don't remember which menu I used to open this issue.

**Comment by aBo0oDyy** [comment]
Added in [Placeholders](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#blockparty) and [Plugins using PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#b) pages.

Thanks for supporting PlaceholderAPI.
