### ISSUE TITLE
PlotSquared Wiki update

### ISSUE THREAD

**Issue by N0tMyFaultOG** [PlaceholderAPI/PlaceholderAPI#178]
### Type
> What kind of change is it? (Multiple selections possible)
- [X] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

I pushed an updated to the PlotSquared expansion earlier and updated some placeholders:
```diff
- %plotsquared_currentplot_members_size%
+ %plotsquared_currentplot_members%

+ %plotsquared_currentplot_members_added%
+ %plotsquared_currentplot_members_trusted%
+ %plotsquared_currentplot_members_denied%
+ %plotsquared_currentplot_x%
+ %plotsquared_currentplot_y%
```

**Comment by aBo0oDyy** [comment]
[Updated](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#plotsquared).

Thanks for using PlaceholderAPI.
