### ISSUE TITLE
PlotSquared-Expansion update v2.1

### ISSUE THREAD

**Issue by N0tMyFaultOG** [PlaceholderAPI/PlaceholderAPI#180]
### Type
> What kind of change is it? (Multiple selections possible)
- [X] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

```diff
+ %plotsquared_currentplot_xy%
+ %plotsquared_currentplot_rating%
+ %plotsquared_currentplot_biome%
```

**Comment by aBo0oDyy** [comment]
[Updated](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#plotsquared).

Thanks for letting us know.
