### ISSUE TITLE
argument me/playername not found in parse command.

### ISSUE THREAD

**Issue by Andre601** [PlaceholderAPI/PlaceholderAPI#185]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Spigot]: https://www.spigotmc.org/resources/6245/
[Jenkins]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

## Please read
This template is only for reporting bugs of PlaceholderAPI!  
If you want to request changes to the code of PlaceholderAPI, use the [Request change (PlaceholderAPI)] template.  
For changes to the wiki use the [Request change (Wiki)] template.

Please also make sure that you use the [latest release][Spigot] or the latest [developement build][Jenkins] and that your bug isn't already reported on the [issues] page.

**Please report issues with expansions/placeholders to the corresponding issue tracker! Only report it here if you can't find any place to report it!**

### Issue
> What is the issue? Describe it like you would tell a friend.

When using `/papi parse me %placeholder%` does PlaceholderAPI respond with "Failed to find player: me".
This also happens when using the actual player name.

### Expected behaviour
> What should PlaceholderAPI do?

It should recognize "me" or the player name and parse the placeholder.

### Actual behaviour
> What does PlaceholderAPI actually do?

Returns the above-mentioned message.

### How to reproduce
> What steps did you made, to get this bug?

1. Setup a 1.14.4 BungeeCord network
   - Proxy: Waterfall
   - Servers: PaperMC
   - IP-Forwarding: true
   - Proxy in online-mode and bungee enabled on backend server.
2. Install PlaceholderAPI 2.10.3
3. Install expansion of choice and reload PlaceholderAPI
4. Join Server (through proxy of course) and run the parse command.

**Comment by Funny-cube** [comment]
Do placeholders still work in other plugins?
ie. anything besides the parse command.

**Comment by Andre601** [comment]
> Do placeholders still work in other plugins?
> ie. anything besides the parse command.

No.
I for example use them in BungeeTablistPlus (I have the bridge plugin for it installed on the server), but for example `{viewer buildbattlepro_status_bb-1}` doesn't work.
![image](https://user-images.githubusercontent.com/11576465/65025827-b5522900-d937-11e9-9c55-ba921d077d80.png)

And according to the PlaceholderAPI page on the BTLP wiki do I just need to have PAPI and the expansion installed and running to show those placeholders.

**Comment by Andre601** [comment]
Could a reason be the world I'm in?

I use SlimeWorldManager and are in an SWM world... Perhaps it misses something that PAPI requires?

**Comment by aBo0oDyy** [comment]
Hello @Andre601,
I've just tried it in a new server, the first time it sent me that message, but when I rejoined it worked.
It seems to be working fine, so it might be because of another plugin. Try removing them and see if it works.

**Comment by Andre601** [comment]
I'm pretty sure it's not caused by another plugin...
The placeholder in the screenshot does work. I just forgot to add a $ at the start and now it shows the right value.
The parse command still doesn't work tho.

**Comment by Andre601** [comment]
I personally don't think this is a "question" and still a bug/issue....

**Comment by Andre601** [comment]
Would it help if I give my server setup?
It's a network using Waterfall and PaperMC.

**Comment by KleinDevDE** [comment]
I tried that mistake once.
**Paper version** git-Paper-652 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
**PlaceholderAPI version** 2.10.4


server log
```
> papi parse KleinDev %placeholder%
[10:55:34 INFO]: Failed to find player: KleinDev
[10:55:42 INFO]: UUID of player KleinDev is cdf5ce70-079a-487b-8b71-b0ad4ffb4fb3
[10:55:43 INFO]: KleinDev[/127.0.0.1:53476] logged in with entity id 95 at ([world]170.5, 73.0, 212.5)
> papi parse KleinDev %placeholder%
[10:55:48 INFO]: Failed to find player: KleinDev
> papi parse KleinDev %placeholder%
[10:55:51 INFO]: Failed to find player: KleinDev
> papi parse KleinDev %player_name%
[11:01:34 INFO]: Failed to find player: KleinDev
```

client log - `/papi parse me %a%`
```
[10:55:45] [Client thread/INFO]: Loaded 0 advancements
[10:56:14] [Client thread/INFO]: [CHAT] You don't have permission to do that!
[10:56:19] [Client thread/INFO]: [CHAT] [Server: Made KleinDev a server operator]
[10:56:20] [Client thread/INFO]: [CHAT] Failed to find player: me
```

client log - `/papi parse KleinDev $player_name% `
```
[11:01:22] [Client thread/INFO]: [CHAT] Failed to find player: KleinDev
```

**Comment by KleinDevDE** [comment]
After Disconneting on the server, the parse command works.
```
[12:42:58 INFO]: KleinDev lost connection: Disconnected
[12:42:58 INFO]: KleinDev left the game
> papi parse KleinDev %player_name%
[12:45:01 INFO]: KleinDev
[12:46:38 INFO]: UUID of player KleinDev is cdf5ce70-079a-487b-8b71-b0ad4ffb4fb3
[12:46:39 INFO]: KleinDev[/127.0.0.1:61460] logged in with entity id 4488 at ([world]167.82144111280894, 71.0, 230.28788039758197)
> papi parse KleinDev %player_name%
[12:46:41 INFO]: KleinDev
```

**Comment by Tanguygab** [comment]
Hey, I just noticed this issue, and wanted to take part of it.
So I started working on my server again a while ago, and noticed that the parse command doesn't work at all for anyone. I tried with `me`, `Tanguygab` and other players but it still didn't work.
I'm on PaperSpigot 1.8.8 with PAPI 2.10.5

BUT on my 1.15.2 test server, with PAPI 2.10.5 too, the player names and `me` does work.

**Comment by darbyjack** [comment]
@Tanguygab Please let me know if this fixes it. 
https://cdn.discordapp.com/attachments/256566347457101825/703802972093808700/PlaceholderAPI-2.10.6-DEV-BUILD_NUMBER.jar

**Comment by Andre601** [comment]
I'll test this too, because I still have this issue.
I also have a guess for my cause which is SlimeWorldManager - which I used - not saving specific infos.
I bet that now that I removed SWM now will the command work.

**Comment by Tanguygab** [comment]
> I'll test this too, because I still have this issue.
> I also have a guess for my cause which is SlimeWorldManager - which I used - not saving specific infos.
> I bet that now that I removed SWM now will the command work.

now that you say this, it's surely the problem because I have it too

**Comment by Tanguygab** [comment]
> @Tanguygab Please let me know if this fixes it.
> https://cdn.discordapp.com/attachments/256566347457101825/703802972093808700/PlaceholderAPI-2.10.6-DEV-BUILD_NUMBER.jar

It did the job, thanks ! But also, I tried on a server without SlimeWorldManager and it did work (without the dev-build) so yeah I guess it was the cause

**Comment by Andre601** [comment]
I can confirm this.
Running the same jar (Not the above dev build), on the same server, but with a normal world and not one from SWM makes the parse command work.
So we can blame SWM on that one for not saving player info where it should.

I'll close this as I trust @Tanguygab's response on testing this and believing it was fixed.
