### ISSUE TITLE
Where is displaying the time/date placeholder?

### ISSUE THREAD

**Issue by FrozenBeard** [PlaceholderAPI/PlaceholderAPI#188]
I swear im going mad, I cannot find what I need to use to get the date/time working as a place holder, this should be a default right? Showing the date is a core function. 
Not the in-game time, the real time and real date.

**Comment by aBooDyy** [comment]
Hello,
Check the `%server_time_<Format>%` placeholder [here](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#server).
This will placeholder will use the timezone of the machine/server that your Minecraft server is on.

**Comment by FrozenBeard** [comment]
Brilliant thanks, I thought this was talking about the world server time!

**Comment by aBooDyy** [comment]
No problem! Glad I could help.
