### ISSUE TITLE
Advancements placeholders

### ISSUE THREAD

**Issue by matahombres** [PlaceholderAPI/PlaceholderAPI#190]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

## Please read
This template is only for requesting new information to be added to the wiki or for updating of already existing information!  
Please use the [Request change (PlaceholderAPI)] template to ask for additions/changes to the plugin PlaceholderAPI.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already have the change and that there isn't a issue about this change on the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

#### Placeholders and explanation:

**```%Advancements_<advancement>%```**
Check if a player run placeholder have the id advancement ID

**```%Advancements_player_<player>;<advancement>%```**
Check if a player send have a advancement ID

**```%Advancements_playerList_<player>%```**
Return a list of advancements with RAW format:
id_adv;true|false,id_adv;true|false,id_adv;true|false..... (This method is to format as you want)

**```%Advancements_playerList_<player>,<command>%```**
Return a list of advancements with RAW format and send to the command

**```%Advancements_playerListFormat_<player>%```**
Return a list of advancements with a simple format:
Adv_id: &atrue
Adv_id: &cfalse

**Comment by aBooDyy** [comment]
[Added](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#advancements).

Thanks for using PlaceholderAPI!

**Comment by Ansandr** [comment]
Please, update expansion.
Add placeholder:

`%Advancements_completedAmount%`
return a int number of completed achievements.

**Comment by Andre601** [comment]
> Please, update expansion.
> Add placeholder:
> 
> `%Advancements_completedAmount_<player>%`
> return a int number of completed achievements for player.

You can PR the change yourself if you want.
Just take a look at the [Wiki README](https://github.com/PlaceholderAPI/PlaceholderAPI/blob/docs/wiki/wiki/README.md) to find out how.

**Comment by Ansandr** [comment]
I would PR, but did not find the source Advancements expansion. I will have to do it all over again.

**Comment by matahombres** [comment]
I'll add it, sorry for taking so long.
It would have been faster to contact me by discord (my name is the same in spigot) and I have a discord server.
I will also add a repository of the advancements
@Ansandr
