### ISSUE TITLE
PlaceholderAPI Lags

### ISSUE THREAD

**Issue by Hite29** [PlaceholderAPI/PlaceholderAPI#191]
### Issue
PlaceholderAPI making a lag? 

### Expected behaviour
> What should PlaceholderAPI do?
Only working.

### Actual behaviour
> What does PlaceholderAPI actually do?
Working but making lags, there is a screen from timings 
https://imgur.com/a/wHETROT

### How to reproduce
> What steps did you made, to get this bug?
1. Nothing, these lag are all time.

**Comment by Andre601** [comment]
Does it actually lag on the server?
A high percentage doesn't mean high lag.

**Comment by aBooDyy** [comment]
As Andre said and is it actually all time? just check the tasks in that class, all of them run once but after x time (the tasks to register the expansions).
Unless it's about other tasks but I don't think so.

**Comment by NEZNAMY** [comment]
> Single
> count(1)
> lag all the time

Are you sure about that ?
