### ISSUE TITLE
TrickOrTreat placeholders

### ISSUE THREAD

**Issue by timderspieler** [PlaceholderAPI/PlaceholderAPI#193]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

- [ X] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.

### Info

My plugin TrickOrTreat ( https://www.spigotmc.org/resources/61370/ ) has now some placeholders. It would be nice if you could add them to the papi wiki ;)

%trickortreat_sweets% - Sweets of the player
%trickortreat_doors_found% - Amount of doors you have found
%trickortreat_sweets_average% - Average of sweets gained per door
%trickortreat_is_at_door% - Is the player currently at a door?
%trickortreat_current_ingredient% - Name of the current ingredient
%trickortreat_current_head% - Skin of the current head
%trickortreat_chestplate% - Current color of the chestplate
%trickortreat_leggings% - Current color of the leggings
%trickortreat_boots% - Current color of the boots

You can also use all papi placeholders in the trickortreat messages!

Thank you very much!

**Comment by aBooDyy** [comment]
Added in [Placeholders](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#trickortreat) and [Plugins using PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#t) pages.

Thanks for supporting PlaceholderAPI!
