### ISSUE TITLE
FactionsUUID wiki updates

### ISSUE THREAD

**Issue by CmdrKittens** [PlaceholderAPI/PlaceholderAPI#194]
### Type
> What kind of change is it? (Multiple selections possible)

- [ ] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [x] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [x] Other: FactionsUUID doesn't just provide placeholders, but also processes placeholders in many of its messages

### Info
Code snippet where we support placeholders

```java
if (FactionsPlugin.getInstance().isClipPlaceholderAPIHooked() && player.isOnline()) {
    line = PlaceholderAPI.setPlaceholders(player, line);
}
```

New placeholders:

`%factionsuuid_player_role_name%` 

Thanks! 😸

**Comment by aBooDyy** [comment]
[Updated](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#f), and [added the placeholder](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#factionsuuid).

Thanks for supporting PlaceholderAPI.

**Comment by aBooDyy** [comment]
[Updated](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#f), and [added the placeholder](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#factionsuuid).

Thanks for supporting PlaceholderAPI.
