### ISSUE TITLE
eCloud error in console, No expansions for download

### ISSUE THREAD

**Issue by DevJorgeMCS** [PlaceholderAPI/PlaceholderAPI#196]
**Please report issues with expansions/placeholders to the corresponding issue tracker! Only report it here if you can't find any place to report it!**

### Issue
> What is the issue? Describe it like you would tell a friend.

ecloud doesn't have expansions to download
Using Paper 1.14.4 #195 - PlaceholderAPI v2.10.4

### Expected behaviour
> What should PlaceholderAPI do?

Let me download the expansions for use it

### Actual behaviour
> What does PlaceholderAPI actually do?

In console problem https://pastebin.com/PFgbt1jh
In game said "ecloud dont have expansions in this moment" or related

### How to reproduce
> What steps did you made, to get this bug?

1. Just appears next to the done message of the server
https://pastebin.com/PFgbt1jh

**Comment by Funny-cube** [comment]
Your server needs to be able to make contact with our api at `api.extendedclip.com/v2/`. That error is telling you it failed to reach it within an acceptable time or the request was blocked.

**Comment by DevJorgeMCS** [comment]
So what could I do? That happens every time I start the server.

**Comment by Funny-cube** [comment]
Speak with your host to see why it wouldn't be talking to the api, or disable the ecloud in the PlaceholderAPI config and manually download expansions via the site https://api.extendedclip.com/all/

**Comment by DevJorgeMCS** [comment]
Thanks!! I'll config manually.
