### ISSUE TITLE
Error with /papi ecloud placeholder player

### ISSUE THREAD

**Issue by tomkeuper** [PlaceholderAPI/PlaceholderAPI#197]
### Issue
> What is the issue? Describe it like you would tell a friend.

I get an error in console when i try to run /papi ecloud placeholders player. I am on the latest version of placeholder api (2.10.4) And the player expansion version is 1.7.2

### Expected behaviour
> What should PlaceholderAPI do?
It should display all the player placeholders

### Actual behaviour
> What does PlaceholderAPI actually do?
http://prntscr.com/pirtpd
https://hastebin.com/ufakebenej.bash

### How to reproduce
> What steps did you made, to get this bug?
1. Execute command: /papi ecloud placeholders player

**Comment by Andre601** [comment]
Did you make sure that your connection to the ecloud isn't blocked?
This is the only real reason I can think of as to why it doesn't work.
