### ISSUE TITLE
Update Towny and TownyChat entries.

### ISSUE THREAD

**Issue by LlmDl** [PlaceholderAPI/PlaceholderAPI#198]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

## Please read
This template is only for requesting new information to be added to the wiki or for updating of already existing information!  
Please use the [Request change (PlaceholderAPI)] template to ask for additions/changes to the plugin PlaceholderAPI.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already have the change and that there isn't a issue about this change on the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
On [this page](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#t):

- The Towny primary website is now https://github.com/TownyAdvanced/Towny

Entries would be the following:

- [Towny](https://github.com/TownyAdvanced/Towny)
  - [ ] Supports placeholders.
  - [x] Provides it's own placeholders. [[Link](https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#placeholderapi-support)]

To add to the page, TownyChat:

- [TownyChat](https://github.com/TownyAdvanced/TownyChat)
  - [x] Supports placeholders.
  - [ ] Provides it's own placeholders.

Not sure what would be done on [this](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#towny) page, as Clip's expansion is still valid and does have a couple tags which I did not add to Towny.

**Comment by aBooDyy** [comment]
Hello,

I've updated Towny's link and added TownyChat in [this page](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#t), and updated Towny and added TownyChat in [this page](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#towny).
For Clip's expansion, it's still available but I've unverified it so users can download it manually only. 

Thanks for letting us know, and for supporting PlaceholderAPI.
