### ISSUE TITLE
Translation for Gamemode placeholder.

### ISSUE THREAD

**Issue by TheIntelloBox** [PlaceholderAPI/PlaceholderAPI#20]
Hi,

I want to translate the Essentials Gamemode Placeholder.
For example if you are in /gm 1, I want that the placeholder says "Créatif" and not "Creative".
Survival --> Survie.
Spectator --> Spectateur.

Thanks ! :)

**Comment by Gaby-TM** [comment]
Does essentials expansio even have a gamemode placeholder? 😅

**Comment by darbyjack** [comment]
@Gaby-TM  There is not, but you can just use the Player placeholder for that.

**Comment by darbyjack** [comment]
@TheIntelloBox Essentials doesn't have a placeholder for that. You'd have to clone the Player expansion and write statements for each gamemode possibility and tell it what to parse. Has nothing to do with the Essentials Expansion.
