### ISSUE TITLE
Suggestion: Add the all-contributors bot to this repo

### ISSUE THREAD

**Issue by Andre601** [PlaceholderAPI/PlaceholderAPI#200]
There seems to be some kind of hype or similar for the @all-contributors bot (and the [allcontributors site](https://allcontributors.org)) since it appears on more and more repositories.
Considering how many people contributed (and still contribute) to this Repository, which is not always through code, I think adding the bot and setting it up would be a nice thing to do, to honour those people and their help.

**Comment by Andre601** [comment]
Any updates to this?

**Comment by extendedclip** [comment]
If this is what you would like I have no problem with it. Just guide me on what to do to get it setup or you can set it up yourself.

**Comment by Andre601** [comment]
I don't have access to this repository, so I can't set it up for you (sadly)

A general installation guide on how to add the bot to the repository is found here: https://allcontributors.org/docs/en/bot/installation

In general would the bot work, where you just type "@all-contributors add X for Y" (Y is one or multiple types which you find [here](https://allcontributors.org/docs/en/emoji-key)) and the bot would make a PR to add the user to wherever you defined contributors to be displayed (I personally recommend having a dedicated, separate markdown file, as the bot puts it on the readme by default.

An example of a working file can you find here:
https://github.com/botblock/JavaBotBlockAPI/blob/master/contributors.md
