### ISSUE TITLE
I'm porting a plugin that uses an old version of PlaceholderAPI. What happened to PlaceholderReplaceEvent and PlaceholderReplacer?

### ISSUE THREAD

**Issue by Chaoscrasher** [PlaceholderAPI/PlaceholderAPI#202]
So this plugin makes a lot of calls to 
 
> PlaceholderAPI.registerPlaceholder(JavaPlugin, String, PlaceholderReplacer)

and in the PlaceholderReplacer it only overrides a single method 

> onPlaceholderReplace(PlaceholderReplaceEvent)

If anyone could point me to how I can port this, I would be very thankful!

**Comment by darbyjack** [comment]
This page will cover how to make an internal / external expansion for your plugin. https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Hook-into-PlaceholderAPI

**Comment by Chaoscrasher** [comment]
For anyone having the same problem as I:
[This is the dependency you are looking for.](https://www.spigotmc.org/resources/mvdwplaceholderapi.11182/)
