### ISSUE TITLE
New placeholders for TNTRun_reloaded

### ISSUE THREAD

**Issue by steve4744** [PlaceholderAPI/PlaceholderAPI#203]
Please add the following placeholder to the list for TNTRun_reloaded:

%tntrun_leaderboard_\<position\>%  

The expansion pack is also no longer required for the most recent versions of the plugin.

Thanks

**Comment by aBooDyy** [comment]
[Updated](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#tntrun_reloaded). Use the template next time please.

Thanks for using PlaceholderAPI.
