### ISSUE TITLE
The link to "create an issue" on the placeholder wiki page bypasses the list of templates

### ISSUE THREAD

**Issue by steve4744** [PlaceholderAPI/PlaceholderAPI#205]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

## Please read
This template is only for requesting new information to be added to the wiki or for updating of already existing information!  
Please use the [Request change (PlaceholderAPI)] template to ask for additions/changes to the plugin PlaceholderAPI.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already have the change and that there isn't a issue about this change on the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [ ] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [x ] Other: __________ Update wiki information

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

The link on this page https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders
to "create an issue" if you want to add more placeholders to your plugin, takes you straight into a new issue page, bypassing the list of templates provided. If you've not used the system before, there is no way of seeing the templates before creating your issue.

**Comment by aBooDyy** [comment]
Thank you for letting us know!
Link has been fixed.
