### ISSUE TITLE
Expansions Doesn't Work

### ISSUE THREAD

**Issue by rudipratm** [PlaceholderAPI/PlaceholderAPI#206]
### Issue
> What is the issue? Describe it like you would tell a friend.
I downloaded the expansion using `/ papi ecloud download <name>`. After I download it, it only displays 0kb on disk, and the `/ papi ecloud list of all <pages>` doesn't show the Green color that should appear if it's already installed.

### Expected behaviour
> What should PlaceholderAPI do?
Showing green text, working placeholders

### Actual behaviour
> What does PlaceholderAPI actually do?
It's only showing text `Expansion <name> download complete!` and the file size is 0kb.

### How to reproduce
> What steps did you made, to get this bug?
1. Trying to install some expansion using /papi ecloud download name

**Comment by aBooDyy** [comment]
To install an expansion, you have to download it using the download command (`/papi ecloud download <ExpansionName>`) and then you have to reload PlaceholderAPI (`/papi reload`).

To get the loaded expansions list, use `/papi list`.

**Comment by rudipratm** [comment]
> To install an expansion, you have to download it using the download command (`/papi ecloud download <ExpansionName>`) and then you have to reload PlaceholderAPI (`/papi reload`).
> 
> To get the loaded expansions list, use `/papi list`.

Yes, I do this. But it doesn't showing my downloaded expansion like "Player, etc". I already restart my server to make sure this works. But still doesn't work.

**Comment by aBooDyy** [comment]
Any errors in console when downloading or reloading?
Does it download the expansion jar in `plugins/PlaceholderAPI/expansions`?

**Comment by rudipratm** [comment]
> Any errors in console when downloading or reloading?
> Does it download the expansion jar in `plugins/PlaceholderAPI/expansions`?

The console didn't send any errors.
It does downloaded on the Expansions directory, but the size is 0KB and in game showing something like **No installed expansion!** when I type `/papi ecloud list installed`.

**Comment by aBooDyy** [comment]
That's weird, try downloading the expansion you want manually from the [eCloud](https://api.extendedclip.com/all/).

**Comment by ShawnFoxter** [comment]
looks like it is happening again, but only locale placeholders is what doesn't work, it happens on PaperMC with just PAPI plugin and Player expansion, happening only in 1.20.2, this is what shows up in console

![image](https://github.com/PlaceholderAPI/PlaceholderAPI/assets/87722509/2fbec40f-5aed-453f-935c-f1144ff713f5)
only locale related placeholders don't work

**Comment by Andre601** [comment]
Not a PAPI issue but one related to the player expansion.
