### ISSUE TITLE
Error on server start

### ISSUE THREAD

**Issue by Nety01** [PlaceholderAPI/PlaceholderAPI#207]
I got this error on server start - https://paste.helpch.at/okonugodiz.php

PlaceholderAPI v2.10.4
Paper 1.13.2 build 652

**Comment by aBooDyy** [comment]
Hello,

Is the plugin connected to the [eCloud](https://api.extendedclip.com/all/)?
You can check this by trying to download any expansion using `/papi ecloud download ExpansionName`. If it returns `No expansion available.` or something like that, then its probably an issue with your host not allowing connections to the PlaceholderAPI eCloud. in this case, you can contact your host or just download the expansions manually form the [eCloud](https://api.extendedclip.com/all/).
To avoid getting this error, disable the cloud in the config.

**Comment by Nety01** [comment]
Yes, plugin is connecteed to eCloud and downloading new expansions with /papi ecloud download command works.

**Comment by KleinDevDE** [comment]
What kind of expansions have you installed?
Go to the folder "plugins/PlaceolderAPI/expansions".

**Comment by Nety01** [comment]
![obrazek](https://user-images.githubusercontent.com/42073765/73264671-9613b400-41d3-11ea-9858-ef09d11bec8f.png)

**Comment by KleinDevDE** [comment]
Jobs and Jobs_2FccrSm couldn't be found.
Please restart the server without these expansions, may it will work after this.
To disable the expandions, simply move the two files out of the expansions folder.

**Comment by Andre601** [comment]
The screenshot shows that you have two Jobs-expansion.
So at least that will cause errors since two expansions try to load with the same information.

**Comment by Nety01** [comment]
Well I haven't seen that error for a month approximately so it's probably okay to close this, thanks for help anyway. If I get that error again I will open a new ticket.
