### ISSUE TITLE
1.14.4 error on enabling

### ISSUE THREAD

**Issue by coolpvpv1** [PlaceholderAPI/PlaceholderAPI#209]
i was on spigot 1.14.4 and when the server started up i got this error from placeholderapi https://paste.ubuntu.com/p/fHBXhjwJ3P/

**Comment by Funny-cube** [comment]
Remove UnlimitedPlugins and redownload PlaceholderAPI and see if it loads correctly, if so then UnlimitedPlugins is doing some funny stuff with startup.
