### ISSUE TITLE
Placeholder wiki page issue

### ISSUE THREAD

**Issue by extendedclip** [PlaceholderAPI/PlaceholderAPI#212]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

## Please read
This template is only for requesting new information to be added to the wiki or for updating of already existing information!  
Please use the [Request change (PlaceholderAPI)] template to ask for additions/changes to the plugin PlaceholderAPI.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already have the change and that there isn't a issue about this change on the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [ ] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [X] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

I suggest that any plugin that provides placeholders on its own and not through the ecloud should manage its own page to list placeholders. Instead of the list being maintained on our placeholders page we will just provide a link to the plugins placeholder list /documentation. This will allow ease of use for the developer of said plugin to maintain the list of placeholders are added/removed/changed. The developer of said plugin should still pr a link so it is added here but them to request an update to the list maintained here could be a bit tedious.

**Comment by aBooDyy** [comment]
Sounds good 👍
Will work on it when I get some time, but I'll keep the placeholders of plugins that don't have wiki and inform the author if possible.

**Comment by Andre601** [comment]
You can't pr wiki changes Clip, but I know what you mean by that.

**Comment by Andre601** [comment]
Imo could an alternative be a system on the ecloud itself, where the user updates a list of placeholders and if it gets verified, would a commit happen towards the wiki o update the right entry with the new values.
The major complication I see there would be A) Make a proper system that commits changes to the wiki and B) have the system locate and change the right values without accidentally breaking stuff.

While A is imo fairly simple, as a wiki is just yet another git-repository (And there even exist GitHub Actions offering such a functionality) is B probably the most difficult task, as the system would require to find the right section to then update the placeholders within it...
