### ISSUE TITLE
LuckPerms error

### ISSUE THREAD

**Issue by Nety01** [PlaceholderAPI/PlaceholderAPI#215]
PlaceholderAPI v2.10.4
Paper 1.13.2 build 652

This occurs on server start, started to happen after updating LuckPerms expansion with papi ecloud command.

https://hastebin.com/dexenogafi.sql

**Comment by aBooDyy** [comment]
Clip doesn't manage LuckPerms expansion. Contact LP author for that.
But from the error, it seem to be an API issue, so make sure that you're using the latest version of LP (if that didn't fix the issue, contact LP author).

**Comment by Andre601** [comment]
![image](https://user-images.githubusercontent.com/11576465/69876562-3591f480-12c0-11ea-9dd9-6105e8b58698.png)
