### ISSUE TITLE
GriefDefender using PAPI

### ISSUE THREAD

**Issue by bloodmc** [PlaceholderAPI/PlaceholderAPI#218]
### Type
> What kind of change is it? (Multiple selections possible)

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

Please add GriefDefender to the list of plugins supporting PAPI. 

https://github.com/bloodmc/GriefDefender/wiki/PlaceholderAPI

Relevant code here
https://github.com/bloodmc/GriefDefender/blob/master/bukkit/src/main/java/com/griefdefender/provider/PlaceholderProvider.java

Thanks!

**Comment by darbyjack** [comment]
Added!
