### ISSUE TITLE
Insecure repository (no HTTPS)

### ISSUE THREAD

**Issue by kh498** [PlaceholderAPI/PlaceholderAPI#220]
The repository that hosts PlaceholderAPI
 jars does not use HTTPS for the given repository `repo.extendedclip.com/content/repositories/placeholderap`.

Please fix this ASAP

**Comment by extendedclip** [comment]
At the time the repo was created we used LetsEncrypt which was not supported by java at the time and unreachable. Seems LetsEncrypt is now by the current java versions so we plan on adding ssl to the repo this coming weekend and testing it out. Will report back after we test it out.

**Comment by games647** [comment]
Any news?

**Comment by games647** [comment]
@kh498 I noticed that the Jenkins plugin repository works with HTTPS:

https://ci.extendedclip.com/plugin/repository/everything/

So you could use this non-official alternative.

**Comment by JLLeitschuh** [comment]
Or consider using JitPack to host your artifacts

**Comment by extendedclip** [comment]
Added SSL to the Nexus repo. Care to test?

**Comment by extendedclip** [comment]
Tested and confirmed ssl is added to the papi nexus repo

**Comment by JLLeitschuh** [comment]
🎉 Glad that my PR inspired more organizations to improve their security! 🎉
