### ISSUE TITLE
Error Ecloud

### ISSUE THREAD

**Issue by Timonplaysmc** [PlaceholderAPI/PlaceholderAPI#221]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Spigot]: https://www.spigotmc.org/resources/6245/
[Jenkins]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

## Please read
This template is only for reporting bugs of PlaceholderAPI!  
If you want to request changes to the code of PlaceholderAPI, use the [Request change (PlaceholderAPI)] template.  
For changes to the wiki use the [Request change (Wiki)] template.

Please also make sure that you use the [latest release][Spigot] or the latest [developement build][Jenkins] and that your bug isn't already reported on the [issues] page.

**Please report issues with expansions/placeholders to the corresponding issue tracker! Only report it here if you can't find any place to report it!**

### Issue
> What is the issue? Describe it like you would tell a friend.

The issue is that PAPI sometime gives this error: "10.12 19:30:06 [Server] WARN [PlaceholderAPI] Plugin PlaceholderAPI v2.10.4 generated an exception while executing task 15
10.12 19:30:06 [Server] INFO java.lang.NullPointerException: null
10.12 19:30:06 [Server] INFO at me.clip.placeholderapi.expansion.cloud.ExpansionCloudManager.lambda$fetch$4(ExpansionCloudManager.java:172) ~[?:?]
10.12 19:30:06 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[custom.jar:git-Paper-235]
10.12 19:30:06 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[custom.jar:git-Paper-235]
10.12 19:30:06 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[custom.jar:git-Paper-235]
10.12 19:30:06 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
10.12 19:30:06 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
10.12 19:30:06 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]"

Ander after that I am not able to use the /papi ecloud download command. Where I get the messege "No cloud expansions are available at this time."
But after trying to refresh of enablecloud disablecloud the plugin works again.
Furthermore I am running the Latest PaperSpigot at this time.

### Expected behaviour
> What should PlaceholderAPI do?

### Actual behaviour
> What does PlaceholderAPI actually do?

### How to reproduce
> What steps did you made, to get this bug?

1.

**Comment by Funny-cube** [comment]
That error is just saying that your server can't connect to our API to get expansions. Your host/firewall is most likely blocking connections to `api.extendedclip.com/api`. Either speak to your host about it or you can manually download expansions from https://placeholderapi.com/ecloud and place them in your /plugins/PlaceholderAPI/expansions/ folder.

Worth noting if you're going to go manual switch ecloud to false in the config to stop the plugin trying to reach our API.
