### ISSUE TITLE
setPlaceholders() issues

### ISSUE THREAD

**Issue by APickledWalrus** [PlaceholderAPI/PlaceholderAPI#224]
### Issue
When trying to set placeholders with setPlaceholders(player, placeholder), I am encountering issues.

Note: I am developing an addon for the plugin Skript, but I do not believe that is related, as the values of other placeholders are returned properly.

A user is trying to get the value of a placeholder from another plugin. When trying to get the value with my plugin, it just returns the placeholder itself. However, when they try the same placeholder in the scoreboard plugin they're using, it works fine and the placeholder is properly set. This could be an issue with the plugin the placeholder is coming from, but since it works for their scoreboard plugin I figured I would report this here. I do check in my plugin if PAPI contains the placeholder, and that check passes successfully.

If you need anymore information let me know :)

### Expected behaviour
The placeholders should be set for both plugins.

### Actual behaviour
The placeholder is only being set for one of the plugins.

### How to reproduce
My Plugin: https://github.com/APickledWalrus/skript-placeholders/blob/56ecd2c3901f34a4fbb4dad3a6348c549059ff73/src/main/java/io/github/apickledwalrus/placeholderaddon/skript/expressions/ExprParsePlaceholder.java#L69
Scoreboard Plugin: https://github.com/RienBijl/Scoreboard-revision/blob/a3871ec6a328bad16ba67292f4cf5f117b5019de/src/rien/bijl/Scoreboard/r/board/ScoreboardHolder.java#L69

**Comment by aBooDyy** [comment]
Why doing all of that while you can use [setBracketPlaceholders](https://aboodyy.net/PlaceholderAPI/me/clip/placeholderapi/PlaceholderAPI.html#setBracketPlaceholders-org.bukkit.OfflinePlayer-java.lang.String-) method to parse the placeholders inside a placeholder with `{}`?
You can parse a placeholder with `%%` and has other placeholders with `%%` inside it. It won't work properly.

If that's not the issue, then can you please send the placeholder text you're trying?

**Comment by Andre601** [comment]
I'm not that much of an expert but I think you mess up there in more than one way.

Just to be clear: The `PlaceholderAPI.setPlaceholders(Player, String)` method is __not__ for one single placeholder to be parsed.
It was made to allow just providing a String (e.g. `%player_name% joined the game!`) and all placeholders in it are getting parsed to the right values (`Andre_601 joined the game!`).
From what I can see are you just parsing a single placeholder which seems a bit bad.

Also, PlaceholderAPI only parses placeholders that have been loaded.
This basically means that either the expansion was downloaded from the ecloud and installed, or that the plugin responsible for it loaded it through its own code.

Please take a look at the wiki on how to integrate PlaceholderAPI into your plugin.
There exists an [example on how to add placeholders from other plugins](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Hook-into-PlaceholderAPI#using-placeholders-from-placeholderapi-in-your-plugin)

Other things I noticed and don't think are right:
[ExprParsePlaceholder#L70](https://github.com/APickledWalrus/skript-placeholders/blob/56ecd2c3901f34a4fbb4dad3a6348c549059ff73/src/main/java/io/github/apickledwalrus/placeholderaddon/skript/expressions/ExprParsePlaceholder.java#L70)
Why are you doing `"".equals(value)`? You are aware that `String#isEmpty()` (aka. `value.isEmpty()`) exists right?

**Comment by APickledWalrus** [comment]
Sorry, as I was not specific enough / left out information with this.

This part of my plugin is just acting as a parser for the placeholders. The user is trying to get a placeholder from https://bg-software.com/superiorskyblock/#placeholders. The placeholder I'm trying to parse is going in as "%superior_island_level%"

Unfortunately, this plugin is premium and I cannot view the source code. The placeholders for it do work in the scoreboard plugin I linked above, but not me for, as setPlaceholders() just returns the placeholder to me.

**Comment by aBooDyy** [comment]
Adding 
```
identifier = PlaceholderAPI.setBracketPlaceholders(player, identifier);
```
In [here](https://github.com/APickledWalrus/skript-placeholders/blob/56ecd2c3901f34a4fbb4dad3a6348c549059ff73/src/main/java/io/github/apickledwalrus/placeholderaddon/placeholderapi/PlaceholderAPIListener.java#L34) would be the easiest and the best (in my opinion) way to support placeholders inside of your placeholder.
Then you can use `%YourIdentifier_name_{superior_island_level}%`.

**Comment by APickledWalrus** [comment]
For this, I'm not trying to create any placeholders. I'm just trying to parse the superior_island_level placeholder and return it's value to the user, but it is only returning the placeholder itself.

**Comment by APickledWalrus** [comment]
Any sort of update or info on this?
