### ISSUE TITLE
WorldGuard placeholder issue

### ISSUE THREAD

**Issue by 1visible** [PlaceholderAPI/PlaceholderAPI#225]
### Issue
> What is the issue? Describe it like you would tell a friend.

Hello, I found a bug with the WorldGuard placeholders, I'm using the latest version of Spigot, WorldGuard and PlaceholderAPI (server currently in 1.14.4).
When I use %worldguard_region_flags% or %worldguard_region_has_flag_<Flag>% on a SetFlag type (such as the "deny-spawn" flag for example), I can't see it in the flags list and "has_flag" returns "no". I tried with a lot of different flags and flag types, and also with custom made flags thanks to WorldGuard API, but flags that contain a list don't work.

### Expected behaviour
> What should PlaceholderAPI do?
PlaceholderAPI should show the flags list when using %worldguard_region_flags% and show "yes" when using %worldguard_region_has_flag_<Flag>% when the flag is set.

### Actual behaviour
> What does PlaceholderAPI actually do?
It miss the flags with list as value, such as "deny-spawn" or "blocked-cmds" flags for example, and show a "no" for them when using %worldguard_region_has_flag_<Flag>%

### How to reproduce
> What steps did you made, to get this bug?

1. I created a worldguard region
2. I set some flags
3. I displayed the flags with placeholders in 2 different plugins
4. The bug happens, only for SetFlag types.

Of course WorldGuard expansion has been downloaded, everything else is working properly, except this kind of flags.
I know this isn't the right place but it could be a nice thing to add a %worldguard_region_flag_<Flag>% in order to get the value of the flag.

Thanks for your time and good luck with your plugin.

**Comment by Andre601** [comment]
You should report this on the right repository for the expansion, which is part of the PlaceholderAPI organisation.

**Comment by 1visible** [comment]
Oh sorry didn't know about that. I'll post it in the right section. Thanks.
