### ISSUE TITLE
Marcely's Bedwars not only supports them, but also provides placeholders

### ISSUE THREAD

**Issue by MrEAlderson** [PlaceholderAPI/PlaceholderAPI#226]
> What kind of change is it? (Multiple selections possible)

- [ ] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [X] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

The plugin [Marcely's Bedwars](https://www.spigotmc.org/resources/marcelys-bedwars-►-4-0-►-supports-1-7-1-15.13622/) provides placeholders.
They're listed here: https://mbedwars.marcely.de/index.php?title=Library_Placeholder#List_of_placeholders_provided_by_MBedwars

**Comment by aBooDyy** [comment]
Added in [Placeholders](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#marcelys-bedwars) page, and updated in [Plugins using PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#m) page.

Thanks for using PlaceholderAPI!
