### ISSUE TITLE
Don't translate color codes by default in setPlaceholders

### ISSUE THREAD

**Issue by Andre601** [PlaceholderAPI/PlaceholderAPI#233]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki
[Pull Requests]: https://github.com/PlaceholderAPI/PlaceholderAPI/pulls

## Please read
This template is only for requesting new functions to be added to PlaceholderAPI or for old one to be changed!  
Please use the [Request change (Wiki)] template to ask for additions/changes to the wiki.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already mention such a function/change and that there isn't a issue about this change on the [issues] page.

We recommend to [open a Pull Request][Pull Requests] for making changes to PlaceholderAPI's code.

### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New function for PlaceholderAPI.  
A new function that developers could use.
- [x] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Info
> What is the change?  
> Please provide as much information (including links, images and code-snippeds) as possible.

The `setPlaceholder` method seems to translate color codes (for some reason) which may have unwanted side effects, as seen in https://github.com/DiscordSRV/DiscordSRV/issues/535 where it translates the `&<number>` from `<@&<id>>` which is unwanted.
DiscordSRV has added a small workaround for this, but I personally think it should be PlaceholderAPI's job to not translate colors.

**Comment by Vankka** [comment]
Removing this now would cause some extensions/plugins to have non translated color codes, that's why I decided to fix this myself in DiscordSRV, as it's also a bit of a edge case (not needing color codes translated for Discord messages).

**Comment by Andre601** [comment]
> Removing this now would cause some extensions/plugins to have non translated color codes, that's why I decided to fix this myself in DiscordSRV, as it's also a bit of a edge case (not needing color codes translated for Discord messages).

Then it should be handled by the dev of the expansion anyway.
I can see why PlaceholderAPI has this, but I still don't think that this should always be done and instead should be handled by the author of the expansion.

**Comment by aBooDyy** [comment]
I'm not sure if this should be removed or not, but I personally feel its not an issue. It's been there for a while and no one complained about it (as far as I know) and instead its great to have that and it's pretty easy to undo.

Anyway, seems like nothing is going to happen in this repository (PAPI v2) according to [Glare's response](https://github.com/PlaceholderAPI/PlaceholderAPI/pull/204#issuecomment-570598688). So if anything is going to be changed regards this, it will be on PAPI v3.

**Comment by Vankka** [comment]
> Then it should be handled by the dev of the expansion anyway.
> I can see why PlaceholderAPI has this, but I still don't think that this should always be done and instead should be handled by the author of the expansion.
Changing this will effect currently available expansions & plugins that integrate to PlaceholderAPI as they might not have color translations, as PAPI automatically translates colors. This is a breaking change (External, not internal (see: first message)). And as I noted Discord messages are a bit of a edge case; because what other plugin/expansion would have a problem with converting color codes (other Discord plugins yes, but what else)?

Anyway, solving this issue would require another method that doesn't translate colors (could be quite useful), or break all current PAPI implementations that expect PAPI to translate colors by changing the main method itself.

**Comment by darbyjack** [comment]
I'd be willing to add in another method that would not translate color codes.

**Comment by Andre601** [comment]
I could imagine it being like this:
- Having a new boolean option `translateColors` for the different methods
  - `setPlaceholders(OfflinePlayer player, String text, boolean translateColors)`
  - `setPlaceholders(OfflinePlayer player, String text, Pattern placeholderPattern, boolean translateColors)`
  - `setBracketPlaceholders(OfflinePlayer player, String text, boolean translateColors)`

Those would be the new "parent methods" and the current ones without the boolean would be like this:
```java
public static String setPlaceholders(OfflinePlayer player, String text){
    return setPlaceholders(player, text, PLACEHOLDER_PATTERN, true);
}

public static String setPlaceholders(OfflinePlayer player, String text, Pattern placeholderPattern){
    return setPlaceholders(player, text, placeholderPattern, true);
}

public static String setBracketPlaceholders(OfflinePlayer player, String text){
    return setPlaceholders(player, text, BRACKET_PLACEHOLDER_PATTERN, true);
}
```

That way could we keep the current behaviour while also allowing the option of not translating the other ones.
And it wouldn't require much more than just adding an `if(translateColors)` check to the root-method,

I could work on this if that should be done as I think PAPI 3 still has a long way to go...

**Comment by extendedclip** [comment]
Done.

Commit 2dbf69a74e9f2f180a4eaa7e8a21dd5dfdf58d4f

 https://ci.extendedclip.com/job/PlaceholderAPI/84/

**Comment by Andre601** [comment]
> Done.
> 
> Commit [2dbf69a](https://github.com/PlaceholderAPI/PlaceholderAPI/commit/2dbf69a74e9f2f180a4eaa7e8a21dd5dfdf58d4f)
> 
> https://ci.extendedclip.com/job/PlaceholderAPI/84/

You took my chance to work on something. :,(
