### ISSUE TITLE
Placeholders: Plan

### ISSUE THREAD

**Issue by Rsl1122** [PlaceholderAPI/PlaceholderAPI#239]
### Type
- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info

I have written a page for placeholders in my plugin's wiki - I think it would be beneficial to link to it to reduce work to a single location when they are updated
- https://github.com/plan-player-analytics/Plan/wiki/PlaceholderAPI

Preferred markdown (feel free to change)
```
- ### [Plan](https://www.spigotmc.org/resources/plan-player-analytics.32536/)

> NO DOWNLOAD COMMAND

The plugin provides placeholders for statistics stored in the plugin for players and the server.

See [Plan Wiki](https://github.com/plan-player-analytics/Plan/wiki/PlaceholderAPI) for the list of placeholders
```

**Comment by aBooDyy** [comment]
Added in [Placeholders](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#plan) and [Plugins using PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#p) pages.
Sorry for the delay.
