### ISSUE TITLE
Error on startup.

### ISSUE THREAD

**Issue by En0tS** [PlaceholderAPI/PlaceholderAPI#245]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Spigot]: https://www.spigotmc.org/resources/6245/
[Jenkins]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

## Please read
This template is only for reporting bugs of PlaceholderAPI!  
If you want to request changes to the code of PlaceholderAPI, use the [Request change (PlaceholderAPI)] template.  
For changes to the wiki use the [Request change (Wiki)] template.

Please also make sure that you use the [latest release][Spigot] or the latest [developement build][Jenkins] and that your bug isn't already reported on the [issues] page.

**Please report issues with expansions/placeholders to the corresponding issue tracker! Only report it here if you can't find any place to report it!**

### Issue
> What is the issue? Describe it like you would tell a friend.
Error on startup: https://pastebin.com/0x9mbqyu

### Expected behaviour
> What should PlaceholderAPI do?
Should work without errors on startup.

### Actual behaviour
> What does PlaceholderAPI actually do?
Throws this error: https://pastebin.com/0x9mbqyu

### How to reproduce
> What steps did you made, to get this bug?
1. Run paperspigot-1618 (final 1.12.2 build).

**Comment by Funny-cube** [comment]
That error is thrown when your host/server is blocking connections to our API,

Should your host not allow connections to the PlaceholderAPI eCloud, you can manually download expansion from https://placeholderapi.com/ecloud and place them in your `/plugins/PlaceholderAPI/expansions/` folder.
