### ISSUE TITLE
Added SpeedPerSec expansion

### ISSUE THREAD

**Issue by thienbao860** [PlaceholderAPI/PlaceholderAPI#246]
### Type
> What kind of change is it? (Multiple selections possible)

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [x] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

Please add all new SpeedPerSecond placeholders, including: 

%speedpersec_blockBreak% - Blocks broken per second
%speedpersec_blockPlace% - Blocks placed per second
%speedpersec_speed% - Blocks moved per second
%speedpersec_expCollected% - EXP collected per second
%speedpersec_damaging% - Entity Damage dealt per second
%speedpersec_hurting% - Damage taken per second

**Comment by aBooDyy** [comment]
[Added](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#speedpersec).

Thanks for using PlaceholderAPI.
