### ISSUE TITLE
{ticktime}

### ISSUE THREAD

**Issue by madtomic** [PlaceholderAPI/PlaceholderAPI#25]
Any way to add a placeholder that display the current in game tick time like {time} HH:MM:SS

Thanks!

**Comment by Gaby-TM** [comment]
https://www.spigotmc.org/wiki/placeholderapi-placeholders/#date-placeholders

**Comment by madtomic** [comment]
I'm aware of that but it's not what I am asking.

![image](https://user-images.githubusercontent.com/6004542/41512996-87f871c2-7262-11e8-9f3c-f2bd15fbd5bc.png)

I am asking for the current in game ticks. 0 ticks or 14000 ticks

**Comment by Banbeucmas** [comment]
You can get it by making a JS placeholder I guess.
Get the milliseconds and do calculation. 
1k ms = 1s
20 tick = 1s;

You know what I mean

**Comment by madtomic** [comment]
Not doing the actually calculation. I simply need to get current game ticks.
