### ISSUE TITLE
Add AdvancedAFK placeholders to the list

### ISSUE THREAD

**Issue by hankur** [PlaceholderAPI/PlaceholderAPI#250]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

### Type
> What kind of change is it? (Multiple selections possible)
- [X] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________

### Info
https://www.spigotmc.org/resources/advancedafk.60761/
`NO DOWNLOAD COMMAND`
```
%aafk_prefix_tablist%
%aafk_prefix_playertag%
```

**Comment by aBooDyy** [comment]
Added in [Placeholders](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#advancedafk) and [Plugins using PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#a) pages.

Thanks for using PlaceholderAPI.

**Comment by hankur** [comment]
Thanks! This plugin also supports placeholders, so you can check that too.
