### ISSUE TITLE
Please teach me how to do this

### ISSUE THREAD

**Issue by BlackFalconJ** [PlaceholderAPI/PlaceholderAPI#251]
Hello,

i am new to this whole thing so please bare with me.

I want to add a placeholder to my server:

%cc_full_color% - Returns the full color of a player. Can then be used to colorise text after it.
%cc_full_color_text% - Returns the full color of a player, as text. e.g. Red, Bold.
%cc_color% - Returns the color only (no modifiers) of a player.
%cc_color_text% - Returns the color only, as text.
%cc_modifiers% - Returns the modifiers only (no color) of a player.
%cc_modifers_text% - Returns the modifiers only, as text.
%cc_<color/modifier>_available% - Returns either 'gui-available' or 'gui-unavailable' from the messages.yml, based on if the player has the necessary permission. e.g. %cc_a_available%

The plugin is: https://www.spigotmc.org/resources/chatcolor.22692/

And i want to know how to manually add this expansion to the plugin.

I just use notepad to open the file

if someone could help me that would be great!

Thanks

**Comment by Andre601** [comment]
Check the wiki page called expansion cloud (or ecloud).
It answers your question on how to install an expansion manually.
