### ISSUE TITLE
Chatcolor2 plugin not working

### ISSUE THREAD

**Issue by BlackFalconJ** [PlaceholderAPI/PlaceholderAPI#253]
Hello,

I use the chat color plugin to change the color of my text it keepy my text on white and my console keeps getting spammed with error messages and i was wondering if anyone could help me out.

This is the plugin i use: https://dev.bukkit.org/projects/chatcolor-s

Error messages:
https://gyazo.com/85ca5e6ec53f403a1c4ce384e8aa05fd
https://gyazo.com/3ff0f196e7b3b8c19c8af62c797e7c76
https://gyazo.com/e2ad44b2ec130b29990a699e1ef57b86

**Comment by Andre601** [comment]
Please contact the dev of the plugin and ask them for help.
This issue tracker is reserved for bug reports and feature requests related to **PlaceholderAPI** which yours isn't.

The errors you show don't point in any way to PlaceholderAPI being the cause of your issue. It is most likely an outdated/unsupported Server version by your ChatColot plugin.

Again: Contact the dev of the ChatColor plugin or ask in the [HelpChat Discord](https://discord.gg/helpchat) for for general support with that plugin.

**Comment by aBooDyy** [comment]
As Andre601 mentioned. Please report this to the plugin's author.
This issue isn't related to PlaceholderAPI plugin in any way.
