### ISSUE TITLE
PAPI will always fail to find player(s) on their first join

### ISSUE THREAD

**Issue by nierw** [PlaceholderAPI/PlaceholderAPI#256]
### Issue
> What is the issue? Describe it like you would tell a friend.

PAPI will fail to find (and parse) placeholders properly for a player who has just joined the server. This will persist until they leave and rejoin, rendering any placeholders based on time or player data in that period unusable. If a player joins and does not disconnect for 12 hours, it affects them throughout that entire period.

### Expected behaviour
> What should PlaceholderAPI do?

Properly find players who have connected for the first time.

### Actual behaviour
> What does PlaceholderAPI actually do?

* Does not find new players until they connect a second time (through `/papi parse`)
* Will still work via API and in other plugins, but many player-based placeholders will not work (stats, achievements, etc).

### How to reproduce
> What steps did you made, to get this bug?

1. Install Bukkit/Spigot/Paper
2. Make a new world
3. Join and attempt to use `/papi parse username` and see it will always fail
4. Reconnect and confirm it now works

**Comment by extendedclip** [comment]
See #185

**Comment by stonar96** [comment]
I still have that issue on 2.10.9.

**Comment by Andre601** [comment]
> I still have that issue on 2.10.9.

Sorry for the delayed response.
Could you please open a new issue for this, so we can properly track it? Don't forget to provide all required information.
