### ISSUE TITLE
New CombatLogX placeholders.

### ISSUE THREAD

**Issue by ziemniok99** [PlaceholderAPI/PlaceholderAPI#258]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

## Please read
This template is only for requesting new information to be added to the wiki or for updating of already existing information!  
Please use the [Request change (PlaceholderAPI)] template to ask for additions/changes to the plugin PlaceholderAPI.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already have the change and that there isn't a issue about this change on the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [ ] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [x] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

Hello, CombatLogX have more placeholders than it is written in wiki
Here are all placeholders:
- %combatlogx_time_left% - Get the time left in combat
- %combatlogx_enemy_name% - The name of the enemy being fought
- %combatlogx_enemy_health% - How much health the enemy has left
- %combatlogx_enemy_health_rounded% - The health of the enemy rounded to the nearest integer
- %combatlogx_enemy_hearts% - Hearts that the enemy has left (health / 2)
- %combatlogx_status% - Fighting/Idle
- %combatlogx_in_combat% - Is the player in combat? (Yes or No)

CombatLogX Wiki: [https://www.spigotmc.org/wiki/combatlogx/](url)

**Comment by aBooDyy** [comment]
[Updated](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#combatlogx).

Thanks for letting us know.
