### ISSUE TITLE
Add AbstractMenus placeholders to the list

### ISSUE THREAD

**Issue by NanitMix** [PlaceholderAPI/PlaceholderAPI#264]
### Type
- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info

[Plugin page](https://www.spigotmc.org/resources/abstract-menus-1-8-1-15-an-advanced-gui-plugin.75107/)
`NO DOWNLOAD COMMAND`

```
%hanim_:<animation_name>:<unique_id>%
%var_:<variable_name>[:<default_value>]%
%var_:<player>.<variable_name>[:<default_value>]%
%varp_:<variable_name>[:<default_value>]%
%vart_:<variable_name>%
%varpt_:<variable_name>%
```

Any information about these placeholders you can find on [page about this placeholders](https://gitlab.com/spigotplugindevs/abstractmenuscommon/-/wikis/Variables#getval)

**Comment by aBooDyy** [comment]
Added to [Placeholders](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#abstractmenus) and [Plugins using PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#a) pages.

Thanks for using PlaceholderAPI.
