### ISSUE TITLE
Add Leak Parkour to wiki

### ISSUE THREAD

**Issue by stijnb1234** [PlaceholderAPI/PlaceholderAPI#266]
# Type
> What kind of change is it? (Multiple selections possible)

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

Please add the Leak Parkour plugin to the list of supporting plugins.
https://www.spigotmc.org/resources/leak-parkour-%E2%98%84%EF%B8%8F.12852/

**Comment by aBooDyy** [comment]
[Added](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#l).

Thanks for supporting PlaceholderAPI.
