### ISSUE TITLE
MineChess support for PlaceholderAPI

### ISSUE THREAD

**Issue by ajneb97** [PlaceholderAPI/PlaceholderAPI#270]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

## Please read
This template is only for requesting new information to be added to the wiki or for updating of already existing information!  
Please use the [Request change (PlaceholderAPI)] template to ask for additions/changes to the plugin PlaceholderAPI.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already have the change and that there isn't a issue about this change on the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

Plugin name: MineChess
Link: https://www.spigotmc.org/resources/minechess-minigame-1-8-1-15.74178/
Variables:
%minechess_wins%
%minechess_loses%
%minechess_ties%
%minechess_played_time%
%minechess_arenaplayers_count_<arena>%
%minechess_arena_status_<arena>%

**Comment by aBooDyy** [comment]
Added in [Placeholders](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#minechess) and [Plugins using PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#m) pages.

Thanks for using PlaceholderAPI.

**Comment by ajneb97** [comment]
Sorry I forgot to add the <arena> at the end of the two last variables, these are the variables fixed, sorry.

Variables:
%minechess_wins%
%minechess_loses%
%minechess_ties%
%minechess_played_time%
%minechess_arenaplayers_count_<arena>%
%minechess_arena_status_<arena>%

**Comment by aBooDyy** [comment]
[Updated](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#minechess).
