### ISSUE TITLE
Superbvotes placeholders are wrong

### ISSUE THREAD

**Issue by JHarris12345** [PlaceholderAPI/PlaceholderAPI#271]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Spigot]: https://www.spigotmc.org/resources/6245/
[Jenkins]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

## Please read
This template is only for reporting bugs of PlaceholderAPI!  
If you want to request changes to the code of PlaceholderAPI, use the [Request change (PlaceholderAPI)] template.  
For changes to the wiki use the [Request change (Wiki)] template.

Please also make sure that you use the [latest release][Spigot] or the latest [developement build][Jenkins] and that your bug isn't already reported on the [issues] page.

**Please report issues with expansions/placeholders to the corresponding issue tracker! Only report it here if you can't find any place to report it!**

### Issue
> What is the issue? Describe it like you would tell a friend.
The placeholders for superbvote work fine however they dont shown the top voter correctly. They start from 2nd place. Look at this screenshot:
![image](https://user-images.githubusercontent.com/46936647/77834199-c5df2980-713a-11ea-8bf8-ce9686bc21d2.png)

The top voter is Georgia but on the hologram it shows 2nd place. The placeholder used is %superbvote_top_voter_name_1% and %superbvote_top_voter_votes_1%. I have even tried setting it to index 0

### Expected behaviour
> What should PlaceholderAPI do?
votes_1 should show the top voter not the 2nd top

### Actual behaviour
> What does PlaceholderAPI actually do?
It shows 2nd place

### How to reproduce
> What steps did you made, to get this bug?

1. Set up a scoreboard to show top voters

**Comment by Andre601** [comment]
> This template is only for reporting bugs of PlaceholderAPI!

Your issue is with an expansion and not PlaceholderAPI itself.
