### ISSUE TITLE
Console Null Error /papi reload

### ISSUE THREAD

**Issue by BboyZeroOne** [PlaceholderAPI/PlaceholderAPI#274]
### Issue
> What is the issue? Describe it like you would tell a friend.

PAPI giving lots of console spam when using /papi reload. In game it says "An internal error has occurred while attempting to perform this command."

### Expected behaviour
> What should PlaceholderAPI do?

Should reload the plugin like normal.

### Actual behaviour
> What does PlaceholderAPI actually do?

Gives console spam and internal error message.
https://pastebin.com/9d93kM4t

### How to reproduce
> What steps did you made, to get this bug?

1. Type /papi reload

Server Version: Paper Spigot- Build 146

**Comment by darbyjack** [comment]
Caused by: java.lang.NoClassDefFoundError: me/lucko/luckperms/api/LuckPermsApi

Update your LuckPerms Expansion + Plugin.
