### ISSUE TITLE
Add TransmuteIt as a Placeholder

### ISSUE THREAD

**Issue by Chew** [PlaceholderAPI/PlaceholderAPI#275]
### Type
> What kind of change is it? (Multiple selections possible)

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

Plugin name: TransmuteIt
Link: https://www.spigotmc.org/resources/transmuteit.76287/
Download command: None, built into the plugin

```
%transmuteit_emc%
%transmuteit_discoveries%
%transmuteit_total_discoveries%
%transmuteit_discovered_[ITEM]%
```

**Comment by aBooDyy** [comment]
Added in [Placeholders](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#transmuteIt) and [Plugins using PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#t) pages.

Thanks for using PlaceholderAPI.
