### ISSUE TITLE
Add BankSystem to List

### ISSUE THREAD

**Issue by mannyseete** [PlaceholderAPI/PlaceholderAPI#276]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

## Please read
This template is only for requesting new information to be added to the wiki or for updating of already existing information!  
Please use the [Request change (PlaceholderAPI)] template to ask for additions/changes to the plugin PlaceholderAPI.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already have the change and that there isn't a issue about this change on the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

%banksystem_name% - Shows the players name
%banksystem_balance% - Shows the players bank balance.
%banksystem_pocket% - Shows the players pocket balance.
%banksystem_total% - Shows the players total balance.
%banksystem_currency% - Shows the currency of bank.

https://www.spigotmc.org/resources/1-8-1-15-banksystem.61580/

**Comment by aBooDyy** [comment]
Added in [Placeholders](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#banksystem) and [Plugins using PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#b) pages.

Thanks for using PlaceholderAPI.
