### ISSUE TITLE
Add ProtectionStones to wiki

### ISSUE THREAD

**Issue by espidev** [PlaceholderAPI/PlaceholderAPI#280]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

## Please read
This template is only for requesting new information to be added to the wiki or for updating of already existing information!  
Please use the [Request change (PlaceholderAPI)] template to ask for additions/changes to the plugin PlaceholderAPI.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already have the change and that there isn't a issue about this change on the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

ProtectionStones has just added PlaceholderAPI support.

Detailed and most up to date information [here](https://github.com/espidev/ProtectionStones/wiki/Placeholders).

Config placeholder information is on the page above.

Player Placeholders:
```
%protectionstones_currentplayer_global_region_limit%
%protectionstones_currentplayer_region_limit_[alias]%
```

Region Placeholders:
```
%protectionstones_currentregion_owners%
%protectionstones_currentregion_members%
%protectionstones_currentregion_name%
%protectionstones_currentregion_id%
%protectionstones_currentregion_type%
%protectionstones_currentregion_alias%
%protectionstones_currentregion_is_hidden%
%protectionstones_currentregion_home_location%
%protectionstones_currentregion_is_for_sale%
%protectionstones_currentregion_rent_stage%
%protectionstones_currentregion_landlord%
%protectionstones_currentregion_rent_period%
%protectionstones_currentregion_rent_amount%
%protectionstones_currentregion_sale_price%
%protectionstones_currentregion_tax_owed%
%protectionstones_currentregion_tax_autopayer%
%protectionstones_currentregion_flags%
%protectionstones_currentregion_flags_[flag]%
%protectionstones_region_[identifier]_owners%
%protectionstones_region_[identifier]_members%
%protectionstones_region_[identifier]_name%
%protectionstones_region_[identifier]_id%
%protectionstones_region_[identifier]_type%
%protectionstones_region_[identifier]_alias%
%protectionstones_region_[identifier]_is_hidden%
%protectionstones_region_[identifier]_home_location%
%protectionstones_region_[identifier]_is_for_sale%
%protectionstones_region_[identifier]_rent_stage%
%protectionstones_region_[identifier]_landlord%
%protectionstones_region_[identifier]_rent_period%
%protectionstones_region_[identifier]_rent_amount%
%protectionstones_region_[identifier]_sale_price%
%protectionstones_region_[identifier]_tax_owed%
%protectionstones_region_[identifier]_tax_autopayer%
%protectionstones_region_[identifier]_flags%
%protectionstones_region_[identifier]_flags_[flag]%
```

**Comment by darbyjack** [comment]
Added! (https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#protectionstones)

Welcome to the PlaceholderAPI family!

**Comment by aBooDyy** [comment]
Added in [Plugins using PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#p) page too 👍
