### ISSUE TITLE
DiscordSRV placeholders

### ISSUE THREAD

**Issue by Vankka** [PlaceholderAPI/PlaceholderAPI#282]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

## Please read
This template is only for requesting new information to be added to the wiki or for updating of already existing information!  
Please use the [Request change (PlaceholderAPI)] template to ask for additions/changes to the plugin PlaceholderAPI.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already have the change and that there isn't a issue about this change on the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [ ] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [x] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

- We keep a updated list of placeholders, here: https://github.com/DiscordSRV/DiscordSRV-PlaceholderAPI-Expansion#placeholders
- It appears that the [eCloud page](https://api.extendedclip.com/expansions/discordsrv/) appears to have out of date placeholders as well
Would appriciate a link back on both if possible, otherwise just a update for the placeholders

Thanks,
Vankka

**Comment by aBooDyy** [comment]
[Updated](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#discordsrv). We will be slowly updating the wiki to link the plugin's wiki if it has one for up-to-date placeholders.

For the eCloud, it seems like @LemmoTresto is managing the expansion.

Thanks for letting us know,
aBooDyy
