### ISSUE TITLE
Add my chat plugin(EzChat) to the list of plugins that support EzChat

### ISSUE THREAD

**Issue by FixedDev** [PlaceholderAPI/PlaceholderAPI#292]
### Type
> What kind of change is it? (Multiple selections possible)

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

I created a chat plugin that supports PlaceholderAPI and I would like it to be added to the list of plugins that support PlaceholderAPI
Here the link to the spigot post: https://www.spigotmc.org/resources/ezchat.75048/

**Comment by aBooDyy** [comment]
[Added](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#e).

Thanks for supporting PlaceholderAPI.
