### ISSUE TITLE
Banned discord?

### ISSUE THREAD

**Issue by Arthurdw** [PlaceholderAPI/PlaceholderAPI#296]
Hey, sorry that I'm using this template but I didn't find an appropriate one.
I got banned in the discord, I was asking for support and corresponded with everything the staff asked.
![image](https://user-images.githubusercontent.com/38541241/80456800-7dc84800-892e-11ea-99dc-dd04ced7ab6c.png)
This is really sad and makes PAPI look unprofessional...

**Comment by Funny-cube** [comment]
@Arthurdw Send me a message on Spigot and I'll let you know of the reasoning, this isn't the place to discuss it.
