### ISSUE TITLE
Default Placeholder Pattern config

### ISSUE THREAD

**Issue by CreepyCre** [PlaceholderAPI/PlaceholderAPI#297]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki
[Pull Requests]: https://github.com/PlaceholderAPI/PlaceholderAPI/pulls

## Please read
This template is only for requesting new functions to be added to PlaceholderAPI or for old one to be changed!  
Please use the [Request change (Wiki)] template to ask for additions/changes to the wiki.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already mention such a function/change and that there isn't a issue about this change on the [issues] page.

We recommend to [open a Pull Request][Pull Requests] for making changes to PlaceholderAPI's code.

### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New function for PlaceholderAPI.  
A new function that developers could use.
- [x] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Info
> What is the change?  
> Please provide as much information (including links, images and code-snippeds) as possible.

The default placeholder pattern (``[%]([^%]+)[%]``) is inherently flawed for the purpose of nesting/ recursively resolving placeholder:

``%placeholder1_%placeholder2%%`` will resolve ``%placeholder1_%`` first, leaving ``placeholder2%%`` behind.

The bracket placeholder pattern and relational placeholder pattern solve this issue. However, most plugin developers will likely choose to use the following functions for resolving placeholders (and retrieving other info), since they are worded as if they were the default:
```
setPlaceholders(OfflinePlayer player, List<String> text)
setPlaceholders(OfflinePlayer player, List<String> text, boolean colorize)
setPlaceholders(OfflinePlayer player, String text)
setPlaceholders(OfflinePlayer player, String text, boolean colorize)
setPlaceholders(Player player, String text)
setPlaceholders(Player player, String text, boolean colorize)
setPlaceholders(Player player, List<String> text)
setPlaceholders(Player player, List<String> text, boolean colorize)
containsPlaceholders(String text)
getPlaceholderPattern()
```

I suggest adding a new config option ``default-placeholder-pattern``. This option could either be a choice between the three current patterns (should add a 4th pattern that is formatted like the relational pattern so they won't interfere e.g.: ``[%](ph_)([^%]+)[%]``) or a String where you can specify a placeholder pattern yourself. This option would be set to the the current default pattern by default.

The functions mentioned above would then be copied to new functions named something like ``setPercentSignPlaceholders`` and the old functions would be changed such that they use the pattern set in the config.

I would also suggest renaming ``PLACEHOLDER_PATTERN`` to ``PERCENT_SIGN_PLACEHOLDER_PATTERN`` for clarity. ``PLACEHOLDER_PATTERN`` may be used as field name of the placeholder pattern set via config.

Since the config will have ``[%]([^%]+)[%]`` set as the default pattern this change will not break backwards compatibility.

If this suggestion gets accepted I would be happy to make a PR containing the changes discussed.

**Comment by Andre601** [comment]
To be fair, using placeholders within placeholders seems like a stupid idea.
People like me however, use the bracket-placeholder (`{placeholder_text}`)  inside the placeholder to achieve a similar result.
F.e. in my Math-expansion can you have `%math_{server_online}+1%` which would result in the number of online players plus one.

In addition can I not see a proper way to have this work without breaking every expansion in existence, that uses the % placeholder, as a simple find-replace doesn't seem like the right solution.

For example Expansion A uses the placeholder `%pl_my-expansion%` while Expansion B uses `%placeholder%`
This would require PAPI to distinguish both placeholders if the first one is available as a custom one.
Next could this become even more difficult if the placeholder has other placeholders within them.

But again: Most expansions (which depend on a plugin) shouldn't have placeholders within placeholders as things like getting the info of a player could easily be done through a separate placeholder.

**Comment by CreepyCre** [comment]
This isn't a per expansion placeholder pattern option. Changing the option will change the pattern Papi attempts to parse placeholders with for all plugins. For example, if you were to set the bracket placeholder pattern as default placeholder pattern you would need to write ``{placeholder}`` for all placeholders. You could however set the default placeholder pattern to anything you like, as it is set as a regex pattern in the config.

This change doesn't actually necessarily allow for nested placeholders, since they don't recursively resolve anyways. I can however push another commit that does this, since I already have it written anyways.

Placeholders within placeholders are necessary if you want to use something like an if-else palceholder. You could implement recursing over the placeholders in the placeholders themselves of course, but I don't see any reason why Papi shouldn't support it out of the box. At the very least there should be an expansion with a recursion placeholder.

**Comment by extendedclip** [comment]
We are actually getting ready to merge a pr that does away with regex so if this is an issue for you after that point please re open and we will revisit the issue at that point.
