### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by KiwiSAMA** [PlaceholderAPI/PlaceholderAPI#30]
This server is running Paper version git-Paper-1475 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
PlaceholderAPI version 2.9.1
Expansions: Multiverse Player Server Vault

https://pastebin.com/5QZEvi6q

**Comment by extendedclip** [comment]
Can you post the full error

**Comment by KiwiSAMA** [comment]
that is.
![hmm](https://airport.mccn.moe/storage/errorscreenshot.jpg)

**Comment by extendedclip** [comment]
Re-open if this issue occurs again.
