### ISSUE TITLE
[Placeholder Request]

### ISSUE THREAD

**Issue by falk-png** [PlaceholderAPI/PlaceholderAPI#301]
### Type
> What kind of request is this? A Placeholder Request

- [x] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Info
> What is the change?  
> Please provide as much information (including links, images and code-snippeds) as possible.

can someone pleasee make a placeholder, which shows the number in K(kilo) and M (million)?
Example: balance=15.000   %formatted_commas_0{vault_eco_balance}% -> 15k 
I think this is needed by many users, i would be very very happy!

**Comment by Andre601** [comment]
The Vault expansion specifically already has a placeholder to return the numbers in a formatted way.
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#economy

`%vault_eco_balance_formatted%` for example.

**Comment by falk-png** [comment]
> The Vault expansion specifically already has a placeholder to return the numbers in a formatted way.
> https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#economy
> 
> `%vault_eco_balance_formatted%` for example.

i know, but this is only for the eco balance, it would be cool, if this works for every number :)

**Comment by aBooDyy** [comment]
Hello there,

Thanks for reaching out!
It seems like @Andre601 has created an expansion for that, [Formatter](https://api.extendedclip.com/expansions/formatter/) expansion (Thanks to him).

Comment back if the expansion doesn't actually fulfill what you want and I'll reopen the issue.

King regards,
aBooDyy
