### ISSUE TITLE
SimpleClans Placeholders change

### ISSUE THREAD

**Issue by Peng1104** [PlaceholderAPI/PlaceholderAPI#302]
### Type
- [ ] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [X] Placeholder(s) changed.
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [X] Other: SimpleClans Ecloud Expansion is now part of the SimpleClans Plugin 

### Plugin
> What is the name of the plugin?

SimpleClans

### What is the new value?
> **Placeholder(s) changed**: Type what the old and the new placeholder(s) is/are.  
> **New Placeholder(s)**: Type the new placeholder(s).  
> **Plugin no longer supports PlaceholderAPI**: Leave this blank.

In the SimpleClans version 2.10.1 (download in https://github.com/marcelo-mason/SimpleClans/releases) the ecloud expansion is now part of the SimpleClans plugin

Placeholder removed:
- %simpleclans_clan_tag_label%

Placeholders added:
- %simpleclans_clanchat_player_color%
- %simpleclans_allychat_player_color%
- %simpleclans_rank_displayname%

**Comment by RoinujNosde** [comment]
The Wiki still says:
> /papi ecloud download SimpleClans

Downloading the expansion is no longer required.

**Comment by cj89898** [comment]
@Peng1104 Can you remove your expansion from the github and confirm?

**Comment by Peng1104** [comment]
> @Peng1104 Can you remove your expansion from the ecloud?

It will stay there for the people that use the old SimpleClans version (2.10.0 or lower)

**Comment by cj89898** [comment]
Ah okay. Thanks!
