### ISSUE TITLE
Placeholder to check player recipe status

### ISSUE THREAD

**Issue by Darwin1546** [PlaceholderAPI/PlaceholderAPI#305]
### Type
- [X] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).

### Info
Ability to check player recipe status. Can be useful on servers with doLimitedCrafting gamerule.
```
%player_can_craft_<recipe>% 
```
> %player_can_craft_minecraft:iron_hoe%
```
%player_known_recipes%
```

**Comment by cj89898** [comment]
Should be over at https://github.com/PlaceholderAPI/Player-Expansion/issues
