### ISSUE TITLE
See if other servers are Online playsholder

### ISSUE THREAD

**Issue by Cheezelaweeze** [PlaceholderAPI/PlaceholderAPI#306]
i would like a playsholder that shows if the other bungeecord servers are online like on the server selecter it would show if the UHC server is online. please add i need it!

**Comment by Andre601** [comment]
Please check for existing solutions next time:
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#bungeecord

**Comment by Andre601** [comment]
Also, please use one of the templates next time. They exist for reasons.
