### ISSUE TITLE
NPE on PlaceholderAPIHook

### ISSUE THREAD

**Issue by ItsHoney** [PlaceholderAPI/PlaceholderAPI#309]
### Issue
> What is the issue? Describe it like you would tell a friend.

I am using Context feature of Luckperms to setup permissions which are only true when certain placeholders return certain values.(ExtraContexts Plugin). However, SuperVanish always returns a huge stacktrace everytime a player joins, and sometimes the permission works as intended, and sometimes it does not.I am using the placeholder, %supervanish_isvanished% to determine if a player is vanished, If so, then I hide their join message otherwise it is showed.

### Expected behaviour
> What should PlaceholderAPI do?

Return the placeholder value everytime it is requested by Luckperms.

### Actual behaviour
> What does PlaceholderAPI actually do?

Returns NPE.

### How to reproduce
> What steps did you made, to get this bug?

1.  Simply loading the plugin with the latest version of PAPI will give you errors when the player joins.

[message.txt](https://github.com/PlaceholderAPI/PlaceholderAPI/files/4602797/message.txt)

**Comment by darbyjack** [comment]
Contact author of SuperVanish.
