### ISSUE TITLE
Pinger Expansion Placeholders Issues

### ISSUE THREAD

**Issue by Jnxd1** [PlaceholderAPI/PlaceholderAPI#31]
**Plugin Used:** "DeluxeMenus 1.10.5", "PlaceholderAPI 2.9.1"
 **- Expansion:** "Pinger"
**Server Version:** Spigot 1.8.8

**Issue:** The placeholder check is broken. Having 2 items with the proper "priority" and "setup", the placeholder :%pinger_online_servername:25858%" is not pinging the server correctly and giving an output as the server is always online.
Even after shutting down the server, opening the GUI the second item is taking priority and showing the server as offline, but when using the option "refresh" on the 2nd item the 1st item will be displayed again although the server is offline.
I know 100% that my configuration of that GUI is correct and so i've tried different configurations of the pinger placeholder (%pinger_online_servername:25858% using the numeric ip and using the alphabetic name as it is in the bungee cord config with caps and without), the result is still the same..

PS. - The server doesn't run on the default Mc port. May that be the issue?

Thanks!

**Comment by aBo0oDyy** [comment]
the default check interval is 30 seconds `check_interval: 30` change it and it should work with you
its in papi config..

**Comment by Jnxd1** [comment]
@aBo0oDyy , i've tried that and it is not working. And if you'd go and read my post again you will see that the issue is not only/or atleast not the only one.
Even if the server that i'm pinging it is offline it will display it in the GUI as it is online. Tested with `check_interval: 30` , `check_interval: 1` , `check_interval: 2` .

**Comment by aBo0oDyy** [comment]
can u send ur menu?

**Comment by Jnxd1** [comment]
`menu_title: '&8Server Selector'
open_command:
- servers
size: 27
update_interval: 1
items:
  KITPVP_ONLINE:
    material: DIAMOND_SWORD
    data: 0
    slot: 11
    hide_attributes: true
    priority: 1
    view_requirement:
      requirements:
        server_online:
          type: string equals ignorecase
          input: '%pinger_online_###.###.##.###:25858%'
          output: '&aOnline'
    display_name: '&d&lKitPvP'
    lore:
    - '&7 * Status: &aOnline'
    - '&7 * Online Players: &e%bungee_kitpvp%'
    - ''
    - ' 8&oClick to connect...'
    left_click_commands:
    - '[connect] kitpvp'
    - '[close]'
    right_click_commands:
    - '[connect] kitpvp'
    - '[close]'
  KITPVP_OFFLINE:
    material: WOOL
    data: 14
    slot: 11
    priority: 2
    display_name: '&cKitPvP'
    lore:
    - '&cOffline'
    left_click_commands:
    - '[refresh]'
    right_click_commands:
    - '[refresh]'
`

**Comment by aBo0oDyy** [comment]
its working fine for me...
i used it with testplugins server and its displaying online item, when i change it to another offline server it displays the offline item
u need to wait after running/shutting down the server then it should work fine

**Comment by Jnxd1** [comment]
@aBo0oDyy , yes you are right. Everything works flawlessly.
I was pinging the wrong server... (face-palm)
Thanks, cheers.

**Comment by aBo0oDyy** [comment]
lol
glad u solved it tho 😁
