### ISSUE TITLE
Add Formatter expansion

### ISSUE THREAD

**Issue by Andre601** [PlaceholderAPI/PlaceholderAPI#310]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

## Please read
This template is only for requesting new information to be added to the wiki or for updating of already existing information!  
Please use the [Request change (PlaceholderAPI)] template to ask for additions/changes to the plugin PlaceholderAPI.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already have the change and that there isn't a issue about this change on the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

Created the [Formatter expansion](https://api.extendedclip.com/expansions/formatter/) ([GitHub](https://github.com/Andre601/Formatter-Expansion)) which allows to format numbers.

Placeholder:
```
%formatter_<options>%
```
Options can be the following things:
- `format:(<format>)` - The actual format, using Java's DecimalFormat system.
- `value:(<value>)` - The number to format. This is the only required option.
- `locale:(<locale>)` - The locale to use. Formats can be different depending on the locale.

**Comment by aBooDyy** [comment]
Hello there,

[Added](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#formatter).

Thanks for your contribution,
aBooDyy

**Comment by Andre601** [comment]
Forgot to mention, that `time` is also a available option to use, to turn the number into a duration.
