### ISSUE TITLE
Remove LeaderHeads

### ISSUE THREAD

**Issue by RobinDeBaets** [PlaceholderAPI/PlaceholderAPI#311]
### Type
- [x] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.

### Info

The [LeaderHeads](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#leaderheads) expansion does not work with newer versions of LeaderHeads. People are confused and think they need it for the plugin to work, but they don't.
Please remove it.

**Comment by aBooDyy** [comment]
Hello there,

Thanks for letting us know.
As I can see from your wiki, you're now providing PAPI placeholders through the plugin itself (I assume). So I've [updated the wiki](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#leaderheads) to show the new placeholders and removed the download command.
Let us know if there's something wrong or you'd like to remove it completely.

Have a nice day,
aBooDyy
