### ISSUE TITLE
FactionsUUID wiki updates

### ISSUE THREAD

**Issue by CmdrKittens** [PlaceholderAPI/PlaceholderAPI#312]
### Type

- [x] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.

### Info

I propose the following as the updated documentation. For convenience, here's a gist of it in [rendered](https://gist.github.com/CmdrKittens/c1228c93c30219ae5164dffe5cb8ac4c) and [raw](https://gist.githubusercontent.com/CmdrKittens/c1228c93c30219ae5164dffe5cb8ac4c/raw/f1c94b7697a4e1adc33e2278b864ed40410e53a3/fuuid_placeholders_20200522.md) form.

---

Descriptions of each placeholder can be found on the [official documentation](https://factions.support/placeholderapi/).

**Player placeholders.** These placeholders will give information about the player themselves.

```
%factionsuuid_player_balance%
%factionsuuid_player_deaths%
%factionsuuid_player_group%
%factionsuuid_player_kills%
%factionsuuid_player_lastseen%
%factionsuuid_player_maxpower%
%factionsuuid_player_name%
%factionsuuid_player_power% 
%factionsuuid_player_role%
%factionsuuid_player_role_name%
```

**Faction placeholders.** These placeholders provide information on the player's current faction.
*However*, if you edit any of these placeholders to instead say `faction_territory`, such as 
`%factionsuuid_faction_territory_name%`, it will instead display information about the faction
which owns the territory in which the player is currently standing. In this way, 
`%factionsuuid_faction_territory_relation_color%` provides the color code for the relationship
between the player and the faction owning the territory they're in.

```
%factionsuuid_faction_allies%
%factionsuuid_faction_allies_players%
%factionsuuid_faction_allies_players_offline%
%factionsuuid_faction_allies_players_online%
%factionsuuid_faction_bank_balance%
%factionsuuid_faction_claims%
%factionsuuid_faction_deaths%
%factionsuuid_faction_description%
%factionsuuid_faction_dtr%
%factionsuuid_faction_dtr_frozen%
%factionsuuid_faction_dtr_frozen_time%
%factionsuuid_faction_dtrmax%
%factionsuuid_faction_enemies%
%factionsuuid_faction_enemies_players%
%factionsuuid_faction_enemies_players_offline%
%factionsuuid_faction_enemies_players_online%
%factionsuuid_faction_founded%
%factionsuuid_faction_home_world%
%factionsuuid_faction_home_x%
%factionsuuid_faction_home_y%
%factionsuuid_faction_home_z%
%factionsuuid_faction_joining%
%factionsuuid_faction_kills%
%factionsuuid_faction_land_refund%
%factionsuuid_faction_land_value%
%factionsuuid_faction_leader%
%factionsuuid_faction_maxclaims%
%factionsuuid_faction_maxvaults%
%factionsuuid_faction_name%
%factionsuuid_faction_name_custom%
%factionsuuid_faction_offline%
%factionsuuid_faction_online%
%factionsuuid_faction_only_space%
%factionsuuid_faction_peaceful%
%factionsuuid_faction_power%
%factionsuuid_faction_powerboost%
%factionsuuid_faction_powermax%
%factionsuuid_faction_raidable%
%factionsuuid_faction_relation_color%
%factionsuuid_faction_size%
%factionsuuid_faction_tnt_balance%
%factionsuuid_faction_tnt_max_balance%
%factionsuuid_faction_truces%
%factionsuuid_faction_truces_players%
%factionsuuid_faction_truces_players_offline%
%factionsuuid_faction_truces_players_online%
%factionsuuid_faction_warps%
```

**Comment by aBooDyy** [comment]
Hello there,

Thanks for letting us know!
I've removed the old placeholders and added the link to your wiki.

Thanks for using PlaceholderAPI,
aBooDyy
