### ISSUE TITLE
Placeholder request: player count per world

### ISSUE THREAD

**Issue by SlimeDog** [PlaceholderAPI/PlaceholderAPI#313]
### Issue
> What is the issue? Describe it like you would tell a friend.

Neither Multiverse placeholders nor ListPlayers placeholders (nor anywhere else I can find) includes a count of players in a world. Use case: Lobby signs could show the number of players in selected worlds. Apologies if my search did not find an existing PAPI placeholder.

### Expected behaviour
> What should PlaceholderAPI do?

Return an integer for the number of players in the specified world.

**Comment by aBooDyy** [comment]
Hello there,

Thanks for reaching out.
Server expansion has a placeholder for that, `%server_online_<world>%`.

Have a nice day,
aBooDyy

**Comment by SlimeDog** [comment]
Thanks. Much appreciated.
