### ISSUE TITLE
Use GitHub Action to auto-update wiki on PR merges

### ISSUE THREAD

**Issue by Andre601** [PlaceholderAPI/PlaceholderAPI#316]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki
[Pull Requests]: https://github.com/PlaceholderAPI/PlaceholderAPI/pulls

## Please read
This template is only for requesting new functions to be added to PlaceholderAPI or for old one to be changed!  
Please use the [Request change (Wiki)] template to ask for additions/changes to the wiki.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already mention such a function/change and that there isn't a issue about this change on the [issues] page.

We recommend to [open a Pull Request][Pull Requests] for making changes to PlaceholderAPI's code.

### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [x] Other: Change to the wiki 

### Info
> What is the change?  
> Please provide as much information (including links, images and code-snippeds) as possible.

I suggest to move the [wiki](../wiki) from where it is to GitHub pages, by either having a `gh-pages` branch or building the page from a `docs` folder.

**What are the benefits?**
Having the wiki in a docs folder on the repository would be a beneficial change, because

- People can much easier request changes by directly making a PR towards the wiki pages.
- It would allow you to keep control about what changes are being accepted and what isn't, where a wiki would be more or less all-or-nothing (Either everyone can make changes or only a selected few).

If you want to stick with the GitHub Wiki could you use something like the [Wiki Page Creator Action](https://github.com/marketplace/actions/wiki-page-creator-action) to automatically update it when changes are merged.

I really see this as a good change since it would allow many more contributions from others and may even help keeping the wiki more up to date.

**Comment by extendedclip** [comment]
This is completely up to you guys.

**Comment by Andre601** [comment]
I personally believe, that at least having the files of the wiki in a separate folder in this repository (wiki folder) and then using a GitHub Action to automatically push changes to the main wiki would be a huge benefit, as people could just make PRs to add/edit pages, which then could be merged/closed.
This would give the freedom of allowing others to edit the wiki, without the risk of having trolls messing it up, since the wiki's perm system is basically all or nothing.

**Comment by axelrindle** [comment]
I can recommend using [orchid](https://orchid.run/). It provides javadoc generation and custom wiki features.

**Comment by Andre601** [comment]
That are some interesting Javadocs.
And I mean sure, why not, it's something new and not just the exact same boring Javadocs.

**Comment by Andre601** [comment]
I actually looked into (and try to use) Orchid and while it sure is interesting, does it have some major flaws.

- Any `{@link}` tag will have the text without any space before and after it.
- `{@link}` to external resources aren't working yet.
- Wiki pages are somewhat a mess and would require an entire rewriting of ALL paths, relative or not.
- Overall structure is weird and configuration isn't that easy. It took me 2 hours and the help of the maintainer/dev of Orchid to get a somewhat working version.

If you have some decent knowledge with it, could you perhaps try it, but other than that do I not see a good reason to switch to it and I would rather recommend the approach with the GitHub Action thing (Auto-updating the wiki on commits towards a specific folder)

**Comment by axelrindle** [comment]
True. I've had the same issues with understanding their docs. Took me some time to get what I wanted. If you want a reference, you could [take a look on what I accomplished](https://axelrindle.github.io/PocketKnife/).

Otherwise I would also recommend sticking with your approach and eventually reconsidering orchid at a later point in time or another static site generator. Maybe have a look [at this list](https://github.com/myles/awesome-static-generators).

**Comment by Andre601** [comment]
The list you linked only has 2 java-related generators. And wiki generators are also basically a joke there.
I think the idea I suggested (with the GitHub Action) is the best solution there is so far...
