### ISSUE TITLE
Issue with Placeholders (1.13-Pre7)

### ISSUE THREAD

**Issue by instantout** [PlaceholderAPI/PlaceholderAPI#32]
So having issues in version 1.13 with placeholders. just dumping them here (well the ones i use).

%statistic_player_kills%
%statistic_time_played%

Most of the Entities for killed/kill
%statistic_kill_entity_<Entity>% (example bottom)
%statistic_kill_entity_GHAST%

i guess Statistic mine and use items... mostly stats.
%statistic_mine_block_COAL_ORE%
%statistic_use_item_COAL_ORE%

**Comment by darbyjack** [comment]
Any errors in the console?

**Comment by Banbeucmas** [comment]
@darbyjack I think we can try to replicate this by using the placeholder itself. I don't think these stuff relies on the Spigot/Bukkit but instead invoking it with reflection/etc.

**Comment by darbyjack** [comment]
@Banbeucmas It these placeholders come directly from the MC system.

**Comment by Mishyy** [comment]
@instantout What exactly is the issue you are having?

**Comment by darbyjack** [comment]
Can we get an update from the OP on the latest 1.13 release?

**Comment by extendedclip** [comment]
https://github.com/PlaceholderAPI/Statistics-Expansion
