### ISSUE TITLE
SimpleClans TopClans Placeholders

### ISSUE THREAD

**Issue by RoinujNosde** [PlaceholderAPI/PlaceholderAPI#320]
### Type
> What kind of change is it? (Multiple selections possible)

- [ ] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [X] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

Added:
```
%simpleclans_topclans_POSITION_color_tag%
%simpleclans_topclans_POSITION_kdr%
%simpleclans_topclans_POSITION_total_kills%
```

POSITION should be replaced by a rank position. Eg.:
%simpleclans_topclans_1_kdr%
%simpleclans_topclans_2_kdr%
%simpleclans_topclans_3_kdr%
%simpleclans_topclans_4_kdr%
%simpleclans_topclans_5_kdr%

**Comment by aBooDyy** [comment]
[Updated](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#simpleclans).
Thanks for letting us know!

Have a nice day,
aBooDyy
