### ISSUE TITLE
ChatColor doesn't work properly 

### ISSUE THREAD

**Issue by jojohamster80** [PlaceholderAPI/PlaceholderAPI#327]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Spigot]: https://www.spigotmc.org/resources/6245/
[Jenkins]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

## Please read
This template is only for reporting bugs of PlaceholderAPI!  
If you want to request changes to the code of PlaceholderAPI, use the [Request change (PlaceholderAPI)] template.  
For changes to the wiki use the [Request change (Wiki)] template.

Please also make sure that you use the [latest release][Spigot] or the latest [developement build][Jenkins] and that your bug isn't already reported on the [issues] page.

**Please report issues with expansions/placeholders to the corresponding issue tracker! Only report it here if you can't find any place to report it!**

### Issue
> What is the issue? Describe it like you would tell a friend.

all day I was trying to figure out why the second line of chat color did not work so I narrowed down the plugins to Placeholderapi 1.9.2. When I deleted the plugin the chat color worked, but the placeholder didn't work since I deleted the plugin. So I put in the newest version of Placeholderapi 2.10.6 and it did the exact same thing as version 1.9.2. So then I deleted the 2.10.6 version and tried an older version Placeholderapi 2.8.6, but for some reason the chat colors do work but then every other placeholder does not work. Is there anything that could meet in the middle?

### Expected behavior
> What should PlaceholderAPI do?

chat color should reach to the second line of the chat  

### Actual behavior
> What does PlaceholderAPI actually do?

the second line of chat turns white and does not continue the color 

### How to reproduce
> What steps did you made, to get this bug?

1. had the version Papi 1.9.2 second line of chat color didn't work
2. tried the most recent version Papi 1.10.6 did the exact same thing as Papi 1.9.2
3. tried version Papi 1.8.7 second-line worked, but every other placeholder did not work

**Comment by aBooDyy** [comment]
Hello there,

PlaceholderAPI job is pretty much replacing the placeholder with its value.
You haven't mentioned anything about where you're using the "chat color". This might be from your chat plugin or the plugin you're using.

PlaceholderAPI has changed the way of providing placeholders by other plugins, so this is probably why v1.8.7 is working with your chat color placeholders but not other placeholders. In this case, your chat color placeholders are most likely outdated and you might want to contact the author of your chat color plugin or whatever the plugin you're using to update it.
Let me know if I've misunderstood your issue.

Regards,
aBooDyy

**Comment by jojohamster80** [comment]
I am using the chat color in chat (ChatColorX). It is not my Chat color plugin because I have used a few different plugins for coloring the text in chat and they all had the same result as the one I am using currently. I message the ChatColorX people and they said everything is up to date. I had this problem previously with a server with version 1.13.2 (I am using version 1.8 currently).

**Comment by jojohamster80** [comment]
I also contacted the chat plugin I am using they said everything was working for them and we tried to sort things out. They directed me to ask the ChatColorX people. I asked them and it worked for them but still had the same problem

**Comment by extendedclip** [comment]
If chat color is breaking when chat reaches the second line it is the chat formatting plugin (which I assume is using JSON) and has nothing to do with papi.
