### ISSUE TITLE
ProCosmetics placeholders

### ISSUE THREAD

**Issue by File14** [PlaceholderAPI/PlaceholderAPI#331]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

## Please read
This template is only for requesting new information to be added to the wiki or for updating of already existing information!  
Please use the [Request change (PlaceholderAPI)] template to ask for additions/changes to the plugin PlaceholderAPI.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already have the change and that there isn't a issue about this change on the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

**[ProCosmetics ](https://www.spigotmc.org/resources/49106)placeholders:**
%procosmetics_coins% - gets a player's current amount of coins. Please note, if Vault support is enabled, the vault money is given.

%procosmetics_cosmetics_activated_% - checks if cosmetics are available to equip. The anti-lag system returns "Activated", "Deactivated" or "Function Disabled" depending on what TPS your server has.

%procosmetics_treasures_(treasure_name)% - replace the (treasure_name) with the name of the treasure to get the current amount of them. Ex: %pcosmetics_treasures_normal% (Note for PAPI staff, I cannot provide all of the treasures as the user themself can create custom treasures). 

Please note, the plugin does support other placeholders as well.

**Comment by Funny-cube** [comment]
[Added](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#procosmetics).

Thanks for supporting PlaceholderAPI.

Cheers,
funnycube

**Comment by NilanFuncke** [comment]
Very cool! What is the placeholder for the Tag of the status that is equipped?
