### ISSUE TITLE
Plugin doesn't work on 1.16

### ISSUE THREAD

**Issue by mybe** [PlaceholderAPI/PlaceholderAPI#339]
### Issue
PlaceholderAPI does not work correctly on 1.16. 

### Expected behaviour
/papi bcparse me %server_tps%
This should return our server's TPS. 

We also use ChatControl, and our join message should appear like:
(+ username)

### Actual behaviour
It actually returns %server_tps%.

Our ChatControl behaves instead like:
(+ %player)

### How to reproduce
We are running a Paper server, updated to the latest version of Paper and latest CI dev build of PlaceholderAPI (PlaceholderAPI-2.10.7-DEV-90.jar). We also tested the latest stable release on Spigot.
/papi bcparse me %server_tps%

**Comment by Andre601** [comment]
1. Please follow the issue template
2. 1.16.1 was released not even a week ago and the same goes for 1.16 itself.

Please give the devs some time to work on the plugin as not everything can be done instantly.
Also, next time, take a look at the open Pull requests of PlaceholderAPI as this is clearly [being worked on](https://github.com/PlaceholderAPI/PlaceholderAPI/pull/333)

**Comment by mybe** [comment]
Please see this issue: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/337#issuecomment-650522763

where it is stated that "Latest release is stable on 1.16 already.". This was two days ago.

**Comment by Sparoney** [comment]
I understand that "Latest release is stable on 1.16 already" but I also have the latest version of the plugin from Spigot and I'm using PaperSpigot 1.16.1 and none of the placeholders work.

**Comment by Frcsty** [comment]
Join the HelpChat discord and provide a startup log, as well as some detail on "placeholders don't work"

**Comment by Sparoney** [comment]
> Join the HelpChat discord and provide a startup log, as well as some detail on "placeholders don't work"

Alright I'll do that, but by "placeholders don't work" I meant the same as OP, it just says "%player_name%" instead of the player's actual name

**Comment by Frcsty** [comment]
> > Join the HelpChat discord and provide a startup log, as well as some detail on "placeholders don't work"
> 
> Alright I'll do that, but by "placeholders don't work" I meant the same as OP, it just says "%player_name%" instead of the player's actual name

Assuming that you have not downloaded the player expansion and reloaded papi

**Comment by Sparoney** [comment]
> > > Join the HelpChat discord and provide a startup log, as well as some detail on "placeholders don't work"
> > 
> > 
> > Alright I'll do that, but by "placeholders don't work" I meant the same as OP, it just says "%player_name%" instead of the player's actual name
> 
> Assuming that you have not downloaded the player expansion and reloaded papi

Oh my god I'm so dumb. I apologise, that is my fault.
