### ISSUE TITLE
TokenEnchant Expansion Won't Update

### ISSUE THREAD

**Issue by axemwa** [PlaceholderAPI/PlaceholderAPI#34]
TokenEnchant Expansion Won't Update

**Comment by extendedclip** [comment]
This is most likely an issue where expansion names do not match (the name of the project on the expansion cloud site and the expansion its self).

**Comment by axemwa** [comment]
Is this something I can fix? Do I have to be more specific when I type "/papi ecloud download TokenEnchant" in chat like include the version name and stuff?

**Comment by extendedclip** [comment]
VK will need to set the getName field in his expansion to match the name his expansion was uploaded as. If the expansion is currently enabled just disregard the color in papi ecloud list for now until he does.
