### ISSUE TITLE
Errors in 1.16

### ISSUE THREAD

**Issue by thecenters** [PlaceholderAPI/PlaceholderAPI#341]
Using 2.10.6 on 1.16.1 I'm getting these errors on the server. I reached out to the developer of TNE and they informed me it was an issue outside of their plugin.

01.07 12:51:59 [Server] WARN [PlaceholderAPI] Plugin PlaceholderAPI v2.10.6 generated an exception while executing task 1009
01.07 12:51:59 [Server] INFO java.lang.NullPointerException: null
01.07 12:51:59 [Server] INFO at net.tnemc.core.common.api.TNEAPI.getHoldings(TNEAPI.java:289) ~[?:?]
01.07 12:51:59 [Server] INFO at net.tnemc.core.common.api.Economy_TheNewEconomy.getBalance(Economy_TheNewEconomy.java:98) ~[?:?]
01.07 12:51:59 [Server] INFO at net.tnemc.core.common.api.Economy_TheNewEconomy.getBalance(Economy_TheNewEconomy.java:93) ~[?:?]
01.07 12:51:59 [Server] INFO at com.extendedclip.papi.expansion.vault.VaultEcoHook.getBalance(VaultEcoHook.java:220) ~[?:?]
01.07 12:51:59 [Server] INFO at com.extendedclip.papi.expansion.vault.BalTopTask.run(BalTopTask.java:48) ~[?:?]
01.07 12:51:59 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-27]
01.07 12:51:59 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.1.jar:git-Paper-27]
01.07 12:51:59 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.1.jar:git-Paper-27]
01.07 12:51:59 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
01.07 12:51:59 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
01.07 12:51:59 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]

01.07 12:52:28 [Server] WARN [PlaceholderAPI] Plugin PlaceholderAPI v2.10.6 generated an exception while executing task 1009
01.07 12:52:28 [Server] INFO java.lang.NullPointerException: null

01.07 12:52:59 [Server] WARN [PlaceholderAPI] Plugin PlaceholderAPI v2.10.6 generated an exception while executing task 1009
01.07 12:52:59 [Server] INFO java.lang.NullPointerException: null

01.07 12:53:28 [Server] WARN [PlaceholderAPI] Plugin PlaceholderAPI v2.10.6 generated an exception while executing task 1009
01.07 12:53:28 [Server] INFO java.lang.NullPointerException: null

**Comment by darbyjack** [comment]
This is related to TNE. We've released dev builds for 1.16 now.
