### ISSUE TITLE
Requesting new Expansion: World

### ISSUE THREAD

**Issue by thienbao860** [PlaceholderAPI/PlaceholderAPI#345]
### Type
> What kind of change is it? (Multiple selections possible)

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

This is the World expansion that was added a long time ago by me. Now will be on Github wiki:
NOTE: For totalBalance placeholder, you must have a service provider plugin (EssentialsX is one)
%world\_\#\_biome%
%world\_\#\_nearbyEntities\_\<radius\>%
%world\_\<world\>\_name%
%world\_\<world\>\_seed%
%world\_\<world\>\_time%
%world\_\<world\>\_canPvP%
%world\_\<world\>\_animalAllowed%
%world\_\<world\>\_monsterAllowed%
%world\_\<world\>\_difficulty%
%world\_\<world\>\_players%
%world\_\<world\>\_players\_\<group\>%
%world\_\<world\>\_difficulty%
%world\_\<world\>\_playerExist%
%world\_\<world\>\_gamerule\_\<gamerule\>%
%world\_\<world\>\_recentjoin%
%world_\<world>_recentquit%
%world\_\<world\>\_totalBalance%

**Comment by Funny-cube** [comment]
Updated.

Thanks for supporting PlaceholderAPI.

Cheers,
Funnycube
