### ISSUE TITLE
Add StaffFacilities to placeholders wiki

### ISSUE THREAD

**Issue by xtomyserrax** [PlaceholderAPI/PlaceholderAPI#347]
### Type
> What kind of change is it? (Multiple selections possible)

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
My plugin StaffFacilities has PAPI support and also has its own placeholders! Here is the download link: /papi ecloud download StaffFacilities

More info about these placeholders can be found [here](https://github.com/xtomyserrax/StaffFacilities/wiki/PlaceholderAPI)

And here is the list of placeholders:

%stafffacilities_bungeetotal%
%stafffacilities_staffonline%
%stafffacilities_onlineplayers%
%stafffacilities_dutysize%
%stafffacilities_ischatmuted%
%stafffacilities_playergamemode%
%stafffacilities_isplayerfrozen%
%stafffacilities_maintenancemode%
%stafffacilities_amountofreports%
%stafffacilities_onduty%
%stafffacilities_ongodmode%
%stafffacilities_onfly%
%stafffacilities_vanished%
%stafffacilities_fakeleaved%
%stafffacilities_watchovered%
%stafffacilities_staffwatched%
%stafffacilities_staffvanished%
%stafffacilities_tab_duty%
%stafffacilities_tab_fakeleave%
%stafffacilities_tab_freeze%
%stafffacilities_tab_staffvanish%
%stafffacilities_tab_vanish%

Thank you so much!!!

**Comment by Funny-cube** [comment]
Updated.

Thanks for supporting PlaceholderAPI.

Cheers,
Funnycube
