### ISSUE TITLE
Request to add Time Tokens placeholders to wiki

### ISSUE THREAD

**Issue by Liinx** [PlaceholderAPI/PlaceholderAPI#348]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

### Type
> What kind of change is it? (Multiple selections possible)

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
I made a plugin called Time Tokens and added support for Placeholder API with my own placeholders that i would like to be added on here.

Here are the placeholders with descriptions:

%timetokens_time_played% - Time player spent on the network.
%timetokens_token_name_plural% - Name of the tokens in plural.
%timetokens_token_name_singular% - Name of the tokens in singular.
%timetokens_player_name% - Players name.
%timetokens_player_tokens% - Amount of tokens that player has on the network.
%timetokens_daily_bonus_remaining% - Time until the next time player can receive there daily bonus.
%timetokens_server_name% - Sub-server name that the player is currently on.
%timetokens_currently_open_menu% - Menu that is currently open to player if there is one.

Thank you in advance.

**Comment by Funny-cube** [comment]
Updated.

Thanks for supporting PlaceholderAPI.

Cheers,
Funnycube
