### ISSUE TITLE
papi enablecloud/disablecloud unknown command

### ISSUE THREAD

**Issue by SlimeDog** [PlaceholderAPI/PlaceholderAPI#350]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Spigot]: https://www.spigotmc.org/resources/6245/
[Jenkins]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

## Please read
This template is only for reporting bugs of PlaceholderAPI!  
If you want to request changes to the code of PlaceholderAPI, use the [Request change (PlaceholderAPI)] template.  
For changes to the wiki use the [Request change (Wiki)] template.

Please also make sure that you use the [latest release][Spigot] or the latest [developement build][Jenkins] and that your bug isn't already reported on the [issues] page.

**Please report issues with expansions/placeholders to the corresponding issue tracker! Only report it here if you can't find any place to report it!**

### Issue
> What is the issue? Describe it like you would tell a friend.

papi enablecloud/disablecloud unknown command

### Expected behaviour
> What should PlaceholderAPI do?

Use to work, still listed in help

### Actual behaviour
> What does PlaceholderAPI actually do?

```
>papi enablecloud
[10:48:59] [Server thread/INFO]: Unknown command.
```

### How to reproduce
> What steps did you made, to get this bug?

1. Upgrade to PAPI dev build 96
2. Start server
3. execute `>papi enablecloud`

**Comment by SlimeDog** [comment]
Further research, commands replaced by
```
> papi ecloud enable
> papi ecloud disable
```

**Comment by extendedclip** [comment]
Need to fix the help command if the correct command is not specified

**Comment by SlimeDog** [comment]
True that. :)

**Comment by SlimeDog** [comment]
disable cloud is also listed on the wiki [commands](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Commands) list

and ecloud enable/disable are not listed there.

**Comment by Sxtanna** [comment]
I've updated the wiki to reflect this, the command will be fixed when I am done rewriting them.
