### ISSUE TITLE
Add new plugin to "Plugins using PlaceholderAPI"

### ISSUE THREAD

**Issue by RainbowDashLabs** [PlaceholderAPI/PlaceholderAPI#351]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

### Type

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info

[Big Doors Opener](https://www.spigotmc.org/resources/big-doors-opener.80805/) allows to use placeholders from Placeholder API

**Comment by Andre601** [comment]
Added to [the list](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI)

Thank you for supporting PlaceholderAPI.
