### ISSUE TITLE
Add new plugin to "Plugins using PlaceholderAPI"

### ISSUE THREAD

**Issue by axelrindle** [PlaceholderAPI/PlaceholderAPI#353]
### Type
- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
I recently added support for using existing placeholders to one of my own plugins: [Broadcaster-Plugin](https://github.com/axelrindle/Broadcaster-Plugin).

As a side note, only **non-player** related placeholders can be used (e.g. server stats, etc.). No own placeholders are provided.

**Comment by Andre601** [comment]
Added to [the list](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI)

Thank you for supporting PlaceholderAPI.
