### ISSUE TITLE
New plugin supporting PlaceholderAPI

### ISSUE THREAD

**Issue by ThePlay3r** [PlaceholderAPI/PlaceholderAPI#356]
### Type
> What kind of change is it? (Multiple selections possible)

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

Hi,

I would like to add my new "[Marriage](https://www.spigotmc.org/resources/marriage-1-8-1-16-show-your-love.81807/)" plugin to the PlaceholderAPI placeholders list, as it supports PAPI.

Placeholders, that I would like to be added:

> %marriage_gender_symbol%
> Returns gender symbol of player, defined in config.yml
> 
> %marriage_gender_color%
> Returns gender color of player, defined in config.yml
> 
> %marriage_partner%
> Returns player's partner

**Comment by Andre601** [comment]
[Added it to the Placeholder list](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#marriage)

Thank you for supporting PlaceholderAPI!
