### ISSUE TITLE
Update all extensions command

### ISSUE THREAD

**Issue by VergilPrime** [PlaceholderAPI/PlaceholderAPI#358]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki
[Pull Requests]: https://github.com/PlaceholderAPI/PlaceholderAPI/pulls

### Type
> What kind of request is this? (Multiple selections possible)
- [ ] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [x] Other: addition of a command, probably won't break stuff

### Info
> What is the change?  
> Please provide as much information (including links, images and code-snippeds) as possible.

Addition of a command to update all extensions at once, example:
```/papi ecloud update all```

**Comment by Sxtanna** [comment]
@VergilPrime I will be adding this with the syntaxes.
```
/papi ecloud update all
/papi ecloud update <expansion>
```

**Comment by Sxtanna** [comment]
All done.
![image](https://user-images.githubusercontent.com/20979389/88460837-3db12c80-ce6d-11ea-945e-774a966bed04.png)
and ofc.
![image](https://user-images.githubusercontent.com/20979389/88460886-8ff24d80-ce6d-11ea-8e67-b5ac833356bf.png)
