### ISSUE TITLE
Sort expansions alphabetically 

### ISSUE THREAD

**Issue by Funny-cube** [PlaceholderAPI/PlaceholderAPI#363]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki
[Pull Requests]: https://github.com/PlaceholderAPI/PlaceholderAPI/pulls

## Please read
This template is only for requesting new functions to be added to PlaceholderAPI or for old one to be changed!  
Please use the [Request change (Wiki)] template to ask for additions/changes to the wiki.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already mention such a function/change and that there isn't a issue about this change on the [issues] page.

We recommend to [open a Pull Request][Pull Requests] for making changes to PlaceholderAPI's code.

### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New function for PlaceholderAPI.  
A new function that developers could use.
- [x] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Info
> What is the change?  
> Please provide as much information (including links, images and code-snippeds) as possible.

The expansion list should be ordered alphabetically to allow users to actually search through the list to find something rather than defaulting to the last update where the list would seem fairly random to the end user.

One solution is to allow the user to specify how it is sorted via some sort of flag/argument

**Comment by Sxtanna** [comment]
> to allow users to actually search through the list to find something
I personally find this to be a moot point, the current command system offers full tab-completion in all places.

![image](https://user-images.githubusercontent.com/20979389/88392327-c8b8f680-cd89-11ea-975d-7fd9e94fe879.png)

If they are looking for something specific they can easily just type the name of it, and have it complete for them.

**Comment by Funny-cube** [comment]
Was talking specifically about the list command not the download command.

I believe it would be a benefit of being able to change how the expansions are sorted via the list command and outlining to the user how it's currently being sorted, as it's not very clear how it's currently sorted without hovering over a number of expansions.

**Comment by Sxtanna** [comment]
> Was talking specifically about the list command not the download command.

I comprehended that, but in your scenario they are "searching" for something by name, in which case simply using the tab completes makes infinite more sense.

> outlining to the user how it's currently being sorted

This is agreeable.

> I believe it would be a benefit of being able to change how the expansions are sorted

This kinda isn't. More opportunity for user error is annoying.

**Comment by Sxtanna** [comment]
> I comprehended that, but in your scenario they are "searching" for something by name, in which case simply using the tab completes makes infinite more sense.

This is of course unless by search you actually meant "browse".

**Comment by Funny-cube** [comment]
> I comprehended that, but in your scenario they are "searching" for something by name, in which case simply using the tab completes makes infinite more sense.

Personally I feel it's more plausible for a user to search via the list rather than tab completing on the download command. If you wanted to find something, you'd list them, you wouldn't naturally go to the download command if you didn't know what you were downloading.

> This is of course unless by "search", you actually meant "browse".
Browsing is definitely another use case various 'sorts' could be useful.

**Comment by Sxtanna** [comment]
> you wouldn't naturally go to the download command if you didn't know what you were downloading.

The example of the download command was just that, an example. The same applies to the info command.
![image](https://user-images.githubusercontent.com/20979389/88395525-39164680-cd8f-11ea-87c3-193cca92f091.png)


If you are indeed "searching" for something, you search by name. When was the last time you looked through the entire index of google?

**Comment by Sxtanna** [comment]
Maybe it's worth adding a search command to fuzzy match?

**Comment by SlimeDog** [comment]
In any case `papi ecloud list installed` should be sorted alphabetically. It used to be, on each page. Even better, the installed list should be sorted across all pages -- ie., the first section of the alphabet on page 1, followed be subsequent sections of the alphabet on subsequent pages, all sorted.

**Comment by SlimeDog** [comment]
And while you're mucking about in that code, please list all installed when executed at the console, unless a specific page is requested. At the console `papi ecloud list installed` should present the entire list (sorted, of course).

**Comment by Sxtanna** [comment]
> And while you're mucking about in that code, please list all installed when executed at the console, unless a specific page is requested. At the console papi ecloud list installed should present the entire list (sorted, of course).

No.

**Comment by SlimeDog** [comment]
Why ever not?

**Comment by Sxtanna** [comment]
> Why ever not? 10-per-page is an arbitrary limit, which has no relevance at the console.

1. I'm not "mucking about", I am making measurable improvements to multiple parts of the codebase.
2. It is completely irrelevant to this issue.

**Comment by SlimeDog** [comment]
Apologies for a small attempt at humor.

It is related; it is in the same code. I understand now that by "no" you meant to say "please open a separate issue." I have done so #375.

**Comment by SlimeDog** [comment]
Confirmed fixed in dev build 33. Thank you.
