### ISSUE TITLE
Add dump command for debugging

### ISSUE THREAD

**Issue by extendedclip** [PlaceholderAPI/PlaceholderAPI#366]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki
[Pull Requests]: https://github.com/PlaceholderAPI/PlaceholderAPI/pulls

## Please read
This template is only for requesting new functions to be added to PlaceholderAPI or for old one to be changed!  
Please use the [Request change (Wiki)] template to ask for additions/changes to the wiki.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already mention such a function/change and that there isn't a issue about this change on the [issues] page.

We recommend to [open a Pull Request][Pull Requests] for making changes to PlaceholderAPI's code.

### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Info
> What is the change?  
> Please provide as much information (including links, images and code-snippeds) as possible.

I suggest we add a dump command that outputs a pastebin/haste link that dumps all relevant information regarding common things such as installed plugins, expansions, server version, plugin version, and anything else we see relevant to assist with debugging problems.

**Comment by Andre601** [comment]
+1 this.
Can help improving general support (Although I barely help) where you can just say "Can you give us the link of `/papi dump`?

My suggestion of what should be added:
- PlaceholderAPI version (maybe with build if possible?)
- Server version and brand
- All expansions installed, including if they are enabled or not
