### ISSUE TITLE
Properly log listed expansions

### ISSUE THREAD

**Issue by Andre601** [PlaceholderAPI/PlaceholderAPI#370]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki
[Pull Requests]: https://github.com/PlaceholderAPI/PlaceholderAPI/pulls

## Please read
This template is only for requesting new functions to be added to PlaceholderAPI or for old one to be changed!  
Please use the [Request change (Wiki)] template to ask for additions/changes to the wiki.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already mention such a function/change and that there isn't a issue about this change on the [issues] page.

We recommend to [open a Pull Request][Pull Requests] for making changes to PlaceholderAPI's code.

### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New function for PlaceholderAPI.  
A new function that developers could use.
- [x] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Info
> What is the change?  
> Please provide as much information (including links, images and code-snippeds) as possible.

The listed expansions in the `papi ecloud list installed` command (When run from the console) should display the listed expansions properly.

By that I mean they should display as:
```
> papi ecloud list installed
[20:44:28] [Server thread/INFO]: Installed Expansions Page: 1
[20:44:28] [Server thread/INFO]: 
[20:44:28] [Server thread/INFO]: 1. Player [Author: clip, Verified: ✔️, Latest Version: 1.7.2]
[20:44:28] [Server thread/INFO]: 2. Vault [Author: clip, Verified: ✔️, Latest Version: 1.6.0]
```

rather than what it is now:
```
> papi ecloud list installed
[20:44:28] [Server thread/INFO]: Installed Expansions Page: 1

1. Player [Author: clip, Verified: ✔️, Latest Version: 1.7.2]
2. Vault [Author: clip, Verified: ✔️, Latest Version: 1.6.0]
```

In general should the logging be improved as it always feels so odd to have PlaceholderAPI display the very first like with the time and thread while all following lines are without it.

**Comment by Sxtanna** [comment]
Your definition of "properly" is incorrect, this indentation issue could simply be fixed by putting the start of the message on a new line when sent to console.

Sending individual messages can introduce interleaving with other messages, which is extremely undesirable.

**Comment by Sxtanna** [comment]
That format bothered me, thoughts on this?
![image](https://user-images.githubusercontent.com/20979389/88445560-80cdba00-cdf1-11ea-8030-c5a22339eb60.png)

**Comment by Andre601** [comment]
I assume the collumns would be adjusted in width depending on the longest entry?
Looks nice (Just on a personal note, I laugh a lot about how tiny the checkmark is in the terminal)

**Comment by Sxtanna** [comment]
> I assume the collumns would be adjusted in width depending on the longest entry?

Yes... thats.. whats being shown in the screenshot, thats an actual output from this being implemented.

Here's another example:
![image](https://user-images.githubusercontent.com/20979389/88446149-a5c42c00-cdf5-11ea-9472-d69062cf65d3.png)

**Comment by Andre601** [comment]
To be honest: Is the index number really required here?
All it is used for is to list the expansions in a sort of nummerical order but doesn't have any other use yet.

**Comment by Sxtanna** [comment]
This exact question was asked to @extendedclip to which he responded in denoting them as a _**"flex"**_ 

So I guess yeah, they're required. 😄

**Comment by Andre601** [comment]
I think this is now "fixed" with the new design for listing expansions
