### ISSUE TITLE
Add "all" argument for /papi list and /papi ecloud list installed

### ISSUE THREAD

**Issue by Andre601** [PlaceholderAPI/PlaceholderAPI#371]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki
[Pull Requests]: https://github.com/PlaceholderAPI/PlaceholderAPI/pulls

## Please read
This template is only for requesting new functions to be added to PlaceholderAPI or for old one to be changed!  
Please use the [Request change (Wiki)] template to ask for additions/changes to the wiki.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already mention such a function/change and that there isn't a issue about this change on the [issues] page.

We recommend to [open a Pull Request][Pull Requests] for making changes to PlaceholderAPI's code.

### Type
> What kind of request is this? (Multiple selections possible)

- [x] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Info
> What is the change?  
> Please provide as much information (including links, images and code-snippeds) as possible.

When running either `papi list` or `papi ecloud list installed` does PlaceholderAPI only list expansions that are active. Expansions that aren't enabled (because they f.e. have a dependency/plugin missing) are just not shown, making this a bit unreliable, as you can't tell which expansions you really have installed.

I would suggest to have an optional argument like `all` or `--all` that would tell PlaceholderAPI to list all expansions, no matter if active or not.

Additionally should the first line of `papi list` be updated to also mention how many inactive/disabled expansions are there and not just the active ones.

**Comment by Sxtanna** [comment]
I don't believe this is actually possible tbh? 
If an expansion is missing a plugin dependency, surely it throw a NCDFE or CNFE when being referenced. 
Same with expansions that might be version specific, it's kind of undefined behaviour atm.

**Comment by Andre601** [comment]
This is actually the case here.
My test enviroment has the Player expansion and the Vault expansion, but no Vault installed.
No errors or similar appear and running the above mentioned commands does only list Player but ommit Vault.

**Comment by Sxtanna** [comment]
Then how do you propose such a system to work? Files are completely decoupled from both cloud expansions and local expansions (at runtime).

**Comment by Andre601** [comment]
So PlaceholderAPI doesn't "know" that an expansion exists in its expansion folder?
Shouldn't be that difficult to check the folder for jar files and compare those with loaded ones to then display how many are loaded and which aren't.

**Comment by Sxtanna** [comment]
> Shouldn't be that difficult to check the folder for jar files and compare those with loaded ones to then display how many are loaded and which aren't.

Papi doesn't track expansions by their files, that's the issue.
