### ISSUE TITLE
Error on startup + Javascript not working

### ISSUE THREAD

**Issue by LoSCraft-Network** [PlaceholderAPI/PlaceholderAPI#372]
### Issue
> What is the issue? Describe it like you would tell a friend.

there is an error on startup and it will prevent javascript placeholders from working

### Expected behaviour
> What should PlaceholderAPI do?

no error

### Actual behaviour
> What does PlaceholderAPI actually do?

error
https://hasteb.in/afikiyan.shell

### How to reproduce
> What steps did you made, to get this bug?

1. Started when I updated to PlaceholderAPI-2.10.7-DEV-25.jar

**Comment by Sxtanna** [comment]
What version are you coming from? And what other plugins are installed? @LoSCraft-Network

**Comment by LoSCraft-Network** [comment]
Admin360-Reloaded*, AdvancedAchievements, AdvancedPortals, AnimatedScoreboard, AntiCooldown, AuctionHouse, BetterSpawners, BuycraftX, ChatControl, ChatReaction, CheaperPhysicsEvent, ChestShop, Citizens, CitizensCMD, CombatLogX, CoreProtect, CrazyCrates, DeluxeMenus, DeluxeTags*, Duels, Elevator, EntityTrackerFixer, Essentials, EssentialsSpawn, FlightControl, GlowAPI*, GPAccruals*, GriefPrevention, GSit, HeadDatabase*, HolographicDisplays, HolographicExtension, IllegalStack, LeaderHeadsRevamped, LimitPillagers, LiteBans, LuckPerms, MarriageMaster, mcMMO, MobFarmManager, Multiverse-Core, MyCommand, NBTAPI, PacketLimiter, PacketListenerApi*, PinataParty, PlaceholderAPI, PlayerWarps, PlugMan, ProtocolLib, RandomTP, Shopkeepers, SimpleClans, SkinsRestorer, SuperVanish, TAB, TokenManager, TopTags, TradePlus, Vault, VillagerOptimiser, VoidGenerator, VoidTeleport, Votifier, WitherAC, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

Version Tuinity version git-Tuinity-"7b639ea" (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by Sxtanna** [comment]
No, I meant which version of PAPI are you coming from.

**Comment by LoSCraft-Network** [comment]
I apologize

I was coming from the first Dev build for 1.16
PlaceholderAPI-2.10.7-DEV

**Comment by Sxtanna** [comment]
Thank you.

**Comment by Sxtanna** [comment]
@LoSCraft-Network 
In regards to the javascript placeholders, I believe this might be of relevance: 
https://github.com/kangarko/ChatControl-Pro/issues/1709

Can you verify that simpleclans is running and operational on your server?

**Comment by LoSCraft-Network** [comment]
Simple Clans was also not running operational.

https://hasteb.in/asamuxun.swift

I reported this to them.

I tried to downgrade versions and I got no errors besides warns on javascript engine not working and javascript placeholders not working

**Comment by Sxtanna** [comment]
Ah yes, this is good actually. 

That method was removed in the last build, as no one should ever use anything other than `PlaceholderExpansion#register` to register an expansion.

I will open an issue on their repo with this information.

**Comment by LoSCraft-Network** [comment]
Also, just to take note (Might help, idk)

- Downgraded to First dev build + Removed ChatControlPro = JavaScript placeholders started working again.

- Tried to Upgrade to dev build 25 again w/o ChatControlPro and javascript placeholders will work but some plugins such as SimpleClans and SuperVanish will break

**Comment by Sxtanna** [comment]
Yes, the issue of other plugins breaking will be a thing until they are updated. 

PAPI is currently going through a massive rewrite of several facets of the plugin, many of which are being completely removed in favour of a simpler external API.

The best thing you can do at this point is to notify authors of this change, link them to this issue.

I'm going to keep this issue open for the sake of information.

**Comment by LoSCraft-Network** [comment]
I notified the SimpleClans and SuperVanish
