### ISSUE TITLE
Configuration option to disable colors

### ISSUE THREAD

**Issue by SlimeDog** [PlaceholderAPI/PlaceholderAPI#378]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki
[Pull Requests]: https://github.com/PlaceholderAPI/PlaceholderAPI/pulls

## Please read
This template is only for requesting new functions to be added to PlaceholderAPI or for old one to be changed!  
Please use the [Request change (Wiki)] template to ask for additions/changes to the wiki.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already mention such a function/change and that there isn't a issue about this change on the [issues] page.

We recommend to [open a Pull Request][Pull Requests] for making changes to PlaceholderAPI's code.

### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New function for PlaceholderAPI.  
A new function that developers could use.
- [x] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [x] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Info
> What is the change?  
> Please provide as much information (including links, images and code-snippeds) as possible.

Please implement configuration option(s) to disable formatting codes in messages and console output. Or more generally, support localization of messages and console output.

As an example of the problem, the default colors do not play well on a dark blue console.

**Comment by Sxtanna** [comment]
From a maintenance perspective this does not seem like that great of an idea.

**Comment by SlimeDog** [comment]
OK. Thanks for thinking about it.

**Comment by Sxtanna** [comment]
> I do not understand the difficulty. Many, many plugins have managed this trick.

It's not really about difficulty. It's just another thing to manage that doesn't really provide much of a benefit.

You can change the background color of pretty much any modern shell.

**Comment by SlimeDog** [comment]
I selected the background color I want, years ago.

**Comment by Sxtanna** [comment]
> I selected the background color I want, years ago.

I highly disagree that the project should pander to things like this, but if someone wants to do this, PR. 

I will review, and potentially merge.

**Comment by SlimeDog** [comment]
At present, PAPI presents us with a set of color choices dictated by the dev team, that cannot be changed. Many other plugins have managed to provide options -- either to disable formatting codes altogether, or to provide color configuration capabilities, or to provide localization of all strings -- to let users choose their own color palettes. It's sad that you view this as "pandering" to your users. I strongly disagree with that characterization. The coding required is minimal to render formatting as variables instead of constants, for a large visual benefit.

**Comment by Sxtanna** [comment]
> It's sad that you view this as "pandering" to your users. I strongly disagree with that characterization.

**Pander**
*gratify or indulge*

Doing literally anything at the request of an issue is pandering.

**Comment by SlimeDog** [comment]
As you are well aware, "pander" is loaded with connotation.

**Comment by Sxtanna** [comment]
> Many other plugins have managed to provide options -- either to disable formatting codes altogether, or to provide color configuration capabilities, or to provide localization of all strings

Every aspect of PAPI commands are locked behind permissions, and are really only meant to be ran by administration of a server. 

Many plugins do in fact provide these levels of customization, but it just doesn't make sense for PAPI.

**Comment by SlimeDog** [comment]
It is an administrator making this request. Why is that less important?

**Comment by Sxtanna** [comment]
> As you are well aware, "pander" is loaded with connotation.

Connotation != Definition.
Not to mention the connotation definitely still applies here.

**Comment by Sxtanna** [comment]
If you would like this for your server, fork, edit, and build it.

If you would like this for everyone else, fork, edit, and PR it. And the team will review.
