### ISSUE TITLE
WorldGuard's placeholders throw errors. (Latest 1.13 Dev Version)

### ISSUE THREAD

**Issue by OverCrave** [PlaceholderAPI/PlaceholderAPI#38]
I would like to reference this issue I posted at enginehub: https://dev.enginehub.org/youtrack/issue/WORLDGUARD-3955

According to them, the issue lays with PlaceholderAPI itself.

**Comment by darbyjack** [comment]
Thank you for the report. It looks like this is still a developer version for WG so this will be updated once a stable release of WG for 1.13 is out.

**Comment by darbyjack** [comment]
Will open back up when WG 7.0.0 has been released.

**Comment by OverCrave** [comment]
There have been multiple betas of 7.0.0, I'd consider it pretty stable at this point. Any update on this issue?
