### ISSUE TITLE
Plugin Placeholders Update

### ISSUE THREAD

**Issue by ThePlay3r** [PlaceholderAPI/PlaceholderAPI#380]
### Type
> What kind of change is it? (Multiple selections possible)
- [ ] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [x] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

Hello,

I would like to update [Marriage](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#marriage) with new added placeholders, which are:
%marrige_gender%
%marriage_pvp%
%marriage_home%
%marriage_x%
%marriage_y%
%marriage_z%
%marriage_yaw%
%marriage_pitch%
%marriage_partner_gender%
%marriage_partner_gender_symbol%
%marriage_partner_gender_color%
%marriage_partner_lastseen%
%marriage_partner_pvp%

**Comment by ThePlay3r** [comment]
And also, I forgot %marriage_state%

**Comment by Andre601** [comment]
Updated
