### ISSUE TITLE
Clans [Free]

### ISSUE THREAD

**Issue by Hempfest** [PlaceholderAPI/PlaceholderAPI#382]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

## Please read
This template is only for requesting new information to be added to the wiki or for updating of already existing information!  
Please use the [Request change (PlaceholderAPI)] template to ask for additions/changes to the plugin PlaceholderAPI.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already have the change and that there isn't a issue about this change on the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

Hello my name is Hempfest the co-developer for Clans [Free] i recently started supporting your plugin and would like to add to your list! : https://www.spigotmc.org/resources/clans-free-1-13-1-16.78415/

**Comment by Andre601** [comment]
Updated the List.

Thanks for supporting PlaceholderAPI

**Comment by Hempfest** [comment]
I know this is a closed post but i noticed you said we support placeholders. We provide our own placeholders but dont support others.

**Comment by Hempfest** [comment]
The current placeholders are:
- %clans_name% : returns the players clan name
- %clans_rank% : returns the players clan rank
- %clans_raidshield% : checks for raidshield activity

**Comment by Andre601** [comment]
Next time mention this in your original post as nothing hinted at you providing placeholders rather than supporting them.

It even mentions it in the Info part of the issue template:
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

I [updated it now](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#clans-1) but next time give the right info straight away.

**Comment by Hempfest** [comment]
Will do, very sorry. As it was my fault. Stayed up to late and decided to write to you guys before bed and the info was too brief. Next time will know exactly what information to include
