### ISSUE TITLE
Clans [Free] Mistake

### ISSUE THREAD

**Issue by Hempfest** [PlaceholderAPI/PlaceholderAPI#383]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

## Please read
This template is only for requesting new information to be added to the wiki or for updating of already existing information!  
Please use the [Request change (PlaceholderAPI)] template to ask for additions/changes to the plugin PlaceholderAPI.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already have the change and that there isn't a issue about this change on the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [ ] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [x] Other: Plugin list mistake 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

I noticed it says we support placeholders when we provide our own. 
The current placeholders are:

%clans_name% : returns the players clan name
%clans_rank% : returns the players clan rank
%clans_raidshield% : checks for raidshield activity

Plugin Clans [Free]: https://www.spigotmc.org/resources/clans-free-1-13-1-16.78415/

**Comment by Andre601** [comment]
Was corrected already.
Responding to the closed issue (#382) is more than enough
