### ISSUE TITLE
Only build on jenkins when there are code changes

### ISSUE THREAD

**Issue by extendedclip** [PlaceholderAPI/PlaceholderAPI#386]
## Please read
This template is only for requesting new functions to be added to PlaceholderAPI or for old one to be changed!  
Please use the [Request change (Wiki)] template to ask for additions/changes to the wiki.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already mention such a function/change and that there isn't a issue about this change on the [issues] page.

We recommend to [open a Pull Request][Pull Requests] for making changes to PlaceholderAPI's code.

### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [x] Other: __________ 

### Info
> What is the change?  
> Please provide as much information (including links, images and code-snippeds) as possible.

I don't have a change just yet but we need to figure it out. I would like to only build on Jenkins when actual code changes are made rather than when things are changed regarding the wiki or other GitHub related things not involving the codebase.

[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki
[Pull Requests]: https://github.com/PlaceholderAPI/PlaceholderAPI/pulls

**Comment by Andre601** [comment]
I myself only have a setup where I don't build anything if the commit message contains `[skip ci]` but that doesn't work that well for obvious reasons.
If Jenkins offers options to check for what files in what directories have changed could this perhaps be used.
Alternatively could yet another GitHub Action be created, which listens for pushes towards the src folder and then triggers a workflow run on Jenkins (Maybe doing a POST request to the Jenkin's VCS URL? Idk)

**Comment by Sxtanna** [comment]
Could also just drop jenkins and use github actions entirely. 🙂

**Comment by Andre601** [comment]
> Could also just drop jenkins and use github actions entirely. 🙂

In what way? GitHub Actions doesn't store the generated files by default (There is some sort of temp/limited storage, but that isn't optimal.)
It setups a workflow based on the repo maybe sets up other stuff based on the used actions (like f.e. a Git Repo when using Checkout Action), performs the actions in order and after that cleans up everything which essentially means, it deletes the stuff afterwards.

The only reliable way to keep jars would be to upload them somewhere like in a GitHub Release or some sort of storage or whatever.

If this isn't what you mean would I like to hear what you meant instead.

**Comment by Andre601** [comment]
I think the best solution would be to send a manual POST request whenever pushes are made to the master branch that aren't just for the `wiki` and `.github` folder.
But for that would we probably need to look into how Jenkins handles the POST webhooks from GitHub. If it just listens for any POST request and doesn't care at all for a request body, then a simple GitHub Action could do the trick. Otherwhise we would need to get the right body to be send too.

**Comment by Sxtanna** [comment]
> In what way? GitHub Actions doesn't store the generated files by default 

GitHub Actions doesn't do anything by default, everything that it can do, you have to tell it to do.

> (There is some sort of temp/limited storage, but that isn't optimal.)

If you use the upload artifact action, the binary is stored on the workflow for 90 days.

> The only reliable way to keep jars would be to upload them somewhere like in a GitHub Release or some sort of storage or whatever.

Which is something actions can do, yes.

**Comment by Sxtanna** [comment]
Workflows can be different per branch as well.

Pushes to the master branch can trigger a workflow that not only creates a release, but also publishes the artifact to wherever we want, be it clip's nexus or github packages.

**Comment by Andre601** [comment]
I am very aware of this... After all am I [using a release action myself](https://github.com/Andre601/OneVersionRemake/blob/master/.github/workflows/maven.yml) but the thing is that a temp-storage won't be a good option and Releases should be reserved for... well... releases.

The best compromise I can see here is to make GitHub trigger a Jenkins build through a custom action IF Jenkins doesn't care about the content of a received POST request and only cares about the POST request itself being made.

You really don't have to explain the basics of GitHub Actions to me. I had to work and struggle with those more than I can remember.
Building jars, publishing them on releases or even to JCenter, update a wiki, to name a few things.

**Comment by Sxtanna** [comment]
> Releases should be reserved for... well... releases.

This doesn't really make sense, releases can be used for literally anything at all.
Many people use releases to mark a project at a point in time, be it alphas, beta, milestones, release candidates, or entire releases.

> You really don't have to explain the basics of GitHub Actions to me. I had to work and struggle with those more than I can remember.

Every single sentence that I replied to had an unsure tone.

**Comment by Sxtanna** [comment]
> Many people use releases to mark a project at a point in time, be it alphas, beta, milestones, release candidates, or entire releases.

https://github.com/JetBrains/intellij-community/releases
https://github.com/JetBrains/kotlin/releases

for example.

**Comment by Andre601** [comment]
Yeah, but having an action creating a release every single time a push is made would be annoying for all the people watching this repository for releases only.

**Comment by extendedclip** [comment]
There’s like 1 person I know of that watches this repo...

**Comment by Andre601** [comment]
According to the watch-button are there 13 people watching this repo.
The question now is how many watch everything and how many just releases.

But a small number of watchers doesn't mean this could get annoying with time.

**Comment by Sxtanna** [comment]
Kotlin has 1.3k watchers...

**Comment by extendedclip** [comment]
No

**Comment by extendedclip** [comment]
I know what you are reaching for with that reply

**Comment by Sxtanna** [comment]
> No

![image](https://user-images.githubusercontent.com/20979389/88976430-0508bd00-d28a-11ea-94a3-c5f715e632f8.png)

What do you mean "No"

**Comment by Andre601** [comment]
This seems to now be resolved?
The Jenkins should now only trigger when pushes are made to the src directory (towards any java files) and the build.gradle if I'm not mistaken.
