### ISSUE TITLE
PlaceholderAPI [2.9.1] - java.lang.ClassNotFoundException: com.google.gson.Gson

### ISSUE THREAD

**Issue by yeetstar** [PlaceholderAPI/PlaceholderAPI#39]
Hi there,

I'm currently using PaperSpigot 1.7.10 for HCF (Hardcore Factions) purposes. I would like to know why this error is happening and how I could fix it.

Full error: https://pastebin.com/raw/DxVUpNGm

I am using the latest PlaceholderAPI plugin.

Thank you.

**Comment by yeetstar** [comment]
Spigot 1.8.3+ required.

**Comment by extendedclip** [comment]
You can probably just disable the "cloud" feature in the config and that would prevent the plugin from interacting with gson. The only bad thing is you have to manually download your expansions for placeholders....

**Comment by LemmoTresto** [comment]
@extendedclip I suggest shading and relocating GSON instead.
