### ISSUE TITLE
Add CustomItems to supported plugins

### ISSUE THREAD

**Issue by jojodmo** [PlaceholderAPI/PlaceholderAPI#399]
## Please read
This template is only for requesting new information to be added to the wiki or for updating of already existing information!  
Please use the [Request change (PlaceholderAPI)] template to ask for additions/changes to the plugin PlaceholderAPI.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already have the change and that there isn't a issue about this change on the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

PlaceholderAPI support was recently added to CustomItems (in version 3.4): https://polymart.org/r/custom-items.1/

The plugin also added two extensions, "cui" and "customitems". They are currently only used for checking the version of the plugin, but more placeholder options will be coming soon!

[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

**Comment by Andre601** [comment]
Does the plugin only support other placeholders, or does provide its own?
If it is the second one, then please also provide the available placeholders.

Alternatively could you also PR changes for the wiki, by editing the markdown files in the [wiki](https://github.com/PlaceholderAPI/PlaceholderAPI/tree/master/wiki) directory (In your case [Plugins-using-PlaceholderAPI.md](https://github.com/PlaceholderAPI/PlaceholderAPI/blob/master/wiki/Plugins-using-PlaceholderAPI.md) and maybe [Placeholders.md](https://github.com/PlaceholderAPI/PlaceholderAPI/blob/master/wiki/Placeholders.md))

**Comment by jojodmo** [comment]
Sorry if that was unclear — the plugin does provide it's own placeholders, but for now it's just %cui_version% and %customitems_version%, just to get CustomItems as a registered placeholder extension. A coming update will add more useful placeholders (which I'll add to the wiki)

**Comment by Andre601** [comment]
I added the placeholders to [the list](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#custom-items)

Once you've added new placeholders, feel free to respond to this one here, or open a separate issue. PRs for the wiki are for now on hold until we find a better way of handling those...

Thank you for supporting PlaceholderAPI.
