### ISSUE TITLE
Latest version broke my plugin and it can't get up

### ISSUE THREAD

**Issue by Azim-D3Tm** [PlaceholderAPI/PlaceholderAPI#404]
### Issue
> What is the issue? Describe it like you would tell a friend.

* `PlaceholderExpansion#register` is deprecated
* neither `PlaceholderExpansion#onPlaceholderRequest(Player, String`) nor `PlaceholderExpansion#onRequest(OfflinePlayer, String)` get triggered after update

### Expected behaviour
> What should PlaceholderAPI do?
* `PlaceholderExpansion#register` not being deprecated (since it is a method used both on wiki page and on spigot update's changenotes
* `PlaceholderExpansion#onRequest(OfflinePlayer, String)` to be triggered when needed

### Actual behaviour
> What does PlaceholderAPI actually do?
* read **Issue**

### How to reproduce
> What steps did you made, to get this bug?

1. updated dependency version in my maven build
2. downloaded latest PAPI to my test server

### Installed expansions
> Please list all expansions that are displayed when running `/papi list`
*  none except mine

[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Spigot]: https://www.spigotmc.org/resources/6245/
[Jenkins]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

**Comment by Andre601** [comment]
Your issue lacks some essential information for us to provide you with proper help.

Please provide the following missing info:
- PlaceholderAPI version you used in your plugin
- PlaceholderAPI version you used on the server (if it is a dev build, also include the build number)
- The actual expansions you use. Just saying "none except mine" is not an answer.
- The code you have in your expansion.

**Comment by Funny-cube** [comment]
@Azim-D3Tm mind also testing the latest dev build: https://ci.extendedclip.com/job/PlaceholderAPI/82/

**Comment by Azim-D3Tm** [comment]
> @Azim-D3Tm mind also testing the latest dev build: https://ci.extendedclip.com/job/PlaceholderAPI/82/

didnt work

**Comment by Andre601** [comment]
Any particular error you receive here?

**Comment by Andre601** [comment]
So the plugin is enabled without any issues?

**Comment by Azim-D3Tm** [comment]
Yes

**Comment by Funny-cube** [comment]
We're looking into this now in Room-1 voice with another developer if you want to join.

**Comment by Funny-cube** [comment]
Seems expansions are fine but built in expansions are having issues.

**Comment by Azim-D3Tm** [comment]
> We're looking into this now in Room-1 voice with another developer if you want to join.

I dont think i can really provide any more information really

**Comment by Andre601** [comment]
That's okay. We will try to find the cause of this issue. So stay tight.

**Comment by Funny-cube** [comment]
@Azim-D3Tm Switch the Identifier to all lowercase and try that

**Comment by Azim-D3Tm** [comment]
> @Azim-D3Tm Switch the Identifier to all lowercase and try that

Now it works

**Comment by Funny-cube** [comment]
> > @Azim-D3Tm Switch the Identifier to all lowercase and try that
> 
> Now it works

Awesome, from build 83 we're forcing identifies to lowercase.

**Comment by Azim-D3Tm** [comment]
> > > @Azim-D3Tm Switch the Identifier to all lowercase and try that
> > 
> > 
> > Now it works
> 
> Awesome, from build 83 we're forcing identifies to lowercase.

that's very inconvinent

**Comment by Funny-cube** [comment]
> > > > @Azim-D3Tm Switch the Identifier to all lowercase and try that
> > > 
> > > 
> > > Now it works
> > 
> > 
> > Awesome, from build 83 we're forcing identifies to lowercase.
> 
> that's very inconvinent

It's to avoid case sensitive placeholders, plus it's the common standard if you see:
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders all identifies are lowercase.

**Comment by Azim-D3Tm** [comment]
Worth mentioning it in the wiki then i guess. Thanks for help though

**Comment by Funny-cube** [comment]
> Worth mentioning it in the wiki then i guess. Thanks for help though

Yup!
