### ISSUE TITLE
Changes to Marcely's Bedwars

### ISSUE THREAD

**Issue by MrEAlderson** [PlaceholderAPI/PlaceholderAPI#405]
## Please read
This template is only for requesting new information to be added to the wiki or for updating of already existing information!  
Please use the [Request change (PlaceholderAPI)] template to ask for additions/changes to the plugin PlaceholderAPI.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already have the change and that there isn't a issue about this change on the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [ ] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [x] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

Changed:
```
> %mbedwars_<arena>-players% to %mbedwars_arena-<arena>-players%
> %mbedwars_<arena>-maxplayers% to %mbedwars_arena-<arena>-maxplayers%
> %mbedwars_<arena>-status% to %mbedwars_arena-<arena>-status%
> %mbedwars_<arena>-teams% to %mbedwars_arena-<arena>-teams%
> %mbedwars_<arena>-teamsize% to %mbedwars_arena-<arena>-teamsize%
```

Changes for stats placeholders:
Stats are now modular, meaning that the general placeholder is ```%mbedwars_stats-<id>%.```
The placeholders for  the default stats are:
```
> %mbedwars_stats-rank%
> %mbedwars_stats-wins%
> %mbedwars_stats-loses%
> %mbedwars_stats-rounds_played% <-- renamed
> %mbedwars_stats-wl% <-- new
> %mbedwars_stats-kills%
> %mbedwars_stats-deaths%
> %mbedwars_stats-kd% <-- new
> %mbedwars_stats-beds_destroyed% <-- renamed
> %mbedwars_stats-play_time% <-- renamed
```

[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

**Comment by Andre601** [comment]
I updated the wiki with the new info.

Please note that we will start to only accept Pull requests in the future.
If you want a page on the wiki updated in the future, feel free to make a Pull request towards the files in the [wiki folder](https://github.com/PlaceholderAPI/PlaceholderAPI/tree/master/wiki)
