### ISSUE TITLE
Nametag edit placeholderapi 

### ISSUE THREAD

**Issue by youseemerunning1** [PlaceholderAPI/PlaceholderAPI#41]
[WARNING] [MVdWPlaceholderAPI] There is no MVdW placeholder plugin installed!

[WARNING] [MVdWPlaceholderAPI] Put on of Maximvdw's premium placeholder plugins in the server!

[INFO] [NametagEdit] As the error above suggests, you do NOT have any placeholder plugins installed. The placeholder API is merely an interface, it requires other plugins to function. This is NOT an issue with NametagEdit.

I've added 

PlaceholderAPI
MVdWPlaceholderAPI
MVdWUpdater 

and I'm still getting this error

**Comment by Gaby-TM** [comment]
Well .. it literally say 
[WARNING] [MVdWPlaceholderAPI] There is **no** MVdW placeholder **plugin installed**!

You need one of maxim's premium plugins

**Comment by aBo0oDyy** [comment]
Idk if nametagedit support papi if it does then make sure u have the latest version of papi
For mvdwpapi u need at least one of MaximVdW premium plugin to use mvdwpapi (like featherboard, animatednames, etc)

**Comment by youseemerunning1** [comment]
> Well .. it literally say
> [WARNING] [MVdWPlaceholderAPI] There is **no** MVdW placeholder **plugin installed**!
> 
> You need one of maxim's premium plugins

I have the plugins...

**Comment by youseemerunning1** [comment]
> Idk if nametagedit support papi if it does then make sure u have the latest version of papi
> For mvdwpapi u need at least one of MaximVdW premium plugin to use mvdwpapi (like featherboard, animatednames, etc)

I don't feel like adding these as I don't need them. How could I disable the message?

**Comment by Gaby-TM** [comment]
You can't, because mvdw api is made to work with maxim's plugins :D

**Comment by aBo0oDyy** [comment]
U cant use mvdwpapi placeholders if u don't have one of maxim's premium plugins.
Check the config file if it has option for disabling the message but i don't think it has one for that

**Comment by youseemerunning1** [comment]
> You can't, because mvdw api is made to work with maxim's plugins :D

So why is nametagedit spamming this?

**Comment by Gaby-TM** [comment]
Remove mvdw api and use papi placeholders

**Comment by youseemerunning1** [comment]
> Remove mvdw api and use papi placeholders

Already tried that. Didn't work

**Comment by darbyjack** [comment]
This doesn't have to do with PlaceholderAPI.
