### ISSUE TITLE
Please add %mv_players_[world]% placeholder.

### ISSUE THREAD

**Issue by CrazyMMG** [PlaceholderAPI/PlaceholderAPI#414]
I was wondering if the placeholder api team could please add the above placeholder (%mv_players_[world]%) into the plugin. This placeholder would return the number of players currently in a certain multiverse world. This would be very useful to a lot of people. Also, I did ask in the multiverse discord however they said to ask the placeholder api team directly, since you were the ones who made the original mv placeholders. Thanks, CrazyMMG

**Comment by Andre601** [comment]
Please follow the issue templates. They exist for a reason.

And there already exists a placeholder for this which is [`%world_<world>_players%`](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#world) (You have to download the World Expansion)

Most expansions and their placeholders can be found on the [wiki](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders) so please check the wiki the next time.
