### ISSUE TITLE
Add request of /papi dump to issue template

### ISSUE THREAD

**Issue by extendedclip** [PlaceholderAPI/PlaceholderAPI#416]
### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [x] Other: __________ 

### Info
> What is the change?  
> Please provide as much information (including links, images and code-snippeds) as possible.

Bug report issue template should request that a link to a /papi dump be included. This would eliminate the need for people submitting issues to provide the plugin version, server version, and what expansions and/or plugins they have installed.

**Comment by Andre601** [comment]
I'll update the template when I'm back home (aprox. 3-4 hours)
