### ISSUE TITLE
Downloading issue

### ISSUE THREAD

**Issue by JustJessieYT** [PlaceholderAPI/PlaceholderAPI#42]
I downloaded factions with /papi ecloud download factions 
it tried using it but it didnt work
i saw in extansions that it was indeed downloaded but when i did /papi list or /papi ecloud list installed it didnt show up can somebody please help me with this problem

**Comment by darbyjack** [comment]
What factions plugin do you have?

**Comment by Gaby-TM** [comment]
> /papi ecloud download factions
Is for [Factions](https://www.spigotmc.org/resources/factions.1900/)

And if you are using [FactionsUUID](https://www.spigotmc.org/resources/factionsuuid.1035/) or [SavageFactions](https://www.spigotmc.org/resources/savagefactions-factionsuuid-reimagined-1-7-1-13.52891/) both have build-in placeholders (no expansion needed)
