### ISSUE TITLE
Class file only recognized up to 52

### ISSUE THREAD

**Issue by Rafcin** [PlaceholderAPI/PlaceholderAPI#424]
Using a shared host i'm unable to pick the version of Java I prefer to use and as a result Placeholder fails.

UnsupportedClassVersionError: me/thienbao860/expansion/world/WorldData has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by MrIvanPlays** [comment]
This is not related to placeholderapi, but the author of the class "WorldData" which is probably from the world expansion. 
Basically says it was compiled on java 13 and it tried to load on java 8

**Comment by thienbao860** [comment]
Hello, author of World expansion here. I will try to resolve this as soon as possible (probably 1 hour later)

**Comment by thienbao860** [comment]
Hello once again. I already updated the expansion and have already tested everything before published. You can give it a try

**Comment by Andre601** [comment]
I'll close this as this isn't an issue on PlaceholderAPI's end and no response to this was given for a week now.
