### ISSUE TITLE
Major changes in World-Expansion format

### ISSUE THREAD

**Issue by thienbao860** [PlaceholderAPI/PlaceholderAPI#425]
The placeholder format will be changed in the newer version (1.1.0): Argument <world> will now be placed behind the placeholder instead.
List of new placeholders available in [here](https://api.extendedclip.com/expansions/world/)

**Comment by Andre601** [comment]
I updated the placeholders.

For the next time would it be awesome, if you could [PR the changes yourself](https://github.com/PlaceholderAPI/PlaceholderAPI/blob/docs/wiki/wiki/README.md)
