### ISSUE TITLE
Javascript variables do not work with ChatControl

### ISSUE THREAD

**Issue by kangarko** [PlaceholderAPI/PlaceholderAPI#426]
## Bug Report

Setting up a new JavaScript variable with ChatControl 8.7.1 (also 8.7.2) fails.

This is the message PAPI outputs when it fails:
[14:07:09 WARN]: [PlaceholderAPI] Failed to set ScriptEngine for javascript placeholder: blocks_flown

How to reproduce: https://github.com/kangarko/ChatControl-Pro/issues/1799

### `/papi dump` output
https://paste.helpch.at/qofuxakuxu

I appreciate if you can guide me why this happens when ChatControl is installed, can you provide me more info regarding that message?

**Comment by kangarko** [comment]
Here is the only code I could find we use that touches the ScriptManager: https://github.com/kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/model/JavaScriptExecutor.java

**Comment by Funny-cube** [comment]
Worth noting I've also seen PlaceholderAPI's JavaScript Engine act up when `Boss` is installed.
`[Server thread/INFO]: [Boss] Enabling Boss v3.8.0`

**Comment by TwerkRekt** [comment]
any new?

**Comment by Affixes** [comment]
Seems to be version dependant as well. On 1.12.2 we have do not experience any issues. Our 1.15 servers do with the same versions of ChatControl and PAPI.

**Comment by kangarko** [comment]
@extendedclip any news regarding this please?

**Comment by Andre601** [comment]
Looking at [the link you provided](https://github.com/kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/model/JavaScriptExecutor.java#L46) do I first wonder, why you do this
```java
final ScriptEngineManager engineManager = new ScriptEngineManager(null);
engine = engineManager.getEngineByName("Nashorn");
```
instead of
```java
final ScriptEngineManager engineManager = new ScriptEngineManager().getEngineByName("Nashorn");
```
as described in [the tutorial](https://winterbe.com/posts/2014/04/05/java8-nashorn-tutorial/) that is linked in the class you use?

Also, did you try it with a different Script engine than nashorn?
Nashorn is deprecated since Java 11 iirc and will probably be removed in a future Java release, so better look forward to it and prepare.

**Comment by kangarko** [comment]
Last time I remember that would not work since some changes in Paper. That is why we had to put (null) there explicitly.

**Comment by kangarko** [comment]
@extendedclip @Andre601 this is a known problem that started to happen across plugins after a certain point in Paper/Spigot.

There are no available engines using Java 8 when calling the engine factory without the "null" in the constructor:

![a](https://i.imgur.com/sCLmiek.png)

Seeing the same issue in the expansion:

![b](https://i.imgur.com/CkRyn2P.png)

To fix that problem simply call `new ScriptEngineManager(null)` instead.
