### ISSUE TITLE
Plugin using PlaceholderAPI placeholders

### ISSUE THREAD

**Issue by Lorenzo0111** [PlaceholderAPI/PlaceholderAPI#430]
I've created a plugin([link](https://bit.ly/RocketJoin)) that supports PlaceholderAPI placeholders. Can you add my plugin in your list?

**Comment by Andre601** [comment]
You can now PR to the wiki directly (on the `docs/wiki` branch)

Please check the readme in the wiki directory.

Also use one of the templates please.

**Comment by Andre601** [comment]
[I now added your plugin to the wiki](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#r)
