### ISSUE TITLE
[Request] Adding my plugin to the List „Plugins using Papi“

### ISSUE THREAD

**Issue by morelaid** [PlaceholderAPI/PlaceholderAPI#451]
It would be cool if you would add my plugin "StreamingDrops" to the list of plugins that use your API.

StreamingDrops has its own placeholders for external plugins (no cloud download).

A link to the plugin:
https://www.spigotmc.org/resources/76996/

An info about all available placeholders from PAPI:
https://github.com/morelaid/StreamDrops/wiki/PlaceholderAPI-Support#placeholderapi

If you need more information, please let me know.

**Comment by Andre601** [comment]
We handle new plugins through Pull requests now.
Check the readme in the wiki folder.

**Comment by Andre601** [comment]
I've added the plugin to the wiki. Thanks for supporting PlaceholderAPI.

P.S.: Consider PRing the changes yourself next time for a faster addition.
