### ISSUE TITLE
Player Absorption Placeholder Vairable

### ISSUE THREAD

**Issue by tdubz1** [PlaceholderAPI/PlaceholderAPI#455]
### Type

- [x] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Description

Player Absorption placeholder vairable which measures the absorption of a player.

%player_absorption%

Would be very useful for many servers.

**Comment by Andre601** [comment]
1. What is "absorption"?
2. Please open an issue with this on the [Player-Expansion Repository](https://github.com/PlaceholderAPI/Player-Expansion)

**Comment by tdubz1** [comment]
> 1. What is "absorption"?
> 2. Please open an issue with this on the [Player-Expansion Repository](https://github.com/PlaceholderAPI/Player-Expansion)

https://github.com/PlaceholderAPI/Player-Expansion/issues/35
