### ISSUE TITLE
Bentobox Placeholders

### ISSUE THREAD

**Issue by fredthedoggy** [PlaceholderAPI/PlaceholderAPI#458]
The Current Bentobox placeholders are outdated.
Here are the updated ones: https://docs.bentobox.world/en/latest/BentoBox/Placeholders/

**Comment by fredthedoggy** [comment]
The Template is not available. When I click it, it does not come up with the pre-made template.

**Comment by Andre601** [comment]
> The Template is not available. When I click it, it does not come up with the pre-made template.

This is because there isn't a issue template for requesting changes to the wiki anymore. Those are now handled through Pull requests, which you seem to have figured out by now.
