### ISSUE TITLE
NullPointerException when using ChestCommands

### ISSUE THREAD

**Issue by DartPower** [PlaceholderAPI/PlaceholderAPI#462]
Paper version git-Paper-174 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

https://hastebin.com/nuxorivado.sql

If this problem does not apply to PAPI, can you give me a advice, which plugin is good using (alternative) for Chest/Inventory GUIs? :-(

**Comment by darbyjack** [comment]
I will look into this. To answer your question about alternatives, the go-to is typically DeluxeMenus (https://www.spigotmc.org/resources/deluxemenus.11734/). It's designed by the same team that makes PlaceholderAPI so the integration is amazing!

**Comment by darbyjack** [comment]
From what I can tell, my guess is that the integration of ChestCommands hasn't been updated since we made changes to PlaceholderAPI over the past few months. My suggestion would be to reach out to the developer of ChestCommands (should you still want to use it) and ask them to update their integration with PlaceholderAPI.

**Comment by DartPower** [comment]
Thanks a lot for info! 👍

**Comment by darbyjack** [comment]
Glad I could help. Feel free to close this whenever.

**Comment by Andre601** [comment]
The error provided seems to point to a rather old release of ChestCommands as the path there is `com.gmail.filoghost` while the one in the [Source Code](https://github.com/filoghost/ChestCommands) (Both API and plugin) is `me.filoghost`

In addition can I not find any bridge package whatsoever which further proofs my point that the version you use seems to be a fairly outdated one.
