### ISSUE TITLE
Bad Time

### ISSUE THREAD

**Issue by XANT3R** [PlaceholderAPI/PlaceholderAPI#464]
I used placeholder "%statistic_time_played%" and unfortunately it charges days incorrectly. He gives me 1 day and 43 hours when he should have already counted the second day.

My Plugins:
Plugins (48): Announcements*, ArmorStandEditor, AuthMe, Citizens, CoreProtect, CraftBook, Cubesurvstats, DeadChest, DiscordSRV, dynmap*, EasyWhitelist*, Essentials, EssentialsChat, EssentialsSpawn, F3Name, FastLogin, HolographicDisplays, IllegalStack, LiquidTanks, LuckPerms, LWC, LWCTrust, MC-AnvilColors*, MLJobs, MyCommand, OpenInv, PlaceholderAPI, PlayerParticles, PreciousStones, ProtocolLib, ServerRestorer, Shopkeepers, SkinsRestorer, SklepMC*, Skript, skript-mirror*, spark, TAB, TitleManager, Trade, TreeAssist, TuSKe*, UltraBar, Vault, ViaBackwards, ViaVersion, WorldEdit, WorldGuard

Paper Version in /ver:

 [19:11:41 INFO]: This server is running Paper version git-Paper-176 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
[19:11:41 INFO]: Checking version, please wait...
[19:11:41 INFO]: Previous version: git-Paper-131 (MC: 1.16.1)
[19:11:41 INFO]: You are 2 version(s) behind

ScreenShot:
https://i.imgur.com/HmKtY18.png

**Comment by Andre601** [comment]
You can find the statistics-expansion here: https://github.com/PlaceholderAPI/Statistics-Expansion

(Also, you didn't follow the issue template. Please do that next time. It exists for a reason)
