### ISSUE TITLE
Add new plugin to "Plugins using PlaceholderAPI"

### ISSUE THREAD

**Issue by axelrindle** [PlaceholderAPI/PlaceholderAPI#468]
### Type
- [x] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
I recently added custom placeholders to one of my own plugins: [SimpleCoins](https://github.com/axelrindle/SimpleCoins).

A list can be found [here](https://github.com/axelrindle/SimpleCoins/wiki/Placeholders).

**Comment by Andre601** [comment]
Was added.
