### ISSUE TITLE
"/papi info <identifier>" is checking the wrong method

### ISSUE THREAD

**Issue by DalBrar** [PlaceholderAPI/PlaceholderAPI#469]
### Issue
When using the command "/papi info <identifier>" the tab complete method correctly lists all identifiers however executing the command does a check against PlaceholderExpansion.getName() instead of against PlaceholderExpansion.getIdentifier().

This problem isn't noticeable when the placeholders name is the same as the identifier but can be seen when trying to use with a placeholder where the name is different, in my case, using my own placeholder "ScoreboardObjectives" (name) who's identifier is "objective".

The "/papi info" command lists "objective" as a possible tab complete, but doing "/papi info objective" returns "**There is no expansion loaded with the identifier: objective**" which is incorrect, the identifier is correct. Doing "/papi info ScoreboardObjectives" returns the proper list of getPlaceholders().

### Expected behaviour
Executing "/papi info objective" should correctly check the getIdentifier().

### Actual behaviour
Executing "/papi info objective" checks against the placeholders getName() method and thus fails when the name does not match the identifier.

### How to reproduce
1. Download the ScoreboardObjectives placeholder from ecloud or it's spigot page.
2. execute "/papi info objective"
3. execute "/papi info scoreboardobjectives"

### `/papi dump` output
https://paste.helpch.at/zehojorusa

- LethalBunny

**Comment by Andre601** [comment]
I've created a PR which *should* fix this.
Feel free to give your input on this if you want. I hope clip will approve it soon.

**Comment by Andre601** [comment]
Hey @DalBrar 

As you may have noticed was the PR I mentioned merged.
Could you be able to try out [Build 118 from Jenkins](https://ci.extendedclip.com/job/PlaceholderAPI/118/) and let us know if the issue was fixed?
