### ISSUE TITLE
Add BetonQuest to your "integrated plugins" list

### ISSUE THREAD

**Issue by SaltyAimbOtter** [PlaceholderAPI/PlaceholderAPI#470]
Heya! 
BetonQuest supports both placeholders from other PAPI plugins and also exposes it's variables through PAPI to other plugins.
[Our docs](https://betonquest.github.io/BetonQuest/versions/dev/User-Documentation/Compatibility/#placeholderapi)

**Comment by Andre601** [comment]
In addition should you follow the templates as we won't look at any ignoring the templates.

**Comment by Andre601** [comment]
Added. But remember to use one of the templates next time as it helps us a lot getting the required info.

**Comment by SaltyAimbOtter** [comment]
Your wiki was misleading here, I was reading through the list of supported plugins and saw the text in the screenshot below: 
![grafik](https://user-images.githubusercontent.com/40303883/93020675-a2237900-f5de-11ea-96c6-0e639b914eb6.png)
This links to an empty template so I assumed it was fine to just write an issue like the text on that page told me 🤷‍♂️ 
Thank you for adding it though!

**Comment by Andre601** [comment]
Thanks for pointing that out. I'll update it asap.
