### ISSUE TITLE
Incorrect work of Player_ping Placeholder

### ISSUE THREAD

**Issue by dailrus** [PlaceholderAPI/PlaceholderAPI#479]
### Issue

%player_ping% doesn't work with TabListPro and outputs empty

### Expected behaviour

Output ping for each player in their Tabs

### Actual behaviour

It outputs empty spot in place where used.

### How to reproduce

1. Use TabListPro
2. Use %player_ping% or %player_colored_ping% in TabList config file
3, Open Tab list in game
![Снимок экрана (168)](https://user-images.githubusercontent.com/50212538/93642215-5cafe300-fa06-11ea-9cef-72c4d225aaa5.png)

### `/papi dump` output

https://paste.helpch.at/rokugikuxo

**Comment by Andre601** [comment]
Your issue isn't related to PAPI but the Player expansion (if at all).

My personal guess is that the tab list plugin is just shit in handling placeholders properly.
