### ISSUE TITLE
[Bug] %server_tps% does not work?

### ISSUE THREAD

**Issue by CloudeLecaw** [PlaceholderAPI/PlaceholderAPI#48]
tried to use a placeholder of the PlaceholderAPI in Tab of CMIs %server_tps% this placeholder seems not to work
in result the tab shows me the word "%server_tps%"
Placeholder API and the server extansion is installed.
othes like %server_ram_used% work

![image](https://user-images.githubusercontent.com/12080017/47050977-8d47cc00-d1a2-11e8-87f3-d783af8dbdb6.png)

**Comment by CloudeLecaw** [comment]
the latest spigot Version..why?

**Comment by darbyjack** [comment]
Alright thanks, I'll look into this shortly.

**Comment by Gaby-TM** [comment]
> ```%server_tps_1%
> %server_tps_5%
> %server_tps_15%
> %server_tps_1_colored%
> %server_tps_5_colored%
> %server_tps_15_colored%
> ```

**Comment by CloudeLecaw** [comment]
Gaby …

These are just other varants of %server_tps%

but yes to be complet it it may be Right to list them too.

**Comment by NiightFuryDragon** [comment]
you need to download the server addon use /papi ecloud download server

**Comment by CloudeLecaw** [comment]
![image](https://user-images.githubusercontent.com/12080017/47437934-c76c2b80-d7a9-11e8-913f-75015fea3612.png)

**Comment by darbyjack** [comment]
![image](https://user-images.githubusercontent.com/21014720/47438313-d6ce8300-d76f-11e8-9116-1af51e054f17.png)
Can not reproduce. Are you still on 1.13.1?

**Comment by darbyjack** [comment]
It's not %server-tps%, it's %server_tps%

**Comment by CloudeLecaw** [comment]
well sorry the - came from later Tests..
![image](https://user-images.githubusercontent.com/12080017/47439465-b4a72600-d7ac-11e8-95e1-bfd43cdd4498.png)

**Comment by darbyjack** [comment]
Yeah, don't know what to tell you, I can't reproduce this.

**Comment by CloudeLecaw** [comment]
Well i tested now just PlaceHolderAPI 4.9.2 + Spigot 1.13.2 + Pex 1.23.4

The Result was the same :(
![image](https://user-images.githubusercontent.com/12080017/47440153-e4a2f900-d7ad-11e8-89d4-c08b36e2b3a7.png)

**Comment by darbyjack** [comment]
How are you on a version PlaceholderAPI that doesn't exist?

**Comment by CloudeLecaw** [comment]
![image](https://user-images.githubusercontent.com/12080017/47075245-76ce5e80-d1fc-11e8-85d9-5136041cd1cb.png)

/plugman list -v

shows the version number written in the plugin.yml
the version is the normal version from spigot

**Comment by darbyjack** [comment]
You said 4.9.2... Anyways, like I said, this can't be reproduced.

**Comment by CloudeLecaw** [comment]
well 4.9.2... im so stupid it was my error *hehe*

But there still need to be a reason why the placeholder is not accepted :(

if u scroll above u see the user Gaby-TM also has this problem

so my TestServer and the Servver of oner owner are not alone..

**Comment by darbyjack** [comment]
Try this jar for the expansion ~ http://ci.extendedclip.com/job/Server-Expansion/5/artifact/target/PAPI-Expansion-Server.jar

**Comment by darbyjack** [comment]
Just replace the current one in the expansions folder 
![image](https://user-images.githubusercontent.com/21014720/47455144-b5cd5880-d796-11e8-9303-eba189b76577.png)

**Comment by CloudeLecaw** [comment]
YEAY This One works =)

![image](https://user-images.githubusercontent.com/12080017/47455392-0ada9000-d7d2-11e8-88ca-312e3c013f6c.png)

**Comment by darbyjack** [comment]
That's so weird, I didn't change anything really, but glad it's working.

**Comment by CloudeLecaw** [comment]
i just saw the old file (i got im the papi command was 11kb) this one was 8kb..


so there must be a little difference

**Comment by lweb20** [comment]
Please upload jar in [expansion-cloud](https://api.extendedclip.com/expansions/server/versions/). Thanks.
