### ISSUE TITLE
Include another file in builds on CI server

### ISSUE THREAD

**Issue by flleeppyy** [PlaceholderAPI/PlaceholderAPI#480]
### Type

- [ ] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [x] Other: __________ 

### Description

 
I'm trying to automate plugin updating on my servers by creating a script that wget's all the latest builds of plugins, and It would be helpful to have a standalone file without a version name or build name, in your plugin builds. (EX: https://ci.extendedclip.com/job/PlaceholderAPI/lastStableBuild/artifact/build/libs/PlaceholderAPI.jar)

**Comment by darbyjack** [comment]
Thanks for the suggestion! Did you know that you can already do this via the API?

Here's a link: https://ci.extendedclip.com/job/PlaceholderAPI/lastSuccessfulBuild/api/json

This will provide you all the information you could need about the latest build, including the jar name! In your script, you can just parse that and then curl / wget that file!

**Comment by flleeppyy** [comment]
Thank you thank you! I knew there was a link for it but i just didnt know what
