### ISSUE TITLE
My Plugins that soft depend on PlaceholderAPI

### ISSUE THREAD

**Issue by HMJosh** [PlaceholderAPI/PlaceholderAPI#481]
https://www.spigotmc.org/resources/boxing.83879/
https://www.spigotmc.org/resources/tplogin.21692/
https://www.spigotmc.org/resources/rankjoin.67551/
and
https://www.spigotmc.org/resources/ticketgui-formerly-helpopgui.68968/

Thanks 👍

**Comment by Andre601** [comment]
Added to the wiki
