### ISSUE TITLE
Add new plugin to "Plugins using PlaceholderAPI"

### ISSUE THREAD

**Issue by AlonsoAliaga** [PlaceholderAPI/PlaceholderAPI#482]
### Type

- [x] New plugin/expansion supporting PlaceholderAPI.
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Description
I recently added custom placeholders to one of my own plugins: [AlonsoLevels](https://www.spigotmc.org/resources/83380/).

A list can be found [here](https://github.com/AlonsoAliaga/AlonsoLevels/wiki/Placeholders).

**Comment by Andre601** [comment]
Added to wiki
