### ISSUE TITLE
Bracket duplication

### ISSUE THREAD

**Issue by Echoblast53** [PlaceholderAPI/PlaceholderAPI#49]
https://github.com/PlaceholderAPI/PlaceholderAPI/blob/dd5ec3705517257e15f09d821480399a22f884a1/src/main/java/me/clip/placeholderapi/PlaceholderAPI.java#L48

The curly bracket seems to be repeated.

**Comment by bigibas123** [comment]
This regex is looking for something between curly braces that isn't containing curly braces hence the [^ in the regex [See here for an explanation of the complete regex](https://regexr.com/41v51)

**Comment by Echoblast53** [comment]
Oh i didn't recognize it as regex, since i usually escape all my non-regex characters.
