### ISSUE TITLE
Nested placeholder support (placeholders within placeholders)

### ISSUE THREAD

**Issue by LeehamElectronics** [PlaceholderAPI/PlaceholderAPI#490]
Hi, is it possible to add nested placeholder support? For example, I want to parse a placeholder within a placeholder like so:
`%otherplayer_health_%core_arena_player_3%%`
How difficult would this be to implement?
Thanks in advanced!

**Comment by MarvinKlar** [comment]
https://api.extendedclip.com/expansions/nestedplaceholders/

**Comment by SpigotRCE** [comment]
I get 

Expansion does not exist.
