### ISSUE TITLE
Can't Reload Plugin

### ISSUE THREAD

**Issue by ArvickC** [PlaceholderAPI/PlaceholderAPI#492]
### Issue

When I try and run the "/papi reload" command on the latest version of papi I get an error.

### Expected behaviour

It should reload without a problem

### Actual behaviour

It gives me this; https://pastebin.com/hF6adZrb error

### How to reproduce

1. Update plugin to latest
2. Run command "/papi ecloud download Server"
3. Run command "/papi reload"

### `/papi dump` output

https://paste.helpch.at/aguhurokax

**Comment by iGabyTM** [comment]
@thienbao860 java 8 please

**Comment by ArvickC** [comment]
?

**Comment by darbyjack** [comment]
Whatever this expansion is, `me/thienbao860/expansion/world/WorldData`, probably some expansion called `World` was compiled using a previous version of Java than the one you are now. If you remove that expansion, it will work fine.

**Comment by ArvickC** [comment]
How do I remove it?

**Comment by darbyjack** [comment]
Remove it from the expansions folder.

**Comment by ArvickC** [comment]
Oh! Lemmie test it

**Comment by Andre601** [comment]
If you can't find it inside the expansions folder, then the expansion was loaded by a plugin, so you have to find out what plugin causes this is.

**Comment by ArvickC** [comment]
> Whatever this expansion is, `me/thienbao860/expansion/world/WorldData`, probably some expansion called `World` was compiled using a previous version of Java than the one you are now. If you remove that expansion, it will work fine.

This worked! Thank you guys!

**Comment by thienbao860** [comment]
Hello, the author of World expansion here. Which exact version of World expansion do you use? Because it seems to load fine for me (v 1.1.1). If you use v 1.1.0, please update it
