### ISSUE TITLE
WorldGuard new placeholder or fix old

### ISSUE THREAD

**Issue by NESTOWL** [PlaceholderAPI/PlaceholderAPI#495]
### Type

- [ ] New function for PlaceholderAPI.  
A new function that developers could use.
- [x] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Description
when 2 regions intersect, then in the placeholder they constantly change in turn
![1111111111](https://user-images.githubusercontent.com/45520187/96709120-e9054b00-13a2-11eb-8182-b3c2ac690561.gif)

Logical to display a higher priority region, or they should be listed separated by commas
example of placeholders:
%worldguard_region_name_priority% - the name of the priority region
%worldguard_region_names% - names of all regions in this position, separated by commas

or fix `%worldguard_region_name%` so that it displays the higher priority region!
or listing all regions separated by commas

**Comment by Andre601** [comment]
Please report this to the worldguard expansion repository.

https://github.com/PlaceholderAPI/WorldGuard-Expansion

**Comment by NESTOWL** [comment]
@Andre601 I did it here [#1656](https://github.com/EngineHub/WorldGuard/issues/1656)
and now you send me back ...

**Comment by Andre601** [comment]
That is NOT the WorldGuard expansion repository.
Actually check the link I send before claiming that I "send you back".

**Comment by NESTOWL** [comment]
@Andre601 Got it, I'll write now
I apologize for not writing there.
