### ISSUE TITLE
Error onDisable w/ Essentials

### ISSUE THREAD

**Issue by Loonyy** [PlaceholderAPI/PlaceholderAPI#497]
https://pastebin.com/hB1V3gCZ

**Comment by Andre601** [comment]
This is also an issue caused by the Essentials-Expansion and not PlaceholderAPI.

Please report it to the [actual repository](https://github.com/PlaceholderAPI/Essentials-Expansion) for it and not here (And next time, follow the issue templates. We have them for reasons)
