### ISSUE TITLE
Change ecloud commands to only require permission node rather than Op

### ISSUE THREAD

**Issue by extendedclip** [PlaceholderAPI/PlaceholderAPI#5]
As stated here: https://www.spigotmc.org/threads/placeholderapi.61918/page-91#post-2944172
Some may find it annoying that ecloud commands require op to be executed. I personally feel it is safer but I guess perm checking is just as secure.  Any feedback is appreciated.

**Comment by RustyDagger** [comment]
I find having to login to my console view to run the command time consuming I can access every thing else from in game with out being Op, If my account was breached they could do far harder things to undo than install a few modules. 

some may ask why I am not Op Op tends to just get handed every thing this can include boots to xp gain on some plugins that's undesirable

**Comment by DoNotSpamPls** [comment]
I think making it a permission would make it more versatile, allowing to reject access even for opped people. It can just be added to plugin.yml with `default: op` as redundancy

**Comment by Banbeucmas** [comment]
Pretty sure this might create some inconvience for some LuckPerm users who `allows-Op` is set to `false` if this doesn't get implemented.

**Comment by extendedclip** [comment]
Thanks @DoNotSpamPls for the PR.

T
