### ISSUE TITLE
PermissionsEx, VIP system extension 

### ISSUE THREAD

**Issue by Straiker123** [PlaceholderAPI/PlaceholderAPI#50]
PermissionsEx:
https://dev.bukkit.org/projects/permissionsex
VIP system:
https://www.spigotmc.org/resources/1-7-x-1-12-vip-system-sql-yaml-configuration-api.44096/

thanks

**Comment by darbyjack** [comment]
![image](https://user-images.githubusercontent.com/21014720/47841900-13f6ce80-dd89-11e8-8c59-6749d291a2a8.png)

**Comment by Straiker123** [comment]
thnkas
