### ISSUE TITLE
[Suggestion] add a option to define the /expansions directory

### ISSUE THREAD

**Issue by RedstoneFuture** [PlaceholderAPI/PlaceholderAPI#504]
### Type

- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [x] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Description
Can you **add a config option to define** the `/expansions` directory? It's useful for a bungeecord system with more than one spigot server. So you down't need an update of all extensions separately.

* new Config option:

```
[...]
expansions_directory: '/home/minecraft-server/main/server/plugins/PlaceholderAPI/expansions'
[...]
```

* Without this config-definition the default directory will be used.

**Comment by Andre601** [comment]
PlaceholderAPI isn't a BungeeCord plugin (yet) so this option doesn't really make sense to have.

**Comment by RedstoneFuture** [comment]
@Andre601 PlaceholderAPI is a plugin for a normal bukkit instance, I know. But if you have 4 servers and in all servers you need the same expansions, like: `Expansion-Pinger.jar`, `Expansion-Player.jar` and `Expansion-Server.jar ` it's unlucky to store it in all servers seperately. Do you understand the benefit?

**Comment by knightzmc** [comment]
I may be wrong, but couldn't you just set up a symlink for each expansions directory?

**Comment by RedstoneFuture** [comment]
@knightzmc You're right. I can use softlinks, but with the focus of software usability, I thought this feature request in an idea.

**Comment by Andre601** [comment]
I do, but there isn't a way to make a central storage.
And even if there is would it be not a good behaviour of a plugin to generate folders outside of the server directory.

**Comment by RedstoneFuture** [comment]
> A plugin should in best case ONLY handle files in its own directory and in worse files in the same server folder as itself (i.e. Bluemap does this).

Ok, I understand your opinion. So we can close this feature-request - it was only an idea.
