### ISSUE TITLE
PlaceholderAPI's placeholders dont work

### ISSUE THREAD

**Issue by SejDevStuff** [PlaceholderAPI/PlaceholderAPI#505]
### Issue

I installed the Statistic and LocalTime extension many times and reloaded PlaceholderAPI but %localtime_time% and %statistic_player_kills% do not work

### Expected behaviour

It should say the local time and also how many kills the player has

### Actual behaviour

It just says "%statistic_player_kills%" and "%localtime_time%"
![image](https://user-images.githubusercontent.com/60989665/101266451-eab68280-3746-11eb-892a-6997a3d8da48.png)

### How to reproduce

I am on 1.16.4 MC PaperMC server, around 17 plugins and AnimatedSidebar where I use PlaceholderAPI, It is not that that is causing the issue since I have another server where PlaceholderAPI works fine with AnimatedSidebar

1. Get a 1.16.4 PaperMC server
2. Download latest PlaceholderAPI and AnimatedSidebar from SpigotMC
3. Start server
4. do ``/papi ecloud download Statistic``
5. Update the animated sidebar config to include %statistic_player_kills% somewhere
6. Reload animatedsidebar (``/sidebar reload``)

### `/papi dump` output

https://paste.helpch.at/zoxemilisi

I am a beginner in the serverworld and only have been hosting a server for a month and a bit now so i am terribly sorry if this issue is easy to fix.
Thanks

**Comment by Andre601** [comment]
Are there any errors in the console?

My only guess here would be, that AnimatedSidebar doesn't hook into PlaceholderAPI properly.
Are you using [this AnimatedSidebar plugin?]() If that's the case would I recommend switching to another plugin as this one is extremely bloated with useless crap no plugin should ever contain.

Some alternatives you could consider are:
- [FeatherBoard (Paid)](https://www.spigotmc.org/resources/2691/)
- [KiteBoard (Paid)](https://www.spigotmc.org/resources/13694/)
- [QuickBoard (Free)](https://www.spigotmc.org/resources/15057/)
- [Scoreboard (Free)](https://www.spigotmc.org/resources/14754/)

**Comment by SejDevStuff** [comment]
Thanks, I will look into using Scoreboard

**Comment by Andre601** [comment]
I'll close this.
If you still encounter the issue, let us know and I'll reopen the issue.
