### ISSUE TITLE
PAPI still fails to find player(s) on their first join

### ISSUE THREAD

**Issue by stonar96** [PlaceholderAPI/PlaceholderAPI#527]
### Issue

When a player joins the server for the first time and someone tries to execute the command `/papi parse ...` with that player as argument, while the player is still online, the execution fails with the message `Failed to find player: ...`. As soon as the player quits the first time it works fine. According to #256 this is already fixed. However, I still have that issue on PlaceholderAPI 2.10.9.

### Expected behaviour

The command shouldn't fail to find a player, who is online.

### Actual behaviour

When a player joins the server for the first time and someone tries to execute the command `/papi parse ...` with that player as argument, while the player is still online, the execution fails with the message `Failed to find player: ...`.

### How to reproduce

1. Download and install the latest version of Paper (git-Paper-354 (MC: 1.16.4)).
2. Download and install the latest version of PlaceholderAPI (2.10.9).
3. Join the server with your Minecraft account.
4. Execute the command `/papi parse yourusername test` in the console.

### `/papi dump` output

https://paste.helpch.at/udebukitit

**Comment by Andre601** [comment]
[dev]: https://ci.extendedclip.com/job/PlaceholderAPI/

Did you try it with a [development build of PlaceholderAPI][dev]?

**Comment by Andre601** [comment]
I can't really reproduce this problem with a dev build.

![image](https://user-images.githubusercontent.com/11576465/103413182-b7fe7f00-4b78-11eb-83d9-9c2f13b388d4.png)

**Comment by stonar96** [comment]
Using the latest dev build on a fresh server.

![grafik](https://user-images.githubusercontent.com/18699205/103418548-76c59980-4b8f-11eb-9a12-1f0ee16f7eb0.png)

**Comment by Andre601** [comment]
I sadly can't reproduce this problem. Do you use any other special plugin, or do you save the worlds in a different way?
Like what is your setup?

**Comment by stonar96** [comment]
Exactly what I have said in  "How to reproduce". Nothing. I just startet a fresh server without anything else, dropped PlaceholderAPI into the plugins folder, restarted the server, that's it.

**Comment by Andre601** [comment]
I was able to reproduce this partially.

Creating a complete new server with fresh world and latest Spigot release did give me the error you experienced.
However! Rejoining the server and trying the command again did parse it as expected, although I did download the Player expansion before so maybe that was an important factor.
I'll test it again with only PAPI and no expansions this time and give you the feedback, but I assume it will be the same result and therefore this being a you-issue, but we'll see.

![image](https://user-images.githubusercontent.com/11576465/103419157-200d8f00-4b92-11eb-9613-d085c00c8a1a.png)

**Comment by stonar96** [comment]
It's independent of installed expansions.

![grafik](https://user-images.githubusercontent.com/18699205/103419234-78449100-4b92-11eb-90d4-7b481877941d.png)

> therefore this being a you-issue, but we'll see.
I don't get it. I did nothing wrong, just installed PlaceholderAPI on a fresh server without any settings.

**Comment by Andre601** [comment]
Nope. Not reproducable.
Completely fresh world and no PlaceholderAPI expansions installed.

While the error appears the first time does it not re-appear after I rejoined the world, so this must be caused by something in your setup. Perhaps a setting or so that prevents the server from saving the playerdata to file?
Double-check that you have a `usercache.json` file in the root of your server as I can only image your server being the core of the issue.

But as you can see on the screenshot below does it not happen more than once.
![image](https://user-images.githubusercontent.com/11576465/103419312-cd80a280-4b92-11eb-8a09-1f6044ac9c31.png)

**Comment by stonar96** [comment]
Yes that's exactly the issue I have described. It happens only on first join.

**Comment by stonar96** [comment]
> As soon as the player quits the first time it works fine.

**Comment by Andre601** [comment]
Sorry. Didn't see that part.
And yeah. Looking at the code does PAPI use this rather odd piece of code to retrieve the player:
https://github.com/PlaceholderAPI/PlaceholderAPI/blob/e8b5660eda3046aee98396ac046537d8f92e78d9/src/main/java/me/clip/placeholderapi/commands/impl/local/CommandParse.java#L212-L222

I'll look into finding a better solution here, but this is a rather minor issue as it only happens once.

**Comment by stonar96** [comment]
I'd suggest:
```java
        OfflinePlayer target = Bukkit.getPlayer(name);

        if (target == null) {
            target = Bukkit.getOfflinePlayer(name); // this is probably not a great idea.
            return target.hasPlayedBefore() ? target : null;
        }

        return target;
```

**Comment by Andre601** [comment]
Already done
https://github.com/PlaceholderAPI/PlaceholderAPI/commit/8fa0f73a46a5e452dc12c57580704ea394659193
