### ISSUE TITLE
Statistic placeholder not working

### ISSUE THREAD

**Issue by 100stars** [PlaceholderAPI/PlaceholderAPI#53]
Hi, I have a private server with 1.8 spigot. I wanted to have like a /stat command using MyCommand and PlaceHolderAPI. I did /papi ecloud download Statistic but in the command, it shows like normally in the text: %statistic_mine_block% instead of a value. Please let me know if it's for me or everyone and what to do. If you want more information let me know.

**Comment by aBo0oDyy** [comment]
Latest version of statistic expansion is for 1.13+
Download v1.7.0 
/papi ecloud download Statistic 1.7.0
/papi reload

**Comment by 100stars** [comment]
Thank you for helping me! :)
