### ISSUE TITLE
Clans [Pro] placeholder launch.

### ISSUE THREAD

**Issue by Hempfest** [PlaceholderAPI/PlaceholderAPI#532]
The new launch of Clans [Pro] (Still pending just posted) : https://www.spigotmc.org/resources/clans-pro-official-launch-1-12-1-16.87515/

Has the following placeholders:
%clanspro_clan_name%
%clanspro_clan_description%
%clanspro_clan_color%
%clanspro_clan_pvp_mode%
%clanspro_clan_balance%
%clanspro_clan_members_online%
%clanspro_member_rank%
%clanspro_member_bio%
%clanspro_raidshield_status%

**Comment by Andre601** [comment]
As long as the plugin also isn't active/available will the wiki not be updated with it.
