### ISSUE TITLE
PlaceholderAPI expansion problem: skript-expansion (unable to load)

### ISSUE THREAD

**Issue by Jortagon** [PlaceholderAPI/PlaceholderAPI#535]
### Issue

Skript expansion not load, seems it like not supported anymore (?)

Console output, after im reload the PlaceholderAPI 
![console-report](https://user-images.githubusercontent.com/60069537/104570987-25d09d80-5685-11eb-8ce9-91accbc12462.png)

### Expected behaviour

PlaceholderAPI must load an skript-expansion, but in this case, the expansion unable to load.

### Actual behaviour

It allow to use skript variables in PlaceholderAPI.

### How to reproduce

1. Download the skript-expansion and reload PlaceholderAPI normally. (through command)
2. /papi ecloud download Skript
3. /papi reload

### `/papi dump` output
[https://paste.helpch.at/axofifuqog](https://paste.helpch.at/axofifuqog)

**Comment by Andre601** [comment]
The script expansion is outdated. Read the error and report it to the expansion author.
