### ISSUE TITLE
Bungeecord placeholders error

### ISSUE THREAD

**Issue by ImTomOriginal** [PlaceholderAPI/PlaceholderAPI#536]
Error for bungeecord ecloud expansion on start of the server

papi dump:
https://paste.helpch.at/mojiriwigi

**Comment by extendedclip** [comment]
You did not provide the error but it looks like you have 2 bungee expansion jars in your expansion folder. Please delete both and redownload the bungee expansion.

**Comment by ImTomOriginal** [comment]
okay.. i did seems like it works now.. also found this

[12:19:50 WARN]: [PlaceholderAPI] PremiumVanish is attempting to unregister placeholders via the PlaceholderAPI class which is no longer supported! Please reach out to [MyzelYam] and let them know that they need to update ASAP!

**Comment by ImTomOriginal** [comment]
well it seems like just updating everything worked. FIXED. Thanks ! :)

**Comment by Andre601** [comment]
Next time use the template pleaye, thanks. :)
