### ISSUE TITLE
Cannot parse %vault_prefix%

### ISSUE THREAD

**Issue by Evidentsinger14** [PlaceholderAPI/PlaceholderAPI#544]
### Issue

When i run "/papi parse Ev1dent %vault_prefix%" on one of my servers, it returns the proper prefix. 
[Image 1](https://imgur.com/a/1uhDkdB)
However, when i run it on my second server, it kicks me with an error.
[Image 2](https://imgur.com/a/Xun5N9T)

### Expected behaviour

Output my prefix with the correct 

### Actual behaviour

Kick me, with an error message on my screen, as shown my message above.

### How to reproduce

1. install placeholderapi, expansions, and setup ranks. then try to parse %vault_prefix%

### `/papi dump` output

https://paste.helpch.at/akoyudezib

**Comment by Andre601** [comment]
We need to know the error to see if it is a papi issue or caused by the expansion alone.

**Comment by Evidentsinger14** [comment]
The button "Image 2" is the error that i get when im kicked. there are no console errors.

**Comment by Andre601** [comment]
The issue is caused by an incomatability with colors, probably related to #489
