### ISSUE TITLE
Plugin launch.

### ISSUE THREAD

**Issue by Hempfest** [PlaceholderAPI/PlaceholderAPI#548]
### Type

- [ ] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [x] Other: Plugin launch, placeholders available. 

### Description

I had an issue opened a while back but the plugin was pending at that point in time. It is now launched and has these current PlaceholderAPI placeholders:

- %clanspro_clan_name%
- %clanspro_clan_description%
- %clanspro_clan_color%
- %clanspro_clan_pvp_mode%
- %clanspro_clan_balance%
- %clanspro_clan_power%
- %clanspro_clan_members_online%
- %clanspro_member_rank%
- %clanspro_member_bio%
- %clanspro_raidshield_status%

Im requesting the addition of this to the wiki page

Here is the link to the spigot page : https://www.spigotmc.org/resources/clans-pro-official-launch-1-12-1-16.87515/

**Comment by Andre601** [comment]
Closing this as the Wiki already has the Plugin listed.
If there have been changes to the Placeholders, go ahead and PR a change as suggested above.
