### ISSUE TITLE
Support for different server platforms

### ISSUE THREAD

**Issue by Leonardo-DGS** [PlaceholderAPI/PlaceholderAPI#550]
## Feature Request
Plugin for different platforms, like Velocity or BungeeCord (see #36).
### Type

- [x] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Description

It should be done a platform-agnostic core module of PlaceholderAPI, and a different implementation for each server (Bukkit, Sponge, BungeeCord, Velocity, ecc.).
For each ecloud extension should be set for which platform is made.

**Comment by Andre601** [comment]
This is a planned feature for v3 of PlaceholderAPI which is currently under development.
It will then support Spigot (+ any fork), BungeeCord and probably other servers such as Sponge or NukkitX.

Unfortunately can we not give an ETA on when v3 will come out, but it will come for sure.

**Comment by Leonardo-DGS** [comment]
> This is a planned feature for v3 of PlaceholderAPI which is currently under development.
> It will then support Spigot (+ any fork), BungeeCord and probably other servers such as Sponge or NukkitX.
> 
> Unfortunately can we not give an ETA on when v3 will come out, but it will come for sure.

If it's planned, why do you close it?

**Comment by Andre601** [comment]
Because it will be tracket on a separate repository.

**Comment by SlimeDog** [comment]
Please provide a link to the V3 repository, so we can follow along.

**Comment by Andre601** [comment]
The repo is private so it wouldn't make much sense to add it here...

Also, just add a 3 to the repo name
