### ISSUE TITLE
[Feature Request] Event that runs when a placeholder change

### ISSUE THREAD

**Issue by Tobi-Jakka** [PlaceholderAPI/PlaceholderAPI#554]
## Feature Request
Event that runs when a placeholder change

### Type
- [x] New function for PlaceholderAPI.  
A new function that developers could use.

### Description

An event that calls whenever a placeholder is updated. Would be useful in the way that you could have stuff run when that event calls (like a function that reconstruct my GUI with new placeholder information).

Not sure if this is already in the plugin, but I did go through the api as well as search through both open & closed tickets, & saw nothing that indicated that this had been brought up before, though I may have just searched with the wrong terms.

Thanks,
- Tobi

**Comment by RobinDeBaets** [comment]
I don't really think this is something worth adding. PlaceholderAPI polls the data for a placeholder from a hook when another plugin requests this placeholder. The hook does not simply push its new data to PlaceholderAPI whenever there's an update. This is a bit contrary to how an 'event' would work.

I would suggest just periodically requesting the placeholder every few seconds to update your GUI.

**Comment by Tobi-Jakka** [comment]
Ah okay, I guess I could do that as well

**Comment by Andre601** [comment]
Not really possible as it would require PlaceholderAPI to keep track of all placeholders used and all their values.
In combination with the fact that placeholders are often per-player would this result in hundreds if not thousands of placeholders which PlaceholderAPI needs to handle, which is extremely heavy and inefficient to do.
