### ISSUE TITLE
Errors on shutdown

### ISSUE THREAD

**Issue by Loonyy** [PlaceholderAPI/PlaceholderAPI#557]
### Issue

Multiple errors when shutting down server
https://pastebin.com/aF6cc6wx

### How to reproduce

1.  Shut down the server

### `/papi dump` output

https://paste.helpch.at/afolabebaq

**Comment by Andre601** [comment]
Two things:

1. Follow the actual issue template as you didn't provide all required information.
2. This is an issue with the Essentials Expansion and not PlaceholderAPI itself.
