### ISSUE TITLE
Vault Placeholders issue

### ISSUE THREAD

**Issue by Dimitryyyy** [PlaceholderAPI/PlaceholderAPI#565]
Bug Report

Issue
In the scoreboard, the %vault_rank% or the other vault placeholders doesnt work. So i dont know why, because i tried at the TAB, and doesnt work there too. So the vault placeholders doesnt work.. Here is an IMG: [click here](https://i.imgur.com/KVuP3TA.png)

Expected behaviour
Help me. :DD | Sorry for the language. The "Rangod" means Your Rank.

Actual behaviour
I dont know why is this happened.

How to reproduce
I'm just refresh the server version 1.8 to 1.8.8.

`/papi dump` output
https://paste.helpch.at/tunizuhivi

**Comment by Andre601** [comment]
If you continue to post empty issues will we block you from this repository

**Comment by Dimitryyyy** [comment]
Hello! Sorry for this, but i dont know how to use the template. Now is good.
