### ISSUE TITLE
Update RGB to parse &#rrggbb in addition to &x&r&r&g&g&b&b

### ISSUE THREAD

**Issue by Stixil** [PlaceholderAPI/PlaceholderAPI#573]
### Type

- [x] New function for PlaceholderAPI.  
A new function that developers could use.
- [x] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Description

Suggestion to include the ability for PAPI to parse RGB color codes in the &#rrggbb format as it is becoming increasingly more popular with other plugins. Currently users have to create multiple versions of their RGB colors to parse in PAPI and parse in other plugins. If PAPI was able to parse both formats, this would solve much headache and allow a single format to work across all plugins which support PAPI and/or either of these formats for parsing.

![image](https://user-images.githubusercontent.com/53889383/107991156-05f20980-6fa4-11eb-937f-4c72c221175a.png)
![image](https://user-images.githubusercontent.com/53889383/107991185-12766200-6fa4-11eb-9c3d-c039a2e80411.png)

The value for displayname is &#f426caO&#ff4176w&#ff9230n&#e2d128e&#93ff85r&f
The value for displayname-papi is &x&f&4&2&6&c&aO&x&f&f&4&1&7&6w&x&f&f&9&2&3&0n&x&e&2&d&1&2&8e&x&9&3&f&f&8&5r&f

**Comment by Andre601** [comment]
The biggest issue I see here is to actually implement a system everyone is okay to use or support.
While `&#rrggbb` is supported by the BungeeCord ChatColor API, is it for once only a shortcut to `&x&r&r&g&g&b&b` and next also not used or liked by everyone, including devs. A lot of different (well-known) devs think that it isn't a good format to use and support.

There are already different variations for the Hex colour. For example `&rrggbb&` which is used by a Fork of ServerListPlus or the MiniMessage format used in plugins such as MiniMOTD.

Supporting this colour, while easy, could bring unwanted side effects to a lot of expansions and plugins.

In my personal opinion is the fact that PAPI is handling colours when parsing Placeholders not a good approach as it either can cause unwanted side-effects (Accidentally turn `&a` in `Example&and&stuff` into `§a`, where `&` is used for options or similar) or just make the result look different than what it should be.

We, of course, will look into this and discuss it too, but there isn't a guarantee for any changes being made here.

**Comment by Stixil** [comment]
Thanks for the quick response! The format is certainly a contentious issue, and I've heard arguments for and against both, so I'm not trying to say which is better than the other.

One solution is, like you said, to not have PAPI handle the colors at all, and instead for them to be pulled before the placeholder (something like &#rrggbbThis is text), however for something like multicolored text using RGB, the placeholder itself would need to be able to support the RGB codes inside of it, and do it concisely. 

PAPI already does support the basic color parsings like &a, &b, &c, etc, so this addition would only allow more options for the end-user to parse their own placeholders. The example I included above is a good example of the issue which is data for a multi-colored RGB display name in both formats, designated for specific plugins. Here is the example of how PAPI already handles the `Example&and&stuff` text.

![image](https://user-images.githubusercontent.com/53889383/107998541-63418700-6fb3-11eb-9e19-086bcd92068a.png)

Perhaps a good solution would be to have the different parsing options togglable in the config? Two boolean values for whether each will parse, one for each? This would be a good way to avoid unwanted side effects, however I cannot think of a single example of a side effect that implementing the &#rrggbb parsing method would cause that is not already present in PAPI with standard color codes.

**Comment by Andre601** [comment]
An actual config option would indeed be good.
But instead of a boolean, perhaps have a String or Integer option, where you can select the option to use (i.e. the color formatter or something).

That sure is something that needs discussing in the team and I can't tell, if that will even be worked on for v2 of PAPI or perhaps become a part of v3 to solve...

**Comment by Stixil** [comment]
Config option would be great! I like your idea there for it.

I hope y'all are able to make something like that happen, thanks!

**Comment by Andre601** [comment]
Some smaller update:
From my first testing does it seem like, that a simple switch from the org.bukkit ChatColor to that of md_5 won't be all to support Hex colors (The method used by ChatColor to allow & seems to not recognize or support the &#<hex> format despite it having a `of` method which does support it)

So a bit more work is required. Worst case would be us requiring to write our own ChatColor class to support hex colors...

**Comment by Stixil** [comment]
Thanks for the update! I think a replace could be a fairly elegant solution?

**Comment by Andre601** [comment]
I created a PR implementing a basic system to work with the format.
While I did some basic testing is it obviously not guaranteed to work perfectly. You can find a download link to the Jar in the PR.

#575

**Comment by Stixil** [comment]
Fantastic! I'll give it some testing, thanks!

**Comment by Stixil** [comment]
Update:
Did just a bit of testing with the format. I used the Pinger placeholder %pinger_isonline_<server>:<port>% with a dummy IP (0.0.0.0) and used `&#ff99b1Offline` in the config to test the parsing.

`pinger:
    offline: '&xff99b1Offline'`

The first line is from running `papi parse me &#ff99b1Offline`. It works perfectly as expected.
The second line is running `papi parse me %pinger_isonline_0.0.0.0%`. I tried this with other placeholders as well (LuckPerms, Vault) and found the same result.

![image](https://user-images.githubusercontent.com/53889383/108269432-f9a0b480-713b-11eb-9219-fd4b8d0fef53.png)

This second test is from using `&x` instead of `&#`. The results are quite unusual.
The first line is from running `papi parse me &xff99b1Offline`.
The second line is running `papi parse me %pinger_isonline_0.0.0.0%`.

![image](https://user-images.githubusercontent.com/53889383/108270002-ce6a9500-713c-11eb-9844-3ac24fe94150.png)

**Comment by Andre601** [comment]
I expected this to happen...
While there is a check for whether the letter is supported (Is a valid Hex value) is this probably a case where it skips this or something...

I barely have any knowledge about how the system works that PAPI uses, so I'll need someone else to assist in fixing this.

As for your test with the placeholder: I believe that the system used for the placeholder parsing is first translating the colors and THEN parsing the Strings after that, which at least causes the first case... There could of course be another reason (i.e. the parser not recognising `#` as character).

This needs a lot more testing from the looks of it, so thanks for finding those issues.

**Comment by Stixil** [comment]
Sure thing, thanks for all the work on this!

**Comment by Andre601** [comment]
I'm closing this because in a future release will PlaceholderAPI no longer parse colors when using the `setPlaceholders` methods.

It shouldn't be the job of a Placeholder Util to also parse colors and if people want that in their expansions should it be added by them.

If anything changes on this topic will I inform you here about this.

**Comment by BurkenDev** [comment]
This is weird since it's been working why disable it. Everyone is using &#xxxxxx hex rgb colors and that is the standard. Bring it back or include an extension for it by default.

**Comment by Andre601** [comment]
> This is weird since it's been working why disable it. Everyone is using &#xxxxxx hex rgb colors and that is the standard. Bring it back or include an extension for it by default.

That is actually not the case.
Colors have not worked reliably on PlaceholderAPI in the past. There have always been cases where it didn't work.
Also, I mentioned it before and mention it again: PlaceholderAPI's core feature is to be a placeholder parsing Util. Anything that goes beyond that is out of scope for it. And parsing of color codes is also such a case.

Finally, `&#rrggbb` is no standard whatsoever for multiple reasons. First of all is it a format Spigot just decided to do, which is not optimal here. Next is the use of `&` no standard, given that plugins explicitly have to set it as an alternative color code to parse. If it was standard, then Spigot would parse it by default, but that isn't the case, only `§` is parsed by default which is Minecraft's legacy color format (keyword here is "legacy").

There are countless alternatives of color codes and formats. Just to name a few:

- MineDown with weird formats like `&gold&text` and `&#abcdef&text`
- MiniMessage with `<gold>text` and `<#abcdef>text`
- CMI with `{#abcdef}text`

So there certainly isn't a standard by itself. I personally consider MiniMessage a standard as more and more plugins adobt it as a format.

Either way, Color parsing is not in scope for PlaceholderAPI, which focuses on placeholder parsing and nothing else.
