### ISSUE TITLE
Placeholder to check if item inhand needs repair

### ISSUE THREAD

**Issue by Bloodlex** [PlaceholderAPI/PlaceholderAPI#577]
## Feature Request
Placeholder to check if item inhand needs repair

### Type

- [X ] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Description
Placeholder to check if item inhand needs repair

**Comment by Andre601** [comment]
[repo]: https://github.com/PlaceholderAPI/CheckItem-Expansion

The issue tracker is reserved for feature requests towards PlaceholderAPI.
Your request fits more in the [CheckItems Expansion-Repository][repo]

**Comment by Bloodlex** [comment]
Thanks, I've reported it there instead.
