### ISSUE TITLE
Plugin not saving expansions

### ISSUE THREAD

**Issue by NotEnergy** [PlaceholderAPI/PlaceholderAPI#578]
Okay so I use minehut (because im poor lol) and whenever i do /papi ecloud download server, and downloading everything i need out of the ecloud, i do /papi reload and everything works fine until i restart the server. After I restart the server it makes me have to do /papi ecloud download whatever stuff again.

Sorry for sloppy wording I usually dont write issues for any plugins.

**Comment by Andre601** [comment]
Don't use MineHut.
I wouldn't be surprised if it blocks connections to the ecloud.
