### ISSUE TITLE
List in /papi ecloud list installed is bugged

### ISSUE THREAD

**Issue by Andre601** [PlaceholderAPI/PlaceholderAPI#58]
When running `/papi ecloud list installed` then the shown expansions have wrong numbers.

The first one has the number 2, the second one number 3 and so on.

Screenshot:
![image](https://user-images.githubusercontent.com/11576465/49049454-54f2cf00-f1df-11e8-96d4-b119d95b50ba.png)

**Comment by Sxtanna** [comment]
That's probably my fault... lol...

**Comment by Andre601** [comment]
Will something be done?

**Comment by Andre601** [comment]
Seems like this issue no longer exists...
Could've been a issue related to a expansion that was installed.
Anyway it works for latest paper spigot for 1.12.2 and 1.13.2, so it seems it was a random bug.
