### ISSUE TITLE
Keybind Placeholder Expansion

### ISSUE THREAD

**Issue by ellaira-ash** [PlaceholderAPI/PlaceholderAPI#581]
### Type

- [X] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Description
I would like to suggest an expansion with adds placeholders for user keybinds, in case someone has a different sprint key, crouch key, etc. Unfortunately I am not experienced enough to suggest how this may be done. I mentioned this idea in the Discord server and was told to post it here by a staff member.

**Comment by Andre601** [comment]
I can imagine this to be doable, but probs requires some work, especially for all the possible keybinds.

I myself will look into this and see what can be made.
