### ISSUE TITLE
Built in support for signs

### ISSUE THREAD

**Issue by mmoomocow** [PlaceholderAPI/PlaceholderAPI#589]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

New API feature

### Description

Add support for using placeholders on signs. Currently, you have to do this with other plugins that often don't work fully. adding this is something that lots of players can/will use

### Code Example

N/A (i don't java)

### Jar file

N/A

### Additional Information

should be some level of support for large placeholders that you cant usually type/paste into signs

**Comment by Andre601** [comment]
PAPI is for handling placeholders only.
Stuff like handling chat, tab list, scoreboards, signs, etc. is out of scope for it.
It's the job of other plugins to handle those.
