### ISSUE TITLE
Mohist 1.16.5 Papi don't work

### ISSUE THREAD

**Issue by WareZ57** [PlaceholderAPI/PlaceholderAPI#592]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

Plugin/Server Incompatability

### What happens?

Using Mohist server 1.16.5-414 Trying download expansions /papi ecloud but is don't work and get error in console

### Expected Behaviour

Download expansions

### How to Reproduce

/papi ecloud download statz (or other) = error console

### `/papi dump` Output

https://paste.helpch.at/nataqadike

### Errors

https://paste.helpch.at/ayubohedub.sql

### Additional Info

Mohist 1.16.5-414 //  PlaceHolderAPI Lasted version

**Comment by Andre601** [comment]
Hey there.
Did you try it with the latest dev build of PAPI?
We made some fixes to the expansion loading there.

**Comment by darbyjack** [comment]
I tested this with the latest build and while there is an error, it's not the one you got and I can download the expansions fine and use them. Also keep in mind that we don't actively support non-regular subsets of Bukkit.

**Comment by WareZ57** [comment]
i try with lasted mohist & lasted build PlaceHolderAPI (122) don't work anymore 

https://haste.mohistmc.com/iveyazopik.sql

**Comment by darbyjack** [comment]
Using Mohist 1.16.5 (434), the plugin loads fine. 

https://paste.helpch.at/axajevigut.md

As I stated before, Mohist changes how they do class loading and it won't surprise me if it breaks something in PlaceholderAPI. I'll also repeat myself in saying that we don't claim to support Mohist. It is a hybrid and the plugin is therefore given as-in working or not.
