### ISSUE TITLE
Formatted %player_world%

### ISSUE THREAD

**Issue by Ari-RERA-43** [PlaceholderAPI/PlaceholderAPI#603]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

New API feature

### Description

There is currently a placeholder called %player_world%. There should also be a Placeholder that shows the world formatted such as making "world" "Overworld" and "world_nether" The Nether. This could also be accomplished by changing the world file's name but a separate placeholder would allow the user to have spaces and other formatting. This would be useful for showing the player their current world in a way that makes more sense if they don't know how the files are organized. 

### Jar file

N/A

**Comment by Andre601** [comment]
> - [x] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

This is a placeholder request which should be made towards the Player expansion and not this repository.
