### ISSUE TITLE
WARN: failed to download expansion information

### ISSUE THREAD

**Issue by Drynael** [PlaceholderAPI/PlaceholderAPI#605]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

Plugin Bug

### What happens?

While Starting after Loading the Plugin i get the Warning

### Expected Behaviour

No Warning

### How to Reproduce

1. Start server
2. Wait

or

1. /papi ecloud refresh

### `/papi dump` Output

https://paste.helpch.at/kukogeduqa

### Console Log

https://paste.helpch.at/zosuxuzamo.md

### Errors

https://paste.helpch.at/jayaxuyabi.pl

**Comment by darbyjack** [comment]
Seems like you might be blocking outbound requests / can't actually ping the eCloud in your network.

**Comment by Drynael** [comment]
> Seems like you might be blocking outbound requests / can't actually ping the eCloud in your network.

where can i find the IP from the eCloud Server?

> Did you try using the latest development builds?

I did try [PlaceholderAPI] Loading PlaceholderAPI v2.10.10-DEV-122 same issue

**Comment by darbyjack** [comment]
In-game it connects to http://api.extendedclip.com/v2/

**Comment by Drynael** [comment]
Alright, Sophos IPS/Web Filter has blocked the request:

Web filter
log_type="Content Filtering"
log_subtype="Denied"
category="Download Freeware & Shareware" 
url="http://api.extendedclip.com/v2/" 
domain="api.extendedclip.com" 
activity_name="Risky Downloads" 

I created an Exception and now everything is working.

**Comment by Andre601** [comment]
Closing this as it was fixed according to you Drynael
