### ISSUE TITLE
Plugins using PlaceholderAPI

### ISSUE THREAD

**Issue by Angeschossen** [PlaceholderAPI/PlaceholderAPI#617]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

New config option

### Description

"If your plugin isn't shown here and you want it to be added, open an issue and we will add it!"

**Provides own placeholders:** https://github.com/Angeschossen/Lands/wiki/PlaceholderAPI-Placeholders#placeholders
https://www.spigotmc.org/resources/53313

Thank you!

**Comment by Andre601** [comment]
I've gone ahead and now added it to the wiki.
You can find it [here](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#lands) and [here](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI). If any of the information is wrong, feel free to submit a Pull request to correct it.
