### ISSUE TITLE
New %bungee_total_<servername>% placeholder

### ISSUE THREAD

**Issue by StiegeRobin** [PlaceholderAPI/PlaceholderAPI#62]
We already have placeholders for total players on the whole network and the online players on one server. It'd be nice if you can add one more placeholder (%bungee_total_<servername>%) to display max. players from given server.

**Comment by darbyjack** [comment]
Are you referring to %bungee_<server name>%?

**Comment by darbyjack** [comment]
Why can't you just use `%server_max_players%`?

**Comment by Andre601** [comment]
The issue with `%server_max_players%` is quite obvious in case of a bungee: You only get max players of the server you're on, not of the other ones.
