### ISSUE TITLE
Registering and unregistering placeholders won't work with new players joining

### ISSUE THREAD

**Issue by xdec0de** [PlaceholderAPI/PlaceholderAPI#632]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

API Bug

### What happens?

Placeholders of my expansion work fine the first time when I start the server, but when I restart my expansion with plugman (This makes my expansion to unregister and then register again), placeholders will only work with the players that were online at the moment of the reload, new players joining will have their placeholders returning null

Note: My plugin is not the one causing this, the chat shows that the internal methods of the plugin are working correctly, just not re-registering correctly to placeholderapi

Using /papi parse (New player that joined after reload) %SMPCore_name_town_colored% throws a null pointer exception that is pasted below. But /papi parse me %SMPCore_name_town_colored% works fine

Here are some screenshots of this happening, many of the placeholders of the scoreboard are also from my plugin and they are working correctly (Chunks for example), so this is only happening with new players, and it's not from my plugin as you can see that that names are working correctly on chat but not on tab (Custom chat of my plugin that doesn't use placeholderapi but the tab plugin does): https://imgur.com/a/q2jW4WQ

### Expected Behaviour

New players having their placeholders working normally.

### How to Reproduce

1. Create an internal expansion and register it with PlaceholderExpansion.register();, also, unregister it at onDisable()
2. Reload the expansion with plugman.
3. New players joining the server won't get their placeholders working, but players that were already on the server, yes.

### `/papi dump` Output

https://paste.helpch.at/aquququnad

### Console Log

https://paste.helpch.at/yahagayodo.md

### Errors

https://paste.helpch.at/oyarovanaq.bash

### Additional Info

Code to reproduce the issue: https://paste.helpch.at/usayecosaf.java

**Comment by Andre601** [comment]
I can't see any proof here that PlaceholderAPI is at fault.

The usage of PlugMan and other plugins to reload plugins is discouraged by many developers and the errors you encounter can easily be a cause of PlugMan and not PlaceholderAPI.
Since this only happens AFTER you reloaded the plugin and since the error you shared doesn't point out anything related to PlaceholderAPI (Just Spigot being unable to handle a command for unknown reasons) can we not say that this is really an Error caused by PlaceholderAPI.

If you have any further proof that PAPI indeed causes this, let us know. But for know is this issue not caused by PAPI in any shape or form.

**Comment by xdec0de** [comment]
Well the proof is that everything on my plugin including commands and current player placeholders are working but placeholders of new players wont, if developers don't like plugman is just because they don't like to add support to it, when it's easily handled (I mean, my plugin has a town system with claims that are stored on ram and nothing goes wrong, you just have to take in count that online players might be on the server while enabling...), anyways, I understand that plugins like ProtocolLib can't support reloading, on heavy protocol plugins like that one it's normal, but PlaceholderAPI should be able to support plugman, nothing is stopping it from doing it as far as I know, I mean, it's just a plugin for placeholders, also, it had support for plugman before the api changes on 2.10.7, this error might be caused by the "new" expansion update not registering and unregistering correctly if the server is running / players are online.
