### ISSUE TITLE
Adventure/MiniMessage Support

### ISSUE THREAD

**Issue by NickNackGus** [PlaceholderAPI/PlaceholderAPI#636]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

New API feature

### Description

I would like to see Adventure/MiniMessage placeholder support for Placeholder API.

Mojang is moving away from legacy section symbol formatting and focusing on raw json text instead. Paper and other servers are now offering Adventure as a replacement, and since editing json messages isn't for everyone, MiniMessage is becoming a new standard for messages.

While MiniMessage has a placeholder system, it has no API for plugins to exchange placeholders. I feel PlaceholderAPI is well positioned to make transitioning away from legacy formatting and towards Adventure's implementation of raw json text easier for server owners, with older plugins' placeholders being converted by Placeholder API when using the newer format.

https://docs.adventure.kyori.net/minimessage.html#placeholder

**Comment by Andre601** [comment]
This is planned for v3
