### ISSUE TITLE
Task #499

### ISSUE THREAD

**Issue by Minigunbryson** [PlaceholderAPI/PlaceholderAPI#638]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

Plugin Bug

### What happens?

I tried to do /ecloud download Vault

### Expected Behaviour

won't download anything

### How to Reproduce

anything

### `/papi dump` Output

https://paste.helpch.at/yikakitiye

### Console Log

https://paste.helpch.at/usabawimob.bash

### Errors

https://paste.helpch.at/usabawimob.bash

### Additional Info

Nope

**Comment by Andre601** [comment]
Did you try thelatest dev build?

**Comment by Andre601** [comment]
Closing this as there was no response within a month. If this is still a prominent issue, let us know so that we can re-open this.
