### ISSUE TITLE
"5 installed expansions have updates avalible" Wheres the update command?

### ISSUE THREAD

**Issue by FrozenBeard** [PlaceholderAPI/PlaceholderAPI#64]
This ecloud is almost like apt-get in the debian environment, except I cant list what expansions need updating or any way to quickly update them. We are all used to `apt-get update && apt-get upgrade`

Can I suggest we have `/papi ecloud upgrade` that will auto download the updates for the modules.

**Comment by Andre601** [comment]
This would be an idea.
At the moment can you update the expansions normally with the same command, that you use, to download the (`apt-ge` uhm... I mean `/papi ecloud download <expansion>`).

It's finally up to the maintainer of the wiki (Clip and Glare) to deside, if that's an idea.
I myself give this idea a thumbsup.

**Comment by FrozenBeard** [comment]
Alright, do I need to restart the server after this? An upgrade would be nice to do them all in one go and not need to type them all out.

**Comment by Andre601** [comment]
You just have to reload the plugin after that with `/papi reload`

**Comment by LemmoTresto** [comment]
apt-get is deprecated use apt instead which is also faster

**Comment by FrozenBeard** [comment]
@LemmoTresto holy crap, had no idea. Been using apt-get for, what 10 years? Haha if I've been using apt-get this entire time can I just move to using apt?

**Comment by LemmoTresto** [comment]
@FrozenBeard yea you can move to apt fine

**Comment by Peng1104** [comment]
@FrozenBeard I think that would be usefull if this new feature could be activated or disabled on the config.yml so the people that dont want to auto update the expansions could disable this (default activated)

**Comment by Andre601** [comment]
This wouldn't be a auto update thing. It would still require a manual input from the player/console.

**Comment by Peng1104** [comment]
I think that if they are creating a update system they could make this automatic, everytime the plugin starts it would update the installed expansions

**Comment by darbyjack** [comment]
Auto update is a bad idea. Someone might release an update for a plug-in you don't have yet and then it breaks.

**Comment by FrozenBeard** [comment]
No auto updates, keep it manual but give us the option to at least do the lot at once.
