### ISSUE TITLE
Statz and Autorank expansions not working

### ISSUE THREAD

**Issue by Xendrae** [PlaceholderAPI/PlaceholderAPI#65]
I am running Spigot 1.12.2 with PAPI 2.9.2.  I am currently using the EssentialsX and Towny expansions without issue. I installed the Statz and AutoRank expansions today in an attempt to use the %statz_mobs_killed_husk% as well as the %autorank_current_rank% placeholders in DeluxeMenus. However, when using these placeholders in DeluxeMenus they did not return anything so I attempted the parse command.  When using both of these placeholders in the parse command, they don't return anything other than exactly what I type (if I put %statz_mobs_killed_husk% it returned "%statz_mobs_killed_husk%"). I was unsuccessful in getting any placeholders from Statz or Autorank to successfully work, with over half of the Statz ones returning an internal exception error.

Note: I did reload PAPI as well as deluxemenus, and I restarted the entire server numerous times.

**Comment by Xendrae** [comment]
Additional info: I am using AutoRank 4.2.5 (latest stable release for 1.12.2) and Statz 1.5.2 (latest stable release for 1.12.2).

**Comment by Andre601** [comment]
Did you try the names in Uppercase?

**Comment by Andre601** [comment]
Also please provide any errors through https://paste.helpch.at

**Comment by Xendrae** [comment]
Changing case does not seem to impact the results.  The error that occurs when trying %statz_mobs_killed% is here: https://paste.helpch.at/ajorapejeg.cs 

This does not occur when typing %statz_mobs_killed_husk% or any other mob name.

**Comment by Xendrae** [comment]
Any updates or ideas on how to resolve this?

**Comment by Andre601** [comment]
Any updates on this issue @Xendrae ?

**Comment by Andre601** [comment]
Closed due to no response from author within 3 days.

**Comment by Xendrae** [comment]
The problem is obviously ongoing and I was hoping for someone to provide a solution.

As I stated, I had the required plugins installed and I also included the version numbers. I also explained that the issue was systemic with the entirety of statz and autorank expansions, including a pastebin log of what was happening.

**Comment by Andre601** [comment]
The error you provided returned a `NoClassDefFoundError` which means that PlaceholderAPI couldn't find a required path/option in the statz-plugin.
And there are only two possible options for when that would happen:
1. The plugin isn't installed or enabled on the server.
2. The plugin had an update, which changed some API stuff, causing the expansion to break.

Your mentioned case is most likely a missing option in the plugin.

Also, you only provided the error for Statz. does the AutoRank-expansion cause a similar error?

**Comment by aBo0oDyy** [comment]
Hey @Xendrae,
Statz expansion has gotten a huge update recently, have you tried it?
And for AutoRank, you haven't provided any errors yet...

Issue will be closed in the next few days if we haven't heard a reply from you.
