### ISSUE TITLE
Vault v1.7.3 not a depend, softdepend or loadbefore of this plugin - startup WARN.

### ISSUE THREAD

**Issue by andrewkm** [PlaceholderAPI/PlaceholderAPI#675]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

Plugin Bug

### What happens?

`[08:46:45] [Server thread/WARN]: [PlaceholderAPI] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER} which is not a depend, softdepend or loadbefore of this plugin.`

### Expected Behaviour

N/A

### How to Reproduce

N/A

### `/papi dump` Output

N/A

**Comment by iGabyTM** [comment]
This is just a warning, you can ignore it.

**Comment by andrewkm** [comment]
I'm aware, but can't we get rid of it by adding the depends?

**Comment by PiggyPiglet** [comment]
You can temporarily get rid of it by adding the plugin as a depends to papi’s plugin.yml, a permanent fix is being worked on.

**Comment by andrewkm** [comment]
Thanks. :)
