### ISSUE TITLE
PAPI not registering expansions

### ISSUE THREAD

**Issue by PapaWulf-Lunar** [PlaceholderAPI/PlaceholderAPI#678]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

Plugin/Server Incompatability

### What happens?

When trying to simply install expansion. I only get the confirmation saying to reload ecloud.

Say I do /papi ecloud download Vault
It will say "Success now use /papi reload"
I use /papi reload, then there's no output, no text, nothing just air

The expansion is clearly installed in my /plugins/placeholderapi/expansions but it is not being registered.

### Expected Behaviour

PlaceholderAPI would usually install the expansion successfully and I would be happy

### How to Reproduce

Say I do /papi ecloud download Vault
It will say "Success now use /papi reload"
I use /papi reload, then there's no output, no text, nothing just air

### `/papi dump` Output

https://paste.helpch.at/eloqubasur

### Console Log

https://paste.helpch.at/wonavuhayo.md

**Comment by Starmism** [comment]
Try removing the Quests expansion, looks like it is blocking your progress. Your server log is not very long, so I couldn't tell if that exception stops PAPI from loading the rest of the expansions or if you stopped the server very quickly afterwards.

**Comment by Andre601** [comment]
I would also suggest removing the Quest expansion/plugin as it seems to lack stuff

**Comment by PapaWulf-Lunar** [comment]
> Try removing the Quests expansion, looks like it is blocking your progress. Your server log is not very long, so I couldn't tell if that exception stops PAPI from loading the rest of the expansions or if you stopped the server very quickly afterwards.

Many thanks, that worked! I saw that and ignored it, as I thought 1 plugin wouldn't be causing so much damage

**Comment by Andre601** [comment]
On another note here: One plugin, namely factionboosters, is trying to register an expansion using deprecated methods. You should try contacting the dev of the plugin and let them know about this and that they should update to the PlaceholderExpansion system
