### ISSUE TITLE
Adding my Plugin ZCoins

### ISSUE THREAD

**Issue by Zukinis** [PlaceholderAPI/PlaceholderAPI#681]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

New API feature

### Description

It would be extremely kind if you could add my plugin ZCoins as a placeholder. The coins can be stored in the given MySQL database. What would you need to add it

### Jar file

N/A

**Comment by Andre601** [comment]
Could you elaborate your request a bit more?
Do you already offer placeholders or do you want an expansion to be made?
If it is the second one do we have to say that the issue tracker is not the place to request expansions to be made.

**Comment by Starmism** [comment]
Submit a PR if you want additions to the wiki.
