### ISSUE TITLE
Error failed to load class files of expansions

### ISSUE THREAD

**Issue by n54b** [PlaceholderAPI/PlaceholderAPI#682]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

Plugin Bug

### What happens?

Expension player cannot work when i use 
Papi ecloud download Player
and papi reload
i have a error.

### Expected Behaviour

Placeholder don't work

### How to Reproduce

Use the latest version au PAPI
try to install expension : Player
And look the console

### `/papi dump` Output

https://paste.helpch.at/hiduniqegi

### Errors

https://paste.helpch.at/olomagufeq.sql

**Comment by Andre601** [comment]
The error is not about the player expansion.
It does mention a NoClassDefFoundException related to net/chimpgamer/networkmanager, so it's an issue with NetworkManager.
