### ISSUE TITLE
Could not load 'plugins\PlaceholderAPI-2.10.10.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by crqch** [PlaceholderAPI/PlaceholderAPI#686]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

Plugin Bug

### What happens?

On loading all plugins, the PAPI occurs an error:
[14:03:27 ERROR]: Could not load 'plugins\PlaceholderAPI-2.10.10.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bstats/charts/CustomChart

Full error message:
https://paste.helpch.at/roxurofawu.sql

### Expected Behaviour

Plugin should load

### How to Reproduce

1. Start a server on version spigot-1.8.8-R0.1-SNAPSHOT-latest.
2. Put PlaceholderAPI-2.10.10 in your server/plugins folder
3. Try reloading/restarting the server
4. Error occurs

### `/papi dump` Output

N/A

### Errors

https://paste.helpch.at/roxurofawu.sql

**Comment by Andre601** [comment]
Make sure you actually use latest 1.8 release and not a modified Spigot fork.

**Comment by crqch** [comment]
What does modified Spigot fork even mean?
This is official release of spigot as seen here https://getbukkit.org/download/spigot

**Comment by PiggyPiglet** [comment]
> What does modified Spigot fork even mean?
> This is official release of spigot as seen here https://getbukkit.org/download/spigot

technically that's not the official release, you can only officially get spigot via buildtools. However that build shouldn't be causing any issues

**Comment by Andre601** [comment]
> What does modified Spigot fork even mean?
> This is official release of spigot as seen here https://getbukkit.org/download/spigot

This is not an official release. As Piggy mentioned does Spigot only offer downloads through their BuildTools and sites such as getBukkit are not part of them, nor do Spigot staff support downloading jars from there.
In fact, what getBukkit does is going against Mojangs terms as the redistribution of modified jars, which Spigot is, is not allowed.

**Comment by crqch** [comment]
> > What does modified Spigot fork even mean?
> > This is official release of spigot as seen here https://getbukkit.org/download/spigot
> 
> This is not an official release. As Piggy mentioned does Spigot only offer downloads through their BuildTools and sites such as getBukkit are not part of them, nor do Spigot staff support downloading jars from there.
> In fact, what getBukkit does is going against Mojangs terms as the redistribution of modified jars, which Spigot is, is not allowed.

I understand now, but in my opinion it should work anyways because the first result in google search is site getbukkit.org, not buildtools from spigotmc, and normal user prefer downloading the server from the site in matter of seconds, not waiting for the cmd prompt to finally finish its work building the spigot.
 
And even after running the server on spigot from the buildtools, the error seems to be happening again.
( https://paste.helpch.at/ivejekevul.sql )

**Comment by Andre601** [comment]
I suggest to you to use [PaperMC](https://papermc.io)
It's a drop-in replacement of Spigot, improves performance and you can actually download jars without the need of build tools.

**Comment by Andre601** [comment]
Also, Placeholder API does relocate BStats into its own classpath which means it should be provided with PlaceholderAPI itself and work without any issues here.
https://github.com/PlaceholderAPI/PlaceholderAPI/blob/6348c88c6f4367679fdd3042c4467f386a34d6df/build.gradle#L66

The error itself doesn't even point to any classes within PlaceholderAPI, so I honestly doubt that PlaceholderAPI is at fault here and instead something else messes stuff up.

Could you please share your startup log with us so that we can investigate? Also, please try out the latest development build to see if this fixes the issue.

**Comment by Starmism** [comment]
Stale issue. No response from Author.
