### ISSUE TITLE
PlotSquared placeholders cause PAPI to break

### ISSUE THREAD

**Issue by Guddina-tim** [PlaceholderAPI/PlaceholderAPI#69]
### Issue
> What is the issue? Describe it like you would tell a friend.

I'm running the latest jenkins build of PAPI and the latest public release of PlotSquared. I downloaded the PlotSquared placeholders using the command as shown in the documentation. However, the placeholders don't show the data, and when I run /papi after installing the expansion PAPI itself gets disabled and I get an error:

`30.01 20:57:46 [Server] ERROR null
30.01 20:57:46 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'papi' in plugin PlaceholderAPI v2.9.2-DEV-59 - plugin is disabled.
30.01 20:57:46 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[patched_1.13.2.jar:git-Paper-509]
30.01 20:57:46 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-509]
30.01 20:57:46 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-509]
30.01 20:57:46 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1796) ~[patched_1.13.2.jar:git-Paper-509]
30.01 20:57:46 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1604) ~[patched_1.13.2.jar:git-Paper-509]
30.01 20:57:46 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-509]
30.01 20:57:46 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-509]
30.01 20:57:46 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-509]
30.01 20:57:46 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_141]
30.01 20:57:46 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_141]
30.01 20:57:46 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-509]
30.01 20:57:46 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-509]
30.01 20:57:46 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-509]
30.01 20:57:46 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-509]
30.01 20:57:46 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-509]
30.01 20:57:46 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]`

I fix this by stopping the server, deleting the PlotSquared expansion, and restarting the server. After that, all other placeholders work again.

### Expected behaviour
> What should PlaceholderAPI do?

It should install the PlotSquared placeholder expansion and display the data.

### Actual behaviour
> What does PlaceholderAPI actually do?

It disables itself.

### How to reproduce
> What steps did you made, to get this bug?

1. Install PlotSquared and PAPI
2. Run the command: /papi ecloud download PlotSquared
3. Put any PlotSquared placeholder somewhere to be displayed.
4. Run /papi

**Comment by Andre601** [comment]
The latest Plotsquared release had breaking API-changes.
Since the expansion is still using the old API,it breaks.

At the moment can we not fix this issue, since the main maintainer of the expansion (Clip) is busy with real life stuff.
You could however ask the devs of Plotsquared, if they don't want to make a own expansion, which would have some benefits.

**Comment by Andre601** [comment]
[IntellectualSites/PlotSquared-Expansion]: https://github.com/IntellectualSites/PlotSquared-Expansion
[release page]: https://github.com/IntellectualSites/PlotSquared-Expansion/releases

There is now a new expansion that you can use.
You can get it from the [IntellectualSites/PlotSquared-Expansion] repository (from their [release page]).
According to the readme is this page also backwards compatible with the old API.
