### ISSUE TITLE
java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.MinecraftServer

### ISSUE THREAD

**Issue by LucidAPs** [PlaceholderAPI/PlaceholderAPI#690]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

API Bug

### What happens?

Console Error on startup
https://nekobin.com/zesixuwece

### Expected Behaviour

No errors

### How to Reproduce

I am not sure

### `/papi dump` Output

https://paste.helpch.at/afijeholey

**Comment by PiggyPiglet** [comment]
Your server expansion is outdated.

**Comment by LucidAPs** [comment]
> Your server expansion is outdated.

What is the best way to update them? Should I just delete them and use papi ecloud download?

**Comment by darbyjack** [comment]
That works fine.
