### ISSUE TITLE
Placholder API unregistered channel Paper Spigot

### ISSUE THREAD

**Issue by dimitriscr** [PlaceholderAPI/PlaceholderAPI#691]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

Plugin Bug

### What happens?

Every minute or so, the plugin outputs this in the console (Moved to Errors)

### Expected Behaviour

It should probably not output that?

### How to Reproduce

have a paper spigot server that is part of a waterfall proxy and tun Placeholder API. I also use chat control pro for managing chats. THe last point seems relevent with the org.bukkit.plugin.messaging.ChannelNotRegisteredException error

### `/papi dump` Output

https://paste.helpch.at/vamugifuvo

### Errors

https://paste.helpch.at/oqinunapar.md

**Comment by Andre601** [comment]
You're using the BungeeCord expansion while your server seems to not have BungeeCord enabled

**Comment by dimitriscr** [comment]
I am using watefall, the paper branch of bungeecord, and the server is properly set up with it. As for the double expensions I will try deleting the doubles

**Comment by dimitriscr** [comment]
Removing the doubles seems to have gotten rid of the error messages, thanks for the help
