### ISSUE TITLE
PlaceholderAPI failed to load class files or expansions

### ISSUE THREAD

**Issue by hadouken-a** [PlaceholderAPI/PlaceholderAPI#695]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

API Bug

### What happens?

I want to download default placeholders with /papi ecloud download Server and /papi reload
I receive an error in console (screenshot below)

![129531032-afa19d20-9a6e-477f-bd09-32417116638a](https://user-images.githubusercontent.com/70557914/129758886-2faf0b02-47bd-4077-9a97-fcba96d044bc.jpeg)

### Expected Behaviour

Completly download extension

### How to Reproduce

1. /papi ecloud download *random extension*
2. /papi reload

### `/papi dump` Output

https://paste.helpch.at/toxacaqico

### Console Log

https://paste.helpch.at/ojuvivejaf.md

### Errors

https://paste.helpch.at/hariqekolu.sql

### Additional Info

Java version - 16.0
Plugin version - latest on spigot
Server version - 1.16.5

**Comment by Andre601** [comment]
This is an issue with the townyadvanced expansion.
