### ISSUE TITLE
OpEconomy - Hook into PlaceholderAPI

### ISSUE THREAD

**Issue by ThisKarolGajda** [PlaceholderAPI/PlaceholderAPI#709]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

New API feature

### Description

Hello!
I want my plugin on the list of plugins supporting it. 

Plugins using PlaceholderAPI:

- **[OpEconomy](https://www.spigotmc.org/resources/95674)**
  - [x] Supports placeholders.
  - [x] Provides own placeholders. Link

Plugin placeholders:

- ### **[OpEconomy](https://www.spigotmc.org/resources/95674)**
  > NO DOWNLOAD COMMAND
  
  [Description and usage for placeholders](https://github.com/ThisKarolGajda/OpEconomy/wiki/PlaceholderAPI)
  
  ```
  %opeconomy_money_<player_name>% - Gets custom player money
  %opeconomy_money% - Gets money
  %opeconomy_baltop_number_<number>% - Gets player's name
  %opeconomy_baltop_player_position_<player_name>% - Gets player's position
  %opeconomy_currency% - Shows active currency
  %opeconomy_is_active_code_<code>% - Boolean, if code is active
  %opeconomy_max_uses_code_<code>% - Shows max uses for code
  %opeconomy_uses_code_<code>% - Shows uses for code
  %opeconomy_reward_code_<code>% - Shows reward for entering code
  ```

**Comment by Andre601** [comment]
Has been added to the wiki by #713 

Thanks again for your contributions
