### ISSUE TITLE
Console Error Spam

### ISSUE THREAD

**Issue by CamManCraft2001** [PlaceholderAPI/PlaceholderAPI#715]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

API Bug

### What happens?

The server and the PlaceholderAPI plugin works normally, but the console is getting spammed with errors about a Number Format Exception for %statistic_seconds_played%. It's makes it very difficult to read the console and see what is going on.

### Expected Behaviour

For my console not to show the error. For the placeholder to work the way it needs to without spamming my console with errors.

### How to Reproduce

I have the latest PlaceholderAPI plugin (2.10.10). I'm not sure how to reproduce this but it could be something with a downloaded expansion or other plugin(s) on the server.

### `/papi dump` Output

https://paste.helpch.at/ahecukudog

### Console Log

https://paste.helpch.at/sabefixuce.md

### Errors

https://paste.helpch.at/edosaxobow.md

### Additional Info

I have another error spamming in the console for WildTP but I'm focusing on the error that's near the bottom of the latest.log file.

**Comment by BlitzOffline** [comment]
Hello my friend. This has nothing to do with PlaceholderAPI.

It has to do with the Statistic expansion and HoloExtension plugin aka Holographic Placeholders.
My assumption is that you made a leaderboard or at least attempted to make one with the `%statistic_seconds_played%` placeholder and now you don't have the statistic expansion installed anymore. so:
Either install the statistic expansion:
 /papi ecloud download statistic
 /papi reload
Or disable the leaderboard from the Holographic Placeholders plugin.

Gonna close this issue now. Please open a new one in the Statistic Expansion repo if you don't get the install to work.
