### ISSUE TITLE
PLUGIN WARN

### ISSUE THREAD

**Issue by 9dolanla** [PlaceholderAPI/PlaceholderAPI#716]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

API Bug

### What happens?

When i start the server Will show this. I don’t know if this is an error.

### Expected Behaviour

Where is the problem, or ignore this error report

### How to Reproduce

1 PlaceholderAPI 2.10.10 +playerpoints 3.03 + ESSX 2.19.0 
2. 1.17.1 paper 257
3.run server

### `/papi dump` Output

https://paste.helpch.at/bebezuseku

### Console Log

https://paste.helpch.at/silomizaro.md

### Errors

https://pastebin.com/r3Tix1cm

**Comment by Andre601** [comment]
Your issue seems to be related to the server expansion. Please make sure to actually use the latest available version of it.
