### ISSUE TITLE
Plotsquared Placeholder %currentowner% issue

### ISSUE THREAD

**Issue by BlackestSheap** [PlaceholderAPI/PlaceholderAPI#72]
Hello and have a nice day dear dev, 

Linking the Plotsquared Placeholder via PlaceholderAPI the placeholder %currentplot% is showing Alphabet Spaghetti When standing on Roads and unoccupied Plots. 

Example 

Leaving the Plot from Player Minecrafter123 to Roads and Free Plots the Placeholder Outputs a very messy 
Feedback like „rafter123“ until the Player Enters the next occupied Plot. 

Hope you can fix that. 
Greetings,

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Andre601** [comment]
Can you please provide more information?
Like what exact placeholder did you use (there is no `%currentplot%` placeholder.), what version of PlotSquared and PlaceholderAPI and if there are any errors.

**Comment by BlackestSheap** [comment]
>Can you please provide more information? ...

@Andre601 

Using the latest Versions of both Plugins. 

The exact Placeholder is %plotsquared_currentplot_owner%

It seems that the Placeholder is confused with unoccupied Plots / Roads because they have no owner

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Andre601** [comment]
Please read the information in issue #71 about latest version of PlotSquared.
Right now does the expansion not support latest version of PlotSquared, due to API-changes.
If that has changed (or the author(s) of PlotSquared have made an own expansion to use), let me know.

**Comment by Andre601** [comment]
[IntellectualSites/PlotSquared-Expansion]: https://github.com/IntellectualSites/PlotSquared-Expansion
[release page]: https://github.com/IntellectualSites/PlotSquared-Expansion/releases

There is now a new expansion that you can use.
You can get it from the [IntellectualSites/PlotSquared-Expansion] repository (from their [release page]).
According to the readme is this page also backwards compatible with the old API.
