### ISSUE TITLE
Exception Error

### ISSUE THREAD

**Issue by DebuffPvP** [PlaceholderAPI/PlaceholderAPI#720]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

Plugin Bug

### What happens?

It generates an error randomly in console

### Expected Behaviour

It shouldn't generate that error as far as i'm aware

### How to Reproduce

To be honest it's random therefore i don't know

### `/papi dump` Output

https://paste.helpch.at/etofucavum

### Console Log

https://paste.helpch.at/wihalucici.md

### Errors

https://paste.helpch.at/ledocilizi.cs

**Comment by Andre601** [comment]
Issue is Vault expansion
