### ISSUE TITLE
WorldBorder-Expansion

### ISSUE THREAD

**Issue by pixar02** [PlaceholderAPI/PlaceholderAPI#73]
[Request change]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

### Notes
This template is for **requesting additions for the wiki** and not for reporting bugs or requesting changes for the wiki!  

### Type
> What kind of request is this? (Multiple selections possible)

- [x] New expansion providing placeholders.
- [ ] New plugin providing placeholders.
- [ ] New plugin supporting PlaceholderAPI.

### Plugin
> What is the name of the plugin/expansion?

Expansion-WorldBorder

> Provide also a link to it.

https://www.spigotmc.org/resources/worldborder-expansion.57000/
https://api.extendedclip.com/expansions/worldborder/
### Placeholders/others
> What are the new placeholders/Any additional info?

 * %worldborder_size%
 * %worldborder_center_z% 
 * %worldborder_center_x%
 * %worldborder_damage_amount%
 * %worldborder_damage_buffer%
 * %worldborder_warning_time%
* %worldborder_warning_distance%

**Comment by Andre601** [comment]
Added the placeholders.
Thanks for supporting PlaceholderAPI.

**Comment by pixar02** [comment]
I hope I'm not annoying you by saying this, but the WorldBorder expansion doesn't need a plugin. Only Spigot/Craftbukkit

**Comment by Andre601** [comment]
For what exactly is this message now?
Do you refer to the "Plugins using PlaceholderAPI" page?

**Comment by pixar02** [comment]
I would prefer it, yes.

**Comment by Andre601** [comment]
Updated the page
