### ISSUE TITLE
GriefPrevention-Expansion add to Wiki

### ISSUE THREAD

**Issue by pixar02** [PlaceholderAPI/PlaceholderAPI#74]
[Request change]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

### Notes
This template is for **requesting additions for the wiki** and not for reporting bugs or requesting changes for the wiki!  

### Type
> What kind of request is this? (Multiple selections possible)

- [x] New expansion providing placeholders.
- [ ] New plugin providing placeholders.
- [ ] New plugin supporting PlaceholderAPI.

### Plugin
> What is the name of the plugin/expansion?

Expansion-GriefPrevention

> Provide also a link to it.

https://www.spigotmc.org/resources/griefprevention-expansion.44640/
https://api.extendedclip.com/expansions/griefprevention/

### Placeholders/others
> What are the new placeholders/Any additional info?

 * %griefprevention_claims%
 * %griefprevention_claims_formatted%
 * %griefprevention_bonusclaims%
 * %griefprevention_accruedclaims%
 * %griefprevention_accruedclaims_formatted%
 * %griefprevention_remainingclaims%
 * %griefprevention_remainingclaims_formatted%
 * %griefprevention_currentclaim_ownername%

**Comment by Andre601** [comment]
Added placeholders to the wiki.
Thanks for using PlaceholderAPI.
