### ISSUE TITLE
The server doesn't start because of this plugin.

### ISSUE THREAD

**Issue by Prophet2002** [PlaceholderAPI/PlaceholderAPI#751]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

Plugin Bug

### What happens?

The plugin tries to load expansions even if they are not in the server folder and server freezes.

[09:36:06] [Server thread/INFO] [me.clip.placeholderapi.PlaceholderAPIPlugin]: [PlaceholderAPI] Placeholder expansion registration initializing...

### Expected Behaviour

I don't know.

### How to Reproduce

1. Download the plugin.
2. Install the plugin.
3. Start server.

### `/papi dump` Output

what?

### Console Log

https://paste.helpch.at/erotihijur.md

**Comment by Andre601** [comment]
You are using PlaceholderAPI on a modded server.
PlaceholderAPI is a **Spigot** plugin and we do not support modded and hybrid servers, as they come with huge disadvantages. Please read the [PSA from EssentialsX](https://essentialsx.net/do-not-use-mohist.html) regarding this.
