### ISSUE TITLE
Otherplayer gives a crash

### ISSUE THREAD

**Issue by Silent-Program** [PlaceholderAPI/PlaceholderAPI#756]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

API Bug

### What happens?

I am using otherplayer in my deluxechat /msg format.  This is the format `[&6%otherplayer_displayname_%recipient_player_name%%&b]`  And it gives me this error https://paste.helpch.at/cemenawesa.bash

It was working, and I changed my display name and it then stopped working.  I already tried removing nicknames, and setting nicknames.  Neither is working.

### Expected Behaviour

It should get the display name properly, instead it causes an error.

### How to Reproduce

`%otherplayer_displayname_%recipient_player_name%%`

### `/papi dump` Output

https://paste.helpch.at/xanijihatu

### Console Log

https://paste.helpch.at/uhefejoxaw.md

### Errors

https://paste.helpch.at/cemenawesa.bash

**Comment by Silent-Program** [comment]
Not sure if it is a deluxe chat issue or a placeholder API issue.

**Comment by Silent-Program** [comment]
Ahh, yes it appears to be a papi issue.  
```
 at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
        at com.extendedclip.papi.expansion.otherplayer.OtherPlayerExpansion.getDisplayname(OtherPlayerExpansion.java:239) ~[?:?]
        at com.extendedclip.papi.expansion.otherplayer.OtherPlayerExpansion.onRequest(OtherPlayerExpansion.java:109) ~[?:?]
```

**Comment by darbyjack** [comment]
It doesn't look like we maintain that expansion. Feel free to reach out to the developer of the expansion on their SpigotMC page. https://www.spigotmc.org/resources/placeholderapi-otherplayer-expansion.51171/

**Comment by Silent-Program** [comment]
> 

Alright :D

**Comment by Silent-Program** [comment]
> It doesn't look like we maintain that expansion. Feel free to reach out to the developer of the expansion on their SpigotMC page. https://www.spigotmc.org/resources/placeholderapi-otherplayer-expansion.51171/

He does appear to be inactive, last online 17w

**Comment by darbyjack** [comment]
Unfortunately we can't really do anything as we don't maintain it nor have the source.

**Comment by Silent-Program** [comment]
> Unfortunately we can't really do anything as we don't maintain it nor have the source.

Are there any other ways to get the display name of the users?

**Comment by Andre601** [comment]
Not sure how DeluxeChat handles internal/own placeholders compared to PlaceholderAPI ones, but PAPI itself doesn't support `%placeholder%` patterns inside other `%placeholder%` patterns.

**Comment by Silent-Program** [comment]
> Not sure how DeluxeChat handles internal/own placeholders compared to PlaceholderAPI ones, but PAPI itself doesn't support `%placeholder%` patterns inside other `%placeholder%` patterns.

So there is no way to get the display name of a user via a placeholder that gets their name?

**Comment by Andre601** [comment]
One way you could perhaps try (if the otherplayer expansion supports it) could be using `{placeholder}` patterns inside the `%placeholder%`
But for that would you need to use different placeholders instead of `%recipient_player_name%` and I'm not sure if DeluxeChat offers support for bracket placeholders.

Either way, the issue seem to be on the otherplayer expansion and not PlaceholderAPI, so nothing we can do here, nor something for this bug-tracker.

Feel free to open a [Discussion](https://github.com/PlaceholderAPI/PlaceholderAPI/discussions) instead to find possible help, or ask in the [Discord Server](https://discord.gg/helpchat)

**Comment by DalBrar** [comment]
Hi i'm the author of the OtherPlayer expansion. As pointed out, you are trying to use a placeholder inside a placerholder which isnt supported. What ends up happening when u try to use `%otherplayer_displayname_%recipient_player_name%%` is that this gets submitted to the expansion: `%otherplayer_displayname_%` which currently doesn't have any elegant way of catching the misuse of the place holder and expects a player name so it crashes.

I will update the expansion today to more elegantly catch the error but it will not support a placeholder-inside-a-placeholder. To get around this you would need to parse out the inside-placeholder first, and then pass the value to the outside-placeholder.

I've also replied to your post on my profile in the spigot forumns with a way to contact me if you'd like to further discuss the matter.
