### ISSUE TITLE
1.18 Support

### ISSUE THREAD

**Issue by JaTiTV** [PlaceholderAPI/PlaceholderAPI#757]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

New API feature

### Description

1.18 Support

**Comment by Andre601** [comment]
1.18 support is being worked on. In fact, there should be a jar file available on the [HelpChat Discord](https://discord.gg/helpchat) to test out, so feel free to do so and report any bugs and issues you encounter along the way.

**Comment by JaTiTV** [comment]
OK, thank you very much.

**Comment by darbyjack** [comment]
Closed via https://github.com/PlaceholderAPI/PlaceholderAPI/commit/acb5728e65737ad819ab4380fa5049d16a350738

**Comment by IoIxD** [comment]
Wait, why hasn't this been pushed to the Spigot page? None of the open issues seem to be related to 1.18.

**Comment by darbyjack** [comment]
Because it has not been yet. It will when we feel it's ready.
