### ISSUE TITLE
MultiChat now supports PlaceholderAPI

### ISSUE THREAD

**Issue by OllieMartin** [PlaceholderAPI/PlaceholderAPI#76]
[Request change]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

### Notes
This template is for **requesting additions for the wiki** and not for reporting bugs or requesting changes for the wiki!  
If you want changes to be made to the wiki, use the [Request change] template.  
For bug reports, use the [Bug report] template.

Also make sure, that your requested placeholders/plugin isn't already added in the [wiki] or listed in the [issues] page.

### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New expansion providing placeholders.
- [ ] New plugin providing placeholders.
- [x] New plugin supporting PlaceholderAPI.

### Plugin
> What is the name of the plugin/expansion?
> Provide also a link to it.

MultiChat
https://www.spigotmc.org/resources/multichat-now-supports-discordsrv-placeholderapi-and-more.26204/

### Placeholders/others
> What are the new placeholders/Any additional info?

MultiChat is a bungeecord chat management plugin that now supports placeholderAPI placeholders in chat formats on both Spigot and Sponge.

**Comment by Andre601** [comment]
[Plugins using PlaceholderAPI]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#M

Added it to [Plugins using PlaceholderAPI].
Thank you for supporting PlaceholderAPI.
