### ISSUE TITLE
parse not working with 2.9.2 on 1.12.2

### ISSUE THREAD

**Issue by Wqrld** [PlaceholderAPI/PlaceholderAPI#77]
### Issue
/papi parse cannot find the user "me" or "Wqrld"

### Expected behaviour
/papi parse Wqrld %server_tps% should give the server tps

### Actual behaviour
"failed to find player wqrld"

### How to reproduce
install the latest papi 2.9.2 from spigot  on a 1.12.2 server and type 
`/papi parse Wqrld %server_tps%`

**Comment by aBo0oDyy** [comment]
Leave and then rejoin, everything should works fine

**Comment by Wqrld** [comment]
ah that works, i hope this won't interferr with featherboard but ill check that
