### ISSUE TITLE
API bug

### ISSUE THREAD

**Issue by darcky12** [PlaceholderAPI/PlaceholderAPI#776]
### Confirmation

- [x] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

API Bug

### What happens?

I have a bug when I give myself money and I go to like 10M from there it starts to show weird numbers like "1.0e7" and I couldn't find any solutions to it so I came here
![g76FiB5](https://user-images.githubusercontent.com/67874936/147687582-89e9306d-cf67-4ae9-8a57-7b5f85172cf4.png)
e

In this picture, you can see what I'm talking about

### Expected Behaviour

![g76FiB5](https://user-images.githubusercontent.com/67874936/147687682-dca33898-3a43-41ae-953e-054f14462494.png)

It should just keep going and not when I hit 10 million to add weird letters and numbers for short when I hit 10 million or more it starts to bug out

### How to Reproduce

To reproduce the bug you need a scoreboard plugin to see how much money you have and essentials so you can give yourself money

### `/papi dump` Output

https://paste.helpch.at/tahuzolopu

### Console Log

https://mclo.gs/bY4eCzn

### Additional Info

/eco give [here put your in-game name] 10000000

and those are 10M and you will see letters in the number and numbers that shouldn't be there

**Comment by Andre601** [comment]
This is just how Java formats extremely large numbers and most likely something to fix in the expansion you use.
