### ISSUE TITLE
Placeholders stop working

### ISSUE THREAD

**Issue by TenReeez** [PlaceholderAPI/PlaceholderAPI#780]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

Plugin Bug

### What happens?

Placeholders just stop working randomly. 

Ie: /papi parse me %statistic_mine_block:budding_amethyst% work one day. Two reboots later it stops working, then a reboot layer starts working again. 
While the Pyrofishpro placeholder just stopped all together.

No errors in console.
I get this:
- [12:13:20] [Thread-74/WARN]: [PlaceholderAPI] Loaded class net.ess3.api.IEssentials from Essentials v2.19.2 which is not a depend, softdepend or loadbefore of this plugin.
- [12:13:26] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: statistic [2.0.1] 
  
But no actual errors.

placeholderapi: 2.10.10 DEV 
&
placeholderapi: 2.11.1
I have tried both. 
I was using the DEV, upgraded tot eh 2.11.1 thats when i noticed it, so have gone back to the 2.10.10 Dev to see if it was a version issue. 
paper 1.18.1

I dont have a problem with essentials or eco, placeholders. Just ingame action ones? If that makes sense

### Expected Behaviour

worked ever time

### How to Reproduce

do /papi parse me %placeholder% and see if the amount changes

### `/papi dump` Output

https://paste.helpch.at/ogoxeriyef

### Console Log

https://pastebin.com/sdjZUfYs

### Additional Info

Only seems to happen to certain placeholders.

I use deluxemenu for levelup etc and use eco and money placeholders, I have no issue, Only seems to be action ones.

**Comment by Starmism** [comment]
Not a PlaceholderAPI issue. The statistics expansion just calls directly from the player data, and I have no idea what the Pyrofishpro expansion is, but it is an issue with the expansion if it does not work as expected.
