### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by FlyingPikachu** [PlaceholderAPI/PlaceholderAPI#79]
### Type
> What kind of request is this? (Multiple selections possible)

- [x] New plugin supporting PlaceholderAPI.

### Plugin
> What is the name of the plugin/expansion?
> Provide also a link to it.

Quests

https://www.spigotmc.org/resources/quests.3711/

### Placeholders/others
> What are the new placeholders/Any additional info?

No new placeholders, but supports the use of existing ones.

**SIDE NOTE: The "open an issue" link on the plugin list page is broken**
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI

**Comment by Andre601** [comment]
Added the plugin to the list.

Also fixed the broken link.
