### ISSUE TITLE
Error noticed after installing GriefDefender (although maybe irrelated)

### ISSUE THREAD

**Issue by MithrandirCraft** [PlaceholderAPI/PlaceholderAPI#799]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

Plugin Bug

### What happens?

https://gist.github.com/MithrandirCraft/ccf0333f5eac720bdce6a2292b99d44d

here's another one that seems to relate to SQL:
https://gist.github.com/MithrandirCraft/808a81923f49615841d9595fe2d30af3

These errors seem to be causing performance issues.

### Expected Behaviour

Well, no errors, that's for certain.

### How to Reproduce

This happens just by starting up the server with, at least with GriefDefender also installed.

### `/papi dump` Output

https://paste.helpch.at/oxunugofav

**Comment by Andre601** [comment]
The issue seems to be related to Vault and/or LuckPerms

**Comment by MithrandirCraft** [comment]
Grief Defender uses LP, and also Vault I'd imagine.

**Comment by Andre601** [comment]
My assumption is that GriefDefender hooks into Vault, which itself connects with LP and LP seems to have connection issues to its database, which propagates the error forward to vault, followed by the Vault expansion.

**Comment by MithrandirCraft** [comment]
What about that "Cannot assign field "color" because "this.root" is null" error.

Seems irrelated to SQL?

**Comment by darbyjack** [comment]
Disable the baltop task in the config. It's being removed from the vault expansion.
