### ISSUE TITLE
Tokens Manager placeholder doesn't work.

### ISSUE THREAD

**Issue by TheTechmo** [PlaceholderAPI/PlaceholderAPI#8]
The placeholder constantly displays a 0 regardless of the player's token balance.

**Comment by Flavourized** [comment]
This is an issue with the latest expansion and the latest version. 

If you are using `TokenManager 2.0.8`, use the expansion which is in `/papi ecloud`. 

If you are using `TokenManager 3.0+`, **remove the PAPI expansion**. TM3 has its own PAPI placeholder which you can find on the resource page. For quick reference, the tokenmanager tokens placeholder `%tm_tokens%`

**Comment by extendedclip** [comment]
Gg
