### ISSUE TITLE
Simpleclans expansion unloading after server restart.

### ISSUE THREAD

**Issue by theblobinc** [PlaceholderAPI/PlaceholderAPI#80]
[New placeholders/plugin]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=feature_request.md
[Request change]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request.md
[Spigot page]: https://www.spigotmc.org/resources/6245/
[Jenkins page]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issue]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

### Issue
> What is the issue? Describe it like you would tell a friend.

Having issues with expansions unloading after server restart's, specifically the simpleclans expansion.
after restart simply doing "/papi reload" fixes the issue... but only temporarily until the next restart.

### Expected behaviour
> What should PlaceholderAPI do?

placeholder api should be able to remember its expansions and load them all properly after server restarts.

### Actual behaviour
> What does PlaceholderAPI actually do?

upon server restart the simpleclans expansion unregisters.

### How to reproduce
> What steps did you made, to get this bug?

1. install the following expansions on a paperclip-1.13.2 server using PlaceholderAPI 2.9.2:
/papi list
[00:35:02 INFO]: [redprotect, server, listplayers, ultracosmetics, statistic, multiverse, pinger, sound, jobs, beautyquests, simpleclans, mypet, playerpoints, javascript, bungee, luckperms, dragonslayer, jobsr, mcmmo, mobhunting, combatlogx, cmi, vault, player]

2. setup a scoreboard with the "quickboard" plugin and associate an entry with a players clan using the placeholder %simpleclans_clan_name%

3. get desired result.

4. restart server, and the placeholder entry reverts back to %simpleclans_clan_name% until you do "/papi reload"

with the following readout from the console:
/papi list
[00:44:01 INFO]: [redprotect, server, listplayers, statistic, ultracosmetics, multiverse, pinger, sound, jobs, beautyquests, mypet, playerpoints, javascript, bungee, luckperms, dragonslayer, jobsr, mcmmo, mobhunting, combatlogx, vault, cmi, player]

**Comment by Andre601** [comment]
The info you provided seems more like an issue with the specific simpleclans expansion/plugin.

Either the expansion loads before SimpleClans does, which most likely results in it not being loaded due to the missing dependency (SimpleClans) or the plugin loads way to late which causes the same issue.

Can you provide the the latest.log through a page like https://paste.helpch.at or a GitHub-gist please?

**Comment by theblobinc** [comment]
here you go:
https://paste.helpch.at/winenimusa.md

**Comment by theblobinc** [comment]
so if thats the case... adding simpleclans as a soft dependency of placeholderapi in its plugin.yml should do the trick right?

tbh id have never considered that, thank you.

will try that and get back to you.

**Comment by theblobinc** [comment]
that totally worked, thank you for the idea.
guildcraft.org thanks you :)

https://paste.helpch.at/guwivohuna.md

**Comment by Andre601** [comment]
No problem.
Glad it helped.
