### ISSUE TITLE
MSPT for spark 

### ISSUE THREAD

**Issue by mastermc05** [PlaceholderAPI/PlaceholderAPI#808]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

New API feature

### Description

there is tps for spark, but i want also mspt, and if i'm not in a server that supports mspt (like spigot) to return empty string

**Comment by iGabyTM** [comment]
Spark has its own placeholders, open an issue on lucko/spark and ask luck to add such placeholder.

**Comment by mastermc05** [comment]
> Spark has its own placeholders, open an issue on https://github.com/lucko/spark and ask luck to add such placeholder **if** the functionality exist on the plugin already.

oh, sorry, didn't know, i'll go there then

**Comment by mastermc05** [comment]
and seems like it was there, but wasn't in your wiki, and you added that already after my issue, lol
