### ISSUE TITLE
Registered Expansions alphabetical ordered in the papi dump.

### ISSUE THREAD

**Issue by BlitzOffline** [PlaceholderAPI/PlaceholderAPI#821]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

Minor Code improvement (Won't affect Servers)

### Description

Basically in PAPI Dumps, both the Expansions Registered list and the Expansion Directory list could be alphabetically ordered. This is more of a QOL change and it would help in situations like this: https://paste.helpch.at/emocuhifaq. Here some expansions are not registered and to find out which, for each of the expansions in the directory I have to go thru all the registered ones to find it because I have no way to estimate where it would be found. Also this is a smaller dumps. there's ones with 20+ external expansions.

**Comment by Andre601** [comment]
Already a thing.
https://github.com/PlaceholderAPI/PlaceholderAPI/pull/801
