### ISSUE TITLE
Error in Start in PlceholderAPI

### ISSUE THREAD

**Issue by Safarival** [PlaceholderAPI/PlaceholderAPI#838]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

Plugin Bug

### What happens?

Hello

Version server: 1.8
tested versions Placeholders: 2.11.1 and 2.11.2-DEV-152
Java version: 17

I get an error when starting my server.

### Expected Behaviour

Who is no longer there this error

### How to Reproduce

Start server.

### `/papi dump` Output

N/A

### Console Log

https://paste.helpch.at/tukinudoha.sql

### Errors

https://paste.helpch.at/uhoxufuhim.sql

**Comment by Andre601** [comment]
This is an issue with your server and not PlaceholderAPI.
PlaceholderAPI (or pretty much any other plugin) uses Google's Gson for BStats metrics, which your server version doesn't have provided.

While we had a fix for this in the past by providing our own Gson, did it cause issues on newer versions, so it was removed (You can read more in #485 and #477).

Your best option here is to use a newer version of the server that does have Gson included, which afaik should also be the case for 1.8 (Tho you should really upgrade to a newer version altogether).
