### ISSUE TITLE
PlaceholderAPI Pinger extension issues.

### ISSUE THREAD

**Issue by Favoslav** [PlaceholderAPI/PlaceholderAPI#843]
### Confirmation

- [x] My issue isn't already found on the Issue tracker.
- [ ] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [x] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

API Bug

### What happens?

%pinger_isonline_large-lands.tk:60002% / %pinger_online_large-lands.tk:60002% always shows offline. I think this could be a problem with bungeecord?

### Expected Behaviour

%pinger_isonline_large-lands.tk:60002% shows if server is online or offline

### How to Reproduce

.

### `/papi dump` Output

https://paste.helpch.at/uhinerisig

**Comment by Andre601** [comment]
I assume the issue is resolved? Or did you post on the wrong issue tracker?

**Comment by DarkTemplar87** [comment]
I am having the same issue. Was this ever resolved or did you just give up?

**Comment by Favoslav** [comment]
I think i resolved somehow.. that was why i closed it. But i don't remember how and my server is currently not working and the files are stored on "damaged" HDD on linux format ext4 so for now i cannot help because the process of restoring rougly 1TB disk takes some time.

**Comment by Favoslav** [comment]
Try to not use the domain but the raw ip of the server.

**Comment by DarkTemplar87** [comment]
Mine is pingable, I think my error has to do with the ping coming from an internal docker container. Seems other people have had similar issues.
