### ISSUE TITLE
Typo in link on latest spigot release

### ISSUE THREAD

**Issue by UntouchedOdin0** [PlaceholderAPI/PlaceholderAPI#851]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

In the line on the latest update log you had It could happen that an expansion may not unregister properly if its identifier contains uppercase letters. This has been fixed by [@Rothes](http://https//github.com/Rothes)

This link won't work as you forgot to add the ":" , the link should be [@Rothes](https://github.com/Rothes). Easy mistake to be done although I know this issue will be ignored and closed when you see my name. Although I am sorry for my history. 

### Expected Behaviour

The link should take you to [https://github.com/Rothes](https://github.com/Rothes)

### How to Reproduce

aaaaaaaaa

### `/papi dump` Output

aaaaaaa

### Console Log

https://paste.helpch.at/

### Errors

https://paste.helpch.at/

### Additional Info

a

**Comment by Andre601** [comment]
Please report this on [Discord](https://discord.gg/helpchat) next time.

**Comment by knightzmc** [comment]
free my guy

**Comment by UntouchedOdin0** [comment]
@Andre601 I can't report it on discord as I was really dumb ages ago and did things I regret and now banned.

**Comment by Funny-cube** [comment]
The typo has been fixed now.
