### ISSUE TITLE
Problem with %server_tps%

### ISSUE THREAD

**Issue by DjGamerDz** [PlaceholderAPI/PlaceholderAPI#86]
![image](https://user-images.githubusercontent.com/42304709/54025379-a295b500-419a-11e9-9e24-5e5548299908.png)

**Comment by Andre601** [comment]
Did you actually installed the server expansion?

**Comment by DjGamerDz** [comment]
done

**Comment by DjGamerDz** [comment]
its working now
https://imgur.com/a/pUnSCF2
