### ISSUE TITLE
Color/Format translations for DeluxeMenus (1.10.5) for MC 1.8 breaks on latest PAPI (2.11.2) version

### ISSUE THREAD

**Issue by TheJoshue** [PlaceholderAPI/PlaceholderAPI#860]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

Using latest PlaceholderAPI (`2.11.2`) plugin version,
using DeluxeMenus plugin versions which is last to support MC 1.8.8 (`DeluxeMenus-1.10.5`),
on MC (spigot/paper) 1.8 server,
we are unable to colorize/format (translate colors/formats) for every lore line and for every display name line for any item that contains ANY papi placeholder inside of it

This was not the case with `PAPI-2.11.1` (just 1 version behind)

Behaviour (this is default example menu, i just added `%player_name%` at the end so we have placeholder to see how this breaks):
![image](https://user-images.githubusercontent.com/56804505/179629529-b4859963-f1a0-4290-b1f4-fec1f6adc118.png)

### Expected Behaviour

Looking at `What happens?`'s screenshot, this is what should happen:
![image](https://user-images.githubusercontent.com/56804505/179629842-b3b27810-17ee-44a4-bbed-749bb0996065.png)

### How to Reproduce

1. Use `DeluxeMenus-1.10.5` plugin version
2. Use latest `PlaceholderAPI` (`2.11.2`) plugin version
3. Start MC 1.8-1.12 server using those 2 plugins
4. Add ANY papi placeholder to any lore line or display name line of any deluxemenus gui
5. The line translation colors/formats will break if any papi placeholder is found inside of it

### `/papi dump` Output

https://paste.helpch.at/eyotixevec

**Comment by Andre601** [comment]
Please read the [latest release changelog](https://github.com/PlaceholderAPI/PlaceholderAPI/releases/tag/2.11.2)

**Comment by TheJoshue** [comment]
> Please read the [latest release changelog](https://github.com/PlaceholderAPI/PlaceholderAPI/releases/tag/2.11.2).
> 
> PlaceholderAPI doesn't parse color codes anymore, so it's the job of DeluxeMenus to deal with that.

Nobody has source of 1.10.5, not even clip...................... sh1t

**Comment by Andre601** [comment]
Clip does have the code, but it's kept private for reason I don't know myself (Could be anything from fear of copy-cats to simply not liking the current state of the code).

Perhaps in the future the plugin will be made open source, but for now is this the situation we have.

**Comment by TheJoshue** [comment]
> Clip does have the code, but it's kept private for reason I don't know myself (Could be anything from fear of copy-cats to simply not liking the current state of the code).
> 
> Perhaps in the future the plugin will be made open source, but for now is this the situation we have.

ok we understand
will we ever get patched version of DeluxeMenus for MC 1.8 (compiled on java8)

thanks in advance

**Comment by extendedclip** [comment]
I will push to get deluxemenus in a public repo this week. It is currently in a private repo managed by helpchat.

**Comment by BlitzOffline** [comment]
> I will push to get deluxemenus in a public repo this week. It is currently in a private repo managed by helpchat.

I'm sorry, what? When did this happen?

**Comment by BlitzOffline** [comment]
> > Clip does have the code, but it's kept private for reason I don't know myself (Could be anything from fear of copy-cats to simply not liking the current state of the code).
> > Perhaps in the future the plugin will be made open source, but for now is this the situation we have.
> 
> ok we understand will we ever get patched version of DeluxeMenus for MC 1.8 (compiled on java8)
> 
> thanks in advance

Making it OS, won't add 1.8 compatibilty but now people can maintain their own forks if they want with 1.8 compatibilty. We (HelpChat) are not supporting 1.8 anymore

**Comment by TheJoshue** [comment]
> 

omg thank you so much
if nothing at all, please give us at least some source for any version we (me, someone else, whoever) will fork and possibly make it work with MC 1.8
it's hard to change plugin when you depend with so much stuff on it, i really can't switch

**Comment by TheJoshue** [comment]
> > > Clip does have the code, but it's kept private for reason I don't know myself (Could be anything from fear of copy-cats to simply not liking the current state of the code).
> > > Perhaps in the future the plugin will be made open source, but for now is this the situation we have.
> > 
> > 
> > ok we understand will we ever get patched version of DeluxeMenus for MC 1.8 (compiled on java8)
> > thanks in advance
> 
> Making it OS, won't add 1.8 compatibilty but now people can maintain their own forks if they want with 1.8 compatibilty. We (HelpChat) are not supporting 1.8 anymore

ok i 100% understand, but we can't even fork it
i hope we will at least get some source code, at least from 10 versions behind latest one, ANY source so we can do stuff, because for now we can't anyhow update any DeluxeMenus source to again be compatible with latest PAPI (because no source is public)

Thanks a lot for answer

**Comment by Andre601** [comment]
> ok i 100% understand, but we can't even fork it i hope we will at least get some source code, at least from 10 versions behind latest one, ANY source so we can do stuff, because for now we can't anyhow update any DeluxeMenus source to again be compatible with latest PAPI (because no source is public)
> 
> Thanks a lot for answer

The source of DeluxeMenus was already here on GitHub. It just is private as of right now. And as clip said, the code will be made available in the near future.

**Comment by TheJoshue** [comment]
> I will push to get deluxemenus in a public repo this week. It is currently in a private repo managed by helpchat.

Hey! Sorry to refer to but *this week* has ended 3 days ago .-.
will we get it?

**Comment by BlitzOffline** [comment]
> > I will push to get deluxemenus in a public repo this week. It is currently in a private repo managed by helpchat.
> 
> Hey! Sorry to refer to but _this week_ has ended 3 days ago .-. will we get it?

I'm afraid not. We've realised there's some major changes we need to make before we do this. We're working on it but it might be slower than clip expected since he wasn't around for a while, he did not know about these changes.

**Comment by TheJoshue** [comment]
> > > I will push to get deluxemenus in a public repo this week. It is currently in a private repo managed by helpchat.
> > 
> > 
> > Hey! Sorry to refer to but _this week_ has ended 3 days ago .-. will we get it?
> 
> I'm afraid not. We've realised there's some major changes we need to make before we do this. We're working on it but it might be slower than clip expected since he wasn't around for a while, he did not know about these changes.

ok thanks a lot for blitz-fast response, can't wait!
