### ISSUE TITLE
Exception thrown at startup

### ISSUE THREAD

**Issue by Vilican** [PlaceholderAPI/PlaceholderAPI#861]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

A ClassNotFoundException is thrown when starting the server.

### Expected Behaviour

Do not throw exceptions at startup.

### How to Reproduce

1. Install the plugin
2. Start the server
3. Observe the console

### `/papi dump` Output

https://paste.helpch.at/xodakevacu

### Console Log

https://paste.helpch.at/uvoqugupag.md

**Comment by BlitzOffline** [comment]
Update your server expansion.
