### ISSUE TITLE
Colors inconsistently parsed inside the parse commands.

### ISSUE THREAD

**Issue by BlitzOffline** [PlaceholderAPI/PlaceholderAPI#872]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

Currently the `/papi bcparse/parse` command has different behavior for different senders and types.

https://github.com/PlaceholderAPI/PlaceholderAPI/blob/46d9a695346e989c768cc8a2fb9c58e1a7d6a025/src/main/java/me/clip/placeholderapi/commands/impl/local/CommandParse.java#L125-L131

So currently, if the action is broadcast or the sender is console (ConsoleSender), the message is passed thru Msg#color before being sent but if the sender is player and the action is not broadcast, the message is being passed to the net.md_5.bungee.api.chat.TextComponent#fromLegacyText method which doesn't actually translate the ampersand color codes `&c`.

### Expected Behaviour

Either don't translate color codes at all, or translate them everywhere. I personally do think they shouldn't be translated at all and should be just sent as the expansion gave it. This, in my opinion gives people a better understanding of what the actual expansion returns and won't be surprised when they use it somewhere else and it won't actually look the same.

### How to Reproduce

explained above.

### `/papi dump` Output

not needed

**Comment by Andre601** [comment]
Has been addressed in #873
