### ISSUE TITLE
1.19.2 server placeholder issues

### ISSUE THREAD

**Issue by TechieBlort** [PlaceholderAPI/PlaceholderAPI#878]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

Placeholder API using 1.19.2 server software PurpurMC (1762) or Paper Spigot (135) doesn't properly load Placeholders on startup even if the plugin results in no errors on startup.

### Expected Behaviour

Placeholders should work upon startup and not require a `/papi reload` to function properly.

### How to Reproduce

Place PAPI 2.11.2 into the server of your choice
Download an expansion example: Server or player
Place them in a tablist/scoreboard/chat plugin that supports PAPI
Reload the papi plugin (notice your placeholder working as intended)
Restart the server and log into the server. (notice the issue without running /papi reload)

### `/papi dump` Output

https://paste.helpch.at/ocenateyup

### Console Log

https://paste.helpch.at/sowayuhepa.md

### Errors

https://paste.helpch.at/satoziyuvo.sql

### Additional Info

Error listed above is at the bottom of the log although all placholders loaded properly (from what I can see from the console log)

**Comment by Andre601** [comment]
2 things:

1. You are not on latest Purpur dev build, so maybe consider updating
2. "Zip file closed" usually indicates that the jar was closed before the classloader (or whatever opened the jar) has finished whatever it did. In this case would my guess be that something (forcefully) closed the jar of an expansion before PAPI had the chance to complete anything.

Could you for the sake of testing quickly test if the error also appears on latest Purpur with just PlaceholderAPI installed?
Make sure to also include any external expansions (located in the expansions folder) that you use for that test.

**Comment by Restland** [comment]
> 2 things:
> 
> 1. You are not on latest Purpur dev build, so maybe consider updating
> 2. "Zip file closed" usually indicates that the jar was closed before the classloader (or whatever opened the jar) has finished whatever it did. In this case would my guess be that something (forcefully) closed the jar of an expansion before PAPI had the chance to complete anything.
> 
> Could you for the sake of testing quickly test if the error also appears on latest Purpur with just PlaceholderAPI installed? Make sure to also include any external expansions (located in the expansions folder) that you use for that test.

Same issue here on paper started today.

**Comment by TechieBlort** [comment]
> 2 things:
> 
> 
> 
> 1. You are not on latest Purpur dev build, so maybe consider updating
> 
> 2. "Zip file closed" usually indicates that the jar was closed before the classloader (or whatever opened the jar) has finished whatever it did. In this case would my guess be that something (forcefully) closed the jar of an expansion before PAPI had the chance to complete anything.
> 
> 
> 
> Could you for the sake of testing quickly test if the error also appears on latest Purpur with just PlaceholderAPI installed?
> 
> Make sure to also include any external expansions (located in the expansions folder) that you use for that test.

I didn't end up doing anything and it seems to fix itself after awhile without doing anything.

**Comment by Andre601** [comment]
This issue is quite outdated, so I'll close it. Should the problem still be present, reply to the issue with up-to-date information.
