### ISSUE TITLE
DungeonsXL

### ISSUE THREAD

**Issue by Sataniel98** [PlaceholderAPI/PlaceholderAPI#88]
### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New expansion providing placeholders.
- [x] New plugin providing placeholders.
- [ ] New plugin supporting PlaceholderAPI.

### Plugin
DungeonsXL.
https://www.spigotmc.org/resources/dungeonsxl.9488/

### Placeholders/others
> What are the new placeholders/Any additional info?

%dxl_group_members%
%dxl_group_name%
%dxl_group_name_raw%
%dxl_group_player_count%
%dxl_game_player_count%
%dxl_floor_player_count%
%dxl_dungeon_name%
%dxl_global_dungeon_count%
%dxl_global_floor_count%
%dxl_global_instance_count%

I should also note that, well, embarrassingly, I somehow overlooked the fat thing saying the wiki page shouldn't be edited and, well, already added it. I am very sorry for that.
![](https://staticdelivery.nexusmods.com/mods/2229/images/thumbnails/1141/1141-1549134653-390096851.jpeg)

**Comment by Andre601** [comment]
I made some smaller corrections but other than that is everything ok.
