### ISSUE TITLE
Dependency 'me.clip:placeholderapi:2.11.2' not found

### ISSUE THREAD

**Issue by Ecc3ssivo** [PlaceholderAPI/PlaceholderAPI#885]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

i am using maven to get placeholderapi dependence but when i insert it in my pom.xml it does not work

**_My pom.xml:_**
![pom](https://user-images.githubusercontent.com/114882836/193476122-17ddf60c-f459-43fd-b152-231909f72c5a.png)

**_Error:_** Dependency 'me.clip:placeholderapi:2.11.2' not found 

pls help

### Expected Behaviour

//

### How to Reproduce

//

### `/papi dump` Output

N/A

**Comment by Ecc3ssivo** [comment]
I solved, it was a small problem, I feel so stupid, you can close the issues

**Comment by PossiblePanda** [comment]
what was it?

> I solved, it was a small problem, I feel so stupid, you can close the issues
