### ISSUE TITLE
Behavioral difference between CharReplacer and RegexReplacer

### ISSUE THREAD

**Issue by xtexChooser** [PlaceholderAPI/PlaceholderAPI#886]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

In PR #354, `CharReplacer` and `RegexReplacer` added.

The `CharReplacer` allows using special characters as identifiers, like `%a,b,c_params%`.

However, `RegexReplacer` only allows `a-zA-Z0-9`, which is not compatibility with the expression above.

### Expected Behaviour

They should have the same behavior, which is to explicitly state whether such identifiers are allowed.

### How to Reproduce

register placeholders with special characters

### `/papi dump` Output

..

**Comment by Andre601** [comment]
This is intentional.
The placeholder's identifier may only have alphanummeric characters.

Also, RegexReplacer isn't used at all in PlaceholderAPI. It was only added for performance benchmarking and comparing it to the CharsReplacer.

**Comment by PiggyPiglet** [comment]
We don't even have regex replacer anymore, look at the current codebase.
