### ISSUE TITLE
New placeholders - Nameless Plugin for v2

### ISSUE THREAD

**Issue by Derkades** [PlaceholderAPI/PlaceholderAPI#89]
### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New expansion providing placeholders.
- [x] New plugin providing placeholders.
- [ ] New plugin supporting PlaceholderAPI.

### Plugin
> What is the name of the plugin/expansion?
> Provide also a link to it.

Spigot plugin for NamelessMC v2
https://www.spigotmc.org/resources/nameless-plugin-for-v2.59032/

### Placeholders/others
> What are the new placeholders/Any additional info?

%namelessmc_notifications% - The number of notifications on the website for a specific player.

**Comment by Andre601** [comment]
Added to the list.

Thanks for supporting PlaceholderAPI.
