### ISSUE TITLE
PlaceholderAPI would not parse all registered placeholder when an invalid expansion in is expansions folder

### ISSUE THREAD

**Issue by TypicalShavonne** [PlaceholderAPI/PlaceholderAPI#893]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin/Server Incompatability

### What happens?

Plugin unable to parse ALL placeholder when an invalid expansion is installed

### Expected Behaviour

Placeholders parse normally

### How to Reproduce

Example: I have Quests plugin installed it expansion through (/papi ecloud download Quests), then uninstall only Quests plugin, restart server, any placeholder would be unable to parse

### `/papi dump` Output

https://paste.helpch.at/igufaruvuh

### Console Log

None

### Errors

https://paste.helpch.at/lawuzezidu.log

### Additional Info

I have tried to delete expansion-quests.jar in expansions folder and it fixed it

**Comment by TypicalShavonne** [comment]
The quest expansion can be downloadd in http://api.extendedclip.com/media/Expansion-Quests_bthXN4A.jar

**Comment by iGabyTM** [comment]
> `[18:54:57 ERROR]: [PlaceholderAPI] Failed to load class files of expansion.`

**Comment by TypicalShavonne** [comment]
yes, it did see that error then remove Quests expansion which fixed it, but it suppose only not to load that expansion, and not causing all placeholders failed to parse

**Comment by Andre601** [comment]
One question I have is, where this happens.

Like do all placeholders across different plugins fail to parse, or is only one specific location/plugin (i.e. chat) affected?
If it is the second one, then it may be an issue within that plugin itself.

Either way, it would be of great help if you could share your full logs through https://paste.helpch.at, as that usually provides extra info for us to work with.

**Comment by TypicalShavonne** [comment]
all placeholders across different plugins fail to parse, every registered one

**Comment by TypicalShavonne** [comment]
![image](https://user-images.githubusercontent.com/53472591/204822070-67e53c08-133e-4cb0-856d-671f493780bf.png)
https://paste.helpch.at/anifinuboz Logs

**Comment by Andre601** [comment]
You're using Pufferfish it seems.

PlaceholderAPI encountered issues with it in the past, namely that it would close jars while PlaceholderAPI was loading them, causing errors (https://github.com/PlaceholderAPI/PlaceholderAPI/issues/868).
The devs since have implemented a fix for it, tho I wouldn't be surprised if they messed up again.

Could you try it with a Paper server and see if everything resolves?

**Comment by TypicalShavonne** [comment]
> You're using Pufferfish it seems.
> 
> PlaceholderAPI encountered issues with it in the past, namely that it would close jars while PlaceholderAPI was loading them, causing errors (#868). The devs since have implemented a fix for it, tho I wouldn't be surprised if they messed up again.
> 
> Could you try it with a Paper server and see if everything resolves?

https://paste.helpch.at/tulatacoki
seems no, also, i have tested few other expansions but only Quests getting make PlaceholderAPI just not be able to parse all placeholders?

**Comment by astronymity** [comment]
i also had this issue today when i uninstalled Quests. I am running a paper server. removing the expansion manually in the files fixed it, but even sending a /papi command would not work and returned the same error

**Comment by Andre601** [comment]
This issue is quite outdated, so I'll close it. Should the problem still be present, reply to the issue with up-to-date information.
