### ISSUE TITLE
PAPI shades Adventure module-info

### ISSUE THREAD

**Issue by Geolykt** [PlaceholderAPI/PlaceholderAPI#894]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

API Bug

### What happens?

The placeholder API jar defines `META-INF/versions/9/module-info.class`.
Decompiled contents hint at it being from Adventure:
```
module net.kyori.examination.string {
    /* transitive */ requires net.kyori.examination.api;

    exports net.kyori.examination.string;

}
```

This results in the jar being completely unusuable should it be present on the module path

### Expected Behaviour

There is no module-info present, or at least one module-info that exports the PAPI API packages

### How to Reproduce

Unzip the built jar

### `/papi dump` Output

N/A

**Comment by iGabyTM** [comment]
> This results in the jar being completely unusuable should it be present on the module path
In what context @Geolykt

**Comment by Geolykt** [comment]
Compilation - in this case I made the issue for a user that had the jar on the module path while compiling through eclipse but any compiler does it UNLESS they don't conform to the JLS
