### ISSUE TITLE
Requesting LevelHearts supports

### ISSUE THREAD

**Issue by Karagra** [PlaceholderAPI/PlaceholderAPI#90]
### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New expansion providing placeholders.
- [ ] New plugin providing placeholders.
- [x] New plugin supporting PlaceholderAPI.

### Plugin
> What is the name of the plugin/expansion?
> Provide also a link to it.

Level Hearts
https://dev.bukkit.org/projects/levelhearts
### Placeholders/others
> What are the new placeholders/Any additional info?

%levelhearts_xp_remaining_health%
%levelhearts_xp_needed_health%
%levelhearts_xp_health%

**Comment by Andre601** [comment]
Does the plugin actually have the placeholders, or do you request them?
Because this GitHub-repo is not for requesting placeholders to be added to a plugin, but to request changes to the wiki.

**Comment by Mishyy** [comment]
@Karagra As Andre indicated, this is not the place to request expansions and alike.  
Such requests should be made at [PlaceholderAPI/Expansion-Suggestions](https://github.com/PlaceholderAPI/Expansion-Suggestions/issues/new).  
  
Additionally, could you include some more information about the placeholders you want added.  
An example based on the information the plugin provides via commands etc. could be useful.
(Eg. Might the plugin have a command or commands that displays the data you want, if so, which one, and which line(s) provide it.)

**Comment by Andre601** [comment]
Since there was no response in almost a month will this issue be closed.

If you want to respond, please respond to this issue @Karagra
