### ISSUE TITLE
Expansion get updated to lower version

### ISSUE THREAD

**Issue by BlockyTheDev** [PlaceholderAPI/PlaceholderAPI#902]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

The expansion version isn't checked in the right way, so PlaceholderAPI is updating the expansion to a lower version as installed. On first install the version `5.4` is installed, when looking into the installed expansion list is shows gold because PlaceholderAPI thinks there is an update. After that when I try to update all expansions it installs the lower version `5.1-R2`

### Expected Behaviour

It shouldn't show that there is an update and install a lower version.

### How to Reproduce

1. Install LuckPerms
2. Install the LuckPerms expansion
3. /papi ecloud download LuckPerms
4. /papi reload
5. /papi ecloud update LuckPerms

### `/papi dump` Output

https://paste.helpch.at/rugunuvupa

**Comment by BlitzOffline** [comment]
After investigating, it seems that the problem is a mismatched version rather than a PlaceholderAPI issue.

The version on the eCloud is set to 5.4 but the version set inside the expansion is 5.1-R2. There is nothing we can do. The expansion author will have to update the expansion with the correct version.

**Comment by BlitzOffline** [comment]
I feel like I should probably update a bit on my message as it is incomplete:

PlaceholderAPI doesn't actually downgrade the version. It still gets the latest version from the eCloud but since the built in version is wrong, it thinks that there's still a new version available on the eCloud.
