### ISSUE TITLE
Placeholders keep unregistering 

### ISSUE THREAD

**Issue by Paperboypaddy** [PlaceholderAPI/PlaceholderAPI#91]
Hello, im having a problem with my plugin. when I reload or restart my server all the placeholders like player and server are unregistered.

**Comment by Andre601** [comment]
Could you provide the latest.log of your server through https:://paste.helpch.at

**Comment by Paperboypaddy** [comment]
https://paste.helpch.at/efeqixovan.md

**Comment by Paperboypaddy** [comment]
there I just restarted my server https://paste.helpch.at/kuyanefopi.md

**Comment by aBo0oDyy** [comment]
I think it stops working after trying to load WorldGuard expansion
Looks like latest version of it only works in 1.13
So try older version of it
/papi ecloud download WorldGuard 1.0.2
/papi reload

**Comment by Paperboypaddy** [comment]
ok ill try that

**Comment by Paperboypaddy** [comment]
> I think it stops working after trying to load WorldGuard expansion
> Looks like latest version of it only works in 1.13
> So try older version of it
> /papi ecloud download WorldGuard 1.0.2
> /papi reload



> I think it stops working after trying to load WorldGuard expansion
> Looks like latest version of it only works in 1.13
> So try older version of it
> /papi ecloud download WorldGuard 1.0.2
> /papi reload

Thanks that worked!

**Comment by aBo0oDyy** [comment]
Glad it did :)

Close the issue please
