### ISSUE TITLE
1.19.3 and bungee not working

### ISSUE THREAD

**Issue by JoshJames04** [PlaceholderAPI/PlaceholderAPI#912]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

API Bug

### What happens?

When using the bungee extension I get an error (shown below)
![image](https://user-images.githubusercontent.com/71925441/216828825-4ae8cc8b-bcf9-4689-a98e-4f66d17be8a8.png)

I've been running PAPI for ages (from around version 1.17) without any issues but since updating to version 1.19 recently I keep getting this error.

Nothing has changed with any servber or PAPI config - only a paper version update and perhaps a PAPI update or two.

I'm running paper 1.19.3 version #386 with Placeholder API version 2.11.2 (at the time of writing this, the latest for both).

The placeholder value is not shown correctly.

### Expected Behaviour

Not throw this error and shgow the bungee placeholder value correctly

### How to Reproduce

Simply use the bungee extension

### `/papi dump` Output

https://paste.helpch.at/inuwiwiyem

### Console Log

https://paste.helpch.at/raw/rucaqidaxi

**Comment by iGabyTM** [comment]
You probably have multiple jars of the bungee expansion, remove all and install the latest. @JoshJames04
