### ISSUE TITLE
Downloading latest TokenEnchant expansion manually and automatically does not update

### ISSUE THREAD

**Issue by axemwa** [PlaceholderAPI/PlaceholderAPI#92]
Downloading latest TokenEnchant expansion manually and automatically does not update, it still syas out of date even after reloading papi and/or restarting the server

Using [Paper 616 ](https://papermc.io/ci/job/Paper-1.13/616/)1.13.2 Latest PAPI (2.92)

**Comment by Andre601** [comment]
Sorry for the late response:
What steps did you do?

Also please use the issue template for bug reports next time ;)

**Comment by axemwa** [comment]
Tried downloading it in game with the usual commands, then using the plugins refresh and reloading commands and after checking it it's still gold and says out of date in the llist no matter what I do, even after restarting still no luck.
I didn't realize a template would be necessary plus I was in a hurry at the time

**Comment by Andre601** [comment]
[ecloud]: https://api.extendedclip.com/home

Hm...
Could you try downloading it manually from the [ecloud] (replace the jar in `plugins/PlaceholderAPI/expansions` with it), reload and check again?
If it still shows as outdated, then perhaps the version that is listed on the ecloud and the one that is saved in the jar-file itself isn't the same...

**Comment by axemwa** [comment]
Yeah that's what I meant when I was trying to manually update it, unfortunately that doesn't work either

**Comment by aBo0oDyy** [comment]
its probably because of the version of the jar is different than the latest version on the cloud, so it gives you that the expansion isn't up to date.
might be another issue as well but i don't think so. 
Can you please send the expansion version? you can check that using the info command `/papi info TokenEnchant`

**Comment by axemwa** [comment]
Expansion version says 
[04:05:32 INFO]: Placeholder expansion info for: tokenenchant
[04:05:32 INFO]: Status: Registered
[04:05:32 INFO]: Created by: vk2gpz
[04:05:32 INFO]: Version: 1.5.0
[04:05:32 INFO]: Requires plugin: TokenEnchant
I download it with "/papi ecloud download tokenenchant" then use "/papi ecloud refresh" then I use "/papi list all 3" to check it and it's no longer gold, but when I go to use "/papi reload" and check the list again tokenenchant goes gold again, no other expansion seems to be having this issue, all the others seem to be updating correctly

**Comment by aBo0oDyy** [comment]
`[04:05:32 INFO]: Version: 1.5.0`
and the latest version on the cloud is 1.6.1, so thats why its telling u thats its not up to date.

the expansion author needs to fix that, since the jar version doesn't math the latest version in the cloud.

**Comment by axemwa** [comment]
Ok thankyou I will message them and reference this issue tracking link

**Comment by vk2gpz** [comment]
this should be fixed now.

**Comment by axemwa** [comment]
Just seen this, thankyou
