### ISSUE TITLE
Inconsistent version checking.

### ISSUE THREAD

**Issue by vk2gpz** [PlaceholderAPI/PlaceholderAPI#924]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

When an expansion is locally provided (through a local file or plugin-provided), even if the locally installed expansion's version is newer, if the version number is different from the latest version on eCloud, PAPI flags it as if it needs an update (or update available).

PAPI should actually check the version number and if the locally surprised version is actually newer, it should not flag "update available".

### Expected Behaviour

If the locally provided expansion has a newer number, PAPI won't/shouldn't flag those expansion.

### How to Reproduce

1. Install newer version of an expansion locally (through a file or via a plugin)
2. run "papi ecloud list installed"
3.  you will see locally newer expansion is flagged as update needed/available.

### `/papi dump` Output

this is not needed because we know exactly where this judgement is carried out in CloudExpansionMager.class

### Console Log

N/A

### Errors

N/A

**Comment by vk2gpz** [comment]
This is not a feature request.  It is a bug.

PAPI does not recognise 3.0.0 is newer than 2.0.0

**Comment by Andre601** [comment]
It's a bug report that asks for a feature to change, therefore the https://github.com/PlaceholderAPI/PlaceholderAPI/labels/Type%3A%20Feature%20%28change%29%20request label is imo valid to be added here. Checking the expansion version is a feature of PAPI.

**Comment by vk2gpz** [comment]
Here is the bug:
           expansion.setShouldUpdate(
                                !local.getVersion().equalsIgnoreCase(expansion.getLatestVersion()));

equalsIgnoreCase should not be used to determine whether it should update or not.

**Comment by vk2gpz** [comment]
> It's a bug report that asks for a feature to change, therefore the [ Type: Feature (change) request](https://github.com/PlaceholderAPI/PlaceholderAPI/labels/Type%3A%20Feature%20%28change%29%20request) Request for a new feature, or to change an existing one. label is imo valid to be added here. Checking the expansion version is a feature of PAPI.

If you believe a new feature is needed, please submit a feature request.
simply providing a new feature, which checks version won't solve the issue I pointed out unless an appropirate value is pass to expansion.setShouldUpdate() method.
