### ISSUE TITLE
Would it be possible to add support for Folia?

### ISSUE THREAD

**Issue by Aitooor** [PlaceholderAPI/PlaceholderAPI#951]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

New API feature

### Description

Would it be possible to add support for Folia?

Folia url: https://github.com/PaperMC/Folia

**Comment by R00tB33rMan** [comment]
Folia is pretty new. Furthermore, it's already a WIP via this tab here. With some small changes, I was able to get some components of the resource working, including some expansions. Feel free to check its progress here: https://github.com/PlaceholderAPI/PlaceholderAPI/tree/feature/folia-support

**Comment by Aitooor** [comment]
Thanks 🙏

**Comment by Netherwhal** [comment]
why is this ticket closed though if its still in progress?

**Comment by iGabyTM** [comment]
What is 'in progress'?

**Comment by Netherwhal** [comment]
Does placeholder already support folia?
