### ISSUE TITLE
Random LinkageError when loading placeholders

### ISSUE THREAD

**Issue by tomkeuper** [PlaceholderAPI/PlaceholderAPI#957]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin/Server Incompatability

### What happens?

A Linkage Error exception spammed the console when a player joined the server. After a reboot the issue was gone and even when reboot a few times it ended up not happening, but after a while, when testing was done by a different developer on a completely seperate server a similar issue occured. 

### Expected Behaviour

Stable server without random errors that are fixed with a reboot as its not reliable. 

### How to Reproduce

The issue is quite random and I got not real steps to reproduce as Im not sure what triggered it.
I guess restarting and joining is the way to go.

### `/papi dump` Output

https://paste.helpch.at/fokazifape

### Console Log

https://paste.helpch.at/tidabenawo.makefile same error different server: https://paste.helpch.at/useqadopak.makefile

### Errors

Both errors: https://paste.helpch.at/kaholixiho.less

### Additional Info

I provided 2 server logs both having this issue but both thrown by different plugins.

**Comment by tomkeuper** [comment]
willing to colaborate to find a solution. the weird thing is the reboot that fixes it. Others have suggested to check if some plugin was shading PAPI but I checked all of them and no shading of papi was found

**Comment by tomkeuper** [comment]
Btw I've also posted this in Help Chat with no luck, so all help is welcome

**Comment by porudev** [comment]
Yeah this bug is quite annoying please fix it

**Comment by iGabyTM** [comment]
Are you sure that none of the plugins have PAPI shaded?

**Comment by tomkeuper** [comment]
The plugins arent shading as far as I can see. I can send the JAR if requested. But this is the plugin thats trying to access the placeholder https://github.com/NEZNAMY/TAB

**Comment by porudev** [comment]
> @porudev are you facing this problem on 1.8 as well or on newer versions (ideally one released in the past 12 months not years)

i've only encounter this problem on 1.8 (Papermc latest 1.8.8 build)

**Comment by Andre601** [comment]
Then this is probably a 1.8 exclusive issue unless someone can provide logs displaying the same issue with a newer (And by that I mean the last 3 major releases) server version.

**Comment by tomkeuper** [comment]
This might very well be the case. I also run basically the same setup on a 1.19.4 server and havent seen it happen. 

But due it it being an old version does that mean this wont get fixed? (Just to know what I can expect)
I know LinkageErrors are hard to figure out whats actually causing it so...

But just so you know im willing to help where I can

**Comment by tomkeuper** [comment]
Honestly havent seen the issue for quite a while personally. I did however update the server to use JAVA 17 instead.

**Comment by porudev** [comment]
I too haven't seen this issue recently, i think it is a Java version related issue. Because ever since switching to java 17 or higher the problem doesn't seems to persist

**Comment by PiggyPiglet** [comment]
Awesome, closing this issue then
