### ISSUE TITLE
Context placeholders

### ISSUE THREAD

**Issue by PukPukov** [PlaceholderAPI/PlaceholderAPI#959]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

New API feature

### Description

Relational placeholders is useful, but not enough abstract. What if I want to pass, for example, relation to the block, not other players?

Let's use the concept of Context.

Every call to PlaceholderAPI is, in general, call with context. Target of the message (player) is part of context, relation to the other player (if such) is also a part of context. We can declare context variables and pass them to every call of placeholder setup to the string, and than, pass them to the placeholder from string.

## Implementation of idea

Let Context be an object with that API:
```java
public Context(Map<String, Object> context);

public <T> @Nullable T get(String variable, Class<T> defineAs);
```

### Message request stage

To allow plugins passing that context, we can add this method to the PlaceholderAPI class:

```java
PlaceholderAPI.setContextPlaceholders(string, context);
```

### Placeholder stage

And we can add the ability to implement this method by expansions to handle context placeholders.

```java
String onPlaceholderRequest(Context context);
```

We also can add the way to handle with this single method all types of placeholders: standart, relational, and new context placeholders. That way viewer of the message will be "viewer" in Context and related player will be "related".

We can also add this methods to Context object to make work with context easier:

```java
public Player viewer() {
    return this.get("viewer", Player.class);
}

public @Nullable Player related() {
    return this.get("related", Player.class);
}
```

## Example

Let imagine, that we have plugin TotalData. TotalData allows player to view data of everything: other blocks, players, mobs, etc. But, what a pity—it doesn't count the amount of blocks, that player mined, and doesn't show it in block data page. However, we have plugin DigCounter, and it can do this. How let them work together? Now it's impossible with PlaceholderAPI, even if every of two plugins support it. 

But with context it is possible!

### Message request stage

TotalData can setup placeholders like this:

```java
Context context = new Context(Map.of(
    "player", player,
    "block", block
));
PlaceholderAPI.setContextPlaceholders(string, context);
```

### Configuration stage

In TotalData config we write this:

```yaml
block-page-form:
  - "Name: %NAME%"
  - "You digged %OreCounter_blockDigged% pieces of this block."
```

### Placeholder stage

And in DigCounter:

```java
public String onPlaceholderRequest(String providedPlaceholder, Context context) {
    String[] arguments = providedPlaceholder.split("_");
    if (arguments[0].equals("blockDigged")) {
        Block block = context.get("block", Block.class);
        Player player = context.player();
        return ""+OreCounterPlayer.of(player).minedBlocks(block);
    }
    return null;
}
```

**Comment by Andre601** [comment]
I can't really imagine the example here.

How is this useful compared to just hooking into a Plugin's API (if it provides one) or the Server API?

I'm fairly sure that what you showed here would be doable by just using the Spigot/Paper API and maybe the plugin itself.

Also, as a side-note: In your example are you not even using the Block you get from the context...

**Comment by ancap-kun** [comment]
>How is this useful compared to just hooking into a Plugin's API (if it provides one) or the Server API?
I deliberately chose an example that requires abstraction. Without context we can't provide the information of what block mining statistics should be collected. 

>In your example are you not even using the Block you get from the context...
Fixed.

**Comment by Starmism** [comment]
This is way too complicated for what can be boiled down to basic string serialization. Just serialize whatever data you need when you make the request into part of the placeholder, you fully control the placeholder format besides the surrounding characters and the name. This would require a ton of effort and drastically complicate parsing of placeholders for little to no benefit.

**Comment by ancap-kun** [comment]
> This is way too complicated for what can be boiled down to basic string serialization. Just serialize whatever data you need when you make the request into part of the placeholder, you fully control the placeholder format besides the surrounding characters and the name. This would require a ton of effort and drastically complicate parsing of placeholders for little to no benefit.

This idea is completely irrelevant to string parsing, it should not change at all.

**Comment by Starmism** [comment]
It is not. You can easily describe what block you want to get the statistics for by putting it in the placeholder string. In fact, this is literally what the Statistic expansion already does for the blocks mined statistics: `%statistic_mine_block:<material>%`.

**Comment by ancap-kun** [comment]
> It is not. You can easily describe what block you want to get the statistics for by putting it in the placeholder string. In fact, this is literally what the Statistic expansion already does for the blocks mined statistics: `%statistic_mine_block:<material>%`.

You didn't understood the idea. The block is dynamic, like players. I can't just put the specific block in config if I, for example, receive that block from command /block <name>.

**Comment by Starmism** [comment]
You can easily modify the placeholder from that config file to add the required context in string form. Like making `"%OreCounter_blockDigged%"` into `"%OreCounter_blockDigged_" + block.toString() + "%"`.

**Comment by ancap-kun** [comment]
> You can easily modify the placeholder from that config file to add the required context in string form. Like making `"%OreCounter_blockDigged%"` into `"%OreCounter_blockDigged_" + block.toString() + "%"`.

If I can hard link two plugins, the placeholder api is not needed at all. The main idea of placeholder api is to achieve less coherence and more abstraction. Why am I even explaining this to you here?

**Comment by Starmism** [comment]
It's not "hard linking" two plugins. The point of PlaceholderAPI, as most programming is, is to make contracts with what you accept. If you accept any block name in a well-defined format in your placeholder, as you should, then any plugin with the proper integration can use placeholders for it. 

Every single expansion we have ever had until now has worked without this mysterious "context", which ends up just looking like a `Map<String, Object>`, which brings its own type safety problems regardless.

**Comment by ancap-kun** [comment]
> It's not "hard linking" two plugins. 

What is it than? If I can type name of plugin in code, than I can there type plugin api and get rid of placeholder api at all.

> Every single expansion we have ever had until now has worked without this mysterious "context", which ends up just looking like a `Map<String, Object>`, which brings its own type safety problems regardless.

Judging by the existence of relative placeholders, you needed it after all.

**Comment by Starmism** [comment]
> If I can type name of plugin in code, than I can there type plugin api and get rid of placeholder api at all.
Bingo. If you want a rich integration, use their plugin API, that's what it's there for.
The point of placeholders in scenarios like these is to allow arbitrary integration without special need for compatibility, a server owner can just put a full string in specifying what they want, in this case I suppose a block name for the blocks broken statistic, and it will be filled.

In your scenario, the fact that the plugin has to provide the Context map manually means that the plugin author would have to be involved in making the placeholders work. In that case, they can just use the plugin API directly, instead of relying on PlaceholderAPI.

> Judging by the existence of relative placeholders, you needed it after all.
Not sure what this means, relative placeholders are about parsing relations between two players, nothing else. It's for scenarios like direct messaging where you want to know the relationship between you and the sender.

**Comment by emilyy-dev** [comment]
How would this actually even work out in practice? How would one plugin using `setContextPlaceholders` even know what values to pass in the context? How would, say, a tablist plugin that passes a configured string for tablist header, know it needs to pass X or Y context values?

**Comment by ancap-kun** [comment]
>The point of placeholders in scenarios like these is to allow arbitrary integration without special need for compatibility, a server owner can just put a full string in specifying what they want, in this case I suppose a block name for the blocks broken statistic, and it will be filled.

That's what I'm describing now. 

>Not sure what this means, relative placeholders are about parsing relations between two players, nothing else. It's for scenarios like direct messaging where you want to know the relationship between you and the sender.

If make abstraction upper it and single-player placeholder, we will get the context. It is the first paragraph of thread.

**Comment by ancap-kun** [comment]
> How would this actually even work out in practice? How would one plugin using `setContextPlaceholders` even know what values to pass in the context? How would, say, a tablist plugin that passes a configured string for tablist header, know it needs to pass X or Y context values?

Just passing everything context-specific. In practice it may be command arguments, or, for example, item with what was killed player in player kill message. Tablist probably shouldn't pass anything to context except from player, that receives it.

**Comment by Andre601** [comment]
> If I can hard link two plugins, the placeholder api is not needed at all. The main idea of placeholder api is to achieve less coherence and more abstraction. Why am I even explaining this to you here?

The main purpose of PlaceholderAPI is above anything else to be a simple core utility to allow cross-plugin placeholder parsing, so that you don't need to support countless placeholder parsing methods from X plugins.

What you want is from what I get pointless boilerplate code that only bloats PlaceholderAPI.
Like as Star described has no expansion so far ever requested nor needed this magical context you now want to be implemented, so at the end would this be at most a solution you alone would use.

When making new features can we not just think of single individuals, but the larger amount of devs. And from what you explained so far is there not really any improvements in this features that would benefit anyone else except you.

If you want context, make it an optional requirement of your placeholder to be provided (i.e. `%OreCounter_blockDigged_<context>%`) but in like 99% of cases does the dev making the expansion know what to expect.
Like I guess in your case is a player executing a command to see their ore mining stats? Why not obtain the info from the command and parse the placeholder with that ore in mind?

This entire thing reads for me like a badly made setup that requires a fix on one of the plugins and not this *feature* in PlaceholderAPI.

If you still want it added, feel free to make a Pull request with it being added. No guarantees it will be merged, but it may give some much needed context (no pun intended) for this entire thing to make sense.

**Comment by PiggyPiglet** [comment]
Yeah, I don't really see the point of this either, closing this issue as I have no intention of implementing it into PAPI.
