### ISSUE TITLE
Placeholder %player_hasitem-mat:<MATERIAL>-amt:<amount>-data:<data value>% not working

### ISSUE THREAD

**Issue by TasmanianNoob** [PlaceholderAPI/PlaceholderAPI#96]
I can't get the placeholder %player_hasitem-mat:<MATERIAL>-amt:<amount>-data:<data value>% to work, I've tried %player_hasitem-mat:STONE-amt:64-data:0% but that didn't work when I did /papi parse TasmanianNoob %player_hasitem-mat:STONE-amt:64-data:0% (just printed "%player_hasitem-mat:STONE-amt:64-data:0%" in chat) so I tried %player_hasitem-mat:stone-amt:64-data:0% but that also didn't work, other Player placeholders work like %player_name%.

I think it is meant to output yes or no but I am not sure, I'm certain it is not meant to respond with the placeholder you just tested though.

Placeholder does not work

1. /papi parse TasmanainNoob %player_hasitem-mat:STONE-amt:64-data:0%
2. read output

**Comment by aBo0oDyy** [comment]
Has item placeholder isn't a placeholder anymore in player expansion.
Use CheckItem expansion instead https://helpch.at/placeholders#checkitem

**Comment by Andre601** [comment]
Is this issue still open @TasmanianNoob ?

**Comment by TasmanianNoob** [comment]
No sorry this has been fixed
