### ISSUE TITLE
Placeholders do not show in tab completion for the /papi parse command

### ISSUE THREAD

**Issue by BlitzOffline** [PlaceholderAPI/PlaceholderAPI#960]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

When returning a list of placeholders from the getPlaceholders method they do not show up in tab completion when using the `/papi parse` command

### Expected Behaviour

They should show up.

### How to Reproduce

1. Create a new expansion that's registered inside a plugin
2. Override the getPlaceholders method
3. Make the method return a list of placeholders
4. Put plugin in server
5. Restart server
6. Try `/papi parse <player> %identifier_`

### `/papi dump` Output

https://paste.helpch.at/oqozayixoh

### Additional Info

This ticket was made at @iGabyTM's request. He wants to look into it. For full conversation, check the HelpChat discord server in the #development channel: https://discord.com/channels/164280494874165248/165129131770511360/1102957601974657095

**Code:**
expansion class: https://github.com/Auxilor/eco/blob/master/eco-core/core-backend/src/main/kotlin/com/willfp/eco/internal/integrations/PAPIExpansion.kt

api frontend:
https://github.com/Auxilor/eco/blob/master/eco-api/src/main/java/com/willfp/eco/core/integrations/placeholder/PlaceholderManager.java

expansion is registered here:
https://github.com/Auxilor/eco/blob/master/eco-api/src/main/java/com/willfp/eco/core/EcoPlugin.java#L391
by calling this internal method:
https://github.com/Auxilor/eco/blob/master/eco-core/core-plugin/src/main/kotlin/com/willfp/eco/internal/spigot/EcoImpl.kt#L129

**Comment by Andre601** [comment]
From what I know does the tab completion for placeholders pull these from the ecloud and not the expansion.

Perhaps a solution could be to check if the placeholders list returns a non-empty list and if true, use that instead of the ecloud data?
