### ISSUE TITLE
reload doesnt work

### ISSUE THREAD

**Issue by czychuuu** [PlaceholderAPI/PlaceholderAPI#965]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

when i reload plugin (/papi reload) i dont get any information about reload was succesful and none expansions work
even if none are installed papi still doesnt reload

### Expected Behaviour

reload and register expansions

### How to Reproduce

1. do /papi reload
2. see bug

### `/papi dump` Output

N/A

### Console Log

https://paste.helpch.at/zicovekuca.makefile

### Additional Info

(/papi dump) does literally nothing, no info in console, no new files

server version: git-Purpur-1933 (MC: 1.19.3)*
papi version: 2.11.4-DEV-174

**Comment by Andre601** [comment]
Please provide a `/papi dump` as requested.

**Comment by Andre601** [comment]
The best guess I can give right now is that your server is blocking the connection to the ecloud and that PAPI is failing silently (Swallows exceptions without mentioning anything).

Another guess is, that the server breaks stuff... again. It's Purpur and they implement pufferfish patches... which broke PlaceholderAPI in the past, so it wouldn't be surprising if something similar happens here again.

If possible, could try out on a Paper server and see if that works?

**Comment by Andre601** [comment]
Does it work if you remove any of the plugins that hook into PAPI (Add their own expansions) like the alonso plugins?

Because my next best guess is, that one of those may have a broken expansion causing some strange loading behaviour (Tho that imo seems unlikely).
The issue with a blocked internet connection may also still be the case. How do you host your server?

**Comment by czychuuu** [comment]
> Does it work if you remove any of the plugins that hook into PAPI (Add their own expansions) like the alonso plugins?
> 
> Because my next best guess is, that one of those may have a broken expansion causing some strange loading behaviour (Tho that imo seems unlikely). The issue with a blocked internet connection may also still be the case. How do you host your server?

i disabled every plugin that has hook to papi but with no success
server is hosted advinservers

**Comment by czychuuu** [comment]
i found solution to this but doesnt work everytime

do /papi list
rename plugins that has hooks ig. .jar to .jarr
stop and start server
install expansions using ecloud
/papi reload
stop server using /stop - by player
rename back plugins to normal
start server

skip installing expansions if you have alr installed everything you need

everytime you install new plugin that have hooks redo this

**Comment by mzrtamp** [comment]
Same, it happens to some of my servers:
Lobby safe
Survival happen
OneBlock happen
Creative safe

All of my server is clone each other (so there's no high diffs), got everything same like the plugins version, etc.

**Comment by mzrtamp** [comment]
I tried disabled ecloud and restarted the server. Then, this what actually happen:

> Before running `/papi reload` after restarted server with `ecloud off`
> 
> ![image](https://github.com/PlaceholderAPI/PlaceholderAPI/assets/40928387/0259c4a8-7d44-4c9a-9dd6-e2ee00467976)


> After running `/papi reload/` after restarted server with `ecloud on` (it getting worse, like the beginning before turning off the ecloud 🙃)
> 
> ![image](https://github.com/PlaceholderAPI/PlaceholderAPI/assets/40928387/aef50060-45e2-4974-b21e-0ad9e6dc892c)


Ah, not to forget I also attached what I did to debug this, with `debug` option to true: https://paste.helpch.at/bidokequqe.makefile (line 462).

Let me know if you guys have any solutions.

**Comment by mzrtamp** [comment]
> Before running `/papi reload` with AnimaBossBar deleted.
> ![image](https://github.com/PlaceholderAPI/PlaceholderAPI/assets/40928387/6cdbc726-58d0-4755-9508-943880b7f0d3)

> After running `/papi reload` with AnimaBossBar deleted (i shall regret this, like... just do not run `/papi reload` for now)
> ![image](https://github.com/PlaceholderAPI/PlaceholderAPI/assets/40928387/815ce657-3e04-440f-bf6e-4f353aa2b554)

**Comment by mzrtamp** [comment]
For myself, its not probably PAPI's fault at all, because this happens to the Geyser too. Just like there's must be a plugin to block some "connections" on the server causing PAPI went offline (cannot fetching when `/papi reload`, etc.) and Geyser not listening to its address/port (maybe we can call it "offline" too).

After hard-debugging, I finally found the impostor. It's Skungee's fault (after the 1.20 updates thing ig). The solution is, **try removing that plugin** (if you have any) or get any latest update if there exist.

Mine solved, thanks guys.
