### ISSUE TITLE
plugin not working. the %blablabla% thing isnt working

### ISSUE THREAD

**Issue by 4kKoZ** [PlaceholderAPI/PlaceholderAPI#983]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

<img width="598" alt="Screenshot 2023-07-07 at 4 59 09 PM" src="https://github.com/PlaceholderAPI/PlaceholderAPI/assets/136613764/a252e5c5-ec45-48ff-aaad-c75e70e326bc">

https://imgur.com/rskEo3c

### Expected Behaviour

show the numbers and not %%

### How to Reproduce

no steps

### `/papi dump` Output

https://paste.helpch.at/ezoculiqas

### Console Log

https://paste.helpch.at/usaminoyim.makefile

### Errors

https://paste.helpch.at/usaminoyim.makefile

### Additional Info

im not gonna be online for 6h so just put all u can and ima review it at home. and when i mean everything, just put all. ty :)

**Comment by iGabyTM** [comment]
> Expansions Registered:
  atr             [Author: [Morelaid], Version: 10.9]
  auctionhouse    [Author: klugemonkey, Version: 3.5]
  discordsrv      [Author: [Scarsz, Androkai, Vankka], Version: 1.26.2]
  excellentcrates [Author: NightExpress, Version: 4.3.0]
  gcore           [Author: GuillaumeVDN, Version: 1.0.0]
  supervanish     [Author: [MyzelYam], Version: 6.2.17]

> Expansions Directory:  

You don't have the expansions installed 😃 (statistic and vault)
