### ISSUE TITLE
missing placeholders 1.19.3

### ISSUE THREAD

**Issue by mat37dev** [PlaceholderAPI/PlaceholderAPI#988]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

API Bug

### What happens?

Missing placeholders in essentialsX extansion. For example in 1.19.3 there not %essentials_baltop_balance_<rank>% or or similar placeholders. (other example: %essentials_baltop_player_<rank>%)

### Expected Behaviour

to add these placeholders as before or they were available

### How to Reproduce

juste use placeholders...

### `/papi dump` Output

don't work

**Comment by Andre601** [comment]
What is that issue exactly about? The Plugin? The Wiki?

If it is the Wiki, then use the discussions and not issues for this.
If it is about the plugin, then this is not a PlaceholderAPI issue at all and should be moved to the right issue tracker.

**Comment by mat37dev** [comment]
it is about placeholder.  it lacks placeholders for essentials as I explained in my problem.  I agree go see them who told me that the problem is with placeholder api.  so either your wiki is not up to date or you have lost placeholders like those mentioned for 1.19.3
I don't know where I should go to report this issue.  this is the only place i have found to report a few things
