### ISSUE TITLE
New plugin placeholders for OreAnnouncer

### ISSUE THREAD

**Issue by AlessioDP** [PlaceholderAPI/PlaceholderAPI#99]
[Request change]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

### Notes
This template is for **requesting additions for the wiki** and not for reporting bugs or requesting changes for the wiki!  
If you want changes to be made to the wiki, use the [Request change] template.  
For bug reports, use the [Bug report] template.

Also make sure, that your requested placeholders/plugin isn't already added in the [wiki] or listed in the [issues] page.

### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New expansion providing placeholders.
- [x] New plugin providing placeholders.
- [x] New plugin supporting PlaceholderAPI.

### Plugin
> What is the name of the plugin/expansion?
> Provide also a link to it.

OreAnnouncer  
[Spigot page](https://www.spigotmc.org/resources/oreannouncer-collects-data-about-mined-blocks.33464/) - [GitHub page](https://github.com/AlessioDP/OreAnnouncer/)

### Placeholders/others
> What are the new placeholders/Any additional info?

This is the list: https://alessiodp.com/docs/oreannouncer/placeholders/#outside

**Comment by Andre601** [comment]
Added the plugin to the [placeholder list](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#oreannouncer)

Thanks for supporting PlaceholderAPI!
