### ISSUE TITLE
Javascript expansion issues

### ISSUE THREAD

**Issue by OfficialBlueseph** [PlaceholderAPI/PlaceholderAPI#997]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

After updating our server to 1.20, the javascript placeholders seem to have stopped working. We use them to help manage store menus via DeluxeMenus, making the expansion a requirement for our stores

I've attempted to redownload the expansion and update PAPI with no luck. Thanks for your time! 

### Expected Behaviour

I was hoping for the expansions to load, similar to how they have in the past

### How to Reproduce

1. Install PAPI
2. Install PAPI JavaScript expansion via `/ecloud`
3. Restart server, locate loading issue in console

### `/papi dump` Output

https://paste.helpch.at/nilokotuti

### Console Log

https://paste.helpch.at/ijizoritox.makefile

### Errors

https://paste.helpch.at/igehicewac.less

**Comment by iGabyTM** [comment]
For the moment, downgrade to PlaceholderAPI 2.11.2. This is but that was accidently introduced in 2.11.3, and it will be fixed in the next release.

**Comment by OfficialBlueseph** [comment]
After downgrading to version 2.11.2, I still seem to be having issues with the Javascript placeholders
